# La transition énergétique et environnementale en Europe

Pour notre projet finale nous avons sélectionné l'intégralité de nos données sur le site Eurostat. Eurostat est l'office statistique de l’Union européenne. Il a pour mission de fournir des statistiques de qualité sur l’Europe. Nous avons pour ce projet choisi 3 thématiques à analyser :

- Les déchets générés et le recyclage 
- La production d'électricité par type de combustible 
- Et enfin la surface agricole biologique 

1 fichier commun est présent dans nos analyses, le bilan énergétique complet en Europe. Le bilan énergétique permet d’évaluer l’importance relative des différents combustibles dans l’économie.

Pour ma partie individuelle j'ai choisi la production d'électricité en Europe en sélectionant 3 caractéristiques de la production d'électricité :
- Les énergies fossiles
- Les énergies renouvelables
- Et le total de la production d'électricité en Europe

![image](capture_ecran/schéma_db.png)

In [42]:
import pandas as pd

In [43]:
pd.set_option('display.max_rows', 600)

In [44]:
pd.set_option('max_colwidth', None)

# Import des fichiers code pays, code siec, code nrg_bal

Ces données ont été extraites du site eurostat afin de les intégrer dans nos tables issues du schéma DB. Ces données sont les suivantes :
- Code_pays : code des pays européens 
- Code_siec : code des types de combustibles 
- Code_nrg : code sur les types d'utilisateurs finaux

In [45]:
code_pays = pd.read_csv('data/nrg_bal_c_GEO.txt', sep='\t')
code_pays

,code,libelle
0,EU27_20,Union européenne - 27 pays (à partir de 2020)
1,EU28,Union européenne - 28 pays (2013-2020)
2,EA19,Zone euro - 19 pays (à partir de 2015)
3,BE,Belgique
4,BG,Bulgarie
5,CZ,Tchéquie
6,DK,Danemark
7,DE,Allemagne jusqu'en 1990 ancien territoire de la RFA
8,EE,Estonie
9,IE,Irlande
10,EL,Grèce
11,ES,Espagne
12,FR,France
13,HR,Croatie
14,IT,Italie
15,CY,Chypre
16,LV,Lettonie
17,LT,Lituanie
18,LU,Luxembourg
19,HU,Hongrie
20,MT,Malte
21,NL,Pays-Bas
22,AT,Autriche
23,PL,Pologne
24,PT,Portugal
25,RO,Roumanie
26,SI,Slovénie
27,SK,Slovaquie
28,FI,Finlande
29,SE,Suède
30,UK,Royaume-Uni
31,IS,Islande
32,NO,Norvège
33,ME,Monténégro
34,MK,Macédoine du Nord
35,AL,Albanie
36,RS,Serbie
37,TR,Turquie
38,BA,Bosnie-Herzégovine
39,XK,Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,MD,Moldavie
41,UA,Ukraine
42,GE,Géorgie

In [46]:
code_pays.insert(0, 'id', range(1, 1 + len(code_pays)))
code_pays

,id,code,libelle
0,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
1,2,EU28,Union européenne - 28 pays (2013-2020)
2,3,EA19,Zone euro - 19 pays (à partir de 2015)
3,4,BE,Belgique
4,5,BG,Bulgarie
5,6,CZ,Tchéquie
6,7,DK,Danemark
7,8,DE,Allemagne jusqu'en 1990 ancien territoire de la RFA
8,9,EE,Estonie
9,10,IE,Irlande
10,11,EL,Grèce
11,12,ES,Espagne
12,13,FR,France
13,14,HR,Croatie
14,15,IT,Italie
15,16,CY,Chypre
16,17,LV,Lettonie
17,18,LT,Lituanie
18,19,LU,Luxembourg
19,20,HU,Hongrie
20,21,MT,Malte
21,22,NL,Pays-Bas
22,23,AT,Autriche
23,24,PL,Pologne
24,25,PT,Portugal
25,26,RO,Roumanie
26,27,SI,Slovénie
27,28,SK,Slovaquie
28,29,FI,Finlande
29,30,SE,Suède
30,31,UK,Royaume-Uni
31,32,IS,Islande
32,33,NO,Norvège
33,34,ME,Monténégro
34,35,MK,Macédoine du Nord
35,36,AL,Albanie
36,37,RS,Serbie
37,38,TR,Turquie
38,39,BA,Bosnie-Herzégovine
39,40,XK,Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,41,MD,Moldavie
41,42,UA,Ukraine
42,43,GE,Géorgie

In [47]:
#code_pays.to_csv('pays_table.tsv',index=False,header=['id','code','libelle'], sep='\t')

In [48]:
code_siec = pd.read_csv('data/nrg_bal_c_SIEC.txt', sep='\t')
code_siec

,code,libelle
0,TOTAL,Total
1,C0000X0350-0370,Combustibles fossiles solides
2,C0110,Anthracite
3,C0121,Charbon à coke
4,C0129,Autre charbon bitumineux
5,C0210,Charbon sous-bitumineux
6,C0220,Lignite
7,C0311,Coke de four à coke
8,C0312,Coke de gaz
9,C0320,Aggloméré
10,C0330,Briquettes de lignite
11,C0340,Goudron de houille
12,C0350-0370,Gaz manufacturés
13,C0350,Gaz de four à coke
14,C0360,Gaz d'usine à gaz
15,C0371,Gaz de haut-fourneau
16,C0379,Autres gaz récupérés
17,P1000,Tourbe et produits dérivés de la tourbe
18,P1100,Tourbe
19,P1200,Produits dérivés de la tourbe
20,S2000,Schistes bitumineux et sables bitumineux
21,G3000,Gaz naturel
22,O4000XBIO,Pétrole et produits pétroliers (part de biocarburant non comprise)
23,O4100_TOT,Pétrole brut
24,O4200,Liquides du gaz naturel
25,O4300,Produits d'alimentation des raffineries
26,O4400X4410,Additifs et composés oxygénés (part de biocarburant non comprise)
27,O4500,Autres hydrocarbures
28,O4610,Gaz de raffinerie
29,O4620,Éthane
30,O4630,Gaz de pétrole liquéfiés
31,O4640,Naphta
32,O4651,Essence d'aviation
33,O4652XR5210B,Essence moteur (part de biocarburant non comprise)
34,O4653,Carburéacteur type essence
35,O4661XR5230B,Carburéacteur type kérosène (part de biocarburant non comprise)
36,O4669,Autre kérosène
37,O4671XR5220B,Gazole et carburant diesel (part de biocarburant non comprise)
38,O4680,Fioul
39,O4691,White spirit et essences industrielles à point de début d'ébullition spécial
40,O4692,Lubrifiants
41,O4693,Cires de paraffine
42,O4694,Coke de pétrole
43,O4695,Bitume
44,O4699,Autres produits pétroliers n.c.a.
45,RA000,Renouvelables et biocarburants
46,RA100,Hydraulique
47,RA200,Géothermique
48,RA300,Éolien
49,RA410,Solaire thermique
50,RA420,Solaire photovoltaïque
51,RA500,Énergie hydrocinétique houlomotrice marémotrice
52,RA600,Chaleur ambiante (pompes à chaleur)
53,R5110-5150_W6000RI,Biocarburants solides primaires
54,R5160,Charbon de bois
55,R5210P,Bioessence pure
56,R5210B,Bioessence mélangée
57,R5220P,Biodiesels purs
58,R5220B,Biodiesels mélangés
59,R5230P,Biokérosène pur
60,R5230B,Biokérosène mélangé
61,R5290,Autres biocarburants liquides
62,R5300,Biogaz
63,W6100,Déchets industriels (non-renouvelables)
64,W6210,Déchets municipaux renouvelables
65,W6220,Déchets municipaux non-renouvelables
66,W6100_6220,Déchets non-renouvelables
67,N900H,Chaleur nucléaire
68,E7000,Électricité
69,H8000,Chaleur
70,BIOE,Bioénergie
71,FE,Énergie fossile

In [49]:
#code_siec.to_csv('code_siec_table.tsv',index=False,header=['code','libelle'], sep='\t')

In [50]:
code_nrg = pd.read_csv('data/nrg_bal_c_NRG.txt', sep='\t')
code_nrg

,code,libelle
0,PPRD,Production primaire
1,RCV_RCY,Produits récupérés et recyclés
2,IMP,Importations
3,EXP,Exportations
4,STK_CHG,Variation de stock
5,GAE,Énergie disponible brute
6,INTMARB,Soutages maritimes internationaux
7,GIC,Consommation intérieure brute
8,INTAVI,Aviation internationale
9,NRGSUP,Approvisionnement énergétique total
10,GIC2020-2030,Consommation intérieure brute (Europe 2020-2030)
11,PEC2020-2030,Consommation d'énergie primaire (Europe 2020-2030)
12,FEC2020-2030,Consommation finale d'énergie (Europe 2020-2030)
13,TI_E,Entrées en transformation - usage énergétique
14,TI_EHG_E,Entrées en transformation - production d'électricité et de chaleur - usage énergétique
15,TI_EHG_MAPE_E,Entrées en transformation - production d'électricité et de chaleur - producteur dont l'activité principale est la production d'électricité uniqueme...
16,TI_EHG_MAPCHP_E,Entrées en transformation - production d'électricité et de chaleur - producteur dont l'activité principale est la cogénération de chaleur et d'élec...
17,TI_EHG_MAPH_E,Entrées en transformation - production d'électricité et de chaleur - producteur dont l'activité principale est la production de chaleur uniquement ...
18,TI_EHG_APE_E,Entrées en transformation - production d'électricité et de chaleur - autoproducteur d'électricité uniquement - usage énergétique
19,TI_EHG_APCHP_E,Entrées en transformation - production d'électricité et de chaleur - autoproducteur de chaleur et d'électricité combinées - usage énergétique
20,TI_EHG_APH_E,Entrées en transformation - production d'électricité et de chaleur - autoproducteur de chaleur uniquement - usage énergétique
21,TI_EHG_EDHP,Entrées en transformation - production d'électricité et de chaleur - pompes à chaleur électriques
22,TI_EHG_EB,Entrées en transformation - production d'électricité et de chaleur - chaudières électriques
23,TI_EHG_EPS,Entrées en transformation - production d'électricité et de chaleur - électricité pour le stockage par pompage
24,TI_EHG_DHEP,Entrées en transformation - production d'électricité et de chaleur - chaleur dérivée pour la production d'électricité
25,TI_CO_E,Entrées en transformation - fours à coke - usage énergétique
26,TI_BF_E,Entrées en transformation - hauts-fourneaux - usage énergétique
27,TI_GW_E,Entrées en transformation - usines à gaz - usage énergétique
28,TI_RPI_E,Entrées en transformation - raffineries et industrie pétrochimique - usage énergétique
29,TI_RPI_RI_E,Entrées en transformation - raffineries et industrie pétrochimique - entrées en raffinerie - usage énergétique
30,TI_RPI_BPI_E,Entrées en transformation - raffineries et industrie pétrochimique - retours de l'industrie pétrochimique - usage énergétique
31,TI_RPI_PT_E,Entrées en transformation - raffineries et industrie pétrochimique - produits transférés - usage énergétique
32,TI_RPI_IT_E,Entrées en transformation - raffineries et industrie pétrochimique - transferts entre produits - usage énergétique
33,TI_RPI_DU_E,Entrées en transformation - raffineries et industrie pétrochimique - usage direct - usage énergétique
34,TI_RPI_PII_E,Entrées en transformation - raffineries et industrie pétrochimique - entrées en industrie pétrochimique - usage énergétique
35,TI_PF_E,Entrées en transformation - fabriques d'agglomérés - usage énergétique
36,TI_BKBPB_E,Entrées en transformation - fabriques de briquettes de lignite et briquettes de tourbe - usage énergétique
37,TI_CL_E,Entrées en transformation - usines de liquéfaction du charbon - usage énergétique
38,TI_BNG_E,Entrées en transformation - pour mélange avec du gaz naturel - usage énergétique
39,TI_LBB_E,Entrées en transformation - biocarburants liquides mélangés - usage énergétique
40,TI_CPP_E,Entrées en transformation - usines de production de charbon de bois - usage énergétique
41,TI_GTL_E,Entrées en transformation - usines de liquéfaction du gaz - usage énergétique
42,TI_NSP_E,Entrées en transformation - non spécifiées ailleurs - usage énergétique
43,TO,Sorties de transformation
44,TO_EHG,Sorties de transformation - production d'électricité et de chaleur
45,TO_EHG_MAPE,Sorties de transformation - production d'électricité et de chaleur - producteur dont l'activité principale est la production d'électricité uniquement
46,TO_EHG_MAPCHP,Sorties de transformation - production d'électricité et de chaleur - producteur dont l'activité principale est la cogénération de chaleur et d'élec...
47,TO_EHG_MAPH,Sorties de transformation - production d'électricité et de chaleur - producteur dont l'activité principale est la production de chaleur uniquement
48,TO_EHG_APE,Sorties de transformation - production d'électricité et de chaleur - autoproducteur d'électricité uniquement
49,TO_EHG_APCHP,Sorties de transformation - production d'électricité et de chaleur - autoproducteur de chaleur et d'électricité combinées
50,TO_EHG_APH,Sorties de transformation - production d'électricité et de chaleur - autoproducteur de chaleur uniquement
51,TO_EHG_EDHP,Sorties de transformation - production d'électricité et de chaleur - pompes à chaleur électriques
52,TO_EHG_EB,Sorties de transformation - production d'électricité et de chaleur - chaudières électriques
53,TO_EHG_PH,Sorties de transformation - production d'électricité et de chaleur - pompage
54,TO_EHG_OTH,Sorties de transformation - production d'électricité et de chaleur - autres sources
55,TO_CO,Sorties de transformation - fours à coke
56,TO_BF,Sorties de transformation - hauts-fourneaux
57,TO_GW,Sorties de transformation - usines à gaz
58,TO_RPI,Sorties de transformation - raffineries et industrie pétrochimique
59,TO_RPI_RO,Sorties de transformation - raffineries et industrie pétrochimique - production des raffineries
60,TO_RPI_BKFLOW,Sorties de transformation - raffineries et industrie pétrochimique - retours
61,TO_RPI_PT,Sorties de transformation - raffineries et industrie pétrochimique - produits transférés
62,TO_RPI_IT,Sorties de transformation - raffineries et industrie pétrochimique - transferts entre produits
63,TO_RPI_PPR,Sorties de transformation - raffineries et industrie pétrochimique - produits primaires reçus
64,TO_RPI_PIR,Sorties de transformation - raffineries et industrie pétrochimique - restitutions de la pétrochimie
65,TO_PF,Sorties de transformation - fabriques d'agglomérés
66,TO_BKBPB,Sorties de transformation - fabriques de briquettes de lignite et briquettes de tourbe
67,TO_CL,Sorties de transformation - usines de liquéfaction du charbon
68,TO_BNG,Sorties de transformation - gaz naturel mélangé
69,TO_LBB,Sorties de transformation - biocarburants liquides mélangés
70,TO_CPP,Sorties de transformation - usines de production de charbon de bois
71,TO_GTL,Sorties de transformation - usines de liquéfaction du gaz
72,TO_NSP,Sorties de transformation - non spécifiées ailleurs
73,NRG_E,Secteur de l'énergie - usage énergétique
74,NRG_EHG_E,Secteur de l'énergie - production d'électricité et de chaleur - usage énergétique
75,NRG_CM_E,Secteur de l'énergie - mines de charbon - usage énergétique
76,NRG_OIL_NG_E,Secteur de l'énergie - usines d'extraction de pétrole et de gaz naturel - usage énergétique
77,NRG_PF_E,Secteur de l'énergie - fabriques d'agglomérés - usage énergétique
78,NRG_CO_E,Secteur de l'énergie - fours à coke - usage énergétique
79,NRG_BKBPB_E,Secteur de l'énergie - fabriques de briquettes de lignite et briquettes de tourbe - usage énergétique
80,NRG_GW_E,Secteur de l'énergie - usines à gaz - usage énergétique
81,NRG_BF_E,Secteur de l'énergie - hauts-fourneaux - usage énergétique
82,NRG_PR_E,Secteur de l'énergie - raffineries de pétrole - usage énergétique
83,NRG_NI_E,Secteur de l'énergie - industrie nucléaire - usage énergétique
84,NRG_CL_E,Secteur de l'énergie - usines de liquéfaction du charbon - usage énergétique
85,NRG_LNG_E,Secteur de l'énergie - usines de liquéfaction et regazéification (GNL) - usage énergétique
86,NRG_BIOG_E,Secteur de l'énergie - usines de gazéification de biogaz - usage énergétique
87,NRG_GTL_E,Secteur de l'énergie - usines de liquéfaction du gaz - usage énergétique
88,NRG_CPP_E,Secteur de l'énergie - usines de production de charbon de bois - usage énergétique
89,NRG_NSP_E,Secteur de l'énergie - non spécifié ailleurs - usage énergétique
90,DL,Pertes de distribution
91,AFC,Disponible pour la consommation finale
92,FC_NE,Consommation finale - usage non-énergétique
93,TI_NRG_FC_IND_NE,"Entrées en transformation, secteur de l'énergie et consommation finale dans le secteur industriel - usage non-énergétique"
94,TI_NE,Entrées en transformation - usage non-énergétique
95,NRG_NE,Secteur de l'énergie - usage non-énergétique
96,FC_IND_NE,Consommation finale - secteur industriel - usage non-énergétique
97,FC_TRA_NE,Consommation finale - secteur des transports - usage non-énergétique
98,FC_OTH_NE,Consommation finale - autres secteurs - usage non-énergétique
99,FC_E,Consommation finale - usage énergétique
100,FC_IND_E,Consommation finale - secteur industriel - usage énergétique
101,FC_IND_IS_E,Consommation finale - secteur industriel - sidérurgie - usage énergétique
102,FC_IND_CPC_E,Consommation finale - secteur industriel - chimie et pétrochimie - usage énergétique
103,FC_IND_NFM_E,Consommation finale - secteur industriel - métaux non-ferreux - usage énergétique
104,FC_IND_NMM_E,Consommation finale - secteur industriel - minéraux non-métalliques - usage énergétique
105,FC_IND_TE_E,Consommation finale - secteur industriel - matériel de transport - usage énergétique
106,FC_IND_MAC_E,Consommation finale - secteur industriel - machines - usage énergétique
107,FC_IND_MQ_E,Consommation finale - secteur industriel - industries extractives - usage énergétique
108,FC_IND_FBT_E,"Consommation finale - secteur industriel - produits alimentaires, boissons et tabac - usage énergétique"
109,FC_IND_PPP_E,"Consommation finale - secteur industriel - papier, pâte à papier et imprimerie - usage énergétique"
110,FC_IND_WP_E,Consommation finale - secteur industriel - bois et produits en bois - usage énergétique
111,FC_IND_CON_E,Consommation finale - secteur industriel - construction - usage énergétique
112,FC_IND_TL_E,Consommation finale - secteur industriel - textiles et cuir - usage énergétique
113,FC_IND_NSP_E,Consommation finale - secteur industriel - non spécifié ailleurs - usage énergétique
114,FC_TRA_E,Consommation finale - secteur des transports - usage énergétique
115,FC_TRA_RAIL_E,Consommation finale - secteur des transports - transport ferroviaire - usage énergétique
116,FC_TRA_ROAD_E,Consommation finale - secteur des transports - transport routier - usage énergétique
117,FC_TRA_DAVI_E,Consommation finale - secteur des transports - aviation intérieure - usage énergétique
118,FC_TRA_DNAVI_E,Consommation finale - secteur des transports - navigation intérieure - usage énergétique
119,FC_TRA_PIPE_E,Consommation finale - secteur des transports - transport par conduites - usage énergétique
120,FC_TRA_NSP_E,Consommation finale - secteur des transports - non spécifié ailleurs - usage énergétique
121,FC_OTH_E,Consommation finale - autres secteurs - usage énergétique
122,FC_OTH_CP_E,Consommation finale - autres secteurs - commerce et services publics - usage énergétique
123,FC_OTH_HH_E,Consommation finale - autres secteurs - ménages - usage énergétique
124,FC_OTH_AF_E,Consommation finale - autres secteurs - agriculture et sylviculture - usage énergétique
125,FC_OTH_FISH_E,Consommation finale - autres secteurs - pêche - usage énergétique
126,FC_OTH_NSP_E,Consommation finale - autres secteurs - non spécifié ailleurs - usage énergétique
127,STATDIFF,Écarts statistiques
128,GEP,Production brute d'électricité
129,GEP_MAPE,Production brute d'électricité - producteur dont l'activité principale est la production d'électricité uniquement
130,GEP_MAPCHP,Production brute d'électricité - producteur dont l'activité principale est la cogénération de chaleur et d'électricité
131,GEP_APE,Production brute d'électricité - autoproducteur d'électricité uniquement
132,GEP_APCHP,Production brute d'électricité - autoproducteur de chaleur et d'électricité combinées
133,GHP,Production brute de chaleur
134,GHP_MAPCHP,Production brute de chaleur - producteur dont l'activité principale est la cogénération de chaleur et d'électricité
135,GHP_MAPH,Production brute de chaleur - producteur dont l'activité principale est la production de chaleur uniquement
136,GHP_APCHP,Production brute de chaleur - autoproducteur de chaleur et d'électricité combinées
137,GHP_APH,Production brute de chaleur - autoproducteur de chaleur uniquement

In [51]:
#code_nrg.to_csv('code_bilan_table.tsv',index=False,header=['code','libelle'], sep='\t')

# Production d'électricité et de chaleur par type de combustible

Ce fichier présente la production d'électricité par type de combustible en Europe de 2009 à 2018. J'ai choisi de faire une analyse sur 3 axes dans la production d'électricité :
- Les énergies fossiles 
- Les énergies renouvelables
- Et la totalité des combustibles

Toutes les données sont présentées en milliers de tonnes équivalent pétrole (TEP). 

Source : https://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=nrg_bal_peh&lang=fr

## 1. Les énergies fossiles (TEP)

![image](capture_ecran/production_electricite_fossile.png)

Nous avons sélectionné parmis l'ensemble de ce dataset le combustible rassemblant l'ensemble des énergie fossiles nommé "combustible fossiles solides" en Europe de 2009 à 2018 en milliers de tonnes équivalent pétrole.

In [52]:
data = pd.read_csv('data/nrg_bal_peh_1_fossiles.tsv', sep='[|\t]', engine='python', encoding = "ISO-8859-1")
data

,"GEO,NRG_BAL,SIEC,UNIT\TIME",2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,"Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","60.496,545","60.294,939","62.359,396","63.861,407","62.675,652","59.566,150","60.618,471","56.678,555","54.930,576","51.213,293"
1,"Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","69.356,132","69.546,358","71.683,730","76.139,395","73.875,738","68.185,153","67.142,824","59.315,580","56.867,846","52.660,533"
2,"Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","39.139,194","38.510,932","39.791,898","42.887,030","42.140,432","39.865,979","41.022,267","37.340,874","35.745,174","32.374,392"
3,"Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","445,228","360,877","298,882","291,402","258,641","179,725","178,392","33,491","7,816","7,850"
4,"Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","1.814,531","1.943,766","2.367,756","1.966,982","1.667,377","1.831,900","1.936,543","1.665,004","1.798,288","1.604,426"
5,"Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","3.950,645","4.032,674","4.014,187","3.781,427","3.535,082","3.501,892","3.537,489","3.609,114","3.563,525","3.542,689"
6,"Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","1.520,808","1.462,253","1.201,720","906,191","1.228,891","951,333","611,339","762,273","533,839","564,954"
7,"Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","21.792,347","22.605,073","22.568,358","23.751,333","24.780,911","23.595,013","23.404,987","22.506,019","20.744,110","19.617,885"
8,"Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","1,118","0,516","0,000","0,000","1,513","0,000"
9,"Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","344,309","305,651","339,189","432,017","368,233","340,219","419,126","403,754","313,376","185,011"
10,"Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","2.939,639","2.648,065","2.670,937","2.675,752","2.270,507","2.213,758","1.900,860","1.623,646","1.613,500","1.477,657"
11,"Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","3.087,704","2.178,332","3.781,599","4.735,512","3.434,308","3.766,724","4.416,681","3.132,760","3.880,224","3.210,748"
12,"France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","1.863,027","2.008,512","1.531,165","1.844,366","2.049,097","966,664","1.020,952","889,463","1.102,163","723,361"
13,"Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","142,562","205,073","222,012","192,433","208,169","203,611","198,624","223,216","117,549","124,901"
14,"Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","3.417,455","3.416,509","3.845,744","4.225,365","3.878,332","3.736,371","3.714,617","3.061,651","2.805,454","2.447,968"
15,"Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000"
16,"Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,172","0,172","0,172","0,172","0,086","0,000","0,000","0,000","0,018","0,029"
17,"Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000"
18,"Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000"
19,"Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","545,142","536,028","557,438","545,486","541,702","515,477","497,850","484,265","424,076","401,462"
20,"Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000"
21,"Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","2.087,532","1.942,218","1.839,209","2.081,857","2.116,423","2.535,254","3.385,632","3.157,362","2.689,212","2.362,017"
22,"Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","323,174","422,909","467,029","377,286","362,139","252,371","254,021","175,634","151,148","155,226"
23,"Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","11.469,390","11.738,091","12.017,025","11.571,195","11.841,617","11.136,715","11.222,614","11.205,675","11.277,603","11.226,393"
24,"Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","1.108,856","610,490","846,776","1.125,279","1.017,885","1.027,687","1.266,294","1.085,985","1.261,049","1.032,361"
25,"Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","1.869,991","1.778,246","2.130,868","1.969,132","1.456,234","1.527,343","1.558,469","1.365,520","1.442,835","1.345,271"
26,"Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","441,273","454,686","456,320","442,390","419,261","323,216","377,042","430,782","414,800","397,444"
27,"Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","331,470","306,965","305,589","293,723","264,316","247,034","243,336","240,671","257,180","258,899"
28,"Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","957,008","1.250,473","840,929","610,576","919,175","681,427","440,327","599,656","503,611","497,936"
29,"Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","44,282","87,876","56,492","41,531","56,148","31,900","33,276","22,614","27,687","28,805"
30,"Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","8.859,587","9.251,419","9.324,334","12.277,988","11.200,086","8.619,003","6.524,353","2.637,025","1.937,270","1.447,240"
31,"Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000"
32,"Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","3,525","3,611","3,353","3,353","3,439","3,267","3,353","3,611","3,697","3,794"
33,"Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","59,243","109,372","124,850","117,541","123,904","122,184","130,009","111,608","117,102","133,680"
34,"Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","456,148","407,825","444,454","415,477","346,088","321,324","283,319","248,773","291,181","244,907"
35,"Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000"
36,"Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","2.309,200","2.151,505","2.468,960","2.262,769","2.465,004","1.902,494","2.335,512","2.342,476","2.275,542","2.151,296"
37,"Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","4.662,855","4.589,682","5.553,654","5.703,525","5.324,592","6.387,532","6.377,902","7.771,969","8.201,627","9.574,849"
38,"Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,:,"946,862","928,891","1.033,620","1.060,963","1.069,390"
39,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","416,251","428,977","487,962","501,548","547,463","453,138","512,812","491,917","492,344","481,557"
40,"Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000"
41,"Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","5.414,015","5.787,016","6.374,893","6.876,440","6.889,682","5.979,020","4.758,126","5.124,678","4.112,201","4.103,173"
42,"Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,"0,000","0,000","0,000","1,376","2,124","1,015"

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   GEO,NRG_BAL,SIEC,UNIT\TIME  43 non-null     object
 1   2009                        43 non-null     object
 2   2010                        43 non-null     object
 3   2011                        43 non-null     object
 4   2012                        43 non-null     object
 5   2013                        43 non-null     object
 6   2014                        43 non-null     object
 7   2015                        43 non-null     object
 8   2016                        43 non-null     object
 9   2017                        43 non-null     object
 10  2018                        43 non-null     object
dtypes: object(11)
memory usage: 3.8+ KB

### 1.1. Split de la colonne GEO,NRG_BAL,SIEC,UNIT\TIME

Dans notre 1ère colonne nous avons plusieurs données que nous devons diviser en plusieurs colonnes. Dans cette colonne nous avons :
- Le nom du pays (GEO)
- Le type d'utilisateurs finaux (NRG_BAL)
- Le type de combustible (SIEC)
- L'unité de mesure (UNIT\TIME)

Le but étant au final de récupérer uniquement la donnée sur le nom des pays (GEO).

==> On vient sélectionner la colonne sur laquelle on veut travailler.

In [54]:
data['GEO,NRG_BAL,SIEC,UNIT\TIME']

0                                     Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
1                                            Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
2                                            Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
3                                                                          Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
4                                                                          Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
5                                                                          Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
6                                                                          Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
7                            Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
8                                                                           Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
9                                                                           Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
10                                                                            Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
11                                                                          Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
12                                                                           France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
13                                                                          Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
14                                                                           Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
15                                                                           Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
16                                                                         Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
17                                                                         Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
18                                                                       Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
19                                                                          Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
20                                                                            Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
21                                                                         Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
22                                                                         Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
23                                                                          Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
24                                                                         Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
25                                                                         Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
26                                                                         Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
27                                                                        Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
28                                                                         Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
29                                                                            Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
30                                                                      Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
31                                                                          Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
32                                                                          Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
33                                                                       Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
34                                                                Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
35                                                                          Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
36                                                                           Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
37                                                                          Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
38                                                               Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
39    Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
40                                                                         Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
41                                                                          Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
42                                                                          Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
Name: GEO,NRG_BAL,SIEC,UNIT\TIME, dtype: object

==> On transforme cette colonne en dataframe.

In [55]:
text_columns = data[['GEO,NRG_BAL,SIEC,UNIT\TIME']]
text_columns

                                                                                                                                                                GEO,NRG_BAL,SIEC,UNIT\TIME
0                                   Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
1                                          Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
2                                          Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
3                                                                        Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
4                                                                        Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
5                                                                        Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
6                                                                        Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
7                          Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
8                                                                         Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
9                                                                         Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
10                                                                          Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
11                                                                        Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
12                                                                         France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
13                                                                        Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
14                                                                         Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
15                                                                         Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
16                                                                       Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
17                                                                       Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
18                                                                     Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
19                                                                        Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
20                                                                          Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
21                                                                       Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
22                                                                       Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
23                                                                        Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
24                                                                       Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
25                                                                       Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
26                                                                       Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
27                                                                      Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
28                                                                       Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
29                                                                          Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
30                                                                    Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
31                                                                        Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
32                                                                        Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
33                                                                     Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
34                                                              Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
35                                                                        Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
36                                                                         Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
37                                                                        Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
38                                                             Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
39  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
40                                                                       Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
41                                                                        Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
42                                                                        Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)

==> Un problème a été dectecté lors du split fait sur les virgule. L'allemagne avec la description "(jusqu'en 1990, ancien territoire de la RFA)" été splité sur la virgule et lors de la jointure l'Allemagne ne matchait pas avec le fichier du nom des pays puisque qu'une partie de la donnée n'apparaissait pas. Il a donc fallu enlever cette virgule dans la description du pays Allemagne pour éviter ce problème.

In [56]:
text_columns = text_columns.replace("Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale")
text_columns

                                                                                                                                                                GEO,NRG_BAL,SIEC,UNIT\TIME
0                                   Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
1                                          Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
2                                          Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
3                                                                        Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
4                                                                        Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
5                                                                        Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
6                                                                        Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
7                                                                                                   Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale
8                                                                         Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
9                                                                         Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
10                                                                          Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
11                                                                        Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
12                                                                         France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
13                                                                        Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
14                                                                         Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
15                                                                         Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
16                                                                       Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
17                                                                       Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
18                                                                     Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
19                                                                        Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
20                                                                          Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
21                                                                       Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
22                                                                       Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
23                                                                        Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
24                                                                       Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
25                                                                       Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
26                                                                       Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
27                                                                      Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
28                                                                       Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
29                                                                          Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
30                                                                    Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
31                                                                        Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
32                                                                        Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
33                                                                     Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
34                                                              Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
35                                                                        Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
36                                                                         Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
37                                                                        Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
38                                                             Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
39  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
40                                                                       Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
41                                                                        Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
42                                                                        Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)

==> On vient séparer chaque élemnent à l'interieur de l'unique colonne pour ajouter ces données dans plusieurs colonnes.

In [57]:
text_columns.columns

Index(['GEO,NRG_BAL,SIEC,UNIT\TIME'], dtype='object')

In [58]:
text_columns[['GEO', 'NRG_BAL', 'SIEC', 'UNIT\TIME']] = text_columns['GEO,NRG_BAL,SIEC,UNIT\TIME'].str.split(pat=',', n=3, expand=True)
text_columns

,"GEO,NRG_BAL,SIEC,UNIT\TIME",GEO,NRG_BAL,SIEC,UNIT\TIME
0,"Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
1,"Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
2,"Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
3,"Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
4,"Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
5,"Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
6,"Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
7,"Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale",Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale,None,None
8,"Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
9,"Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
10,"Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
11,"Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
12,"France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
13,"Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
14,"Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
15,"Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
16,"Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
17,"Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
18,"Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
19,"Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
20,"Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
21,"Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
22,"Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
23,"Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
24,"Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
25,"Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
26,"Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
27,"Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
28,"Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
29,"Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
30,"Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
31,"Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
32,"Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
33,"Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
34,"Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
35,"Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
36,"Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
37,"Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
38,"Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
39,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
40,"Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
41,"Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
42,"Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)

==> On ajoute la seule colonne qui nous intérèsse, le nom des pays, dans un dataframe.

In [59]:
new_column = text_columns[['GEO']]
new_column

                                                                              GEO
0                                   Union européenne - 27 pays (à partir de 2020)
1                                          Union européenne - 28 pays (2013-2020)
2                                          Zone euro - 19 pays (à partir de 2015)
3                                                                        Belgique
4                                                                        Bulgarie
5                                                                        Tchéquie
6                                                                        Danemark
7                             Allemagne jusqu'en 1990 ancien territoire de la RFA
8                                                                         Estonie
9                                                                         Irlande
10                                                                          Grèce
11                                                                        Espagne
12                                                                         France
13                                                                        Croatie
14                                                                         Italie
15                                                                         Chypre
16                                                                       Lettonie
17                                                                       Lituanie
18                                                                     Luxembourg
19                                                                        Hongrie
20                                                                          Malte
21                                                                       Pays-Bas
22                                                                       Autriche
23                                                                        Pologne
24                                                                       Portugal
25                                                                       Roumanie
26                                                                       Slovénie
27                                                                      Slovaquie
28                                                                       Finlande
29                                                                          Suède
30                                                                    Royaume-Uni
31                                                                        Islande
32                                                                        Norvège
33                                                                     Monténégro
34                                                              Macédoine du Nord
35                                                                        Albanie
36                                                                         Serbie
37                                                                        Turquie
38                                                             Bosnie-Herzégovine
39  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40                                                                       Moldavie
41                                                                        Ukraine
42                                                                        Géorgie

==> Le but étant d'ajouter cette nouvelle colonne à notre dataframe de base.

In [60]:
df1 = pd.concat([data, new_column], axis=1)
df1

,"GEO,NRG_BAL,SIEC,UNIT\TIME",2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO
0,"Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","60.496,545","60.294,939","62.359,396","63.861,407","62.675,652","59.566,150","60.618,471","56.678,555","54.930,576","51.213,293",Union européenne - 27 pays (à partir de 2020)
1,"Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","69.356,132","69.546,358","71.683,730","76.139,395","73.875,738","68.185,153","67.142,824","59.315,580","56.867,846","52.660,533",Union européenne - 28 pays (2013-2020)
2,"Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","39.139,194","38.510,932","39.791,898","42.887,030","42.140,432","39.865,979","41.022,267","37.340,874","35.745,174","32.374,392",Zone euro - 19 pays (à partir de 2015)
3,"Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","445,228","360,877","298,882","291,402","258,641","179,725","178,392","33,491","7,816","7,850",Belgique
4,"Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","1.814,531","1.943,766","2.367,756","1.966,982","1.667,377","1.831,900","1.936,543","1.665,004","1.798,288","1.604,426",Bulgarie
5,"Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","3.950,645","4.032,674","4.014,187","3.781,427","3.535,082","3.501,892","3.537,489","3.609,114","3.563,525","3.542,689",Tchéquie
6,"Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","1.520,808","1.462,253","1.201,720","906,191","1.228,891","951,333","611,339","762,273","533,839","564,954",Danemark
7,"Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","21.792,347","22.605,073","22.568,358","23.751,333","24.780,911","23.595,013","23.404,987","22.506,019","20.744,110","19.617,885",Allemagne jusqu'en 1990 ancien territoire de la RFA
8,"Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","1,118","0,516","0,000","0,000","1,513","0,000",Estonie
9,"Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","344,309","305,651","339,189","432,017","368,233","340,219","419,126","403,754","313,376","185,011",Irlande
10,"Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","2.939,639","2.648,065","2.670,937","2.675,752","2.270,507","2.213,758","1.900,860","1.623,646","1.613,500","1.477,657",Grèce
11,"Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","3.087,704","2.178,332","3.781,599","4.735,512","3.434,308","3.766,724","4.416,681","3.132,760","3.880,224","3.210,748",Espagne
12,"France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","1.863,027","2.008,512","1.531,165","1.844,366","2.049,097","966,664","1.020,952","889,463","1.102,163","723,361",France
13,"Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","142,562","205,073","222,012","192,433","208,169","203,611","198,624","223,216","117,549","124,901",Croatie
14,"Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","3.417,455","3.416,509","3.845,744","4.225,365","3.878,332","3.736,371","3.714,617","3.061,651","2.805,454","2.447,968",Italie
15,"Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Chypre
16,"Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,172","0,172","0,172","0,172","0,086","0,000","0,000","0,000","0,018","0,029",Lettonie
17,"Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Lituanie
18,"Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Luxembourg
19,"Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","545,142","536,028","557,438","545,486","541,702","515,477","497,850","484,265","424,076","401,462",Hongrie
20,"Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Malte
21,"Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","2.087,532","1.942,218","1.839,209","2.081,857","2.116,423","2.535,254","3.385,632","3.157,362","2.689,212","2.362,017",Pays-Bas
22,"Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","323,174","422,909","467,029","377,286","362,139","252,371","254,021","175,634","151,148","155,226",Autriche
23,"Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","11.469,390","11.738,091","12.017,025","11.571,195","11.841,617","11.136,715","11.222,614","11.205,675","11.277,603","11.226,393",Pologne
24,"Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","1.108,856","610,490","846,776","1.125,279","1.017,885","1.027,687","1.266,294","1.085,985","1.261,049","1.032,361",Portugal
25,"Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","1.869,991","1.778,246","2.130,868","1.969,132","1.456,234","1.527,343","1.558,469","1.365,520","1.442,835","1.345,271",Roumanie
26,"Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","441,273","454,686","456,320","442,390","419,261","323,216","377,042","430,782","414,800","397,444",Slovénie
27,"Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","331,470","306,965","305,589","293,723","264,316","247,034","243,336","240,671","257,180","258,899",Slovaquie
28,"Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","957,008","1.250,473","840,929","610,576","919,175","681,427","440,327","599,656","503,611","497,936",Finlande
29,"Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","44,282","87,876","56,492","41,531","56,148","31,900","33,276","22,614","27,687","28,805",Suède
30,"Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","8.859,587","9.251,419","9.324,334","12.277,988","11.200,086","8.619,003","6.524,353","2.637,025","1.937,270","1.447,240",Royaume-Uni
31,"Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Islande
32,"Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","3,525","3,611","3,353","3,353","3,439","3,267","3,353","3,611","3,697","3,794",Norvège
33,"Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","59,243","109,372","124,850","117,541","123,904","122,184","130,009","111,608","117,102","133,680",Monténégro
34,"Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","456,148","407,825","444,454","415,477","346,088","321,324","283,319","248,773","291,181","244,907",Macédoine du Nord
35,"Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Albanie
36,"Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","2.309,200","2.151,505","2.468,960","2.262,769","2.465,004","1.902,494","2.335,512","2.342,476","2.275,542","2.151,296",Serbie
37,"Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","4.662,855","4.589,682","5.553,654","5.703,525","5.324,592","6.387,532","6.377,902","7.771,969","8.201,627","9.574,849",Turquie
38,"Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,:,"946,862","928,891","1.033,620","1.060,963","1.069,390",Bosnie-Herzégovine
39,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","416,251","428,977","487,962","501,548","547,463","453,138","512,812","491,917","492,344","481,557",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,"Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Moldavie
41,"Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","5.414,015","5.787,016","6.374,893","6.876,440","6.889,682","5.979,020","4.758,126","5.124,678","4.112,201","4.103,173",Ukraine
42,"Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,"0,000","0,000","0,000","1,376","2,124","1,015",Géorgie

==> On supprime la colonne qui ne nous sert plus.

In [61]:
df1 = df1.drop(columns=['GEO,NRG_BAL,SIEC,UNIT\TIME'])
df1

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO
0,"60.496,545","60.294,939","62.359,396","63.861,407","62.675,652","59.566,150","60.618,471","56.678,555","54.930,576","51.213,293",Union européenne - 27 pays (à partir de 2020)
1,"69.356,132","69.546,358","71.683,730","76.139,395","73.875,738","68.185,153","67.142,824","59.315,580","56.867,846","52.660,533",Union européenne - 28 pays (2013-2020)
2,"39.139,194","38.510,932","39.791,898","42.887,030","42.140,432","39.865,979","41.022,267","37.340,874","35.745,174","32.374,392",Zone euro - 19 pays (à partir de 2015)
3,"445,228","360,877","298,882","291,402","258,641","179,725","178,392","33,491","7,816","7,850",Belgique
4,"1.814,531","1.943,766","2.367,756","1.966,982","1.667,377","1.831,900","1.936,543","1.665,004","1.798,288","1.604,426",Bulgarie
5,"3.950,645","4.032,674","4.014,187","3.781,427","3.535,082","3.501,892","3.537,489","3.609,114","3.563,525","3.542,689",Tchéquie
6,"1.520,808","1.462,253","1.201,720","906,191","1.228,891","951,333","611,339","762,273","533,839","564,954",Danemark
7,"21.792,347","22.605,073","22.568,358","23.751,333","24.780,911","23.595,013","23.404,987","22.506,019","20.744,110","19.617,885",Allemagne jusqu'en 1990 ancien territoire de la RFA
8,"0,000","0,000","0,000","0,000","1,118","0,516","0,000","0,000","1,513","0,000",Estonie
9,"344,309","305,651","339,189","432,017","368,233","340,219","419,126","403,754","313,376","185,011",Irlande
10,"2.939,639","2.648,065","2.670,937","2.675,752","2.270,507","2.213,758","1.900,860","1.623,646","1.613,500","1.477,657",Grèce
11,"3.087,704","2.178,332","3.781,599","4.735,512","3.434,308","3.766,724","4.416,681","3.132,760","3.880,224","3.210,748",Espagne
12,"1.863,027","2.008,512","1.531,165","1.844,366","2.049,097","966,664","1.020,952","889,463","1.102,163","723,361",France
13,"142,562","205,073","222,012","192,433","208,169","203,611","198,624","223,216","117,549","124,901",Croatie
14,"3.417,455","3.416,509","3.845,744","4.225,365","3.878,332","3.736,371","3.714,617","3.061,651","2.805,454","2.447,968",Italie
15,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Chypre
16,"0,172","0,172","0,172","0,172","0,086","0,000","0,000","0,000","0,018","0,029",Lettonie
17,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Lituanie
18,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Luxembourg
19,"545,142","536,028","557,438","545,486","541,702","515,477","497,850","484,265","424,076","401,462",Hongrie
20,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Malte
21,"2.087,532","1.942,218","1.839,209","2.081,857","2.116,423","2.535,254","3.385,632","3.157,362","2.689,212","2.362,017",Pays-Bas
22,"323,174","422,909","467,029","377,286","362,139","252,371","254,021","175,634","151,148","155,226",Autriche
23,"11.469,390","11.738,091","12.017,025","11.571,195","11.841,617","11.136,715","11.222,614","11.205,675","11.277,603","11.226,393",Pologne
24,"1.108,856","610,490","846,776","1.125,279","1.017,885","1.027,687","1.266,294","1.085,985","1.261,049","1.032,361",Portugal
25,"1.869,991","1.778,246","2.130,868","1.969,132","1.456,234","1.527,343","1.558,469","1.365,520","1.442,835","1.345,271",Roumanie
26,"441,273","454,686","456,320","442,390","419,261","323,216","377,042","430,782","414,800","397,444",Slovénie
27,"331,470","306,965","305,589","293,723","264,316","247,034","243,336","240,671","257,180","258,899",Slovaquie
28,"957,008","1.250,473","840,929","610,576","919,175","681,427","440,327","599,656","503,611","497,936",Finlande
29,"44,282","87,876","56,492","41,531","56,148","31,900","33,276","22,614","27,687","28,805",Suède
30,"8.859,587","9.251,419","9.324,334","12.277,988","11.200,086","8.619,003","6.524,353","2.637,025","1.937,270","1.447,240",Royaume-Uni
31,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Islande
32,"3,525","3,611","3,353","3,353","3,439","3,267","3,353","3,611","3,697","3,794",Norvège
33,"59,243","109,372","124,850","117,541","123,904","122,184","130,009","111,608","117,102","133,680",Monténégro
34,"456,148","407,825","444,454","415,477","346,088","321,324","283,319","248,773","291,181","244,907",Macédoine du Nord
35,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Albanie
36,"2.309,200","2.151,505","2.468,960","2.262,769","2.465,004","1.902,494","2.335,512","2.342,476","2.275,542","2.151,296",Serbie
37,"4.662,855","4.589,682","5.553,654","5.703,525","5.324,592","6.387,532","6.377,902","7.771,969","8.201,627","9.574,849",Turquie
38,:,:,:,:,:,"946,862","928,891","1.033,620","1.060,963","1.069,390",Bosnie-Herzégovine
39,"416,251","428,977","487,962","501,548","547,463","453,138","512,812","491,917","492,344","481,557",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Moldavie
41,"5.414,015","5.787,016","6.374,893","6.876,440","6.889,682","5.979,020","4.758,126","5.124,678","4.112,201","4.103,173",Ukraine
42,:,:,:,:,"0,000","0,000","0,000","1,376","2,124","1,015",Géorgie

==> Maintenant que nous avons récupéré le noms des pays on vient faire une jointure avec le dataframe sur les codes geo (chaque nom de pays à un code qui lui est attribué). L'objectif est de venir ajouter une nouvelle colonne "pays_id" qui sera notre clé étrangère.

In [62]:
df_merge = pd.merge(df1, code_pays, how ='inner', left_on='GEO', right_on= 'libelle')
df_merge

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO,id,code,libelle
0,"60.496,545","60.294,939","62.359,396","63.861,407","62.675,652","59.566,150","60.618,471","56.678,555","54.930,576","51.213,293",Union européenne - 27 pays (à partir de 2020),1,EU27_20,Union européenne - 27 pays (à partir de 2020)
1,"69.356,132","69.546,358","71.683,730","76.139,395","73.875,738","68.185,153","67.142,824","59.315,580","56.867,846","52.660,533",Union européenne - 28 pays (2013-2020),2,EU28,Union européenne - 28 pays (2013-2020)
2,"39.139,194","38.510,932","39.791,898","42.887,030","42.140,432","39.865,979","41.022,267","37.340,874","35.745,174","32.374,392",Zone euro - 19 pays (à partir de 2015),3,EA19,Zone euro - 19 pays (à partir de 2015)
3,"445,228","360,877","298,882","291,402","258,641","179,725","178,392","33,491","7,816","7,850",Belgique,4,BE,Belgique
4,"1.814,531","1.943,766","2.367,756","1.966,982","1.667,377","1.831,900","1.936,543","1.665,004","1.798,288","1.604,426",Bulgarie,5,BG,Bulgarie
5,"3.950,645","4.032,674","4.014,187","3.781,427","3.535,082","3.501,892","3.537,489","3.609,114","3.563,525","3.542,689",Tchéquie,6,CZ,Tchéquie
6,"1.520,808","1.462,253","1.201,720","906,191","1.228,891","951,333","611,339","762,273","533,839","564,954",Danemark,7,DK,Danemark
7,"21.792,347","22.605,073","22.568,358","23.751,333","24.780,911","23.595,013","23.404,987","22.506,019","20.744,110","19.617,885",Allemagne jusqu'en 1990 ancien territoire de la RFA,8,DE,Allemagne jusqu'en 1990 ancien territoire de la RFA
8,"0,000","0,000","0,000","0,000","1,118","0,516","0,000","0,000","1,513","0,000",Estonie,9,EE,Estonie
9,"344,309","305,651","339,189","432,017","368,233","340,219","419,126","403,754","313,376","185,011",Irlande,10,IE,Irlande
10,"2.939,639","2.648,065","2.670,937","2.675,752","2.270,507","2.213,758","1.900,860","1.623,646","1.613,500","1.477,657",Grèce,11,EL,Grèce
11,"3.087,704","2.178,332","3.781,599","4.735,512","3.434,308","3.766,724","4.416,681","3.132,760","3.880,224","3.210,748",Espagne,12,ES,Espagne
12,"1.863,027","2.008,512","1.531,165","1.844,366","2.049,097","966,664","1.020,952","889,463","1.102,163","723,361",France,13,FR,France
13,"142,562","205,073","222,012","192,433","208,169","203,611","198,624","223,216","117,549","124,901",Croatie,14,HR,Croatie
14,"3.417,455","3.416,509","3.845,744","4.225,365","3.878,332","3.736,371","3.714,617","3.061,651","2.805,454","2.447,968",Italie,15,IT,Italie
15,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Chypre,16,CY,Chypre
16,"0,172","0,172","0,172","0,172","0,086","0,000","0,000","0,000","0,018","0,029",Lettonie,17,LV,Lettonie
17,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Lituanie,18,LT,Lituanie
18,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Luxembourg,19,LU,Luxembourg
19,"545,142","536,028","557,438","545,486","541,702","515,477","497,850","484,265","424,076","401,462",Hongrie,20,HU,Hongrie
20,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Malte,21,MT,Malte
21,"2.087,532","1.942,218","1.839,209","2.081,857","2.116,423","2.535,254","3.385,632","3.157,362","2.689,212","2.362,017",Pays-Bas,22,NL,Pays-Bas
22,"323,174","422,909","467,029","377,286","362,139","252,371","254,021","175,634","151,148","155,226",Autriche,23,AT,Autriche
23,"11.469,390","11.738,091","12.017,025","11.571,195","11.841,617","11.136,715","11.222,614","11.205,675","11.277,603","11.226,393",Pologne,24,PL,Pologne
24,"1.108,856","610,490","846,776","1.125,279","1.017,885","1.027,687","1.266,294","1.085,985","1.261,049","1.032,361",Portugal,25,PT,Portugal
25,"1.869,991","1.778,246","2.130,868","1.969,132","1.456,234","1.527,343","1.558,469","1.365,520","1.442,835","1.345,271",Roumanie,26,RO,Roumanie
26,"441,273","454,686","456,320","442,390","419,261","323,216","377,042","430,782","414,800","397,444",Slovénie,27,SI,Slovénie
27,"331,470","306,965","305,589","293,723","264,316","247,034","243,336","240,671","257,180","258,899",Slovaquie,28,SK,Slovaquie
28,"957,008","1.250,473","840,929","610,576","919,175","681,427","440,327","599,656","503,611","497,936",Finlande,29,FI,Finlande
29,"44,282","87,876","56,492","41,531","56,148","31,900","33,276","22,614","27,687","28,805",Suède,30,SE,Suède
30,"8.859,587","9.251,419","9.324,334","12.277,988","11.200,086","8.619,003","6.524,353","2.637,025","1.937,270","1.447,240",Royaume-Uni,31,UK,Royaume-Uni
31,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Islande,32,IS,Islande
32,"3,525","3,611","3,353","3,353","3,439","3,267","3,353","3,611","3,697","3,794",Norvège,33,NO,Norvège
33,"59,243","109,372","124,850","117,541","123,904","122,184","130,009","111,608","117,102","133,680",Monténégro,34,ME,Monténégro
34,"456,148","407,825","444,454","415,477","346,088","321,324","283,319","248,773","291,181","244,907",Macédoine du Nord,35,MK,Macédoine du Nord
35,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Albanie,36,AL,Albanie
36,"2.309,200","2.151,505","2.468,960","2.262,769","2.465,004","1.902,494","2.335,512","2.342,476","2.275,542","2.151,296",Serbie,37,RS,Serbie
37,"4.662,855","4.589,682","5.553,654","5.703,525","5.324,592","6.387,532","6.377,902","7.771,969","8.201,627","9.574,849",Turquie,38,TR,Turquie
38,:,:,:,:,:,"946,862","928,891","1.033,620","1.060,963","1.069,390",Bosnie-Herzégovine,39,BA,Bosnie-Herzégovine
39,"416,251","428,977","487,962","501,548","547,463","453,138","512,812","491,917","492,344","481,557",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),40,XK,Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",Moldavie,41,MD,Moldavie
41,"5.414,015","5.787,016","6.374,893","6.876,440","6.889,682","5.979,020","4.758,126","5.124,678","4.112,201","4.103,173",Ukraine,42,UA,Ukraine
42,:,:,:,:,"0,000","0,000","0,000","1,376","2,124","1,015",Géorgie,43,GE,Géorgie

==> On supprime les colonnes qui ne vont pas nous servir afin de récupérer seulement l'id.

In [63]:
df_merge = df_merge.drop(columns=['libelle', 'GEO', 'code'])
df_merge

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,id
0,"60.496,545","60.294,939","62.359,396","63.861,407","62.675,652","59.566,150","60.618,471","56.678,555","54.930,576","51.213,293",1
1,"69.356,132","69.546,358","71.683,730","76.139,395","73.875,738","68.185,153","67.142,824","59.315,580","56.867,846","52.660,533",2
2,"39.139,194","38.510,932","39.791,898","42.887,030","42.140,432","39.865,979","41.022,267","37.340,874","35.745,174","32.374,392",3
3,"445,228","360,877","298,882","291,402","258,641","179,725","178,392","33,491","7,816","7,850",4
4,"1.814,531","1.943,766","2.367,756","1.966,982","1.667,377","1.831,900","1.936,543","1.665,004","1.798,288","1.604,426",5
5,"3.950,645","4.032,674","4.014,187","3.781,427","3.535,082","3.501,892","3.537,489","3.609,114","3.563,525","3.542,689",6
6,"1.520,808","1.462,253","1.201,720","906,191","1.228,891","951,333","611,339","762,273","533,839","564,954",7
7,"21.792,347","22.605,073","22.568,358","23.751,333","24.780,911","23.595,013","23.404,987","22.506,019","20.744,110","19.617,885",8
8,"0,000","0,000","0,000","0,000","1,118","0,516","0,000","0,000","1,513","0,000",9
9,"344,309","305,651","339,189","432,017","368,233","340,219","419,126","403,754","313,376","185,011",10
10,"2.939,639","2.648,065","2.670,937","2.675,752","2.270,507","2.213,758","1.900,860","1.623,646","1.613,500","1.477,657",11
11,"3.087,704","2.178,332","3.781,599","4.735,512","3.434,308","3.766,724","4.416,681","3.132,760","3.880,224","3.210,748",12
12,"1.863,027","2.008,512","1.531,165","1.844,366","2.049,097","966,664","1.020,952","889,463","1.102,163","723,361",13
13,"142,562","205,073","222,012","192,433","208,169","203,611","198,624","223,216","117,549","124,901",14
14,"3.417,455","3.416,509","3.845,744","4.225,365","3.878,332","3.736,371","3.714,617","3.061,651","2.805,454","2.447,968",15
15,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",16
16,"0,172","0,172","0,172","0,172","0,086","0,000","0,000","0,000","0,018","0,029",17
17,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",18
18,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",19
19,"545,142","536,028","557,438","545,486","541,702","515,477","497,850","484,265","424,076","401,462",20
20,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",21
21,"2.087,532","1.942,218","1.839,209","2.081,857","2.116,423","2.535,254","3.385,632","3.157,362","2.689,212","2.362,017",22
22,"323,174","422,909","467,029","377,286","362,139","252,371","254,021","175,634","151,148","155,226",23
23,"11.469,390","11.738,091","12.017,025","11.571,195","11.841,617","11.136,715","11.222,614","11.205,675","11.277,603","11.226,393",24
24,"1.108,856","610,490","846,776","1.125,279","1.017,885","1.027,687","1.266,294","1.085,985","1.261,049","1.032,361",25
25,"1.869,991","1.778,246","2.130,868","1.969,132","1.456,234","1.527,343","1.558,469","1.365,520","1.442,835","1.345,271",26
26,"441,273","454,686","456,320","442,390","419,261","323,216","377,042","430,782","414,800","397,444",27
27,"331,470","306,965","305,589","293,723","264,316","247,034","243,336","240,671","257,180","258,899",28
28,"957,008","1.250,473","840,929","610,576","919,175","681,427","440,327","599,656","503,611","497,936",29
29,"44,282","87,876","56,492","41,531","56,148","31,900","33,276","22,614","27,687","28,805",30
30,"8.859,587","9.251,419","9.324,334","12.277,988","11.200,086","8.619,003","6.524,353","2.637,025","1.937,270","1.447,240",31
31,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",32
32,"3,525","3,611","3,353","3,353","3,439","3,267","3,353","3,611","3,697","3,794",33
33,"59,243","109,372","124,850","117,541","123,904","122,184","130,009","111,608","117,102","133,680",34
34,"456,148","407,825","444,454","415,477","346,088","321,324","283,319","248,773","291,181","244,907",35
35,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",36
36,"2.309,200","2.151,505","2.468,960","2.262,769","2.465,004","1.902,494","2.335,512","2.342,476","2.275,542","2.151,296",37
37,"4.662,855","4.589,682","5.553,654","5.703,525","5.324,592","6.387,532","6.377,902","7.771,969","8.201,627","9.574,849",38
38,:,:,:,:,:,"946,862","928,891","1.033,620","1.060,963","1.069,390",39
39,"416,251","428,977","487,962","501,548","547,463","453,138","512,812","491,917","492,344","481,557",40
40,"0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000","0,000",41
41,"5.414,015","5.787,016","6.374,893","6.876,440","6.889,682","5.979,020","4.758,126","5.124,678","4.112,201","4.103,173",42
42,:,:,:,:,"0,000","0,000","0,000","1,376","2,124","1,015",43

### 1.2. Transformation des colonnes "années" en lignes

==> Nous venons retravailler notre dataframe afin de transformer les années qui sont en colonnes en lignes. Ce travaille est nécéssaire pour correspondre à notre table dans la base de données.

In [64]:
df_merge.columns

Index(['2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', 'id'],
      dtype='object')

In [65]:
df_global = []
for i in range(2009,2019):
    df_i = df_merge[[f'{i}', 'id']]
    df_i.rename(columns={f'{i}':'quantite_tep', 'id':'pays_id'}, inplace=True)
    df_i['annee'] = i
    df_global.append(df_i)
df_global[0]

/home/camille/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
<ipython-input-65-eeebe292c68f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_i['annee'] = i

   quantite_tep  pays_id  annee
0    60.496,545        1   2009
1    69.356,132        2   2009
2    39.139,194        3   2009
3       445,228        4   2009
4     1.814,531        5   2009
5     3.950,645        6   2009
6     1.520,808        7   2009
7    21.792,347        8   2009
8         0,000        9   2009
9       344,309       10   2009
10    2.939,639       11   2009
11    3.087,704       12   2009
12    1.863,027       13   2009
13      142,562       14   2009
14    3.417,455       15   2009
15        0,000       16   2009
16        0,172       17   2009
17        0,000       18   2009
18        0,000       19   2009
19      545,142       20   2009
20        0,000       21   2009
21    2.087,532       22   2009
22      323,174       23   2009
23   11.469,390       24   2009
24    1.108,856       25   2009
25    1.869,991       26   2009
26      441,273       27   2009
27      331,470       28   2009
28      957,008       29   2009
29       44,282       30   2009
30    8.859,587       31   2009
31        0,000       32   2009
32        3,525       33   2009
33       59,243       34   2009
34      456,148       35   2009
35        0,000       36   2009
36    2.309,200       37   2009
37    4.662,855       38   2009
38            :       39   2009
39      416,251       40   2009
40        0,000       41   2009
41    5.414,015       42   2009
42            :       43   2009

In [66]:
len(df_global)

10

==> On vient ajouter l'ensemble des dataframes de chaque année en un seul, donc 10 dataframes car il y a 10 années.

In [67]:
frames = [ df_global[i] for i in range(0,10) ]
production_electricite_fossile = pd.concat(frames)
production_electricite_fossile

   quantite_tep  pays_id  annee
0    60.496,545        1   2009
1    69.356,132        2   2009
2    39.139,194        3   2009
3       445,228        4   2009
4     1.814,531        5   2009
5     3.950,645        6   2009
6     1.520,808        7   2009
7    21.792,347        8   2009
8         0,000        9   2009
9       344,309       10   2009
10    2.939,639       11   2009
11    3.087,704       12   2009
12    1.863,027       13   2009
13      142,562       14   2009
14    3.417,455       15   2009
15        0,000       16   2009
16        0,172       17   2009
17        0,000       18   2009
18        0,000       19   2009
19      545,142       20   2009
20        0,000       21   2009
21    2.087,532       22   2009
22      323,174       23   2009
23   11.469,390       24   2009
24    1.108,856       25   2009
25    1.869,991       26   2009
26      441,273       27   2009
27      331,470       28   2009
28      957,008       29   2009
29       44,282       30   2009
30    8.859,587       31   2009
31        0,000       32   2009
32        3,525       33   2009
33       59,243       34   2009
34      456,148       35   2009
35        0,000       36   2009
36    2.309,200       37   2009
37    4.662,855       38   2009
38            :       39   2009
39      416,251       40   2009
40        0,000       41   2009
41    5.414,015       42   2009
42            :       43   2009
0    60.294,939        1   2010
1    69.546,358        2   2010
2    38.510,932        3   2010
3       360,877        4   2010
4     1.943,766        5   2010
5     4.032,674        6   2010
6     1.462,253        7   2010
7    22.605,073        8   2010
8         0,000        9   2010
9       305,651       10   2010
10    2.648,065       11   2010
11    2.178,332       12   2010
12    2.008,512       13   2010
13      205,073       14   2010
14    3.416,509       15   2010
15        0,000       16   2010
16        0,172       17   2010
17        0,000       18   2010
18        0,000       19   2010
19      536,028       20   2010
20        0,000       21   2010
21    1.942,218       22   2010
22      422,909       23   2010
23   11.738,091       24   2010
24      610,490       25   2010
25    1.778,246       26   2010
26      454,686       27   2010
27      306,965       28   2010
28    1.250,473       29   2010
29       87,876       30   2010
30    9.251,419       31   2010
31        0,000       32   2010
32        3,611       33   2010
33      109,372       34   2010
34      407,825       35   2010
35        0,000       36   2010
36    2.151,505       37   2010
37    4.589,682       38   2010
38            :       39   2010
39      428,977       40   2010
40        0,000       41   2010
41    5.787,016       42   2010
42            :       43   2010
0    62.359,396        1   2011
1    71.683,730        2   2011
2    39.791,898        3   2011
3       298,882        4   2011
4     2.367,756        5   2011
5     4.014,187        6   2011
6     1.201,720        7   2011
7    22.568,358        8   2011
8         0,000        9   2011
9       339,189       10   2011
10    2.670,937       11   2011
11    3.781,599       12   2011
12    1.531,165       13   2011
13      222,012       14   2011
14    3.845,744       15   2011
15        0,000       16   2011
16        0,172       17   2011
17        0,000       18   2011
18        0,000       19   2011
19      557,438       20   2011
20        0,000       21   2011
21    1.839,209       22   2011
22      467,029       23   2011
23   12.017,025       24   2011
24      846,776       25   2011
25    2.130,868       26   2011
26      456,320       27   2011
27      305,589       28   2011
28      840,929       29   2011
29       56,492       30   2011
30    9.324,334       31   2011
31        0,000       32   2011
32        3,353       33   2011
33      124,850       34   2011
34      444,454       35   2011
35        0,000       36   2011
36    2.468,960       37   2011
37    5.553,654       38   2011
38            :       39   2011
39      487,962       40   2011
40        0,000       41   2011
41    6.374,893       42   2011
42            :       43   2011
0    63.861,407        1   2012
1    76.139,395        2   2012
2    42.887,030        3   2012
3       291,402        4   2012
4     1.966,982        5   2012
5     3.781,427        6   2012
6       906,191        7   2012
7    23.751,333        8   2012
8         0,000        9   2012
9       432,017       10   2012
10    2.675,752       11   2012
11    4.735,512       12   2012
12    1.844,366       13   2012
13      192,433       14   2012
14    4.225,365       15   2012
15        0,000       16   2012
16        0,172       17   2012
17        0,000       18   2012
18        0,000       19   2012
19      545,486       20   2012
20        0,000       21   2012
21    2.081,857       22   2012
22      377,286       23   2012
23   11.571,195       24   2012
24    1.125,279       25   2012
25    1.969,132       26   2012
26      442,390       27   2012
27      293,723       28   2012
28      610,576       29   2012
29       41,531       30   2012
30   12.277,988       31   2012
31        0,000       32   2012
32        3,353       33   2012
33      117,541       34   2012
34      415,477       35   2012
35        0,000       36   2012
36    2.262,769       37   2012
37    5.703,525       38   2012
38            :       39   2012
39      501,548       40   2012
40        0,000       41   2012
41    6.876,440       42   2012
42            :       43   2012
0    62.675,652        1   2013
1    73.875,738        2   2013
2    42.140,432        3   2013
3       258,641        4   2013
4     1.667,377        5   2013
5     3.535,082        6   2013
6     1.228,891        7   2013
7    24.780,911        8   2013
8         1,118        9   2013
9       368,233       10   2013
10    2.270,507       11   2013
11    3.434,308       12   2013
12    2.049,097       13   2013
13      208,169       14   2013
14    3.878,332       15   2013
15        0,000       16   2013
16        0,086       17   2013
17        0,000       18   2013
18        0,000       19   2013
19      541,702       20   2013
20        0,000       21   2013
21    2.116,423       22   2013
22      362,139       23   2013
23   11.841,617       24   2013
24    1.017,885       25   2013
25    1.456,234       26   2013
26      419,261       27   2013
27      264,316       28   2013
28      919,175       29   2013
29       56,148       30   2013
30   11.200,086       31   2013
31        0,000       32   2013
32        3,439       33   2013
33      123,904       34   2013
34      346,088       35   2013
35        0,000       36   2013
36    2.465,004       37   2013
37    5.324,592       38   2013
38            :       39   2013
39      547,463       40   2013
40        0,000       41   2013
41    6.889,682       42   2013
42        0,000       43   2013
0    59.566,150        1   2014
1    68.185,153        2   2014
2    39.865,979        3   2014
3       179,725        4   2014
4     1.831,900        5   2014
5     3.501,892        6   2014
6       951,333        7   2014
7    23.595,013        8   2014
8         0,516        9   2014
9       340,219       10   2014
10    2.213,758       11   2014
11    3.766,724       12   2014
12      966,664       13   2014
13      203,611       14   2014
14    3.736,371       15   2014
15        0,000       16   2014
16        0,000       17   2014
17        0,000       18   2014
18        0,000       19   2014
19      515,477       20   2014
20        0,000       21   2014
21    2.535,254       22   2014
22      252,371       23   2014
23   11.136,715       24   2014
24    1.027,687       25   2014
25    1.527,343       26   2014
26      323,216       27   2014
27      247,034       28   2014
28      681,427       29   2014
29       31,900       30   2014
30    8.619,003       31   2014
31        0,000       32   2014
32        3,267       33   2014
33      122,184       34   2014
34      321,324       35   2014
35        0,000       36   2014
36    1.902,494       37   2014
37    6.387,532       38   2014
38      946,862       39   2014
39      453,138       40   2014
40        0,000       41   2014
41    5.979,020       42   2014
42        0,000       43   2014
0    60.618,471        1   2015
1    67.142,824        2   2015
2    41.022,267        3   2015
3       178,392        4   2015
4     1.936,543        5   2015
5     3.537,489        6   2015
6       611,339        7   2015
7    23.404,987        8   2015
8         0,000        9   2015
9       419,126       10   2015
10    1.900,860       11   2015
11    4.416,681       12   2015
12    1.020,952       13   2015
13      198,624       14   2015
14    3.714,617       15   2015
15        0,000       16   2015
16        0,000       17   2015
17        0,000       18   2015
18        0,000       19   2015
19      497,850       20   2015
20        0,000       21   2015
21    3.385,632       22   2015
22      254,021       23   2015
23   11.222,614       24   2015
24    1.266,294       25   2015
25    1.558,469       26   2015
26      377,042       27   2015
27      243,336       28   2015
28      440,327       29   2015
29       33,276       30   2015
30    6.524,353       31   2015
31        0,000       32   2015
32        3,353       33   2015
33      130,009       34   2015
34      283,319       35   2015
35        0,000       36   2015
36    2.335,512       37   2015
37    6.377,902       38   2015
38      928,891       39   2015
39      512,812       40   2015
40        0,000       41   2015
41    4.758,126       42   2015
42        0,000       43   2015
0    56.678,555        1   2016
1    59.315,580        2   2016
2    37.340,874        3   2016
3        33,491        4   2016
4     1.665,004        5   2016
5     3.609,114        6   2016
6       762,273        7   2016
7    22.506,019        8   2016
8         0,000        9   2016
9       403,754       10   2016
10    1.623,646       11   2016
11    3.132,760       12   2016
12      889,463       13   2016
13      223,216       14   2016
14    3.061,651       15   2016
15        0,000       16   2016
16        0,000       17   2016
17        0,000       18   2016
18        0,000       19   2016
19      484,265       20   2016
20        0,000       21   2016
21    3.157,362       22   2016
22      175,634       23   2016
23   11.205,675       24   2016
24    1.085,985       25   2016
25    1.365,520       26   2016
26      430,782       27   2016
27      240,671       28   2016
28      599,656       29   2016
29       22,614       30   2016
30    2.637,025       31   2016
31        0,000       32   2016
32        3,611       33   2016
33      111,608       34   2016
34      248,773       35   2016
35        0,000       36   2016
36    2.342,476       37   2016
37    7.771,969       38   2016
38    1.033,620       39   2016
39      491,917       40   2016
40        0,000       41   2016
41    5.124,678       42   2016
42        1,376       43   2016
0    54.930,576        1   2017
1    56.867,846        2   2017
2    35.745,174        3   2017
3         7,816        4   2017
4     1.798,288        5   2017
5     3.563,525        6   2017
6       533,839        7   2017
7    20.744,110        8   2017
8         1,513        9   2017
9       313,376       10   2017
10    1.613,500       11   2017
11    3.880,224       12   2017
12    1.102,163       13   2017
13      117,549       14   2017
14    2.805,454       15   2017
15        0,000       16   2017
16        0,018       17   2017
17        0,000       18   2017
18        0,000       19   2017
19      424,076       20   2017
20        0,000       21   2017
21    2.689,212       22   2017
22      151,148       23   2017
23   11.277,603       24   2017
24    1.261,049       25   2017
25    1.442,835       26   2017
26      414,800       27   2017
27      257,180       28   2017
28      503,611       29   2017
29       27,687       30   2017
30    1.937,270       31   2017
31        0,000       32   2017
32        3,697       33   2017
33      117,102       34   2017
34      291,181       35   2017
35        0,000       36   2017
36    2.275,542       37   2017
37    8.201,627       38   2017
38    1.060,963       39   2017
39      492,344       40   2017
40        0,000       41   2017
41    4.112,201       42   2017
42        2,124       43   2017
0    51.213,293        1   2018
1    52.660,533        2   2018
2    32.374,392        3   2018
3         7,850        4   2018
4     1.604,426        5   2018
5     3.542,689        6   2018
6       564,954        7   2018
7    19.617,885        8   2018
8         0,000        9   2018
9       185,011       10   2018
10    1.477,657       11   2018
11    3.210,748       12   2018
12      723,361       13   2018
13      124,901       14   2018
14    2.447,968       15   2018
15        0,000       16   2018
16        0,029       17   2018
17        0,000       18   2018
18        0,000       19   2018
19      401,462       20   2018
20        0,000       21   2018
21    2.362,017       22   2018
22      155,226       23   2018
23   11.226,393       24   2018
24    1.032,361       25   2018
25    1.345,271       26   2018
26      397,444       27   2018
27      258,899       28   2018
28      497,936       29   2018
29       28,805       30   2018
30    1.447,240       31   2018
31        0,000       32   2018
32        3,794       33   2018
33      133,680       34   2018
34      244,907       35   2018
35        0,000       36   2018
36    2.151,296       37   2018
37    9.574,849       38   2018
38    1.069,390       39   2018
39      481,557       40   2018
40        0,000       41   2018
41    4.103,173       42   2018
42        1,015       43   2018

### 1.3. Nettoyage de la donnée

==> Ici on vient remplacer les valeur ":" et "0,000" par une valeur nulle pour éviter des problèmes dans la DB ou l'analyse de la donnée. On veut éviter que les 0 soient pris en compte dans des moyennes ou graphiques par la suite.

In [68]:
production_electricite_fossile = production_electricite_fossile.replace([':', '0,000'], '')
production_electricite_fossile

   quantite_tep  pays_id  annee
0    60.496,545        1   2009
1    69.356,132        2   2009
2    39.139,194        3   2009
3       445,228        4   2009
4     1.814,531        5   2009
5     3.950,645        6   2009
6     1.520,808        7   2009
7    21.792,347        8   2009
8                      9   2009
9       344,309       10   2009
10    2.939,639       11   2009
11    3.087,704       12   2009
12    1.863,027       13   2009
13      142,562       14   2009
14    3.417,455       15   2009
15                    16   2009
16        0,172       17   2009
17                    18   2009
18                    19   2009
19      545,142       20   2009
20                    21   2009
21    2.087,532       22   2009
22      323,174       23   2009
23   11.469,390       24   2009
24    1.108,856       25   2009
25    1.869,991       26   2009
26      441,273       27   2009
27      331,470       28   2009
28      957,008       29   2009
29       44,282       30   2009
30    8.859,587       31   2009
31                    32   2009
32        3,525       33   2009
33       59,243       34   2009
34      456,148       35   2009
35                    36   2009
36    2.309,200       37   2009
37    4.662,855       38   2009
38                    39   2009
39      416,251       40   2009
40                    41   2009
41    5.414,015       42   2009
42                    43   2009
0    60.294,939        1   2010
1    69.546,358        2   2010
2    38.510,932        3   2010
3       360,877        4   2010
4     1.943,766        5   2010
5     4.032,674        6   2010
6     1.462,253        7   2010
7    22.605,073        8   2010
8                      9   2010
9       305,651       10   2010
10    2.648,065       11   2010
11    2.178,332       12   2010
12    2.008,512       13   2010
13      205,073       14   2010
14    3.416,509       15   2010
15                    16   2010
16        0,172       17   2010
17                    18   2010
18                    19   2010
19      536,028       20   2010
20                    21   2010
21    1.942,218       22   2010
22      422,909       23   2010
23   11.738,091       24   2010
24      610,490       25   2010
25    1.778,246       26   2010
26      454,686       27   2010
27      306,965       28   2010
28    1.250,473       29   2010
29       87,876       30   2010
30    9.251,419       31   2010
31                    32   2010
32        3,611       33   2010
33      109,372       34   2010
34      407,825       35   2010
35                    36   2010
36    2.151,505       37   2010
37    4.589,682       38   2010
38                    39   2010
39      428,977       40   2010
40                    41   2010
41    5.787,016       42   2010
42                    43   2010
0    62.359,396        1   2011
1    71.683,730        2   2011
2    39.791,898        3   2011
3       298,882        4   2011
4     2.367,756        5   2011
5     4.014,187        6   2011
6     1.201,720        7   2011
7    22.568,358        8   2011
8                      9   2011
9       339,189       10   2011
10    2.670,937       11   2011
11    3.781,599       12   2011
12    1.531,165       13   2011
13      222,012       14   2011
14    3.845,744       15   2011
15                    16   2011
16        0,172       17   2011
17                    18   2011
18                    19   2011
19      557,438       20   2011
20                    21   2011
21    1.839,209       22   2011
22      467,029       23   2011
23   12.017,025       24   2011
24      846,776       25   2011
25    2.130,868       26   2011
26      456,320       27   2011
27      305,589       28   2011
28      840,929       29   2011
29       56,492       30   2011
30    9.324,334       31   2011
31                    32   2011
32        3,353       33   2011
33      124,850       34   2011
34      444,454       35   2011
35                    36   2011
36    2.468,960       37   2011
37    5.553,654       38   2011
38                    39   2011
39      487,962       40   2011
40                    41   2011
41    6.374,893       42   2011
42                    43   2011
0    63.861,407        1   2012
1    76.139,395        2   2012
2    42.887,030        3   2012
3       291,402        4   2012
4     1.966,982        5   2012
5     3.781,427        6   2012
6       906,191        7   2012
7    23.751,333        8   2012
8                      9   2012
9       432,017       10   2012
10    2.675,752       11   2012
11    4.735,512       12   2012
12    1.844,366       13   2012
13      192,433       14   2012
14    4.225,365       15   2012
15                    16   2012
16        0,172       17   2012
17                    18   2012
18                    19   2012
19      545,486       20   2012
20                    21   2012
21    2.081,857       22   2012
22      377,286       23   2012
23   11.571,195       24   2012
24    1.125,279       25   2012
25    1.969,132       26   2012
26      442,390       27   2012
27      293,723       28   2012
28      610,576       29   2012
29       41,531       30   2012
30   12.277,988       31   2012
31                    32   2012
32        3,353       33   2012
33      117,541       34   2012
34      415,477       35   2012
35                    36   2012
36    2.262,769       37   2012
37    5.703,525       38   2012
38                    39   2012
39      501,548       40   2012
40                    41   2012
41    6.876,440       42   2012
42                    43   2012
0    62.675,652        1   2013
1    73.875,738        2   2013
2    42.140,432        3   2013
3       258,641        4   2013
4     1.667,377        5   2013
5     3.535,082        6   2013
6     1.228,891        7   2013
7    24.780,911        8   2013
8         1,118        9   2013
9       368,233       10   2013
10    2.270,507       11   2013
11    3.434,308       12   2013
12    2.049,097       13   2013
13      208,169       14   2013
14    3.878,332       15   2013
15                    16   2013
16        0,086       17   2013
17                    18   2013
18                    19   2013
19      541,702       20   2013
20                    21   2013
21    2.116,423       22   2013
22      362,139       23   2013
23   11.841,617       24   2013
24    1.017,885       25   2013
25    1.456,234       26   2013
26      419,261       27   2013
27      264,316       28   2013
28      919,175       29   2013
29       56,148       30   2013
30   11.200,086       31   2013
31                    32   2013
32        3,439       33   2013
33      123,904       34   2013
34      346,088       35   2013
35                    36   2013
36    2.465,004       37   2013
37    5.324,592       38   2013
38                    39   2013
39      547,463       40   2013
40                    41   2013
41    6.889,682       42   2013
42                    43   2013
0    59.566,150        1   2014
1    68.185,153        2   2014
2    39.865,979        3   2014
3       179,725        4   2014
4     1.831,900        5   2014
5     3.501,892        6   2014
6       951,333        7   2014
7    23.595,013        8   2014
8         0,516        9   2014
9       340,219       10   2014
10    2.213,758       11   2014
11    3.766,724       12   2014
12      966,664       13   2014
13      203,611       14   2014
14    3.736,371       15   2014
15                    16   2014
16                    17   2014
17                    18   2014
18                    19   2014
19      515,477       20   2014
20                    21   2014
21    2.535,254       22   2014
22      252,371       23   2014
23   11.136,715       24   2014
24    1.027,687       25   2014
25    1.527,343       26   2014
26      323,216       27   2014
27      247,034       28   2014
28      681,427       29   2014
29       31,900       30   2014
30    8.619,003       31   2014
31                    32   2014
32        3,267       33   2014
33      122,184       34   2014
34      321,324       35   2014
35                    36   2014
36    1.902,494       37   2014
37    6.387,532       38   2014
38      946,862       39   2014
39      453,138       40   2014
40                    41   2014
41    5.979,020       42   2014
42                    43   2014
0    60.618,471        1   2015
1    67.142,824        2   2015
2    41.022,267        3   2015
3       178,392        4   2015
4     1.936,543        5   2015
5     3.537,489        6   2015
6       611,339        7   2015
7    23.404,987        8   2015
8                      9   2015
9       419,126       10   2015
10    1.900,860       11   2015
11    4.416,681       12   2015
12    1.020,952       13   2015
13      198,624       14   2015
14    3.714,617       15   2015
15                    16   2015
16                    17   2015
17                    18   2015
18                    19   2015
19      497,850       20   2015
20                    21   2015
21    3.385,632       22   2015
22      254,021       23   2015
23   11.222,614       24   2015
24    1.266,294       25   2015
25    1.558,469       26   2015
26      377,042       27   2015
27      243,336       28   2015
28      440,327       29   2015
29       33,276       30   2015
30    6.524,353       31   2015
31                    32   2015
32        3,353       33   2015
33      130,009       34   2015
34      283,319       35   2015
35                    36   2015
36    2.335,512       37   2015
37    6.377,902       38   2015
38      928,891       39   2015
39      512,812       40   2015
40                    41   2015
41    4.758,126       42   2015
42                    43   2015
0    56.678,555        1   2016
1    59.315,580        2   2016
2    37.340,874        3   2016
3        33,491        4   2016
4     1.665,004        5   2016
5     3.609,114        6   2016
6       762,273        7   2016
7    22.506,019        8   2016
8                      9   2016
9       403,754       10   2016
10    1.623,646       11   2016
11    3.132,760       12   2016
12      889,463       13   2016
13      223,216       14   2016
14    3.061,651       15   2016
15                    16   2016
16                    17   2016
17                    18   2016
18                    19   2016
19      484,265       20   2016
20                    21   2016
21    3.157,362       22   2016
22      175,634       23   2016
23   11.205,675       24   2016
24    1.085,985       25   2016
25    1.365,520       26   2016
26      430,782       27   2016
27      240,671       28   2016
28      599,656       29   2016
29       22,614       30   2016
30    2.637,025       31   2016
31                    32   2016
32        3,611       33   2016
33      111,608       34   2016
34      248,773       35   2016
35                    36   2016
36    2.342,476       37   2016
37    7.771,969       38   2016
38    1.033,620       39   2016
39      491,917       40   2016
40                    41   2016
41    5.124,678       42   2016
42        1,376       43   2016
0    54.930,576        1   2017
1    56.867,846        2   2017
2    35.745,174        3   2017
3         7,816        4   2017
4     1.798,288        5   2017
5     3.563,525        6   2017
6       533,839        7   2017
7    20.744,110        8   2017
8         1,513        9   2017
9       313,376       10   2017
10    1.613,500       11   2017
11    3.880,224       12   2017
12    1.102,163       13   2017
13      117,549       14   2017
14    2.805,454       15   2017
15                    16   2017
16        0,018       17   2017
17                    18   2017
18                    19   2017
19      424,076       20   2017
20                    21   2017
21    2.689,212       22   2017
22      151,148       23   2017
23   11.277,603       24   2017
24    1.261,049       25   2017
25    1.442,835       26   2017
26      414,800       27   2017
27      257,180       28   2017
28      503,611       29   2017
29       27,687       30   2017
30    1.937,270       31   2017
31                    32   2017
32        3,697       33   2017
33      117,102       34   2017
34      291,181       35   2017
35                    36   2017
36    2.275,542       37   2017
37    8.201,627       38   2017
38    1.060,963       39   2017
39      492,344       40   2017
40                    41   2017
41    4.112,201       42   2017
42        2,124       43   2017
0    51.213,293        1   2018
1    52.660,533        2   2018
2    32.374,392        3   2018
3         7,850        4   2018
4     1.604,426        5   2018
5     3.542,689        6   2018
6       564,954        7   2018
7    19.617,885        8   2018
8                      9   2018
9       185,011       10   2018
10    1.477,657       11   2018
11    3.210,748       12   2018
12      723,361       13   2018
13      124,901       14   2018
14    2.447,968       15   2018
15                    16   2018
16        0,029       17   2018
17                    18   2018
18                    19   2018
19      401,462       20   2018
20                    21   2018
21    2.362,017       22   2018
22      155,226       23   2018
23   11.226,393       24   2018
24    1.032,361       25   2018
25    1.345,271       26   2018
26      397,444       27   2018
27      258,899       28   2018
28      497,936       29   2018
29       28,805       30   2018
30    1.447,240       31   2018
31                    32   2018
32        3,794       33   2018
33      133,680       34   2018
34      244,907       35   2018
35                    36   2018
36    2.151,296       37   2018
37    9.574,849       38   2018
38    1.069,390       39   2018
39      481,557       40   2018
40                    41   2018
41    4.103,173       42   2018
42        1,015       43   2018

==> On remplace les points dans les valeurs numérique avec des milliers

In [69]:
production_electricite_fossile['quantite_tep'] = production_electricite_fossile['quantite_tep'].apply(lambda x: x.replace('.', ''))
production_electricite_fossile

   quantite_tep  pays_id  annee
0     60496,545        1   2009
1     69356,132        2   2009
2     39139,194        3   2009
3       445,228        4   2009
4      1814,531        5   2009
5      3950,645        6   2009
6      1520,808        7   2009
7     21792,347        8   2009
8                      9   2009
9       344,309       10   2009
10     2939,639       11   2009
11     3087,704       12   2009
12     1863,027       13   2009
13      142,562       14   2009
14     3417,455       15   2009
15                    16   2009
16        0,172       17   2009
17                    18   2009
18                    19   2009
19      545,142       20   2009
20                    21   2009
21     2087,532       22   2009
22      323,174       23   2009
23    11469,390       24   2009
24     1108,856       25   2009
25     1869,991       26   2009
26      441,273       27   2009
27      331,470       28   2009
28      957,008       29   2009
29       44,282       30   2009
30     8859,587       31   2009
31                    32   2009
32        3,525       33   2009
33       59,243       34   2009
34      456,148       35   2009
35                    36   2009
36     2309,200       37   2009
37     4662,855       38   2009
38                    39   2009
39      416,251       40   2009
40                    41   2009
41     5414,015       42   2009
42                    43   2009
0     60294,939        1   2010
1     69546,358        2   2010
2     38510,932        3   2010
3       360,877        4   2010
4      1943,766        5   2010
5      4032,674        6   2010
6      1462,253        7   2010
7     22605,073        8   2010
8                      9   2010
9       305,651       10   2010
10     2648,065       11   2010
11     2178,332       12   2010
12     2008,512       13   2010
13      205,073       14   2010
14     3416,509       15   2010
15                    16   2010
16        0,172       17   2010
17                    18   2010
18                    19   2010
19      536,028       20   2010
20                    21   2010
21     1942,218       22   2010
22      422,909       23   2010
23    11738,091       24   2010
24      610,490       25   2010
25     1778,246       26   2010
26      454,686       27   2010
27      306,965       28   2010
28     1250,473       29   2010
29       87,876       30   2010
30     9251,419       31   2010
31                    32   2010
32        3,611       33   2010
33      109,372       34   2010
34      407,825       35   2010
35                    36   2010
36     2151,505       37   2010
37     4589,682       38   2010
38                    39   2010
39      428,977       40   2010
40                    41   2010
41     5787,016       42   2010
42                    43   2010
0     62359,396        1   2011
1     71683,730        2   2011
2     39791,898        3   2011
3       298,882        4   2011
4      2367,756        5   2011
5      4014,187        6   2011
6      1201,720        7   2011
7     22568,358        8   2011
8                      9   2011
9       339,189       10   2011
10     2670,937       11   2011
11     3781,599       12   2011
12     1531,165       13   2011
13      222,012       14   2011
14     3845,744       15   2011
15                    16   2011
16        0,172       17   2011
17                    18   2011
18                    19   2011
19      557,438       20   2011
20                    21   2011
21     1839,209       22   2011
22      467,029       23   2011
23    12017,025       24   2011
24      846,776       25   2011
25     2130,868       26   2011
26      456,320       27   2011
27      305,589       28   2011
28      840,929       29   2011
29       56,492       30   2011
30     9324,334       31   2011
31                    32   2011
32        3,353       33   2011
33      124,850       34   2011
34      444,454       35   2011
35                    36   2011
36     2468,960       37   2011
37     5553,654       38   2011
38                    39   2011
39      487,962       40   2011
40                    41   2011
41     6374,893       42   2011
42                    43   2011
0     63861,407        1   2012
1     76139,395        2   2012
2     42887,030        3   2012
3       291,402        4   2012
4      1966,982        5   2012
5      3781,427        6   2012
6       906,191        7   2012
7     23751,333        8   2012
8                      9   2012
9       432,017       10   2012
10     2675,752       11   2012
11     4735,512       12   2012
12     1844,366       13   2012
13      192,433       14   2012
14     4225,365       15   2012
15                    16   2012
16        0,172       17   2012
17                    18   2012
18                    19   2012
19      545,486       20   2012
20                    21   2012
21     2081,857       22   2012
22      377,286       23   2012
23    11571,195       24   2012
24     1125,279       25   2012
25     1969,132       26   2012
26      442,390       27   2012
27      293,723       28   2012
28      610,576       29   2012
29       41,531       30   2012
30    12277,988       31   2012
31                    32   2012
32        3,353       33   2012
33      117,541       34   2012
34      415,477       35   2012
35                    36   2012
36     2262,769       37   2012
37     5703,525       38   2012
38                    39   2012
39      501,548       40   2012
40                    41   2012
41     6876,440       42   2012
42                    43   2012
0     62675,652        1   2013
1     73875,738        2   2013
2     42140,432        3   2013
3       258,641        4   2013
4      1667,377        5   2013
5      3535,082        6   2013
6      1228,891        7   2013
7     24780,911        8   2013
8         1,118        9   2013
9       368,233       10   2013
10     2270,507       11   2013
11     3434,308       12   2013
12     2049,097       13   2013
13      208,169       14   2013
14     3878,332       15   2013
15                    16   2013
16        0,086       17   2013
17                    18   2013
18                    19   2013
19      541,702       20   2013
20                    21   2013
21     2116,423       22   2013
22      362,139       23   2013
23    11841,617       24   2013
24     1017,885       25   2013
25     1456,234       26   2013
26      419,261       27   2013
27      264,316       28   2013
28      919,175       29   2013
29       56,148       30   2013
30    11200,086       31   2013
31                    32   2013
32        3,439       33   2013
33      123,904       34   2013
34      346,088       35   2013
35                    36   2013
36     2465,004       37   2013
37     5324,592       38   2013
38                    39   2013
39      547,463       40   2013
40                    41   2013
41     6889,682       42   2013
42                    43   2013
0     59566,150        1   2014
1     68185,153        2   2014
2     39865,979        3   2014
3       179,725        4   2014
4      1831,900        5   2014
5      3501,892        6   2014
6       951,333        7   2014
7     23595,013        8   2014
8         0,516        9   2014
9       340,219       10   2014
10     2213,758       11   2014
11     3766,724       12   2014
12      966,664       13   2014
13      203,611       14   2014
14     3736,371       15   2014
15                    16   2014
16                    17   2014
17                    18   2014
18                    19   2014
19      515,477       20   2014
20                    21   2014
21     2535,254       22   2014
22      252,371       23   2014
23    11136,715       24   2014
24     1027,687       25   2014
25     1527,343       26   2014
26      323,216       27   2014
27      247,034       28   2014
28      681,427       29   2014
29       31,900       30   2014
30     8619,003       31   2014
31                    32   2014
32        3,267       33   2014
33      122,184       34   2014
34      321,324       35   2014
35                    36   2014
36     1902,494       37   2014
37     6387,532       38   2014
38      946,862       39   2014
39      453,138       40   2014
40                    41   2014
41     5979,020       42   2014
42                    43   2014
0     60618,471        1   2015
1     67142,824        2   2015
2     41022,267        3   2015
3       178,392        4   2015
4      1936,543        5   2015
5      3537,489        6   2015
6       611,339        7   2015
7     23404,987        8   2015
8                      9   2015
9       419,126       10   2015
10     1900,860       11   2015
11     4416,681       12   2015
12     1020,952       13   2015
13      198,624       14   2015
14     3714,617       15   2015
15                    16   2015
16                    17   2015
17                    18   2015
18                    19   2015
19      497,850       20   2015
20                    21   2015
21     3385,632       22   2015
22      254,021       23   2015
23    11222,614       24   2015
24     1266,294       25   2015
25     1558,469       26   2015
26      377,042       27   2015
27      243,336       28   2015
28      440,327       29   2015
29       33,276       30   2015
30     6524,353       31   2015
31                    32   2015
32        3,353       33   2015
33      130,009       34   2015
34      283,319       35   2015
35                    36   2015
36     2335,512       37   2015
37     6377,902       38   2015
38      928,891       39   2015
39      512,812       40   2015
40                    41   2015
41     4758,126       42   2015
42                    43   2015
0     56678,555        1   2016
1     59315,580        2   2016
2     37340,874        3   2016
3        33,491        4   2016
4      1665,004        5   2016
5      3609,114        6   2016
6       762,273        7   2016
7     22506,019        8   2016
8                      9   2016
9       403,754       10   2016
10     1623,646       11   2016
11     3132,760       12   2016
12      889,463       13   2016
13      223,216       14   2016
14     3061,651       15   2016
15                    16   2016
16                    17   2016
17                    18   2016
18                    19   2016
19      484,265       20   2016
20                    21   2016
21     3157,362       22   2016
22      175,634       23   2016
23    11205,675       24   2016
24     1085,985       25   2016
25     1365,520       26   2016
26      430,782       27   2016
27      240,671       28   2016
28      599,656       29   2016
29       22,614       30   2016
30     2637,025       31   2016
31                    32   2016
32        3,611       33   2016
33      111,608       34   2016
34      248,773       35   2016
35                    36   2016
36     2342,476       37   2016
37     7771,969       38   2016
38     1033,620       39   2016
39      491,917       40   2016
40                    41   2016
41     5124,678       42   2016
42        1,376       43   2016
0     54930,576        1   2017
1     56867,846        2   2017
2     35745,174        3   2017
3         7,816        4   2017
4      1798,288        5   2017
5      3563,525        6   2017
6       533,839        7   2017
7     20744,110        8   2017
8         1,513        9   2017
9       313,376       10   2017
10     1613,500       11   2017
11     3880,224       12   2017
12     1102,163       13   2017
13      117,549       14   2017
14     2805,454       15   2017
15                    16   2017
16        0,018       17   2017
17                    18   2017
18                    19   2017
19      424,076       20   2017
20                    21   2017
21     2689,212       22   2017
22      151,148       23   2017
23    11277,603       24   2017
24     1261,049       25   2017
25     1442,835       26   2017
26      414,800       27   2017
27      257,180       28   2017
28      503,611       29   2017
29       27,687       30   2017
30     1937,270       31   2017
31                    32   2017
32        3,697       33   2017
33      117,102       34   2017
34      291,181       35   2017
35                    36   2017
36     2275,542       37   2017
37     8201,627       38   2017
38     1060,963       39   2017
39      492,344       40   2017
40                    41   2017
41     4112,201       42   2017
42        2,124       43   2017
0     51213,293        1   2018
1     52660,533        2   2018
2     32374,392        3   2018
3         7,850        4   2018
4      1604,426        5   2018
5      3542,689        6   2018
6       564,954        7   2018
7     19617,885        8   2018
8                      9   2018
9       185,011       10   2018
10     1477,657       11   2018
11     3210,748       12   2018
12      723,361       13   2018
13      124,901       14   2018
14     2447,968       15   2018
15                    16   2018
16        0,029       17   2018
17                    18   2018
18                    19   2018
19      401,462       20   2018
20                    21   2018
21     2362,017       22   2018
22      155,226       23   2018
23    11226,393       24   2018
24     1032,361       25   2018
25     1345,271       26   2018
26      397,444       27   2018
27      258,899       28   2018
28      497,936       29   2018
29       28,805       30   2018
30     1447,240       31   2018
31                    32   2018
32        3,794       33   2018
33      133,680       34   2018
34      244,907       35   2018
35                    36   2018
36     2151,296       37   2018
37     9574,849       38   2018
38     1069,390       39   2018
39      481,557       40   2018
40                    41   2018
41     4103,173       42   2018
42        1,015       43   2018

==> On enlève les virgules pour pouvoir transformer les strings en float à l'étape suivante

In [70]:
production_electricite_fossile.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 430 entries, 0 to 42
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   quantite_tep  430 non-null    object
 1   pays_id       430 non-null    int64
 2   annee         430 non-null    int64
dtypes: int64(2), object(1)
memory usage: 13.4+ KB

In [71]:
production_electricite_fossile['quantite_tep'] = production_electricite_fossile['quantite_tep'].apply(lambda x: x.replace(',', '.'))
production_electricite_fossile

   quantite_tep  pays_id  annee
0     60496.545        1   2009
1     69356.132        2   2009
2     39139.194        3   2009
3       445.228        4   2009
4      1814.531        5   2009
5      3950.645        6   2009
6      1520.808        7   2009
7     21792.347        8   2009
8                      9   2009
9       344.309       10   2009
10     2939.639       11   2009
11     3087.704       12   2009
12     1863.027       13   2009
13      142.562       14   2009
14     3417.455       15   2009
15                    16   2009
16        0.172       17   2009
17                    18   2009
18                    19   2009
19      545.142       20   2009
20                    21   2009
21     2087.532       22   2009
22      323.174       23   2009
23    11469.390       24   2009
24     1108.856       25   2009
25     1869.991       26   2009
26      441.273       27   2009
27      331.470       28   2009
28      957.008       29   2009
29       44.282       30   2009
30     8859.587       31   2009
31                    32   2009
32        3.525       33   2009
33       59.243       34   2009
34      456.148       35   2009
35                    36   2009
36     2309.200       37   2009
37     4662.855       38   2009
38                    39   2009
39      416.251       40   2009
40                    41   2009
41     5414.015       42   2009
42                    43   2009
0     60294.939        1   2010
1     69546.358        2   2010
2     38510.932        3   2010
3       360.877        4   2010
4      1943.766        5   2010
5      4032.674        6   2010
6      1462.253        7   2010
7     22605.073        8   2010
8                      9   2010
9       305.651       10   2010
10     2648.065       11   2010
11     2178.332       12   2010
12     2008.512       13   2010
13      205.073       14   2010
14     3416.509       15   2010
15                    16   2010
16        0.172       17   2010
17                    18   2010
18                    19   2010
19      536.028       20   2010
20                    21   2010
21     1942.218       22   2010
22      422.909       23   2010
23    11738.091       24   2010
24      610.490       25   2010
25     1778.246       26   2010
26      454.686       27   2010
27      306.965       28   2010
28     1250.473       29   2010
29       87.876       30   2010
30     9251.419       31   2010
31                    32   2010
32        3.611       33   2010
33      109.372       34   2010
34      407.825       35   2010
35                    36   2010
36     2151.505       37   2010
37     4589.682       38   2010
38                    39   2010
39      428.977       40   2010
40                    41   2010
41     5787.016       42   2010
42                    43   2010
0     62359.396        1   2011
1     71683.730        2   2011
2     39791.898        3   2011
3       298.882        4   2011
4      2367.756        5   2011
5      4014.187        6   2011
6      1201.720        7   2011
7     22568.358        8   2011
8                      9   2011
9       339.189       10   2011
10     2670.937       11   2011
11     3781.599       12   2011
12     1531.165       13   2011
13      222.012       14   2011
14     3845.744       15   2011
15                    16   2011
16        0.172       17   2011
17                    18   2011
18                    19   2011
19      557.438       20   2011
20                    21   2011
21     1839.209       22   2011
22      467.029       23   2011
23    12017.025       24   2011
24      846.776       25   2011
25     2130.868       26   2011
26      456.320       27   2011
27      305.589       28   2011
28      840.929       29   2011
29       56.492       30   2011
30     9324.334       31   2011
31                    32   2011
32        3.353       33   2011
33      124.850       34   2011
34      444.454       35   2011
35                    36   2011
36     2468.960       37   2011
37     5553.654       38   2011
38                    39   2011
39      487.962       40   2011
40                    41   2011
41     6374.893       42   2011
42                    43   2011
0     63861.407        1   2012
1     76139.395        2   2012
2     42887.030        3   2012
3       291.402        4   2012
4      1966.982        5   2012
5      3781.427        6   2012
6       906.191        7   2012
7     23751.333        8   2012
8                      9   2012
9       432.017       10   2012
10     2675.752       11   2012
11     4735.512       12   2012
12     1844.366       13   2012
13      192.433       14   2012
14     4225.365       15   2012
15                    16   2012
16        0.172       17   2012
17                    18   2012
18                    19   2012
19      545.486       20   2012
20                    21   2012
21     2081.857       22   2012
22      377.286       23   2012
23    11571.195       24   2012
24     1125.279       25   2012
25     1969.132       26   2012
26      442.390       27   2012
27      293.723       28   2012
28      610.576       29   2012
29       41.531       30   2012
30    12277.988       31   2012
31                    32   2012
32        3.353       33   2012
33      117.541       34   2012
34      415.477       35   2012
35                    36   2012
36     2262.769       37   2012
37     5703.525       38   2012
38                    39   2012
39      501.548       40   2012
40                    41   2012
41     6876.440       42   2012
42                    43   2012
0     62675.652        1   2013
1     73875.738        2   2013
2     42140.432        3   2013
3       258.641        4   2013
4      1667.377        5   2013
5      3535.082        6   2013
6      1228.891        7   2013
7     24780.911        8   2013
8         1.118        9   2013
9       368.233       10   2013
10     2270.507       11   2013
11     3434.308       12   2013
12     2049.097       13   2013
13      208.169       14   2013
14     3878.332       15   2013
15                    16   2013
16        0.086       17   2013
17                    18   2013
18                    19   2013
19      541.702       20   2013
20                    21   2013
21     2116.423       22   2013
22      362.139       23   2013
23    11841.617       24   2013
24     1017.885       25   2013
25     1456.234       26   2013
26      419.261       27   2013
27      264.316       28   2013
28      919.175       29   2013
29       56.148       30   2013
30    11200.086       31   2013
31                    32   2013
32        3.439       33   2013
33      123.904       34   2013
34      346.088       35   2013
35                    36   2013
36     2465.004       37   2013
37     5324.592       38   2013
38                    39   2013
39      547.463       40   2013
40                    41   2013
41     6889.682       42   2013
42                    43   2013
0     59566.150        1   2014
1     68185.153        2   2014
2     39865.979        3   2014
3       179.725        4   2014
4      1831.900        5   2014
5      3501.892        6   2014
6       951.333        7   2014
7     23595.013        8   2014
8         0.516        9   2014
9       340.219       10   2014
10     2213.758       11   2014
11     3766.724       12   2014
12      966.664       13   2014
13      203.611       14   2014
14     3736.371       15   2014
15                    16   2014
16                    17   2014
17                    18   2014
18                    19   2014
19      515.477       20   2014
20                    21   2014
21     2535.254       22   2014
22      252.371       23   2014
23    11136.715       24   2014
24     1027.687       25   2014
25     1527.343       26   2014
26      323.216       27   2014
27      247.034       28   2014
28      681.427       29   2014
29       31.900       30   2014
30     8619.003       31   2014
31                    32   2014
32        3.267       33   2014
33      122.184       34   2014
34      321.324       35   2014
35                    36   2014
36     1902.494       37   2014
37     6387.532       38   2014
38      946.862       39   2014
39      453.138       40   2014
40                    41   2014
41     5979.020       42   2014
42                    43   2014
0     60618.471        1   2015
1     67142.824        2   2015
2     41022.267        3   2015
3       178.392        4   2015
4      1936.543        5   2015
5      3537.489        6   2015
6       611.339        7   2015
7     23404.987        8   2015
8                      9   2015
9       419.126       10   2015
10     1900.860       11   2015
11     4416.681       12   2015
12     1020.952       13   2015
13      198.624       14   2015
14     3714.617       15   2015
15                    16   2015
16                    17   2015
17                    18   2015
18                    19   2015
19      497.850       20   2015
20                    21   2015
21     3385.632       22   2015
22      254.021       23   2015
23    11222.614       24   2015
24     1266.294       25   2015
25     1558.469       26   2015
26      377.042       27   2015
27      243.336       28   2015
28      440.327       29   2015
29       33.276       30   2015
30     6524.353       31   2015
31                    32   2015
32        3.353       33   2015
33      130.009       34   2015
34      283.319       35   2015
35                    36   2015
36     2335.512       37   2015
37     6377.902       38   2015
38      928.891       39   2015
39      512.812       40   2015
40                    41   2015
41     4758.126       42   2015
42                    43   2015
0     56678.555        1   2016
1     59315.580        2   2016
2     37340.874        3   2016
3        33.491        4   2016
4      1665.004        5   2016
5      3609.114        6   2016
6       762.273        7   2016
7     22506.019        8   2016
8                      9   2016
9       403.754       10   2016
10     1623.646       11   2016
11     3132.760       12   2016
12      889.463       13   2016
13      223.216       14   2016
14     3061.651       15   2016
15                    16   2016
16                    17   2016
17                    18   2016
18                    19   2016
19      484.265       20   2016
20                    21   2016
21     3157.362       22   2016
22      175.634       23   2016
23    11205.675       24   2016
24     1085.985       25   2016
25     1365.520       26   2016
26      430.782       27   2016
27      240.671       28   2016
28      599.656       29   2016
29       22.614       30   2016
30     2637.025       31   2016
31                    32   2016
32        3.611       33   2016
33      111.608       34   2016
34      248.773       35   2016
35                    36   2016
36     2342.476       37   2016
37     7771.969       38   2016
38     1033.620       39   2016
39      491.917       40   2016
40                    41   2016
41     5124.678       42   2016
42        1.376       43   2016
0     54930.576        1   2017
1     56867.846        2   2017
2     35745.174        3   2017
3         7.816        4   2017
4      1798.288        5   2017
5      3563.525        6   2017
6       533.839        7   2017
7     20744.110        8   2017
8         1.513        9   2017
9       313.376       10   2017
10     1613.500       11   2017
11     3880.224       12   2017
12     1102.163       13   2017
13      117.549       14   2017
14     2805.454       15   2017
15                    16   2017
16        0.018       17   2017
17                    18   2017
18                    19   2017
19      424.076       20   2017
20                    21   2017
21     2689.212       22   2017
22      151.148       23   2017
23    11277.603       24   2017
24     1261.049       25   2017
25     1442.835       26   2017
26      414.800       27   2017
27      257.180       28   2017
28      503.611       29   2017
29       27.687       30   2017
30     1937.270       31   2017
31                    32   2017
32        3.697       33   2017
33      117.102       34   2017
34      291.181       35   2017
35                    36   2017
36     2275.542       37   2017
37     8201.627       38   2017
38     1060.963       39   2017
39      492.344       40   2017
40                    41   2017
41     4112.201       42   2017
42        2.124       43   2017
0     51213.293        1   2018
1     52660.533        2   2018
2     32374.392        3   2018
3         7.850        4   2018
4      1604.426        5   2018
5      3542.689        6   2018
6       564.954        7   2018
7     19617.885        8   2018
8                      9   2018
9       185.011       10   2018
10     1477.657       11   2018
11     3210.748       12   2018
12      723.361       13   2018
13      124.901       14   2018
14     2447.968       15   2018
15                    16   2018
16        0.029       17   2018
17                    18   2018
18                    19   2018
19      401.462       20   2018
20                    21   2018
21     2362.017       22   2018
22      155.226       23   2018
23    11226.393       24   2018
24     1032.361       25   2018
25     1345.271       26   2018
26      397.444       27   2018
27      258.899       28   2018
28      497.936       29   2018
29       28.805       30   2018
30     1447.240       31   2018
31                    32   2018
32        3.794       33   2018
33      133.680       34   2018
34      244.907       35   2018
35                    36   2018
36     2151.296       37   2018
37     9574.849       38   2018
38     1069.390       39   2018
39      481.557       40   2018
40                    41   2018
41     4103.173       42   2018
42        1.015       43   2018

==> On transforme les strings en float

In [72]:
production_electricite_fossile["quantite_tep"] = pd.to_numeric(production_electricite_fossile['quantite_tep'])
production_electricite_fossile

    quantite_tep  pays_id  annee
0      60496.545        1   2009
1      69356.132        2   2009
2      39139.194        3   2009
3        445.228        4   2009
4       1814.531        5   2009
5       3950.645        6   2009
6       1520.808        7   2009
7      21792.347        8   2009
8            NaN        9   2009
9        344.309       10   2009
10      2939.639       11   2009
11      3087.704       12   2009
12      1863.027       13   2009
13       142.562       14   2009
14      3417.455       15   2009
15           NaN       16   2009
16         0.172       17   2009
17           NaN       18   2009
18           NaN       19   2009
19       545.142       20   2009
20           NaN       21   2009
21      2087.532       22   2009
22       323.174       23   2009
23     11469.390       24   2009
24      1108.856       25   2009
25      1869.991       26   2009
26       441.273       27   2009
27       331.470       28   2009
28       957.008       29   2009
29        44.282       30   2009
30      8859.587       31   2009
31           NaN       32   2009
32         3.525       33   2009
33        59.243       34   2009
34       456.148       35   2009
35           NaN       36   2009
36      2309.200       37   2009
37      4662.855       38   2009
38           NaN       39   2009
39       416.251       40   2009
40           NaN       41   2009
41      5414.015       42   2009
42           NaN       43   2009
0      60294.939        1   2010
1      69546.358        2   2010
2      38510.932        3   2010
3        360.877        4   2010
4       1943.766        5   2010
5       4032.674        6   2010
6       1462.253        7   2010
7      22605.073        8   2010
8            NaN        9   2010
9        305.651       10   2010
10      2648.065       11   2010
11      2178.332       12   2010
12      2008.512       13   2010
13       205.073       14   2010
14      3416.509       15   2010
15           NaN       16   2010
16         0.172       17   2010
17           NaN       18   2010
18           NaN       19   2010
19       536.028       20   2010
20           NaN       21   2010
21      1942.218       22   2010
22       422.909       23   2010
23     11738.091       24   2010
24       610.490       25   2010
25      1778.246       26   2010
26       454.686       27   2010
27       306.965       28   2010
28      1250.473       29   2010
29        87.876       30   2010
30      9251.419       31   2010
31           NaN       32   2010
32         3.611       33   2010
33       109.372       34   2010
34       407.825       35   2010
35           NaN       36   2010
36      2151.505       37   2010
37      4589.682       38   2010
38           NaN       39   2010
39       428.977       40   2010
40           NaN       41   2010
41      5787.016       42   2010
42           NaN       43   2010
0      62359.396        1   2011
1      71683.730        2   2011
2      39791.898        3   2011
3        298.882        4   2011
4       2367.756        5   2011
5       4014.187        6   2011
6       1201.720        7   2011
7      22568.358        8   2011
8            NaN        9   2011
9        339.189       10   2011
10      2670.937       11   2011
11      3781.599       12   2011
12      1531.165       13   2011
13       222.012       14   2011
14      3845.744       15   2011
15           NaN       16   2011
16         0.172       17   2011
17           NaN       18   2011
18           NaN       19   2011
19       557.438       20   2011
20           NaN       21   2011
21      1839.209       22   2011
22       467.029       23   2011
23     12017.025       24   2011
24       846.776       25   2011
25      2130.868       26   2011
26       456.320       27   2011
27       305.589       28   2011
28       840.929       29   2011
29        56.492       30   2011
30      9324.334       31   2011
31           NaN       32   2011
32         3.353       33   2011
33       124.850       34   2011
34       444.454       35   2011
35           NaN       36   2011
36      2468.960       37   2011
37      5553.654       38   2011
38           NaN       39   2011
39       487.962       40   2011
40           NaN       41   2011
41      6374.893       42   2011
42           NaN       43   2011
0      63861.407        1   2012
1      76139.395        2   2012
2      42887.030        3   2012
3        291.402        4   2012
4       1966.982        5   2012
5       3781.427        6   2012
6        906.191        7   2012
7      23751.333        8   2012
8            NaN        9   2012
9        432.017       10   2012
10      2675.752       11   2012
11      4735.512       12   2012
12      1844.366       13   2012
13       192.433       14   2012
14      4225.365       15   2012
15           NaN       16   2012
16         0.172       17   2012
17           NaN       18   2012
18           NaN       19   2012
19       545.486       20   2012
20           NaN       21   2012
21      2081.857       22   2012
22       377.286       23   2012
23     11571.195       24   2012
24      1125.279       25   2012
25      1969.132       26   2012
26       442.390       27   2012
27       293.723       28   2012
28       610.576       29   2012
29        41.531       30   2012
30     12277.988       31   2012
31           NaN       32   2012
32         3.353       33   2012
33       117.541       34   2012
34       415.477       35   2012
35           NaN       36   2012
36      2262.769       37   2012
37      5703.525       38   2012
38           NaN       39   2012
39       501.548       40   2012
40           NaN       41   2012
41      6876.440       42   2012
42           NaN       43   2012
0      62675.652        1   2013
1      73875.738        2   2013
2      42140.432        3   2013
3        258.641        4   2013
4       1667.377        5   2013
5       3535.082        6   2013
6       1228.891        7   2013
7      24780.911        8   2013
8          1.118        9   2013
9        368.233       10   2013
10      2270.507       11   2013
11      3434.308       12   2013
12      2049.097       13   2013
13       208.169       14   2013
14      3878.332       15   2013
15           NaN       16   2013
16         0.086       17   2013
17           NaN       18   2013
18           NaN       19   2013
19       541.702       20   2013
20           NaN       21   2013
21      2116.423       22   2013
22       362.139       23   2013
23     11841.617       24   2013
24      1017.885       25   2013
25      1456.234       26   2013
26       419.261       27   2013
27       264.316       28   2013
28       919.175       29   2013
29        56.148       30   2013
30     11200.086       31   2013
31           NaN       32   2013
32         3.439       33   2013
33       123.904       34   2013
34       346.088       35   2013
35           NaN       36   2013
36      2465.004       37   2013
37      5324.592       38   2013
38           NaN       39   2013
39       547.463       40   2013
40           NaN       41   2013
41      6889.682       42   2013
42           NaN       43   2013
0      59566.150        1   2014
1      68185.153        2   2014
2      39865.979        3   2014
3        179.725        4   2014
4       1831.900        5   2014
5       3501.892        6   2014
6        951.333        7   2014
7      23595.013        8   2014
8          0.516        9   2014
9        340.219       10   2014
10      2213.758       11   2014
11      3766.724       12   2014
12       966.664       13   2014
13       203.611       14   2014
14      3736.371       15   2014
15           NaN       16   2014
16           NaN       17   2014
17           NaN       18   2014
18           NaN       19   2014
19       515.477       20   2014
20           NaN       21   2014
21      2535.254       22   2014
22       252.371       23   2014
23     11136.715       24   2014
24      1027.687       25   2014
25      1527.343       26   2014
26       323.216       27   2014
27       247.034       28   2014
28       681.427       29   2014
29        31.900       30   2014
30      8619.003       31   2014
31           NaN       32   2014
32         3.267       33   2014
33       122.184       34   2014
34       321.324       35   2014
35           NaN       36   2014
36      1902.494       37   2014
37      6387.532       38   2014
38       946.862       39   2014
39       453.138       40   2014
40           NaN       41   2014
41      5979.020       42   2014
42           NaN       43   2014
0      60618.471        1   2015
1      67142.824        2   2015
2      41022.267        3   2015
3        178.392        4   2015
4       1936.543        5   2015
5       3537.489        6   2015
6        611.339        7   2015
7      23404.987        8   2015
8            NaN        9   2015
9        419.126       10   2015
10      1900.860       11   2015
11      4416.681       12   2015
12      1020.952       13   2015
13       198.624       14   2015
14      3714.617       15   2015
15           NaN       16   2015
16           NaN       17   2015
17           NaN       18   2015
18           NaN       19   2015
19       497.850       20   2015
20           NaN       21   2015
21      3385.632       22   2015
22       254.021       23   2015
23     11222.614       24   2015
24      1266.294       25   2015
25      1558.469       26   2015
26       377.042       27   2015
27       243.336       28   2015
28       440.327       29   2015
29        33.276       30   2015
30      6524.353       31   2015
31           NaN       32   2015
32         3.353       33   2015
33       130.009       34   2015
34       283.319       35   2015
35           NaN       36   2015
36      2335.512       37   2015
37      6377.902       38   2015
38       928.891       39   2015
39       512.812       40   2015
40           NaN       41   2015
41      4758.126       42   2015
42           NaN       43   2015
0      56678.555        1   2016
1      59315.580        2   2016
2      37340.874        3   2016
3         33.491        4   2016
4       1665.004        5   2016
5       3609.114        6   2016
6        762.273        7   2016
7      22506.019        8   2016
8            NaN        9   2016
9        403.754       10   2016
10      1623.646       11   2016
11      3132.760       12   2016
12       889.463       13   2016
13       223.216       14   2016
14      3061.651       15   2016
15           NaN       16   2016
16           NaN       17   2016
17           NaN       18   2016
18           NaN       19   2016
19       484.265       20   2016
20           NaN       21   2016
21      3157.362       22   2016
22       175.634       23   2016
23     11205.675       24   2016
24      1085.985       25   2016
25      1365.520       26   2016
26       430.782       27   2016
27       240.671       28   2016
28       599.656       29   2016
29        22.614       30   2016
30      2637.025       31   2016
31           NaN       32   2016
32         3.611       33   2016
33       111.608       34   2016
34       248.773       35   2016
35           NaN       36   2016
36      2342.476       37   2016
37      7771.969       38   2016
38      1033.620       39   2016
39       491.917       40   2016
40           NaN       41   2016
41      5124.678       42   2016
42         1.376       43   2016
0      54930.576        1   2017
1      56867.846        2   2017
2      35745.174        3   2017
3          7.816        4   2017
4       1798.288        5   2017
5       3563.525        6   2017
6        533.839        7   2017
7      20744.110        8   2017
8          1.513        9   2017
9        313.376       10   2017
10      1613.500       11   2017
11      3880.224       12   2017
12      1102.163       13   2017
13       117.549       14   2017
14      2805.454       15   2017
15           NaN       16   2017
16         0.018       17   2017
17           NaN       18   2017
18           NaN       19   2017
19       424.076       20   2017
20           NaN       21   2017
21      2689.212       22   2017
22       151.148       23   2017
23     11277.603       24   2017
24      1261.049       25   2017
25      1442.835       26   2017
26       414.800       27   2017
27       257.180       28   2017
28       503.611       29   2017
29        27.687       30   2017
30      1937.270       31   2017
31           NaN       32   2017
32         3.697       33   2017
33       117.102       34   2017
34       291.181       35   2017
35           NaN       36   2017
36      2275.542       37   2017
37      8201.627       38   2017
38      1060.963       39   2017
39       492.344       40   2017
40           NaN       41   2017
41      4112.201       42   2017
42         2.124       43   2017
0      51213.293        1   2018
1      52660.533        2   2018
2      32374.392        3   2018
3          7.850        4   2018
4       1604.426        5   2018
5       3542.689        6   2018
6        564.954        7   2018
7      19617.885        8   2018
8            NaN        9   2018
9        185.011       10   2018
10      1477.657       11   2018
11      3210.748       12   2018
12       723.361       13   2018
13       124.901       14   2018
14      2447.968       15   2018
15           NaN       16   2018
16         0.029       17   2018
17           NaN       18   2018
18           NaN       19   2018
19       401.462       20   2018
20           NaN       21   2018
21      2362.017       22   2018
22       155.226       23   2018
23     11226.393       24   2018
24      1032.361       25   2018
25      1345.271       26   2018
26       397.444       27   2018
27       258.899       28   2018
28       497.936       29   2018
29        28.805       30   2018
30      1447.240       31   2018
31           NaN       32   2018
32         3.794       33   2018
33       133.680       34   2018
34       244.907       35   2018
35           NaN       36   2018
36      2151.296       37   2018
37      9574.849       38   2018
38      1069.390       39   2018
39       481.557       40   2018
40           NaN       41   2018
41      4103.173       42   2018
42         1.015       43   2018

In [73]:
production_electricite_fossile.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 430 entries, 0 to 42
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   quantite_tep  338 non-null    float64
 1   pays_id       430 non-null    int64
 2   annee         430 non-null    int64
dtypes: float64(1), int64(2)
memory usage: 13.4 KB

==> On ajoute une colonne avec l'id de la futur table.

In [74]:
production_electricite_fossile.insert(0, 'id', range(1, 1 + len(production_electricite_fossile)))
production_electricite_fossile

     id  quantite_tep  pays_id  annee
0     1     60496.545        1   2009
1     2     69356.132        2   2009
2     3     39139.194        3   2009
3     4       445.228        4   2009
4     5      1814.531        5   2009
5     6      3950.645        6   2009
6     7      1520.808        7   2009
7     8     21792.347        8   2009
8     9           NaN        9   2009
9    10       344.309       10   2009
10   11      2939.639       11   2009
11   12      3087.704       12   2009
12   13      1863.027       13   2009
13   14       142.562       14   2009
14   15      3417.455       15   2009
15   16           NaN       16   2009
16   17         0.172       17   2009
17   18           NaN       18   2009
18   19           NaN       19   2009
19   20       545.142       20   2009
20   21           NaN       21   2009
21   22      2087.532       22   2009
22   23       323.174       23   2009
23   24     11469.390       24   2009
24   25      1108.856       25   2009
25   26      1869.991       26   2009
26   27       441.273       27   2009
27   28       331.470       28   2009
28   29       957.008       29   2009
29   30        44.282       30   2009
30   31      8859.587       31   2009
31   32           NaN       32   2009
32   33         3.525       33   2009
33   34        59.243       34   2009
34   35       456.148       35   2009
35   36           NaN       36   2009
36   37      2309.200       37   2009
37   38      4662.855       38   2009
38   39           NaN       39   2009
39   40       416.251       40   2009
40   41           NaN       41   2009
41   42      5414.015       42   2009
42   43           NaN       43   2009
0    44     60294.939        1   2010
1    45     69546.358        2   2010
2    46     38510.932        3   2010
3    47       360.877        4   2010
4    48      1943.766        5   2010
5    49      4032.674        6   2010
6    50      1462.253        7   2010
7    51     22605.073        8   2010
8    52           NaN        9   2010
9    53       305.651       10   2010
10   54      2648.065       11   2010
11   55      2178.332       12   2010
12   56      2008.512       13   2010
13   57       205.073       14   2010
14   58      3416.509       15   2010
15   59           NaN       16   2010
16   60         0.172       17   2010
17   61           NaN       18   2010
18   62           NaN       19   2010
19   63       536.028       20   2010
20   64           NaN       21   2010
21   65      1942.218       22   2010
22   66       422.909       23   2010
23   67     11738.091       24   2010
24   68       610.490       25   2010
25   69      1778.246       26   2010
26   70       454.686       27   2010
27   71       306.965       28   2010
28   72      1250.473       29   2010
29   73        87.876       30   2010
30   74      9251.419       31   2010
31   75           NaN       32   2010
32   76         3.611       33   2010
33   77       109.372       34   2010
34   78       407.825       35   2010
35   79           NaN       36   2010
36   80      2151.505       37   2010
37   81      4589.682       38   2010
38   82           NaN       39   2010
39   83       428.977       40   2010
40   84           NaN       41   2010
41   85      5787.016       42   2010
42   86           NaN       43   2010
0    87     62359.396        1   2011
1    88     71683.730        2   2011
2    89     39791.898        3   2011
3    90       298.882        4   2011
4    91      2367.756        5   2011
5    92      4014.187        6   2011
6    93      1201.720        7   2011
7    94     22568.358        8   2011
8    95           NaN        9   2011
9    96       339.189       10   2011
10   97      2670.937       11   2011
11   98      3781.599       12   2011
12   99      1531.165       13   2011
13  100       222.012       14   2011
14  101      3845.744       15   2011
15  102           NaN       16   2011
16  103         0.172       17   2011
17  104           NaN       18   2011
18  105           NaN       19   2011
19  106       557.438       20   2011
20  107           NaN       21   2011
21  108      1839.209       22   2011
22  109       467.029       23   2011
23  110     12017.025       24   2011
24  111       846.776       25   2011
25  112      2130.868       26   2011
26  113       456.320       27   2011
27  114       305.589       28   2011
28  115       840.929       29   2011
29  116        56.492       30   2011
30  117      9324.334       31   2011
31  118           NaN       32   2011
32  119         3.353       33   2011
33  120       124.850       34   2011
34  121       444.454       35   2011
35  122           NaN       36   2011
36  123      2468.960       37   2011
37  124      5553.654       38   2011
38  125           NaN       39   2011
39  126       487.962       40   2011
40  127           NaN       41   2011
41  128      6374.893       42   2011
42  129           NaN       43   2011
0   130     63861.407        1   2012
1   131     76139.395        2   2012
2   132     42887.030        3   2012
3   133       291.402        4   2012
4   134      1966.982        5   2012
5   135      3781.427        6   2012
6   136       906.191        7   2012
7   137     23751.333        8   2012
8   138           NaN        9   2012
9   139       432.017       10   2012
10  140      2675.752       11   2012
11  141      4735.512       12   2012
12  142      1844.366       13   2012
13  143       192.433       14   2012
14  144      4225.365       15   2012
15  145           NaN       16   2012
16  146         0.172       17   2012
17  147           NaN       18   2012
18  148           NaN       19   2012
19  149       545.486       20   2012
20  150           NaN       21   2012
21  151      2081.857       22   2012
22  152       377.286       23   2012
23  153     11571.195       24   2012
24  154      1125.279       25   2012
25  155      1969.132       26   2012
26  156       442.390       27   2012
27  157       293.723       28   2012
28  158       610.576       29   2012
29  159        41.531       30   2012
30  160     12277.988       31   2012
31  161           NaN       32   2012
32  162         3.353       33   2012
33  163       117.541       34   2012
34  164       415.477       35   2012
35  165           NaN       36   2012
36  166      2262.769       37   2012
37  167      5703.525       38   2012
38  168           NaN       39   2012
39  169       501.548       40   2012
40  170           NaN       41   2012
41  171      6876.440       42   2012
42  172           NaN       43   2012
0   173     62675.652        1   2013
1   174     73875.738        2   2013
2   175     42140.432        3   2013
3   176       258.641        4   2013
4   177      1667.377        5   2013
5   178      3535.082        6   2013
6   179      1228.891        7   2013
7   180     24780.911        8   2013
8   181         1.118        9   2013
9   182       368.233       10   2013
10  183      2270.507       11   2013
11  184      3434.308       12   2013
12  185      2049.097       13   2013
13  186       208.169       14   2013
14  187      3878.332       15   2013
15  188           NaN       16   2013
16  189         0.086       17   2013
17  190           NaN       18   2013
18  191           NaN       19   2013
19  192       541.702       20   2013
20  193           NaN       21   2013
21  194      2116.423       22   2013
22  195       362.139       23   2013
23  196     11841.617       24   2013
24  197      1017.885       25   2013
25  198      1456.234       26   2013
26  199       419.261       27   2013
27  200       264.316       28   2013
28  201       919.175       29   2013
29  202        56.148       30   2013
30  203     11200.086       31   2013
31  204           NaN       32   2013
32  205         3.439       33   2013
33  206       123.904       34   2013
34  207       346.088       35   2013
35  208           NaN       36   2013
36  209      2465.004       37   2013
37  210      5324.592       38   2013
38  211           NaN       39   2013
39  212       547.463       40   2013
40  213           NaN       41   2013
41  214      6889.682       42   2013
42  215           NaN       43   2013
0   216     59566.150        1   2014
1   217     68185.153        2   2014
2   218     39865.979        3   2014
3   219       179.725        4   2014
4   220      1831.900        5   2014
5   221      3501.892        6   2014
6   222       951.333        7   2014
7   223     23595.013        8   2014
8   224         0.516        9   2014
9   225       340.219       10   2014
10  226      2213.758       11   2014
11  227      3766.724       12   2014
12  228       966.664       13   2014
13  229       203.611       14   2014
14  230      3736.371       15   2014
15  231           NaN       16   2014
16  232           NaN       17   2014
17  233           NaN       18   2014
18  234           NaN       19   2014
19  235       515.477       20   2014
20  236           NaN       21   2014
21  237      2535.254       22   2014
22  238       252.371       23   2014
23  239     11136.715       24   2014
24  240      1027.687       25   2014
25  241      1527.343       26   2014
26  242       323.216       27   2014
27  243       247.034       28   2014
28  244       681.427       29   2014
29  245        31.900       30   2014
30  246      8619.003       31   2014
31  247           NaN       32   2014
32  248         3.267       33   2014
33  249       122.184       34   2014
34  250       321.324       35   2014
35  251           NaN       36   2014
36  252      1902.494       37   2014
37  253      6387.532       38   2014
38  254       946.862       39   2014
39  255       453.138       40   2014
40  256           NaN       41   2014
41  257      5979.020       42   2014
42  258           NaN       43   2014
0   259     60618.471        1   2015
1   260     67142.824        2   2015
2   261     41022.267        3   2015
3   262       178.392        4   2015
4   263      1936.543        5   2015
5   264      3537.489        6   2015
6   265       611.339        7   2015
7   266     23404.987        8   2015
8   267           NaN        9   2015
9   268       419.126       10   2015
10  269      1900.860       11   2015
11  270      4416.681       12   2015
12  271      1020.952       13   2015
13  272       198.624       14   2015
14  273      3714.617       15   2015
15  274           NaN       16   2015
16  275           NaN       17   2015
17  276           NaN       18   2015
18  277           NaN       19   2015
19  278       497.850       20   2015
20  279           NaN       21   2015
21  280      3385.632       22   2015
22  281       254.021       23   2015
23  282     11222.614       24   2015
24  283      1266.294       25   2015
25  284      1558.469       26   2015
26  285       377.042       27   2015
27  286       243.336       28   2015
28  287       440.327       29   2015
29  288        33.276       30   2015
30  289      6524.353       31   2015
31  290           NaN       32   2015
32  291         3.353       33   2015
33  292       130.009       34   2015
34  293       283.319       35   2015
35  294           NaN       36   2015
36  295      2335.512       37   2015
37  296      6377.902       38   2015
38  297       928.891       39   2015
39  298       512.812       40   2015
40  299           NaN       41   2015
41  300      4758.126       42   2015
42  301           NaN       43   2015
0   302     56678.555        1   2016
1   303     59315.580        2   2016
2   304     37340.874        3   2016
3   305        33.491        4   2016
4   306      1665.004        5   2016
5   307      3609.114        6   2016
6   308       762.273        7   2016
7   309     22506.019        8   2016
8   310           NaN        9   2016
9   311       403.754       10   2016
10  312      1623.646       11   2016
11  313      3132.760       12   2016
12  314       889.463       13   2016
13  315       223.216       14   2016
14  316      3061.651       15   2016
15  317           NaN       16   2016
16  318           NaN       17   2016
17  319           NaN       18   2016
18  320           NaN       19   2016
19  321       484.265       20   2016
20  322           NaN       21   2016
21  323      3157.362       22   2016
22  324       175.634       23   2016
23  325     11205.675       24   2016
24  326      1085.985       25   2016
25  327      1365.520       26   2016
26  328       430.782       27   2016
27  329       240.671       28   2016
28  330       599.656       29   2016
29  331        22.614       30   2016
30  332      2637.025       31   2016
31  333           NaN       32   2016
32  334         3.611       33   2016
33  335       111.608       34   2016
34  336       248.773       35   2016
35  337           NaN       36   2016
36  338      2342.476       37   2016
37  339      7771.969       38   2016
38  340      1033.620       39   2016
39  341       491.917       40   2016
40  342           NaN       41   2016
41  343      5124.678       42   2016
42  344         1.376       43   2016
0   345     54930.576        1   2017
1   346     56867.846        2   2017
2   347     35745.174        3   2017
3   348         7.816        4   2017
4   349      1798.288        5   2017
5   350      3563.525        6   2017
6   351       533.839        7   2017
7   352     20744.110        8   2017
8   353         1.513        9   2017
9   354       313.376       10   2017
10  355      1613.500       11   2017
11  356      3880.224       12   2017
12  357      1102.163       13   2017
13  358       117.549       14   2017
14  359      2805.454       15   2017
15  360           NaN       16   2017
16  361         0.018       17   2017
17  362           NaN       18   2017
18  363           NaN       19   2017
19  364       424.076       20   2017
20  365           NaN       21   2017
21  366      2689.212       22   2017
22  367       151.148       23   2017
23  368     11277.603       24   2017
24  369      1261.049       25   2017
25  370      1442.835       26   2017
26  371       414.800       27   2017
27  372       257.180       28   2017
28  373       503.611       29   2017
29  374        27.687       30   2017
30  375      1937.270       31   2017
31  376           NaN       32   2017
32  377         3.697       33   2017
33  378       117.102       34   2017
34  379       291.181       35   2017
35  380           NaN       36   2017
36  381      2275.542       37   2017
37  382      8201.627       38   2017
38  383      1060.963       39   2017
39  384       492.344       40   2017
40  385           NaN       41   2017
41  386      4112.201       42   2017
42  387         2.124       43   2017
0   388     51213.293        1   2018
1   389     52660.533        2   2018
2   390     32374.392        3   2018
3   391         7.850        4   2018
4   392      1604.426        5   2018
5   393      3542.689        6   2018
6   394       564.954        7   2018
7   395     19617.885        8   2018
8   396           NaN        9   2018
9   397       185.011       10   2018
10  398      1477.657       11   2018
11  399      3210.748       12   2018
12  400       723.361       13   2018
13  401       124.901       14   2018
14  402      2447.968       15   2018
15  403           NaN       16   2018
16  404         0.029       17   2018
17  405           NaN       18   2018
18  406           NaN       19   2018
19  407       401.462       20   2018
20  408           NaN       21   2018
21  409      2362.017       22   2018
22  410       155.226       23   2018
23  411     11226.393       24   2018
24  412      1032.361       25   2018
25  413      1345.271       26   2018
26  414       397.444       27   2018
27  415       258.899       28   2018
28  416       497.936       29   2018
29  417        28.805       30   2018
30  418      1447.240       31   2018
31  419           NaN       32   2018
32  420         3.794       33   2018
33  421       133.680       34   2018
34  422       244.907       35   2018
35  423           NaN       36   2018
36  424      2151.296       37   2018
37  425      9574.849       38   2018
38  426      1069.390       39   2018
39  427       481.557       40   2018
40  428           NaN       41   2018
41  429      4103.173       42   2018
42  430         1.015       43   2018

==> On ordonne les colonnes pour correspondre à notre table en base de données.

In [75]:
production_electricite_fossile = production_electricite_fossile[['id','pays_id','annee','quantite_tep']]
production_electricite_fossile

     id  pays_id  annee  quantite_tep
0     1        1   2009     60496.545
1     2        2   2009     69356.132
2     3        3   2009     39139.194
3     4        4   2009       445.228
4     5        5   2009      1814.531
5     6        6   2009      3950.645
6     7        7   2009      1520.808
7     8        8   2009     21792.347
8     9        9   2009           NaN
9    10       10   2009       344.309
10   11       11   2009      2939.639
11   12       12   2009      3087.704
12   13       13   2009      1863.027
13   14       14   2009       142.562
14   15       15   2009      3417.455
15   16       16   2009           NaN
16   17       17   2009         0.172
17   18       18   2009           NaN
18   19       19   2009           NaN
19   20       20   2009       545.142
20   21       21   2009           NaN
21   22       22   2009      2087.532
22   23       23   2009       323.174
23   24       24   2009     11469.390
24   25       25   2009      1108.856
25   26       26   2009      1869.991
26   27       27   2009       441.273
27   28       28   2009       331.470
28   29       29   2009       957.008
29   30       30   2009        44.282
30   31       31   2009      8859.587
31   32       32   2009           NaN
32   33       33   2009         3.525
33   34       34   2009        59.243
34   35       35   2009       456.148
35   36       36   2009           NaN
36   37       37   2009      2309.200
37   38       38   2009      4662.855
38   39       39   2009           NaN
39   40       40   2009       416.251
40   41       41   2009           NaN
41   42       42   2009      5414.015
42   43       43   2009           NaN
0    44        1   2010     60294.939
1    45        2   2010     69546.358
2    46        3   2010     38510.932
3    47        4   2010       360.877
4    48        5   2010      1943.766
5    49        6   2010      4032.674
6    50        7   2010      1462.253
7    51        8   2010     22605.073
8    52        9   2010           NaN
9    53       10   2010       305.651
10   54       11   2010      2648.065
11   55       12   2010      2178.332
12   56       13   2010      2008.512
13   57       14   2010       205.073
14   58       15   2010      3416.509
15   59       16   2010           NaN
16   60       17   2010         0.172
17   61       18   2010           NaN
18   62       19   2010           NaN
19   63       20   2010       536.028
20   64       21   2010           NaN
21   65       22   2010      1942.218
22   66       23   2010       422.909
23   67       24   2010     11738.091
24   68       25   2010       610.490
25   69       26   2010      1778.246
26   70       27   2010       454.686
27   71       28   2010       306.965
28   72       29   2010      1250.473
29   73       30   2010        87.876
30   74       31   2010      9251.419
31   75       32   2010           NaN
32   76       33   2010         3.611
33   77       34   2010       109.372
34   78       35   2010       407.825
35   79       36   2010           NaN
36   80       37   2010      2151.505
37   81       38   2010      4589.682
38   82       39   2010           NaN
39   83       40   2010       428.977
40   84       41   2010           NaN
41   85       42   2010      5787.016
42   86       43   2010           NaN
0    87        1   2011     62359.396
1    88        2   2011     71683.730
2    89        3   2011     39791.898
3    90        4   2011       298.882
4    91        5   2011      2367.756
5    92        6   2011      4014.187
6    93        7   2011      1201.720
7    94        8   2011     22568.358
8    95        9   2011           NaN
9    96       10   2011       339.189
10   97       11   2011      2670.937
11   98       12   2011      3781.599
12   99       13   2011      1531.165
13  100       14   2011       222.012
14  101       15   2011      3845.744
15  102       16   2011           NaN
16  103       17   2011         0.172
17  104       18   2011           NaN
18  105       19   2011           NaN
19  106       20   2011       557.438
20  107       21   2011           NaN
21  108       22   2011      1839.209
22  109       23   2011       467.029
23  110       24   2011     12017.025
24  111       25   2011       846.776
25  112       26   2011      2130.868
26  113       27   2011       456.320
27  114       28   2011       305.589
28  115       29   2011       840.929
29  116       30   2011        56.492
30  117       31   2011      9324.334
31  118       32   2011           NaN
32  119       33   2011         3.353
33  120       34   2011       124.850
34  121       35   2011       444.454
35  122       36   2011           NaN
36  123       37   2011      2468.960
37  124       38   2011      5553.654
38  125       39   2011           NaN
39  126       40   2011       487.962
40  127       41   2011           NaN
41  128       42   2011      6374.893
42  129       43   2011           NaN
0   130        1   2012     63861.407
1   131        2   2012     76139.395
2   132        3   2012     42887.030
3   133        4   2012       291.402
4   134        5   2012      1966.982
5   135        6   2012      3781.427
6   136        7   2012       906.191
7   137        8   2012     23751.333
8   138        9   2012           NaN
9   139       10   2012       432.017
10  140       11   2012      2675.752
11  141       12   2012      4735.512
12  142       13   2012      1844.366
13  143       14   2012       192.433
14  144       15   2012      4225.365
15  145       16   2012           NaN
16  146       17   2012         0.172
17  147       18   2012           NaN
18  148       19   2012           NaN
19  149       20   2012       545.486
20  150       21   2012           NaN
21  151       22   2012      2081.857
22  152       23   2012       377.286
23  153       24   2012     11571.195
24  154       25   2012      1125.279
25  155       26   2012      1969.132
26  156       27   2012       442.390
27  157       28   2012       293.723
28  158       29   2012       610.576
29  159       30   2012        41.531
30  160       31   2012     12277.988
31  161       32   2012           NaN
32  162       33   2012         3.353
33  163       34   2012       117.541
34  164       35   2012       415.477
35  165       36   2012           NaN
36  166       37   2012      2262.769
37  167       38   2012      5703.525
38  168       39   2012           NaN
39  169       40   2012       501.548
40  170       41   2012           NaN
41  171       42   2012      6876.440
42  172       43   2012           NaN
0   173        1   2013     62675.652
1   174        2   2013     73875.738
2   175        3   2013     42140.432
3   176        4   2013       258.641
4   177        5   2013      1667.377
5   178        6   2013      3535.082
6   179        7   2013      1228.891
7   180        8   2013     24780.911
8   181        9   2013         1.118
9   182       10   2013       368.233
10  183       11   2013      2270.507
11  184       12   2013      3434.308
12  185       13   2013      2049.097
13  186       14   2013       208.169
14  187       15   2013      3878.332
15  188       16   2013           NaN
16  189       17   2013         0.086
17  190       18   2013           NaN
18  191       19   2013           NaN
19  192       20   2013       541.702
20  193       21   2013           NaN
21  194       22   2013      2116.423
22  195       23   2013       362.139
23  196       24   2013     11841.617
24  197       25   2013      1017.885
25  198       26   2013      1456.234
26  199       27   2013       419.261
27  200       28   2013       264.316
28  201       29   2013       919.175
29  202       30   2013        56.148
30  203       31   2013     11200.086
31  204       32   2013           NaN
32  205       33   2013         3.439
33  206       34   2013       123.904
34  207       35   2013       346.088
35  208       36   2013           NaN
36  209       37   2013      2465.004
37  210       38   2013      5324.592
38  211       39   2013           NaN
39  212       40   2013       547.463
40  213       41   2013           NaN
41  214       42   2013      6889.682
42  215       43   2013           NaN
0   216        1   2014     59566.150
1   217        2   2014     68185.153
2   218        3   2014     39865.979
3   219        4   2014       179.725
4   220        5   2014      1831.900
5   221        6   2014      3501.892
6   222        7   2014       951.333
7   223        8   2014     23595.013
8   224        9   2014         0.516
9   225       10   2014       340.219
10  226       11   2014      2213.758
11  227       12   2014      3766.724
12  228       13   2014       966.664
13  229       14   2014       203.611
14  230       15   2014      3736.371
15  231       16   2014           NaN
16  232       17   2014           NaN
17  233       18   2014           NaN
18  234       19   2014           NaN
19  235       20   2014       515.477
20  236       21   2014           NaN
21  237       22   2014      2535.254
22  238       23   2014       252.371
23  239       24   2014     11136.715
24  240       25   2014      1027.687
25  241       26   2014      1527.343
26  242       27   2014       323.216
27  243       28   2014       247.034
28  244       29   2014       681.427
29  245       30   2014        31.900
30  246       31   2014      8619.003
31  247       32   2014           NaN
32  248       33   2014         3.267
33  249       34   2014       122.184
34  250       35   2014       321.324
35  251       36   2014           NaN
36  252       37   2014      1902.494
37  253       38   2014      6387.532
38  254       39   2014       946.862
39  255       40   2014       453.138
40  256       41   2014           NaN
41  257       42   2014      5979.020
42  258       43   2014           NaN
0   259        1   2015     60618.471
1   260        2   2015     67142.824
2   261        3   2015     41022.267
3   262        4   2015       178.392
4   263        5   2015      1936.543
5   264        6   2015      3537.489
6   265        7   2015       611.339
7   266        8   2015     23404.987
8   267        9   2015           NaN
9   268       10   2015       419.126
10  269       11   2015      1900.860
11  270       12   2015      4416.681
12  271       13   2015      1020.952
13  272       14   2015       198.624
14  273       15   2015      3714.617
15  274       16   2015           NaN
16  275       17   2015           NaN
17  276       18   2015           NaN
18  277       19   2015           NaN
19  278       20   2015       497.850
20  279       21   2015           NaN
21  280       22   2015      3385.632
22  281       23   2015       254.021
23  282       24   2015     11222.614
24  283       25   2015      1266.294
25  284       26   2015      1558.469
26  285       27   2015       377.042
27  286       28   2015       243.336
28  287       29   2015       440.327
29  288       30   2015        33.276
30  289       31   2015      6524.353
31  290       32   2015           NaN
32  291       33   2015         3.353
33  292       34   2015       130.009
34  293       35   2015       283.319
35  294       36   2015           NaN
36  295       37   2015      2335.512
37  296       38   2015      6377.902
38  297       39   2015       928.891
39  298       40   2015       512.812
40  299       41   2015           NaN
41  300       42   2015      4758.126
42  301       43   2015           NaN
0   302        1   2016     56678.555
1   303        2   2016     59315.580
2   304        3   2016     37340.874
3   305        4   2016        33.491
4   306        5   2016      1665.004
5   307        6   2016      3609.114
6   308        7   2016       762.273
7   309        8   2016     22506.019
8   310        9   2016           NaN
9   311       10   2016       403.754
10  312       11   2016      1623.646
11  313       12   2016      3132.760
12  314       13   2016       889.463
13  315       14   2016       223.216
14  316       15   2016      3061.651
15  317       16   2016           NaN
16  318       17   2016           NaN
17  319       18   2016           NaN
18  320       19   2016           NaN
19  321       20   2016       484.265
20  322       21   2016           NaN
21  323       22   2016      3157.362
22  324       23   2016       175.634
23  325       24   2016     11205.675
24  326       25   2016      1085.985
25  327       26   2016      1365.520
26  328       27   2016       430.782
27  329       28   2016       240.671
28  330       29   2016       599.656
29  331       30   2016        22.614
30  332       31   2016      2637.025
31  333       32   2016           NaN
32  334       33   2016         3.611
33  335       34   2016       111.608
34  336       35   2016       248.773
35  337       36   2016           NaN
36  338       37   2016      2342.476
37  339       38   2016      7771.969
38  340       39   2016      1033.620
39  341       40   2016       491.917
40  342       41   2016           NaN
41  343       42   2016      5124.678
42  344       43   2016         1.376
0   345        1   2017     54930.576
1   346        2   2017     56867.846
2   347        3   2017     35745.174
3   348        4   2017         7.816
4   349        5   2017      1798.288
5   350        6   2017      3563.525
6   351        7   2017       533.839
7   352        8   2017     20744.110
8   353        9   2017         1.513
9   354       10   2017       313.376
10  355       11   2017      1613.500
11  356       12   2017      3880.224
12  357       13   2017      1102.163
13  358       14   2017       117.549
14  359       15   2017      2805.454
15  360       16   2017           NaN
16  361       17   2017         0.018
17  362       18   2017           NaN
18  363       19   2017           NaN
19  364       20   2017       424.076
20  365       21   2017           NaN
21  366       22   2017      2689.212
22  367       23   2017       151.148
23  368       24   2017     11277.603
24  369       25   2017      1261.049
25  370       26   2017      1442.835
26  371       27   2017       414.800
27  372       28   2017       257.180
28  373       29   2017       503.611
29  374       30   2017        27.687
30  375       31   2017      1937.270
31  376       32   2017           NaN
32  377       33   2017         3.697
33  378       34   2017       117.102
34  379       35   2017       291.181
35  380       36   2017           NaN
36  381       37   2017      2275.542
37  382       38   2017      8201.627
38  383       39   2017      1060.963
39  384       40   2017       492.344
40  385       41   2017           NaN
41  386       42   2017      4112.201
42  387       43   2017         2.124
0   388        1   2018     51213.293
1   389        2   2018     52660.533
2   390        3   2018     32374.392
3   391        4   2018         7.850
4   392        5   2018      1604.426
5   393        6   2018      3542.689
6   394        7   2018       564.954
7   395        8   2018     19617.885
8   396        9   2018           NaN
9   397       10   2018       185.011
10  398       11   2018      1477.657
11  399       12   2018      3210.748
12  400       13   2018       723.361
13  401       14   2018       124.901
14  402       15   2018      2447.968
15  403       16   2018           NaN
16  404       17   2018         0.029
17  405       18   2018           NaN
18  406       19   2018           NaN
19  407       20   2018       401.462
20  408       21   2018           NaN
21  409       22   2018      2362.017
22  410       23   2018       155.226
23  411       24   2018     11226.393
24  412       25   2018      1032.361
25  413       26   2018      1345.271
26  414       27   2018       397.444
27  415       28   2018       258.899
28  416       29   2018       497.936
29  417       30   2018        28.805
30  418       31   2018      1447.240
31  419       32   2018           NaN
32  420       33   2018         3.794
33  421       34   2018       133.680
34  422       35   2018       244.907
35  423       36   2018           NaN
36  424       37   2018      2151.296
37  425       38   2018      9574.849
38  426       39   2018      1069.390
39  427       40   2018       481.557
40  428       41   2018           NaN
41  429       42   2018      4103.173
42  430       43   2018         1.015

### 1.4. Création du fichier 'production_electricite_fossile_table.tsv"

In [76]:
#production_electricite_fossile.to_csv('production_electricite_fossile_table.tsv',index=False,header=['id','pays_id','annee','quantite_tep'], sep='\t')

## 2. Les énergie renouvelables (TEP)

![image](capture_ecran/production_electricite_renouvelable.png)

Nous avons sélectionné parmis l'ensemble de ce dataset le combustible rassemblant l'ensemble des énergies renouvelables nommé "Renouvelables et biocarburants" en Europe de 2009 à 2018 en milliers de tonnes équivalent pétrole.

In [77]:
data2 = pd.read_csv('data/nrg_bal_peh_1_renouvelables.tsv', sep='[|\t]', engine='python', encoding = "ISO-8859-1")
data2

,"GEO,NRG_BAL,SIEC,UNIT\TIME",2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,"Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","51.552,228","58.628,867","57.692,693","65.027,849","71.850,431","74.476,702","75.990,530","77.295,623","77.694,057","83.301,821"
1,"Union européenne - 28 pays (2013-2020),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","54.039,770","61.150,949","60.970,325","68.829,735","76.675,722","80.272,653","83.326,362","84.567,113","86.284,800","92.814,199"
2,"Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","39.937,608","45.552,691","44.857,780","50.520,665","57.496,442","58.724,171","58.598,098","61.083,460","60.968,477","66.595,788"
3,"Belgique,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","590,598","675,015","825,790","1.011,186","1.117,508","1.155,623","1.342,339","1.330,344","1.461,350","1.562,003"
4,"Bulgarie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","369,767","552,364","404,867","522,468","657,027","683,273","795,487","664,894","584,347","823,384"
5,"Tchéquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","447,811","558,406","683,277","756,345","878,193","879,079","919,719","910,213","927,885","900,766"
6,"Danemark,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","865,262","1.068,717","1.219,334","1.275,772","1.372,977","1.546,318","1.628,293","1.581,258","1.875,581","1.785,530"
7,"Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","8.735,082","9.594,153","11.167,498","12.823,474","13.596,131","14.478,332","16.741,702","16.789,338","19.116,767","19.857,008"
8,"Estonie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","46,459","89,758","101,438","126,954","104,864","119,408","129,114","131,013","154,875","171,006"
9,"Irlande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","383,855","335,825","466,345","470,167","513,527","573,622","700,739","671,143","780,980","897,003"
10,"Grèce,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","727,088","906,852","722,921","889,001","1.237,105","1.058,236","1.281,376","1.282,454","1.193,319","1.389,930"
11,"Espagne,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","6.606,277","8.682,992","7.724,592","7.788,360","9.939,208","9.808,213","8.625,649","9.295,161","7.796,389","9.144,798"
12,"France,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","6.417,020","7.137,404","6.119,954","7.750,414","8.979,710","8.577,690","8.322,338","8.930,284","8.405,001","10.206,624"
13,"Croatie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","651,132","808,647","465,793","466,376","806,644","864,475","659,878","736,785","629,063","848,263"
14,"Italie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","6.325,070","6.900,625","7.299,712","8.099,869","9.794,199","10.523,626","9.487,207","9.445,147","9.090,595","9.985,469"
15,"Chypre,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","2,640","6,298","15,323","22,084","28,118","27,250","34,372","36,514","37,421","41,052"
16,"Lettonie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","305,681","312,548","264,597","353,377","303,820","240,964","238,798","299,363","469,622","300,825"
17,"Lituanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","120,286","143,248","145,188","145,881","178,272","189,129","202,444","230,898","268,007","235,013"
18,"Luxembourg,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","85,527","140,014","112,922","117,728","121,162","125,383","160,117","160,786","166,527","165,818"
19,"Hongrie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","248,900","259,629","232,863","227,486","239,664","270,972","277,667","280,149","299,398","322,700"
20,"Malte,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,058","0,851","2,206","3,048","6,439","8,744","11,715","14,791","17,075"
21,"Pays-Bas,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","931,644","962,740","1.059,345","1.073,152","1.040,914","1.001,505","1.176,696","1.270,585","1.499,269","1.623,759"
22,"Autriche,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","4.294,920","4.143,882","3.822,112","4.748,239","4.664,912","4.644,253","4.386,648","4.653,458","4.723,709","4.609,975"
23,"Pologne,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","797,763","985,122","1.166,572","1.488,156","1.515,417","1.753,492","2.002,327","2.002,545","2.114,914","1.894,634"
24,"Portugal,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","1.635,078","2.472,105","2.122,934","1.754,966","2.631,972","2.786,235","2.193,535","2.880,145","2.090,102","2.634,305"
25,"Roumanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","1.360,804","1.776,428","1.421,408","1.306,694","1.762,583","2.373,200","2.285,007","2.362,575","2.118,726","2.289,569"
26,"Slovénie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","421,912","424,135","345,953","388,389","464,614","592,044","398,806","458,924","405,883","466,487"
27,"Slovaquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","442,525","544,621","461,495","499,570","573,603","557,352","542,648","591,230","587,360","524,076"
28,"Finlande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","1.865,946","2.080,418","2.078,810","2.455,648","2.203,755","2.258,867","2.624,826","2.614,958","2.706,510","2.763,562"
29,"Suède,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","6.873,181","7.066,863","7.240,799","8.463,887","7.121,484","7.381,722","8.824,054","7.673,744","8.175,666","7.841,187"
30,"Royaume-Uni,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","2.487,542","2.522,082","3.277,632","3.801,886","4.825,291","5.795,951","7.335,832","7.271,490","8.590,743","9.512,378"
31,"Islande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","1.447,374","1.466,673","1.479,648","1.508,691","1.557,233","1.558,024","1.616,050","1.594,676","1.654,037","1.704,891"
32,"Norvège,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","10.944,196","10.179,278","10.591,144","12.440,585","11.261,909","11.922,614","12.142,820","12.533,620","12.573,087","12.346,615"
33,"Monténégro,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","178,074","236,457","103,513","127,007","215,320","150,615","128,203","158,486","96,380","193,981"
34,"Macédoine du Nord,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","109,230","209,071","123,327","89,734","136,975","111,063","174,444","177,692","111,441","169,006"
35,"Albanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","447,206","650,645","355,288","406,277","598,366","406,229","506,879","669,106","389,181","735,467"
36,"Serbie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","958,212","1.080,911","794,755","852,966","934,910","1.001,290","930,095","996,733","850,280","1.002,437"
37,"Turquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","3.279,547","4.790,449","4.995,672","5.607,654","5.951,859","4.525,253","7.193,311","7.759,618","7.500,897","8.406,527"
38,"Bosnie-Herzégovine,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,:,"510,318","477,300","487,069","345,142","571,883"
39,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","10,318","13,500","9,020","8,218","12,322","13,015","12,062","21,110","15,495","26,177"
40,"Moldavie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","0,000","6,793","6,535","2,914","4,127","6,404","5,839","4,971","6,879","8,598"
41,"Ukraine,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","1.041,935","1.151,419","962,984","1.010,249","1.356,991","946,741","746,036","935,864","1.070,610","1.255,503"
42,"Géorgie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,"711,196","716,710","726,893","802,944","799,501","862,743"

In [78]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   GEO,NRG_BAL,SIEC,UNIT\TIME  43 non-null     object
 1   2009                        43 non-null     object
 2   2010                        43 non-null     object
 3   2011                        43 non-null     object
 4   2012                        43 non-null     object
 5   2013                        43 non-null     object
 6   2014                        43 non-null     object
 7   2015                        43 non-null     object
 8   2016                        43 non-null     object
 9   2017                        43 non-null     object
 10  2018                        43 non-null     object
dtypes: object(11)
memory usage: 3.8+ KB

### 2.1. Split de la colonne GEO,NRG_BAL,SIEC,UNIT\TIME

In [79]:
data2['GEO,NRG_BAL,SIEC,UNIT\TIME']

0                                     Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
1                                            Union européenne - 28 pays (2013-2020),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
2                                            Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
3                                                                          Belgique,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
4                                                                          Bulgarie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
5                                                                          Tchéquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
6                                                                          Danemark,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
7                            Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
8                                                                           Estonie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
9                                                                           Irlande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
10                                                                            Grèce,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
11                                                                          Espagne,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
12                                                                           France,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
13                                                                          Croatie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
14                                                                           Italie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
15                                                                           Chypre,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
16                                                                         Lettonie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
17                                                                         Lituanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
18                                                                       Luxembourg,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
19                                                                          Hongrie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
20                                                                            Malte,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
21                                                                         Pays-Bas,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
22                                                                         Autriche,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
23                                                                          Pologne,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
24                                                                         Portugal,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
25                                                                         Roumanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
26                                                                         Slovénie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
27                                                                        Slovaquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
28                                                                         Finlande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
29                                                                            Suède,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
30                                                                      Royaume-Uni,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
31                                                                          Islande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
32                                                                          Norvège,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
33                                                                       Monténégro,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
34                                                                Macédoine du Nord,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
35                                                                          Albanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
36                                                                           Serbie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
37                                                                          Turquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
38                                                               Bosnie-Herzégovine,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
39    Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
40                                                                         Moldavie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
41                                                                          Ukraine,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
42                                                                          Géorgie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
Name: GEO,NRG_BAL,SIEC,UNIT\TIME, dtype: object

In [80]:
text_columns2 = data2[['GEO,NRG_BAL,SIEC,UNIT\TIME']]
text_columns2

                                                                                                                                                                 GEO,NRG_BAL,SIEC,UNIT\TIME
0                                   Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
1                                          Union européenne - 28 pays (2013-2020),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
2                                          Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
3                                                                        Belgique,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
4                                                                        Bulgarie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
5                                                                        Tchéquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
6                                                                        Danemark,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
7                          Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
8                                                                         Estonie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
9                                                                         Irlande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
10                                                                          Grèce,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
11                                                                        Espagne,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
12                                                                         France,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
13                                                                        Croatie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
14                                                                         Italie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
15                                                                         Chypre,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
16                                                                       Lettonie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
17                                                                       Lituanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
18                                                                     Luxembourg,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
19                                                                        Hongrie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
20                                                                          Malte,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
21                                                                       Pays-Bas,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
22                                                                       Autriche,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
23                                                                        Pologne,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
24                                                                       Portugal,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
25                                                                       Roumanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
26                                                                       Slovénie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
27                                                                      Slovaquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
28                                                                       Finlande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
29                                                                          Suède,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
30                                                                    Royaume-Uni,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
31                                                                        Islande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
32                                                                        Norvège,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
33                                                                     Monténégro,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
34                                                              Macédoine du Nord,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
35                                                                        Albanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
36                                                                         Serbie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
37                                                                        Turquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
38                                                             Bosnie-Herzégovine,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
39  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
40                                                                       Moldavie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
41                                                                        Ukraine,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)
42                                                                        Géorgie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)

In [81]:
text_columns2 = text_columns.replace("Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale")
text_columns2

,"GEO,NRG_BAL,SIEC,UNIT\TIME",GEO,NRG_BAL,SIEC,UNIT\TIME
0,"Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
1,"Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
2,"Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
3,"Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
4,"Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
5,"Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
6,"Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
7,"Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale",Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale,None,None
8,"Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
9,"Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
10,"Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
11,"Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
12,"France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
13,"Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
14,"Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
15,"Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
16,"Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
17,"Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
18,"Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
19,"Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
20,"Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
21,"Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
22,"Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
23,"Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
24,"Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
25,"Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
26,"Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
27,"Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
28,"Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
29,"Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
30,"Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
31,"Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
32,"Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
33,"Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
34,"Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
35,"Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
36,"Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
37,"Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
38,"Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
39,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
40,"Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
41,"Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
42,"Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)

In [82]:
text_columns2[['GEO', 'NRG_BAL', 'SIEC', 'UNIT\TIME']] = text_columns2['GEO,NRG_BAL,SIEC,UNIT\TIME'].str.split(pat=',', n=3,expand=True)
text_columns2

,"GEO,NRG_BAL,SIEC,UNIT\TIME",GEO,NRG_BAL,SIEC,UNIT\TIME
0,"Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
1,"Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
2,"Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
3,"Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
4,"Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
5,"Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
6,"Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
7,"Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale",Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale,None,None
8,"Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
9,"Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
10,"Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
11,"Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
12,"France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
13,"Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
14,"Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
15,"Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
16,"Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
17,"Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
18,"Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
19,"Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
20,"Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
21,"Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
22,"Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
23,"Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
24,"Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
25,"Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
26,"Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
27,"Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
28,"Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
29,"Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
30,"Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
31,"Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
32,"Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
33,"Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
34,"Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
35,"Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
36,"Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
37,"Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
38,"Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
39,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
40,"Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
41,"Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
42,"Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)

In [83]:
new_column2 = text_columns2[['GEO']]
new_column2

                                                                              GEO
0                                   Union européenne - 27 pays (à partir de 2020)
1                                          Union européenne - 28 pays (2013-2020)
2                                          Zone euro - 19 pays (à partir de 2015)
3                                                                        Belgique
4                                                                        Bulgarie
5                                                                        Tchéquie
6                                                                        Danemark
7                             Allemagne jusqu'en 1990 ancien territoire de la RFA
8                                                                         Estonie
9                                                                         Irlande
10                                                                          Grèce
11                                                                        Espagne
12                                                                         France
13                                                                        Croatie
14                                                                         Italie
15                                                                         Chypre
16                                                                       Lettonie
17                                                                       Lituanie
18                                                                     Luxembourg
19                                                                        Hongrie
20                                                                          Malte
21                                                                       Pays-Bas
22                                                                       Autriche
23                                                                        Pologne
24                                                                       Portugal
25                                                                       Roumanie
26                                                                       Slovénie
27                                                                      Slovaquie
28                                                                       Finlande
29                                                                          Suède
30                                                                    Royaume-Uni
31                                                                        Islande
32                                                                        Norvège
33                                                                     Monténégro
34                                                              Macédoine du Nord
35                                                                        Albanie
36                                                                         Serbie
37                                                                        Turquie
38                                                             Bosnie-Herzégovine
39  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40                                                                       Moldavie
41                                                                        Ukraine
42                                                                        Géorgie

In [84]:
df2 = pd.concat([data2, new_column2], axis=1)
df2

,"GEO,NRG_BAL,SIEC,UNIT\TIME",2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO
0,"Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","51.552,228","58.628,867","57.692,693","65.027,849","71.850,431","74.476,702","75.990,530","77.295,623","77.694,057","83.301,821",Union européenne - 27 pays (à partir de 2020)
1,"Union européenne - 28 pays (2013-2020),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","54.039,770","61.150,949","60.970,325","68.829,735","76.675,722","80.272,653","83.326,362","84.567,113","86.284,800","92.814,199",Union européenne - 28 pays (2013-2020)
2,"Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","39.937,608","45.552,691","44.857,780","50.520,665","57.496,442","58.724,171","58.598,098","61.083,460","60.968,477","66.595,788",Zone euro - 19 pays (à partir de 2015)
3,"Belgique,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","590,598","675,015","825,790","1.011,186","1.117,508","1.155,623","1.342,339","1.330,344","1.461,350","1.562,003",Belgique
4,"Bulgarie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","369,767","552,364","404,867","522,468","657,027","683,273","795,487","664,894","584,347","823,384",Bulgarie
5,"Tchéquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","447,811","558,406","683,277","756,345","878,193","879,079","919,719","910,213","927,885","900,766",Tchéquie
6,"Danemark,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","865,262","1.068,717","1.219,334","1.275,772","1.372,977","1.546,318","1.628,293","1.581,258","1.875,581","1.785,530",Danemark
7,"Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","8.735,082","9.594,153","11.167,498","12.823,474","13.596,131","14.478,332","16.741,702","16.789,338","19.116,767","19.857,008",Allemagne jusqu'en 1990 ancien territoire de la RFA
8,"Estonie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","46,459","89,758","101,438","126,954","104,864","119,408","129,114","131,013","154,875","171,006",Estonie
9,"Irlande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","383,855","335,825","466,345","470,167","513,527","573,622","700,739","671,143","780,980","897,003",Irlande
10,"Grèce,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","727,088","906,852","722,921","889,001","1.237,105","1.058,236","1.281,376","1.282,454","1.193,319","1.389,930",Grèce
11,"Espagne,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","6.606,277","8.682,992","7.724,592","7.788,360","9.939,208","9.808,213","8.625,649","9.295,161","7.796,389","9.144,798",Espagne
12,"France,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","6.417,020","7.137,404","6.119,954","7.750,414","8.979,710","8.577,690","8.322,338","8.930,284","8.405,001","10.206,624",France
13,"Croatie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","651,132","808,647","465,793","466,376","806,644","864,475","659,878","736,785","629,063","848,263",Croatie
14,"Italie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","6.325,070","6.900,625","7.299,712","8.099,869","9.794,199","10.523,626","9.487,207","9.445,147","9.090,595","9.985,469",Italie
15,"Chypre,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","2,640","6,298","15,323","22,084","28,118","27,250","34,372","36,514","37,421","41,052",Chypre
16,"Lettonie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","305,681","312,548","264,597","353,377","303,820","240,964","238,798","299,363","469,622","300,825",Lettonie
17,"Lituanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","120,286","143,248","145,188","145,881","178,272","189,129","202,444","230,898","268,007","235,013",Lituanie
18,"Luxembourg,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","85,527","140,014","112,922","117,728","121,162","125,383","160,117","160,786","166,527","165,818",Luxembourg
19,"Hongrie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","248,900","259,629","232,863","227,486","239,664","270,972","277,667","280,149","299,398","322,700",Hongrie
20,"Malte,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","0,000","0,058","0,851","2,206","3,048","6,439","8,744","11,715","14,791","17,075",Malte
21,"Pays-Bas,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","931,644","962,740","1.059,345","1.073,152","1.040,914","1.001,505","1.176,696","1.270,585","1.499,269","1.623,759",Pays-Bas
22,"Autriche,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","4.294,920","4.143,882","3.822,112","4.748,239","4.664,912","4.644,253","4.386,648","4.653,458","4.723,709","4.609,975",Autriche
23,"Pologne,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","797,763","985,122","1.166,572","1.488,156","1.515,417","1.753,492","2.002,327","2.002,545","2.114,914","1.894,634",Pologne
24,"Portugal,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","1.635,078","2.472,105","2.122,934","1.754,966","2.631,972","2.786,235","2.193,535","2.880,145","2.090,102","2.634,305",Portugal
25,"Roumanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","1.360,804","1.776,428","1.421,408","1.306,694","1.762,583","2.373,200","2.285,007","2.362,575","2.118,726","2.289,569",Roumanie
26,"Slovénie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","421,912","424,135","345,953","388,389","464,614","592,044","398,806","458,924","405,883","466,487",Slovénie
27,"Slovaquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","442,525","544,621","461,495","499,570","573,603","557,352","542,648","591,230","587,360","524,076",Slovaquie
28,"Finlande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","1.865,946","2.080,418","2.078,810","2.455,648","2.203,755","2.258,867","2.624,826","2.614,958","2.706,510","2.763,562",Finlande
29,"Suède,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","6.873,181","7.066,863","7.240,799","8.463,887","7.121,484","7.381,722","8.824,054","7.673,744","8.175,666","7.841,187",Suède
30,"Royaume-Uni,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","2.487,542","2.522,082","3.277,632","3.801,886","4.825,291","5.795,951","7.335,832","7.271,490","8.590,743","9.512,378",Royaume-Uni
31,"Islande,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","1.447,374","1.466,673","1.479,648","1.508,691","1.557,233","1.558,024","1.616,050","1.594,676","1.654,037","1.704,891",Islande
32,"Norvège,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","10.944,196","10.179,278","10.591,144","12.440,585","11.261,909","11.922,614","12.142,820","12.533,620","12.573,087","12.346,615",Norvège
33,"Monténégro,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","178,074","236,457","103,513","127,007","215,320","150,615","128,203","158,486","96,380","193,981",Monténégro
34,"Macédoine du Nord,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","109,230","209,071","123,327","89,734","136,975","111,063","174,444","177,692","111,441","169,006",Macédoine du Nord
35,"Albanie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","447,206","650,645","355,288","406,277","598,366","406,229","506,879","669,106","389,181","735,467",Albanie
36,"Serbie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","958,212","1.080,911","794,755","852,966","934,910","1.001,290","930,095","996,733","850,280","1.002,437",Serbie
37,"Turquie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","3.279,547","4.790,449","4.995,672","5.607,654","5.951,859","4.525,253","7.193,311","7.759,618","7.500,897","8.406,527",Turquie
38,"Bosnie-Herzégovine,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,:,"510,318","477,300","487,069","345,142","571,883",Bosnie-Herzégovine
39,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","10,318","13,500","9,020","8,218","12,322","13,015","12,062","21,110","15,495","26,177",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,"Moldavie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","0,000","6,793","6,535","2,914","4,127","6,404","5,839","4,971","6,879","8,598",Moldavie
41,"Ukraine,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)","1.041,935","1.151,419","962,984","1.010,249","1.356,991","946,741","746,036","935,864","1.070,610","1.255,503",Ukraine
42,"Géorgie,Production brute d'électricité,Renouvelables et biocarburants,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,"711,196","716,710","726,893","802,944","799,501","862,743",Géorgie

In [85]:
df2 = df2.drop(columns=['GEO,NRG_BAL,SIEC,UNIT\TIME'])
df2

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO
0,"51.552,228","58.628,867","57.692,693","65.027,849","71.850,431","74.476,702","75.990,530","77.295,623","77.694,057","83.301,821",Union européenne - 27 pays (à partir de 2020)
1,"54.039,770","61.150,949","60.970,325","68.829,735","76.675,722","80.272,653","83.326,362","84.567,113","86.284,800","92.814,199",Union européenne - 28 pays (2013-2020)
2,"39.937,608","45.552,691","44.857,780","50.520,665","57.496,442","58.724,171","58.598,098","61.083,460","60.968,477","66.595,788",Zone euro - 19 pays (à partir de 2015)
3,"590,598","675,015","825,790","1.011,186","1.117,508","1.155,623","1.342,339","1.330,344","1.461,350","1.562,003",Belgique
4,"369,767","552,364","404,867","522,468","657,027","683,273","795,487","664,894","584,347","823,384",Bulgarie
5,"447,811","558,406","683,277","756,345","878,193","879,079","919,719","910,213","927,885","900,766",Tchéquie
6,"865,262","1.068,717","1.219,334","1.275,772","1.372,977","1.546,318","1.628,293","1.581,258","1.875,581","1.785,530",Danemark
7,"8.735,082","9.594,153","11.167,498","12.823,474","13.596,131","14.478,332","16.741,702","16.789,338","19.116,767","19.857,008",Allemagne jusqu'en 1990 ancien territoire de la RFA
8,"46,459","89,758","101,438","126,954","104,864","119,408","129,114","131,013","154,875","171,006",Estonie
9,"383,855","335,825","466,345","470,167","513,527","573,622","700,739","671,143","780,980","897,003",Irlande
10,"727,088","906,852","722,921","889,001","1.237,105","1.058,236","1.281,376","1.282,454","1.193,319","1.389,930",Grèce
11,"6.606,277","8.682,992","7.724,592","7.788,360","9.939,208","9.808,213","8.625,649","9.295,161","7.796,389","9.144,798",Espagne
12,"6.417,020","7.137,404","6.119,954","7.750,414","8.979,710","8.577,690","8.322,338","8.930,284","8.405,001","10.206,624",France
13,"651,132","808,647","465,793","466,376","806,644","864,475","659,878","736,785","629,063","848,263",Croatie
14,"6.325,070","6.900,625","7.299,712","8.099,869","9.794,199","10.523,626","9.487,207","9.445,147","9.090,595","9.985,469",Italie
15,"2,640","6,298","15,323","22,084","28,118","27,250","34,372","36,514","37,421","41,052",Chypre
16,"305,681","312,548","264,597","353,377","303,820","240,964","238,798","299,363","469,622","300,825",Lettonie
17,"120,286","143,248","145,188","145,881","178,272","189,129","202,444","230,898","268,007","235,013",Lituanie
18,"85,527","140,014","112,922","117,728","121,162","125,383","160,117","160,786","166,527","165,818",Luxembourg
19,"248,900","259,629","232,863","227,486","239,664","270,972","277,667","280,149","299,398","322,700",Hongrie
20,"0,000","0,058","0,851","2,206","3,048","6,439","8,744","11,715","14,791","17,075",Malte
21,"931,644","962,740","1.059,345","1.073,152","1.040,914","1.001,505","1.176,696","1.270,585","1.499,269","1.623,759",Pays-Bas
22,"4.294,920","4.143,882","3.822,112","4.748,239","4.664,912","4.644,253","4.386,648","4.653,458","4.723,709","4.609,975",Autriche
23,"797,763","985,122","1.166,572","1.488,156","1.515,417","1.753,492","2.002,327","2.002,545","2.114,914","1.894,634",Pologne
24,"1.635,078","2.472,105","2.122,934","1.754,966","2.631,972","2.786,235","2.193,535","2.880,145","2.090,102","2.634,305",Portugal
25,"1.360,804","1.776,428","1.421,408","1.306,694","1.762,583","2.373,200","2.285,007","2.362,575","2.118,726","2.289,569",Roumanie
26,"421,912","424,135","345,953","388,389","464,614","592,044","398,806","458,924","405,883","466,487",Slovénie
27,"442,525","544,621","461,495","499,570","573,603","557,352","542,648","591,230","587,360","524,076",Slovaquie
28,"1.865,946","2.080,418","2.078,810","2.455,648","2.203,755","2.258,867","2.624,826","2.614,958","2.706,510","2.763,562",Finlande
29,"6.873,181","7.066,863","7.240,799","8.463,887","7.121,484","7.381,722","8.824,054","7.673,744","8.175,666","7.841,187",Suède
30,"2.487,542","2.522,082","3.277,632","3.801,886","4.825,291","5.795,951","7.335,832","7.271,490","8.590,743","9.512,378",Royaume-Uni
31,"1.447,374","1.466,673","1.479,648","1.508,691","1.557,233","1.558,024","1.616,050","1.594,676","1.654,037","1.704,891",Islande
32,"10.944,196","10.179,278","10.591,144","12.440,585","11.261,909","11.922,614","12.142,820","12.533,620","12.573,087","12.346,615",Norvège
33,"178,074","236,457","103,513","127,007","215,320","150,615","128,203","158,486","96,380","193,981",Monténégro
34,"109,230","209,071","123,327","89,734","136,975","111,063","174,444","177,692","111,441","169,006",Macédoine du Nord
35,"447,206","650,645","355,288","406,277","598,366","406,229","506,879","669,106","389,181","735,467",Albanie
36,"958,212","1.080,911","794,755","852,966","934,910","1.001,290","930,095","996,733","850,280","1.002,437",Serbie
37,"3.279,547","4.790,449","4.995,672","5.607,654","5.951,859","4.525,253","7.193,311","7.759,618","7.500,897","8.406,527",Turquie
38,:,:,:,:,:,"510,318","477,300","487,069","345,142","571,883",Bosnie-Herzégovine
39,"10,318","13,500","9,020","8,218","12,322","13,015","12,062","21,110","15,495","26,177",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,"0,000","6,793","6,535","2,914","4,127","6,404","5,839","4,971","6,879","8,598",Moldavie
41,"1.041,935","1.151,419","962,984","1.010,249","1.356,991","946,741","746,036","935,864","1.070,610","1.255,503",Ukraine
42,:,:,:,:,"711,196","716,710","726,893","802,944","799,501","862,743",Géorgie

In [86]:
df_merge2 = pd.merge(df2, code_pays, how ='inner', left_on='GEO', right_on= 'libelle')
df_merge2

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO,id,code,libelle
0,"51.552,228","58.628,867","57.692,693","65.027,849","71.850,431","74.476,702","75.990,530","77.295,623","77.694,057","83.301,821",Union européenne - 27 pays (à partir de 2020),1,EU27_20,Union européenne - 27 pays (à partir de 2020)
1,"54.039,770","61.150,949","60.970,325","68.829,735","76.675,722","80.272,653","83.326,362","84.567,113","86.284,800","92.814,199",Union européenne - 28 pays (2013-2020),2,EU28,Union européenne - 28 pays (2013-2020)
2,"39.937,608","45.552,691","44.857,780","50.520,665","57.496,442","58.724,171","58.598,098","61.083,460","60.968,477","66.595,788",Zone euro - 19 pays (à partir de 2015),3,EA19,Zone euro - 19 pays (à partir de 2015)
3,"590,598","675,015","825,790","1.011,186","1.117,508","1.155,623","1.342,339","1.330,344","1.461,350","1.562,003",Belgique,4,BE,Belgique
4,"369,767","552,364","404,867","522,468","657,027","683,273","795,487","664,894","584,347","823,384",Bulgarie,5,BG,Bulgarie
5,"447,811","558,406","683,277","756,345","878,193","879,079","919,719","910,213","927,885","900,766",Tchéquie,6,CZ,Tchéquie
6,"865,262","1.068,717","1.219,334","1.275,772","1.372,977","1.546,318","1.628,293","1.581,258","1.875,581","1.785,530",Danemark,7,DK,Danemark
7,"8.735,082","9.594,153","11.167,498","12.823,474","13.596,131","14.478,332","16.741,702","16.789,338","19.116,767","19.857,008",Allemagne jusqu'en 1990 ancien territoire de la RFA,8,DE,Allemagne jusqu'en 1990 ancien territoire de la RFA
8,"46,459","89,758","101,438","126,954","104,864","119,408","129,114","131,013","154,875","171,006",Estonie,9,EE,Estonie
9,"383,855","335,825","466,345","470,167","513,527","573,622","700,739","671,143","780,980","897,003",Irlande,10,IE,Irlande
10,"727,088","906,852","722,921","889,001","1.237,105","1.058,236","1.281,376","1.282,454","1.193,319","1.389,930",Grèce,11,EL,Grèce
11,"6.606,277","8.682,992","7.724,592","7.788,360","9.939,208","9.808,213","8.625,649","9.295,161","7.796,389","9.144,798",Espagne,12,ES,Espagne
12,"6.417,020","7.137,404","6.119,954","7.750,414","8.979,710","8.577,690","8.322,338","8.930,284","8.405,001","10.206,624",France,13,FR,France
13,"651,132","808,647","465,793","466,376","806,644","864,475","659,878","736,785","629,063","848,263",Croatie,14,HR,Croatie
14,"6.325,070","6.900,625","7.299,712","8.099,869","9.794,199","10.523,626","9.487,207","9.445,147","9.090,595","9.985,469",Italie,15,IT,Italie
15,"2,640","6,298","15,323","22,084","28,118","27,250","34,372","36,514","37,421","41,052",Chypre,16,CY,Chypre
16,"305,681","312,548","264,597","353,377","303,820","240,964","238,798","299,363","469,622","300,825",Lettonie,17,LV,Lettonie
17,"120,286","143,248","145,188","145,881","178,272","189,129","202,444","230,898","268,007","235,013",Lituanie,18,LT,Lituanie
18,"85,527","140,014","112,922","117,728","121,162","125,383","160,117","160,786","166,527","165,818",Luxembourg,19,LU,Luxembourg
19,"248,900","259,629","232,863","227,486","239,664","270,972","277,667","280,149","299,398","322,700",Hongrie,20,HU,Hongrie
20,"0,000","0,058","0,851","2,206","3,048","6,439","8,744","11,715","14,791","17,075",Malte,21,MT,Malte
21,"931,644","962,740","1.059,345","1.073,152","1.040,914","1.001,505","1.176,696","1.270,585","1.499,269","1.623,759",Pays-Bas,22,NL,Pays-Bas
22,"4.294,920","4.143,882","3.822,112","4.748,239","4.664,912","4.644,253","4.386,648","4.653,458","4.723,709","4.609,975",Autriche,23,AT,Autriche
23,"797,763","985,122","1.166,572","1.488,156","1.515,417","1.753,492","2.002,327","2.002,545","2.114,914","1.894,634",Pologne,24,PL,Pologne
24,"1.635,078","2.472,105","2.122,934","1.754,966","2.631,972","2.786,235","2.193,535","2.880,145","2.090,102","2.634,305",Portugal,25,PT,Portugal
25,"1.360,804","1.776,428","1.421,408","1.306,694","1.762,583","2.373,200","2.285,007","2.362,575","2.118,726","2.289,569",Roumanie,26,RO,Roumanie
26,"421,912","424,135","345,953","388,389","464,614","592,044","398,806","458,924","405,883","466,487",Slovénie,27,SI,Slovénie
27,"442,525","544,621","461,495","499,570","573,603","557,352","542,648","591,230","587,360","524,076",Slovaquie,28,SK,Slovaquie
28,"1.865,946","2.080,418","2.078,810","2.455,648","2.203,755","2.258,867","2.624,826","2.614,958","2.706,510","2.763,562",Finlande,29,FI,Finlande
29,"6.873,181","7.066,863","7.240,799","8.463,887","7.121,484","7.381,722","8.824,054","7.673,744","8.175,666","7.841,187",Suède,30,SE,Suède
30,"2.487,542","2.522,082","3.277,632","3.801,886","4.825,291","5.795,951","7.335,832","7.271,490","8.590,743","9.512,378",Royaume-Uni,31,UK,Royaume-Uni
31,"1.447,374","1.466,673","1.479,648","1.508,691","1.557,233","1.558,024","1.616,050","1.594,676","1.654,037","1.704,891",Islande,32,IS,Islande
32,"10.944,196","10.179,278","10.591,144","12.440,585","11.261,909","11.922,614","12.142,820","12.533,620","12.573,087","12.346,615",Norvège,33,NO,Norvège
33,"178,074","236,457","103,513","127,007","215,320","150,615","128,203","158,486","96,380","193,981",Monténégro,34,ME,Monténégro
34,"109,230","209,071","123,327","89,734","136,975","111,063","174,444","177,692","111,441","169,006",Macédoine du Nord,35,MK,Macédoine du Nord
35,"447,206","650,645","355,288","406,277","598,366","406,229","506,879","669,106","389,181","735,467",Albanie,36,AL,Albanie
36,"958,212","1.080,911","794,755","852,966","934,910","1.001,290","930,095","996,733","850,280","1.002,437",Serbie,37,RS,Serbie
37,"3.279,547","4.790,449","4.995,672","5.607,654","5.951,859","4.525,253","7.193,311","7.759,618","7.500,897","8.406,527",Turquie,38,TR,Turquie
38,:,:,:,:,:,"510,318","477,300","487,069","345,142","571,883",Bosnie-Herzégovine,39,BA,Bosnie-Herzégovine
39,"10,318","13,500","9,020","8,218","12,322","13,015","12,062","21,110","15,495","26,177",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),40,XK,Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,"0,000","6,793","6,535","2,914","4,127","6,404","5,839","4,971","6,879","8,598",Moldavie,41,MD,Moldavie
41,"1.041,935","1.151,419","962,984","1.010,249","1.356,991","946,741","746,036","935,864","1.070,610","1.255,503",Ukraine,42,UA,Ukraine
42,:,:,:,:,"711,196","716,710","726,893","802,944","799,501","862,743",Géorgie,43,GE,Géorgie

In [87]:
df_merge2 = df_merge2.drop(columns=['libelle', 'GEO', 'code'])
df_merge2

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,id
0,"51.552,228","58.628,867","57.692,693","65.027,849","71.850,431","74.476,702","75.990,530","77.295,623","77.694,057","83.301,821",1
1,"54.039,770","61.150,949","60.970,325","68.829,735","76.675,722","80.272,653","83.326,362","84.567,113","86.284,800","92.814,199",2
2,"39.937,608","45.552,691","44.857,780","50.520,665","57.496,442","58.724,171","58.598,098","61.083,460","60.968,477","66.595,788",3
3,"590,598","675,015","825,790","1.011,186","1.117,508","1.155,623","1.342,339","1.330,344","1.461,350","1.562,003",4
4,"369,767","552,364","404,867","522,468","657,027","683,273","795,487","664,894","584,347","823,384",5
5,"447,811","558,406","683,277","756,345","878,193","879,079","919,719","910,213","927,885","900,766",6
6,"865,262","1.068,717","1.219,334","1.275,772","1.372,977","1.546,318","1.628,293","1.581,258","1.875,581","1.785,530",7
7,"8.735,082","9.594,153","11.167,498","12.823,474","13.596,131","14.478,332","16.741,702","16.789,338","19.116,767","19.857,008",8
8,"46,459","89,758","101,438","126,954","104,864","119,408","129,114","131,013","154,875","171,006",9
9,"383,855","335,825","466,345","470,167","513,527","573,622","700,739","671,143","780,980","897,003",10
10,"727,088","906,852","722,921","889,001","1.237,105","1.058,236","1.281,376","1.282,454","1.193,319","1.389,930",11
11,"6.606,277","8.682,992","7.724,592","7.788,360","9.939,208","9.808,213","8.625,649","9.295,161","7.796,389","9.144,798",12
12,"6.417,020","7.137,404","6.119,954","7.750,414","8.979,710","8.577,690","8.322,338","8.930,284","8.405,001","10.206,624",13
13,"651,132","808,647","465,793","466,376","806,644","864,475","659,878","736,785","629,063","848,263",14
14,"6.325,070","6.900,625","7.299,712","8.099,869","9.794,199","10.523,626","9.487,207","9.445,147","9.090,595","9.985,469",15
15,"2,640","6,298","15,323","22,084","28,118","27,250","34,372","36,514","37,421","41,052",16
16,"305,681","312,548","264,597","353,377","303,820","240,964","238,798","299,363","469,622","300,825",17
17,"120,286","143,248","145,188","145,881","178,272","189,129","202,444","230,898","268,007","235,013",18
18,"85,527","140,014","112,922","117,728","121,162","125,383","160,117","160,786","166,527","165,818",19
19,"248,900","259,629","232,863","227,486","239,664","270,972","277,667","280,149","299,398","322,700",20
20,"0,000","0,058","0,851","2,206","3,048","6,439","8,744","11,715","14,791","17,075",21
21,"931,644","962,740","1.059,345","1.073,152","1.040,914","1.001,505","1.176,696","1.270,585","1.499,269","1.623,759",22
22,"4.294,920","4.143,882","3.822,112","4.748,239","4.664,912","4.644,253","4.386,648","4.653,458","4.723,709","4.609,975",23
23,"797,763","985,122","1.166,572","1.488,156","1.515,417","1.753,492","2.002,327","2.002,545","2.114,914","1.894,634",24
24,"1.635,078","2.472,105","2.122,934","1.754,966","2.631,972","2.786,235","2.193,535","2.880,145","2.090,102","2.634,305",25
25,"1.360,804","1.776,428","1.421,408","1.306,694","1.762,583","2.373,200","2.285,007","2.362,575","2.118,726","2.289,569",26
26,"421,912","424,135","345,953","388,389","464,614","592,044","398,806","458,924","405,883","466,487",27
27,"442,525","544,621","461,495","499,570","573,603","557,352","542,648","591,230","587,360","524,076",28
28,"1.865,946","2.080,418","2.078,810","2.455,648","2.203,755","2.258,867","2.624,826","2.614,958","2.706,510","2.763,562",29
29,"6.873,181","7.066,863","7.240,799","8.463,887","7.121,484","7.381,722","8.824,054","7.673,744","8.175,666","7.841,187",30
30,"2.487,542","2.522,082","3.277,632","3.801,886","4.825,291","5.795,951","7.335,832","7.271,490","8.590,743","9.512,378",31
31,"1.447,374","1.466,673","1.479,648","1.508,691","1.557,233","1.558,024","1.616,050","1.594,676","1.654,037","1.704,891",32
32,"10.944,196","10.179,278","10.591,144","12.440,585","11.261,909","11.922,614","12.142,820","12.533,620","12.573,087","12.346,615",33
33,"178,074","236,457","103,513","127,007","215,320","150,615","128,203","158,486","96,380","193,981",34
34,"109,230","209,071","123,327","89,734","136,975","111,063","174,444","177,692","111,441","169,006",35
35,"447,206","650,645","355,288","406,277","598,366","406,229","506,879","669,106","389,181","735,467",36
36,"958,212","1.080,911","794,755","852,966","934,910","1.001,290","930,095","996,733","850,280","1.002,437",37
37,"3.279,547","4.790,449","4.995,672","5.607,654","5.951,859","4.525,253","7.193,311","7.759,618","7.500,897","8.406,527",38
38,:,:,:,:,:,"510,318","477,300","487,069","345,142","571,883",39
39,"10,318","13,500","9,020","8,218","12,322","13,015","12,062","21,110","15,495","26,177",40
40,"0,000","6,793","6,535","2,914","4,127","6,404","5,839","4,971","6,879","8,598",41
41,"1.041,935","1.151,419","962,984","1.010,249","1.356,991","946,741","746,036","935,864","1.070,610","1.255,503",42
42,:,:,:,:,"711,196","716,710","726,893","802,944","799,501","862,743",43

### 2.2. Transformation des colonnes "années" en lignes

In [88]:
df_global2 = []
for i in range(2009,2019):
    df_i2 = df_merge2[[f'{i}', 'id']]
    df_i2.rename(columns={f'{i}':'quantite_tep', 'id':'pays_id'}, inplace=True)
    df_i2['annee'] = i
    df_global2.append(df_i2)
df_global2[0]

/home/camille/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
<ipython-input-88-76e51b3a028f>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_i2['annee'] = i

   quantite_tep  pays_id  annee
0    51.552,228        1   2009
1    54.039,770        2   2009
2    39.937,608        3   2009
3       590,598        4   2009
4       369,767        5   2009
5       447,811        6   2009
6       865,262        7   2009
7     8.735,082        8   2009
8        46,459        9   2009
9       383,855       10   2009
10      727,088       11   2009
11    6.606,277       12   2009
12    6.417,020       13   2009
13      651,132       14   2009
14    6.325,070       15   2009
15        2,640       16   2009
16      305,681       17   2009
17      120,286       18   2009
18       85,527       19   2009
19      248,900       20   2009
20        0,000       21   2009
21      931,644       22   2009
22    4.294,920       23   2009
23      797,763       24   2009
24    1.635,078       25   2009
25    1.360,804       26   2009
26      421,912       27   2009
27      442,525       28   2009
28    1.865,946       29   2009
29    6.873,181       30   2009
30    2.487,542       31   2009
31    1.447,374       32   2009
32   10.944,196       33   2009
33      178,074       34   2009
34      109,230       35   2009
35      447,206       36   2009
36      958,212       37   2009
37    3.279,547       38   2009
38            :       39   2009
39       10,318       40   2009
40        0,000       41   2009
41    1.041,935       42   2009
42            :       43   2009

In [89]:
len(df_global2)

10

In [90]:
frames = [ df_global2[i] for i in range(0,10) ]
production_electricite_renouvelable = pd.concat(frames)
production_electricite_renouvelable

   quantite_tep  pays_id  annee
0    51.552,228        1   2009
1    54.039,770        2   2009
2    39.937,608        3   2009
3       590,598        4   2009
4       369,767        5   2009
5       447,811        6   2009
6       865,262        7   2009
7     8.735,082        8   2009
8        46,459        9   2009
9       383,855       10   2009
10      727,088       11   2009
11    6.606,277       12   2009
12    6.417,020       13   2009
13      651,132       14   2009
14    6.325,070       15   2009
15        2,640       16   2009
16      305,681       17   2009
17      120,286       18   2009
18       85,527       19   2009
19      248,900       20   2009
20        0,000       21   2009
21      931,644       22   2009
22    4.294,920       23   2009
23      797,763       24   2009
24    1.635,078       25   2009
25    1.360,804       26   2009
26      421,912       27   2009
27      442,525       28   2009
28    1.865,946       29   2009
29    6.873,181       30   2009
30    2.487,542       31   2009
31    1.447,374       32   2009
32   10.944,196       33   2009
33      178,074       34   2009
34      109,230       35   2009
35      447,206       36   2009
36      958,212       37   2009
37    3.279,547       38   2009
38            :       39   2009
39       10,318       40   2009
40        0,000       41   2009
41    1.041,935       42   2009
42            :       43   2009
0    58.628,867        1   2010
1    61.150,949        2   2010
2    45.552,691        3   2010
3       675,015        4   2010
4       552,364        5   2010
5       558,406        6   2010
6     1.068,717        7   2010
7     9.594,153        8   2010
8        89,758        9   2010
9       335,825       10   2010
10      906,852       11   2010
11    8.682,992       12   2010
12    7.137,404       13   2010
13      808,647       14   2010
14    6.900,625       15   2010
15        6,298       16   2010
16      312,548       17   2010
17      143,248       18   2010
18      140,014       19   2010
19      259,629       20   2010
20        0,058       21   2010
21      962,740       22   2010
22    4.143,882       23   2010
23      985,122       24   2010
24    2.472,105       25   2010
25    1.776,428       26   2010
26      424,135       27   2010
27      544,621       28   2010
28    2.080,418       29   2010
29    7.066,863       30   2010
30    2.522,082       31   2010
31    1.466,673       32   2010
32   10.179,278       33   2010
33      236,457       34   2010
34      209,071       35   2010
35      650,645       36   2010
36    1.080,911       37   2010
37    4.790,449       38   2010
38            :       39   2010
39       13,500       40   2010
40        6,793       41   2010
41    1.151,419       42   2010
42            :       43   2010
0    57.692,693        1   2011
1    60.970,325        2   2011
2    44.857,780        3   2011
3       825,790        4   2011
4       404,867        5   2011
5       683,277        6   2011
6     1.219,334        7   2011
7    11.167,498        8   2011
8       101,438        9   2011
9       466,345       10   2011
10      722,921       11   2011
11    7.724,592       12   2011
12    6.119,954       13   2011
13      465,793       14   2011
14    7.299,712       15   2011
15       15,323       16   2011
16      264,597       17   2011
17      145,188       18   2011
18      112,922       19   2011
19      232,863       20   2011
20        0,851       21   2011
21    1.059,345       22   2011
22    3.822,112       23   2011
23    1.166,572       24   2011
24    2.122,934       25   2011
25    1.421,408       26   2011
26      345,953       27   2011
27      461,495       28   2011
28    2.078,810       29   2011
29    7.240,799       30   2011
30    3.277,632       31   2011
31    1.479,648       32   2011
32   10.591,144       33   2011
33      103,513       34   2011
34      123,327       35   2011
35      355,288       36   2011
36      794,755       37   2011
37    4.995,672       38   2011
38            :       39   2011
39        9,020       40   2011
40        6,535       41   2011
41      962,984       42   2011
42            :       43   2011
0    65.027,849        1   2012
1    68.829,735        2   2012
2    50.520,665        3   2012
3     1.011,186        4   2012
4       522,468        5   2012
5       756,345        6   2012
6     1.275,772        7   2012
7    12.823,474        8   2012
8       126,954        9   2012
9       470,167       10   2012
10      889,001       11   2012
11    7.788,360       12   2012
12    7.750,414       13   2012
13      466,376       14   2012
14    8.099,869       15   2012
15       22,084       16   2012
16      353,377       17   2012
17      145,881       18   2012
18      117,728       19   2012
19      227,486       20   2012
20        2,206       21   2012
21    1.073,152       22   2012
22    4.748,239       23   2012
23    1.488,156       24   2012
24    1.754,966       25   2012
25    1.306,694       26   2012
26      388,389       27   2012
27      499,570       28   2012
28    2.455,648       29   2012
29    8.463,887       30   2012
30    3.801,886       31   2012
31    1.508,691       32   2012
32   12.440,585       33   2012
33      127,007       34   2012
34       89,734       35   2012
35      406,277       36   2012
36      852,966       37   2012
37    5.607,654       38   2012
38            :       39   2012
39        8,218       40   2012
40        2,914       41   2012
41    1.010,249       42   2012
42            :       43   2012
0    71.850,431        1   2013
1    76.675,722        2   2013
2    57.496,442        3   2013
3     1.117,508        4   2013
4       657,027        5   2013
5       878,193        6   2013
6     1.372,977        7   2013
7    13.596,131        8   2013
8       104,864        9   2013
9       513,527       10   2013
10    1.237,105       11   2013
11    9.939,208       12   2013
12    8.979,710       13   2013
13      806,644       14   2013
14    9.794,199       15   2013
15       28,118       16   2013
16      303,820       17   2013
17      178,272       18   2013
18      121,162       19   2013
19      239,664       20   2013
20        3,048       21   2013
21    1.040,914       22   2013
22    4.664,912       23   2013
23    1.515,417       24   2013
24    2.631,972       25   2013
25    1.762,583       26   2013
26      464,614       27   2013
27      573,603       28   2013
28    2.203,755       29   2013
29    7.121,484       30   2013
30    4.825,291       31   2013
31    1.557,233       32   2013
32   11.261,909       33   2013
33      215,320       34   2013
34      136,975       35   2013
35      598,366       36   2013
36      934,910       37   2013
37    5.951,859       38   2013
38            :       39   2013
39       12,322       40   2013
40        4,127       41   2013
41    1.356,991       42   2013
42      711,196       43   2013
0    74.476,702        1   2014
1    80.272,653        2   2014
2    58.724,171        3   2014
3     1.155,623        4   2014
4       683,273        5   2014
5       879,079        6   2014
6     1.546,318        7   2014
7    14.478,332        8   2014
8       119,408        9   2014
9       573,622       10   2014
10    1.058,236       11   2014
11    9.808,213       12   2014
12    8.577,690       13   2014
13      864,475       14   2014
14   10.523,626       15   2014
15       27,250       16   2014
16      240,964       17   2014
17      189,129       18   2014
18      125,383       19   2014
19      270,972       20   2014
20        6,439       21   2014
21    1.001,505       22   2014
22    4.644,253       23   2014
23    1.753,492       24   2014
24    2.786,235       25   2014
25    2.373,200       26   2014
26      592,044       27   2014
27      557,352       28   2014
28    2.258,867       29   2014
29    7.381,722       30   2014
30    5.795,951       31   2014
31    1.558,024       32   2014
32   11.922,614       33   2014
33      150,615       34   2014
34      111,063       35   2014
35      406,229       36   2014
36    1.001,290       37   2014
37    4.525,253       38   2014
38      510,318       39   2014
39       13,015       40   2014
40        6,404       41   2014
41      946,741       42   2014
42      716,710       43   2014
0    75.990,530        1   2015
1    83.326,362        2   2015
2    58.598,098        3   2015
3     1.342,339        4   2015
4       795,487        5   2015
5       919,719        6   2015
6     1.628,293        7   2015
7    16.741,702        8   2015
8       129,114        9   2015
9       700,739       10   2015
10    1.281,376       11   2015
11    8.625,649       12   2015
12    8.322,338       13   2015
13      659,878       14   2015
14    9.487,207       15   2015
15       34,372       16   2015
16      238,798       17   2015
17      202,444       18   2015
18      160,117       19   2015
19      277,667       20   2015
20        8,744       21   2015
21    1.176,696       22   2015
22    4.386,648       23   2015
23    2.002,327       24   2015
24    2.193,535       25   2015
25    2.285,007       26   2015
26      398,806       27   2015
27      542,648       28   2015
28    2.624,826       29   2015
29    8.824,054       30   2015
30    7.335,832       31   2015
31    1.616,050       32   2015
32   12.142,820       33   2015
33      128,203       34   2015
34      174,444       35   2015
35      506,879       36   2015
36      930,095       37   2015
37    7.193,311       38   2015
38      477,300       39   2015
39       12,062       40   2015
40        5,839       41   2015
41      746,036       42   2015
42      726,893       43   2015
0    77.295,623        1   2016
1    84.567,113        2   2016
2    61.083,460        3   2016
3     1.330,344        4   2016
4       664,894        5   2016
5       910,213        6   2016
6     1.581,258        7   2016
7    16.789,338        8   2016
8       131,013        9   2016
9       671,143       10   2016
10    1.282,454       11   2016
11    9.295,161       12   2016
12    8.930,284       13   2016
13      736,785       14   2016
14    9.445,147       15   2016
15       36,514       16   2016
16      299,363       17   2016
17      230,898       18   2016
18      160,786       19   2016
19      280,149       20   2016
20       11,715       21   2016
21    1.270,585       22   2016
22    4.653,458       23   2016
23    2.002,545       24   2016
24    2.880,145       25   2016
25    2.362,575       26   2016
26      458,924       27   2016
27      591,230       28   2016
28    2.614,958       29   2016
29    7.673,744       30   2016
30    7.271,490       31   2016
31    1.594,676       32   2016
32   12.533,620       33   2016
33      158,486       34   2016
34      177,692       35   2016
35      669,106       36   2016
36      996,733       37   2016
37    7.759,618       38   2016
38      487,069       39   2016
39       21,110       40   2016
40        4,971       41   2016
41      935,864       42   2016
42      802,944       43   2016
0    77.694,057        1   2017
1    86.284,800        2   2017
2    60.968,477        3   2017
3     1.461,350        4   2017
4       584,347        5   2017
5       927,885        6   2017
6     1.875,581        7   2017
7    19.116,767        8   2017
8       154,875        9   2017
9       780,980       10   2017
10    1.193,319       11   2017
11    7.796,389       12   2017
12    8.405,001       13   2017
13      629,063       14   2017
14    9.090,595       15   2017
15       37,421       16   2017
16      469,622       17   2017
17      268,007       18   2017
18      166,527       19   2017
19      299,398       20   2017
20       14,791       21   2017
21    1.499,269       22   2017
22    4.723,709       23   2017
23    2.114,914       24   2017
24    2.090,102       25   2017
25    2.118,726       26   2017
26      405,883       27   2017
27      587,360       28   2017
28    2.706,510       29   2017
29    8.175,666       30   2017
30    8.590,743       31   2017
31    1.654,037       32   2017
32   12.573,087       33   2017
33       96,380       34   2017
34      111,441       35   2017
35      389,181       36   2017
36      850,280       37   2017
37    7.500,897       38   2017
38      345,142       39   2017
39       15,495       40   2017
40        6,879       41   2017
41    1.070,610       42   2017
42      799,501       43   2017
0    83.301,821        1   2018
1    92.814,199        2   2018
2    66.595,788        3   2018
3     1.562,003        4   2018
4       823,384        5   2018
5       900,766        6   2018
6     1.785,530        7   2018
7    19.857,008        8   2018
8       171,006        9   2018
9       897,003       10   2018
10    1.389,930       11   2018
11    9.144,798       12   2018
12   10.206,624       13   2018
13      848,263       14   2018
14    9.985,469       15   2018
15       41,052       16   2018
16      300,825       17   2018
17      235,013       18   2018
18      165,818       19   2018
19      322,700       20   2018
20       17,075       21   2018
21    1.623,759       22   2018
22    4.609,975       23   2018
23    1.894,634       24   2018
24    2.634,305       25   2018
25    2.289,569       26   2018
26      466,487       27   2018
27      524,076       28   2018
28    2.763,562       29   2018
29    7.841,187       30   2018
30    9.512,378       31   2018
31    1.704,891       32   2018
32   12.346,615       33   2018
33      193,981       34   2018
34      169,006       35   2018
35      735,467       36   2018
36    1.002,437       37   2018
37    8.406,527       38   2018
38      571,883       39   2018
39       26,177       40   2018
40        8,598       41   2018
41    1.255,503       42   2018
42      862,743       43   2018

### 2.3. Nettoyage de la donnée

In [91]:
production_electricite_renouvelable = production_electricite_renouvelable.replace([':', '0,000'], '')
production_electricite_renouvelable

   quantite_tep  pays_id  annee
0    51.552,228        1   2009
1    54.039,770        2   2009
2    39.937,608        3   2009
3       590,598        4   2009
4       369,767        5   2009
5       447,811        6   2009
6       865,262        7   2009
7     8.735,082        8   2009
8        46,459        9   2009
9       383,855       10   2009
10      727,088       11   2009
11    6.606,277       12   2009
12    6.417,020       13   2009
13      651,132       14   2009
14    6.325,070       15   2009
15        2,640       16   2009
16      305,681       17   2009
17      120,286       18   2009
18       85,527       19   2009
19      248,900       20   2009
20                    21   2009
21      931,644       22   2009
22    4.294,920       23   2009
23      797,763       24   2009
24    1.635,078       25   2009
25    1.360,804       26   2009
26      421,912       27   2009
27      442,525       28   2009
28    1.865,946       29   2009
29    6.873,181       30   2009
30    2.487,542       31   2009
31    1.447,374       32   2009
32   10.944,196       33   2009
33      178,074       34   2009
34      109,230       35   2009
35      447,206       36   2009
36      958,212       37   2009
37    3.279,547       38   2009
38                    39   2009
39       10,318       40   2009
40                    41   2009
41    1.041,935       42   2009
42                    43   2009
0    58.628,867        1   2010
1    61.150,949        2   2010
2    45.552,691        3   2010
3       675,015        4   2010
4       552,364        5   2010
5       558,406        6   2010
6     1.068,717        7   2010
7     9.594,153        8   2010
8        89,758        9   2010
9       335,825       10   2010
10      906,852       11   2010
11    8.682,992       12   2010
12    7.137,404       13   2010
13      808,647       14   2010
14    6.900,625       15   2010
15        6,298       16   2010
16      312,548       17   2010
17      143,248       18   2010
18      140,014       19   2010
19      259,629       20   2010
20        0,058       21   2010
21      962,740       22   2010
22    4.143,882       23   2010
23      985,122       24   2010
24    2.472,105       25   2010
25    1.776,428       26   2010
26      424,135       27   2010
27      544,621       28   2010
28    2.080,418       29   2010
29    7.066,863       30   2010
30    2.522,082       31   2010
31    1.466,673       32   2010
32   10.179,278       33   2010
33      236,457       34   2010
34      209,071       35   2010
35      650,645       36   2010
36    1.080,911       37   2010
37    4.790,449       38   2010
38                    39   2010
39       13,500       40   2010
40        6,793       41   2010
41    1.151,419       42   2010
42                    43   2010
0    57.692,693        1   2011
1    60.970,325        2   2011
2    44.857,780        3   2011
3       825,790        4   2011
4       404,867        5   2011
5       683,277        6   2011
6     1.219,334        7   2011
7    11.167,498        8   2011
8       101,438        9   2011
9       466,345       10   2011
10      722,921       11   2011
11    7.724,592       12   2011
12    6.119,954       13   2011
13      465,793       14   2011
14    7.299,712       15   2011
15       15,323       16   2011
16      264,597       17   2011
17      145,188       18   2011
18      112,922       19   2011
19      232,863       20   2011
20        0,851       21   2011
21    1.059,345       22   2011
22    3.822,112       23   2011
23    1.166,572       24   2011
24    2.122,934       25   2011
25    1.421,408       26   2011
26      345,953       27   2011
27      461,495       28   2011
28    2.078,810       29   2011
29    7.240,799       30   2011
30    3.277,632       31   2011
31    1.479,648       32   2011
32   10.591,144       33   2011
33      103,513       34   2011
34      123,327       35   2011
35      355,288       36   2011
36      794,755       37   2011
37    4.995,672       38   2011
38                    39   2011
39        9,020       40   2011
40        6,535       41   2011
41      962,984       42   2011
42                    43   2011
0    65.027,849        1   2012
1    68.829,735        2   2012
2    50.520,665        3   2012
3     1.011,186        4   2012
4       522,468        5   2012
5       756,345        6   2012
6     1.275,772        7   2012
7    12.823,474        8   2012
8       126,954        9   2012
9       470,167       10   2012
10      889,001       11   2012
11    7.788,360       12   2012
12    7.750,414       13   2012
13      466,376       14   2012
14    8.099,869       15   2012
15       22,084       16   2012
16      353,377       17   2012
17      145,881       18   2012
18      117,728       19   2012
19      227,486       20   2012
20        2,206       21   2012
21    1.073,152       22   2012
22    4.748,239       23   2012
23    1.488,156       24   2012
24    1.754,966       25   2012
25    1.306,694       26   2012
26      388,389       27   2012
27      499,570       28   2012
28    2.455,648       29   2012
29    8.463,887       30   2012
30    3.801,886       31   2012
31    1.508,691       32   2012
32   12.440,585       33   2012
33      127,007       34   2012
34       89,734       35   2012
35      406,277       36   2012
36      852,966       37   2012
37    5.607,654       38   2012
38                    39   2012
39        8,218       40   2012
40        2,914       41   2012
41    1.010,249       42   2012
42                    43   2012
0    71.850,431        1   2013
1    76.675,722        2   2013
2    57.496,442        3   2013
3     1.117,508        4   2013
4       657,027        5   2013
5       878,193        6   2013
6     1.372,977        7   2013
7    13.596,131        8   2013
8       104,864        9   2013
9       513,527       10   2013
10    1.237,105       11   2013
11    9.939,208       12   2013
12    8.979,710       13   2013
13      806,644       14   2013
14    9.794,199       15   2013
15       28,118       16   2013
16      303,820       17   2013
17      178,272       18   2013
18      121,162       19   2013
19      239,664       20   2013
20        3,048       21   2013
21    1.040,914       22   2013
22    4.664,912       23   2013
23    1.515,417       24   2013
24    2.631,972       25   2013
25    1.762,583       26   2013
26      464,614       27   2013
27      573,603       28   2013
28    2.203,755       29   2013
29    7.121,484       30   2013
30    4.825,291       31   2013
31    1.557,233       32   2013
32   11.261,909       33   2013
33      215,320       34   2013
34      136,975       35   2013
35      598,366       36   2013
36      934,910       37   2013
37    5.951,859       38   2013
38                    39   2013
39       12,322       40   2013
40        4,127       41   2013
41    1.356,991       42   2013
42      711,196       43   2013
0    74.476,702        1   2014
1    80.272,653        2   2014
2    58.724,171        3   2014
3     1.155,623        4   2014
4       683,273        5   2014
5       879,079        6   2014
6     1.546,318        7   2014
7    14.478,332        8   2014
8       119,408        9   2014
9       573,622       10   2014
10    1.058,236       11   2014
11    9.808,213       12   2014
12    8.577,690       13   2014
13      864,475       14   2014
14   10.523,626       15   2014
15       27,250       16   2014
16      240,964       17   2014
17      189,129       18   2014
18      125,383       19   2014
19      270,972       20   2014
20        6,439       21   2014
21    1.001,505       22   2014
22    4.644,253       23   2014
23    1.753,492       24   2014
24    2.786,235       25   2014
25    2.373,200       26   2014
26      592,044       27   2014
27      557,352       28   2014
28    2.258,867       29   2014
29    7.381,722       30   2014
30    5.795,951       31   2014
31    1.558,024       32   2014
32   11.922,614       33   2014
33      150,615       34   2014
34      111,063       35   2014
35      406,229       36   2014
36    1.001,290       37   2014
37    4.525,253       38   2014
38      510,318       39   2014
39       13,015       40   2014
40        6,404       41   2014
41      946,741       42   2014
42      716,710       43   2014
0    75.990,530        1   2015
1    83.326,362        2   2015
2    58.598,098        3   2015
3     1.342,339        4   2015
4       795,487        5   2015
5       919,719        6   2015
6     1.628,293        7   2015
7    16.741,702        8   2015
8       129,114        9   2015
9       700,739       10   2015
10    1.281,376       11   2015
11    8.625,649       12   2015
12    8.322,338       13   2015
13      659,878       14   2015
14    9.487,207       15   2015
15       34,372       16   2015
16      238,798       17   2015
17      202,444       18   2015
18      160,117       19   2015
19      277,667       20   2015
20        8,744       21   2015
21    1.176,696       22   2015
22    4.386,648       23   2015
23    2.002,327       24   2015
24    2.193,535       25   2015
25    2.285,007       26   2015
26      398,806       27   2015
27      542,648       28   2015
28    2.624,826       29   2015
29    8.824,054       30   2015
30    7.335,832       31   2015
31    1.616,050       32   2015
32   12.142,820       33   2015
33      128,203       34   2015
34      174,444       35   2015
35      506,879       36   2015
36      930,095       37   2015
37    7.193,311       38   2015
38      477,300       39   2015
39       12,062       40   2015
40        5,839       41   2015
41      746,036       42   2015
42      726,893       43   2015
0    77.295,623        1   2016
1    84.567,113        2   2016
2    61.083,460        3   2016
3     1.330,344        4   2016
4       664,894        5   2016
5       910,213        6   2016
6     1.581,258        7   2016
7    16.789,338        8   2016
8       131,013        9   2016
9       671,143       10   2016
10    1.282,454       11   2016
11    9.295,161       12   2016
12    8.930,284       13   2016
13      736,785       14   2016
14    9.445,147       15   2016
15       36,514       16   2016
16      299,363       17   2016
17      230,898       18   2016
18      160,786       19   2016
19      280,149       20   2016
20       11,715       21   2016
21    1.270,585       22   2016
22    4.653,458       23   2016
23    2.002,545       24   2016
24    2.880,145       25   2016
25    2.362,575       26   2016
26      458,924       27   2016
27      591,230       28   2016
28    2.614,958       29   2016
29    7.673,744       30   2016
30    7.271,490       31   2016
31    1.594,676       32   2016
32   12.533,620       33   2016
33      158,486       34   2016
34      177,692       35   2016
35      669,106       36   2016
36      996,733       37   2016
37    7.759,618       38   2016
38      487,069       39   2016
39       21,110       40   2016
40        4,971       41   2016
41      935,864       42   2016
42      802,944       43   2016
0    77.694,057        1   2017
1    86.284,800        2   2017
2    60.968,477        3   2017
3     1.461,350        4   2017
4       584,347        5   2017
5       927,885        6   2017
6     1.875,581        7   2017
7    19.116,767        8   2017
8       154,875        9   2017
9       780,980       10   2017
10    1.193,319       11   2017
11    7.796,389       12   2017
12    8.405,001       13   2017
13      629,063       14   2017
14    9.090,595       15   2017
15       37,421       16   2017
16      469,622       17   2017
17      268,007       18   2017
18      166,527       19   2017
19      299,398       20   2017
20       14,791       21   2017
21    1.499,269       22   2017
22    4.723,709       23   2017
23    2.114,914       24   2017
24    2.090,102       25   2017
25    2.118,726       26   2017
26      405,883       27   2017
27      587,360       28   2017
28    2.706,510       29   2017
29    8.175,666       30   2017
30    8.590,743       31   2017
31    1.654,037       32   2017
32   12.573,087       33   2017
33       96,380       34   2017
34      111,441       35   2017
35      389,181       36   2017
36      850,280       37   2017
37    7.500,897       38   2017
38      345,142       39   2017
39       15,495       40   2017
40        6,879       41   2017
41    1.070,610       42   2017
42      799,501       43   2017
0    83.301,821        1   2018
1    92.814,199        2   2018
2    66.595,788        3   2018
3     1.562,003        4   2018
4       823,384        5   2018
5       900,766        6   2018
6     1.785,530        7   2018
7    19.857,008        8   2018
8       171,006        9   2018
9       897,003       10   2018
10    1.389,930       11   2018
11    9.144,798       12   2018
12   10.206,624       13   2018
13      848,263       14   2018
14    9.985,469       15   2018
15       41,052       16   2018
16      300,825       17   2018
17      235,013       18   2018
18      165,818       19   2018
19      322,700       20   2018
20       17,075       21   2018
21    1.623,759       22   2018
22    4.609,975       23   2018
23    1.894,634       24   2018
24    2.634,305       25   2018
25    2.289,569       26   2018
26      466,487       27   2018
27      524,076       28   2018
28    2.763,562       29   2018
29    7.841,187       30   2018
30    9.512,378       31   2018
31    1.704,891       32   2018
32   12.346,615       33   2018
33      193,981       34   2018
34      169,006       35   2018
35      735,467       36   2018
36    1.002,437       37   2018
37    8.406,527       38   2018
38      571,883       39   2018
39       26,177       40   2018
40        8,598       41   2018
41    1.255,503       42   2018
42      862,743       43   2018

In [92]:
production_electricite_renouvelable['quantite_tep'] = production_electricite_renouvelable['quantite_tep'].apply(lambda x: x.replace('.', ''))
production_electricite_renouvelable

   quantite_tep  pays_id  annee
0     51552,228        1   2009
1     54039,770        2   2009
2     39937,608        3   2009
3       590,598        4   2009
4       369,767        5   2009
5       447,811        6   2009
6       865,262        7   2009
7      8735,082        8   2009
8        46,459        9   2009
9       383,855       10   2009
10      727,088       11   2009
11     6606,277       12   2009
12     6417,020       13   2009
13      651,132       14   2009
14     6325,070       15   2009
15        2,640       16   2009
16      305,681       17   2009
17      120,286       18   2009
18       85,527       19   2009
19      248,900       20   2009
20                    21   2009
21      931,644       22   2009
22     4294,920       23   2009
23      797,763       24   2009
24     1635,078       25   2009
25     1360,804       26   2009
26      421,912       27   2009
27      442,525       28   2009
28     1865,946       29   2009
29     6873,181       30   2009
30     2487,542       31   2009
31     1447,374       32   2009
32    10944,196       33   2009
33      178,074       34   2009
34      109,230       35   2009
35      447,206       36   2009
36      958,212       37   2009
37     3279,547       38   2009
38                    39   2009
39       10,318       40   2009
40                    41   2009
41     1041,935       42   2009
42                    43   2009
0     58628,867        1   2010
1     61150,949        2   2010
2     45552,691        3   2010
3       675,015        4   2010
4       552,364        5   2010
5       558,406        6   2010
6      1068,717        7   2010
7      9594,153        8   2010
8        89,758        9   2010
9       335,825       10   2010
10      906,852       11   2010
11     8682,992       12   2010
12     7137,404       13   2010
13      808,647       14   2010
14     6900,625       15   2010
15        6,298       16   2010
16      312,548       17   2010
17      143,248       18   2010
18      140,014       19   2010
19      259,629       20   2010
20        0,058       21   2010
21      962,740       22   2010
22     4143,882       23   2010
23      985,122       24   2010
24     2472,105       25   2010
25     1776,428       26   2010
26      424,135       27   2010
27      544,621       28   2010
28     2080,418       29   2010
29     7066,863       30   2010
30     2522,082       31   2010
31     1466,673       32   2010
32    10179,278       33   2010
33      236,457       34   2010
34      209,071       35   2010
35      650,645       36   2010
36     1080,911       37   2010
37     4790,449       38   2010
38                    39   2010
39       13,500       40   2010
40        6,793       41   2010
41     1151,419       42   2010
42                    43   2010
0     57692,693        1   2011
1     60970,325        2   2011
2     44857,780        3   2011
3       825,790        4   2011
4       404,867        5   2011
5       683,277        6   2011
6      1219,334        7   2011
7     11167,498        8   2011
8       101,438        9   2011
9       466,345       10   2011
10      722,921       11   2011
11     7724,592       12   2011
12     6119,954       13   2011
13      465,793       14   2011
14     7299,712       15   2011
15       15,323       16   2011
16      264,597       17   2011
17      145,188       18   2011
18      112,922       19   2011
19      232,863       20   2011
20        0,851       21   2011
21     1059,345       22   2011
22     3822,112       23   2011
23     1166,572       24   2011
24     2122,934       25   2011
25     1421,408       26   2011
26      345,953       27   2011
27      461,495       28   2011
28     2078,810       29   2011
29     7240,799       30   2011
30     3277,632       31   2011
31     1479,648       32   2011
32    10591,144       33   2011
33      103,513       34   2011
34      123,327       35   2011
35      355,288       36   2011
36      794,755       37   2011
37     4995,672       38   2011
38                    39   2011
39        9,020       40   2011
40        6,535       41   2011
41      962,984       42   2011
42                    43   2011
0     65027,849        1   2012
1     68829,735        2   2012
2     50520,665        3   2012
3      1011,186        4   2012
4       522,468        5   2012
5       756,345        6   2012
6      1275,772        7   2012
7     12823,474        8   2012
8       126,954        9   2012
9       470,167       10   2012
10      889,001       11   2012
11     7788,360       12   2012
12     7750,414       13   2012
13      466,376       14   2012
14     8099,869       15   2012
15       22,084       16   2012
16      353,377       17   2012
17      145,881       18   2012
18      117,728       19   2012
19      227,486       20   2012
20        2,206       21   2012
21     1073,152       22   2012
22     4748,239       23   2012
23     1488,156       24   2012
24     1754,966       25   2012
25     1306,694       26   2012
26      388,389       27   2012
27      499,570       28   2012
28     2455,648       29   2012
29     8463,887       30   2012
30     3801,886       31   2012
31     1508,691       32   2012
32    12440,585       33   2012
33      127,007       34   2012
34       89,734       35   2012
35      406,277       36   2012
36      852,966       37   2012
37     5607,654       38   2012
38                    39   2012
39        8,218       40   2012
40        2,914       41   2012
41     1010,249       42   2012
42                    43   2012
0     71850,431        1   2013
1     76675,722        2   2013
2     57496,442        3   2013
3      1117,508        4   2013
4       657,027        5   2013
5       878,193        6   2013
6      1372,977        7   2013
7     13596,131        8   2013
8       104,864        9   2013
9       513,527       10   2013
10     1237,105       11   2013
11     9939,208       12   2013
12     8979,710       13   2013
13      806,644       14   2013
14     9794,199       15   2013
15       28,118       16   2013
16      303,820       17   2013
17      178,272       18   2013
18      121,162       19   2013
19      239,664       20   2013
20        3,048       21   2013
21     1040,914       22   2013
22     4664,912       23   2013
23     1515,417       24   2013
24     2631,972       25   2013
25     1762,583       26   2013
26      464,614       27   2013
27      573,603       28   2013
28     2203,755       29   2013
29     7121,484       30   2013
30     4825,291       31   2013
31     1557,233       32   2013
32    11261,909       33   2013
33      215,320       34   2013
34      136,975       35   2013
35      598,366       36   2013
36      934,910       37   2013
37     5951,859       38   2013
38                    39   2013
39       12,322       40   2013
40        4,127       41   2013
41     1356,991       42   2013
42      711,196       43   2013
0     74476,702        1   2014
1     80272,653        2   2014
2     58724,171        3   2014
3      1155,623        4   2014
4       683,273        5   2014
5       879,079        6   2014
6      1546,318        7   2014
7     14478,332        8   2014
8       119,408        9   2014
9       573,622       10   2014
10     1058,236       11   2014
11     9808,213       12   2014
12     8577,690       13   2014
13      864,475       14   2014
14    10523,626       15   2014
15       27,250       16   2014
16      240,964       17   2014
17      189,129       18   2014
18      125,383       19   2014
19      270,972       20   2014
20        6,439       21   2014
21     1001,505       22   2014
22     4644,253       23   2014
23     1753,492       24   2014
24     2786,235       25   2014
25     2373,200       26   2014
26      592,044       27   2014
27      557,352       28   2014
28     2258,867       29   2014
29     7381,722       30   2014
30     5795,951       31   2014
31     1558,024       32   2014
32    11922,614       33   2014
33      150,615       34   2014
34      111,063       35   2014
35      406,229       36   2014
36     1001,290       37   2014
37     4525,253       38   2014
38      510,318       39   2014
39       13,015       40   2014
40        6,404       41   2014
41      946,741       42   2014
42      716,710       43   2014
0     75990,530        1   2015
1     83326,362        2   2015
2     58598,098        3   2015
3      1342,339        4   2015
4       795,487        5   2015
5       919,719        6   2015
6      1628,293        7   2015
7     16741,702        8   2015
8       129,114        9   2015
9       700,739       10   2015
10     1281,376       11   2015
11     8625,649       12   2015
12     8322,338       13   2015
13      659,878       14   2015
14     9487,207       15   2015
15       34,372       16   2015
16      238,798       17   2015
17      202,444       18   2015
18      160,117       19   2015
19      277,667       20   2015
20        8,744       21   2015
21     1176,696       22   2015
22     4386,648       23   2015
23     2002,327       24   2015
24     2193,535       25   2015
25     2285,007       26   2015
26      398,806       27   2015
27      542,648       28   2015
28     2624,826       29   2015
29     8824,054       30   2015
30     7335,832       31   2015
31     1616,050       32   2015
32    12142,820       33   2015
33      128,203       34   2015
34      174,444       35   2015
35      506,879       36   2015
36      930,095       37   2015
37     7193,311       38   2015
38      477,300       39   2015
39       12,062       40   2015
40        5,839       41   2015
41      746,036       42   2015
42      726,893       43   2015
0     77295,623        1   2016
1     84567,113        2   2016
2     61083,460        3   2016
3      1330,344        4   2016
4       664,894        5   2016
5       910,213        6   2016
6      1581,258        7   2016
7     16789,338        8   2016
8       131,013        9   2016
9       671,143       10   2016
10     1282,454       11   2016
11     9295,161       12   2016
12     8930,284       13   2016
13      736,785       14   2016
14     9445,147       15   2016
15       36,514       16   2016
16      299,363       17   2016
17      230,898       18   2016
18      160,786       19   2016
19      280,149       20   2016
20       11,715       21   2016
21     1270,585       22   2016
22     4653,458       23   2016
23     2002,545       24   2016
24     2880,145       25   2016
25     2362,575       26   2016
26      458,924       27   2016
27      591,230       28   2016
28     2614,958       29   2016
29     7673,744       30   2016
30     7271,490       31   2016
31     1594,676       32   2016
32    12533,620       33   2016
33      158,486       34   2016
34      177,692       35   2016
35      669,106       36   2016
36      996,733       37   2016
37     7759,618       38   2016
38      487,069       39   2016
39       21,110       40   2016
40        4,971       41   2016
41      935,864       42   2016
42      802,944       43   2016
0     77694,057        1   2017
1     86284,800        2   2017
2     60968,477        3   2017
3      1461,350        4   2017
4       584,347        5   2017
5       927,885        6   2017
6      1875,581        7   2017
7     19116,767        8   2017
8       154,875        9   2017
9       780,980       10   2017
10     1193,319       11   2017
11     7796,389       12   2017
12     8405,001       13   2017
13      629,063       14   2017
14     9090,595       15   2017
15       37,421       16   2017
16      469,622       17   2017
17      268,007       18   2017
18      166,527       19   2017
19      299,398       20   2017
20       14,791       21   2017
21     1499,269       22   2017
22     4723,709       23   2017
23     2114,914       24   2017
24     2090,102       25   2017
25     2118,726       26   2017
26      405,883       27   2017
27      587,360       28   2017
28     2706,510       29   2017
29     8175,666       30   2017
30     8590,743       31   2017
31     1654,037       32   2017
32    12573,087       33   2017
33       96,380       34   2017
34      111,441       35   2017
35      389,181       36   2017
36      850,280       37   2017
37     7500,897       38   2017
38      345,142       39   2017
39       15,495       40   2017
40        6,879       41   2017
41     1070,610       42   2017
42      799,501       43   2017
0     83301,821        1   2018
1     92814,199        2   2018
2     66595,788        3   2018
3      1562,003        4   2018
4       823,384        5   2018
5       900,766        6   2018
6      1785,530        7   2018
7     19857,008        8   2018
8       171,006        9   2018
9       897,003       10   2018
10     1389,930       11   2018
11     9144,798       12   2018
12    10206,624       13   2018
13      848,263       14   2018
14     9985,469       15   2018
15       41,052       16   2018
16      300,825       17   2018
17      235,013       18   2018
18      165,818       19   2018
19      322,700       20   2018
20       17,075       21   2018
21     1623,759       22   2018
22     4609,975       23   2018
23     1894,634       24   2018
24     2634,305       25   2018
25     2289,569       26   2018
26      466,487       27   2018
27      524,076       28   2018
28     2763,562       29   2018
29     7841,187       30   2018
30     9512,378       31   2018
31     1704,891       32   2018
32    12346,615       33   2018
33      193,981       34   2018
34      169,006       35   2018
35      735,467       36   2018
36     1002,437       37   2018
37     8406,527       38   2018
38      571,883       39   2018
39       26,177       40   2018
40        8,598       41   2018
41     1255,503       42   2018
42      862,743       43   2018

In [93]:
production_electricite_renouvelable.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 430 entries, 0 to 42
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   quantite_tep  430 non-null    object
 1   pays_id       430 non-null    int64
 2   annee         430 non-null    int64
dtypes: int64(2), object(1)
memory usage: 13.4+ KB

In [94]:
production_electricite_renouvelable['quantite_tep'] = production_electricite_renouvelable['quantite_tep'].apply(lambda x: x.replace(',', '.'))
production_electricite_renouvelable

   quantite_tep  pays_id  annee
0     51552.228        1   2009
1     54039.770        2   2009
2     39937.608        3   2009
3       590.598        4   2009
4       369.767        5   2009
5       447.811        6   2009
6       865.262        7   2009
7      8735.082        8   2009
8        46.459        9   2009
9       383.855       10   2009
10      727.088       11   2009
11     6606.277       12   2009
12     6417.020       13   2009
13      651.132       14   2009
14     6325.070       15   2009
15        2.640       16   2009
16      305.681       17   2009
17      120.286       18   2009
18       85.527       19   2009
19      248.900       20   2009
20                    21   2009
21      931.644       22   2009
22     4294.920       23   2009
23      797.763       24   2009
24     1635.078       25   2009
25     1360.804       26   2009
26      421.912       27   2009
27      442.525       28   2009
28     1865.946       29   2009
29     6873.181       30   2009
30     2487.542       31   2009
31     1447.374       32   2009
32    10944.196       33   2009
33      178.074       34   2009
34      109.230       35   2009
35      447.206       36   2009
36      958.212       37   2009
37     3279.547       38   2009
38                    39   2009
39       10.318       40   2009
40                    41   2009
41     1041.935       42   2009
42                    43   2009
0     58628.867        1   2010
1     61150.949        2   2010
2     45552.691        3   2010
3       675.015        4   2010
4       552.364        5   2010
5       558.406        6   2010
6      1068.717        7   2010
7      9594.153        8   2010
8        89.758        9   2010
9       335.825       10   2010
10      906.852       11   2010
11     8682.992       12   2010
12     7137.404       13   2010
13      808.647       14   2010
14     6900.625       15   2010
15        6.298       16   2010
16      312.548       17   2010
17      143.248       18   2010
18      140.014       19   2010
19      259.629       20   2010
20        0.058       21   2010
21      962.740       22   2010
22     4143.882       23   2010
23      985.122       24   2010
24     2472.105       25   2010
25     1776.428       26   2010
26      424.135       27   2010
27      544.621       28   2010
28     2080.418       29   2010
29     7066.863       30   2010
30     2522.082       31   2010
31     1466.673       32   2010
32    10179.278       33   2010
33      236.457       34   2010
34      209.071       35   2010
35      650.645       36   2010
36     1080.911       37   2010
37     4790.449       38   2010
38                    39   2010
39       13.500       40   2010
40        6.793       41   2010
41     1151.419       42   2010
42                    43   2010
0     57692.693        1   2011
1     60970.325        2   2011
2     44857.780        3   2011
3       825.790        4   2011
4       404.867        5   2011
5       683.277        6   2011
6      1219.334        7   2011
7     11167.498        8   2011
8       101.438        9   2011
9       466.345       10   2011
10      722.921       11   2011
11     7724.592       12   2011
12     6119.954       13   2011
13      465.793       14   2011
14     7299.712       15   2011
15       15.323       16   2011
16      264.597       17   2011
17      145.188       18   2011
18      112.922       19   2011
19      232.863       20   2011
20        0.851       21   2011
21     1059.345       22   2011
22     3822.112       23   2011
23     1166.572       24   2011
24     2122.934       25   2011
25     1421.408       26   2011
26      345.953       27   2011
27      461.495       28   2011
28     2078.810       29   2011
29     7240.799       30   2011
30     3277.632       31   2011
31     1479.648       32   2011
32    10591.144       33   2011
33      103.513       34   2011
34      123.327       35   2011
35      355.288       36   2011
36      794.755       37   2011
37     4995.672       38   2011
38                    39   2011
39        9.020       40   2011
40        6.535       41   2011
41      962.984       42   2011
42                    43   2011
0     65027.849        1   2012
1     68829.735        2   2012
2     50520.665        3   2012
3      1011.186        4   2012
4       522.468        5   2012
5       756.345        6   2012
6      1275.772        7   2012
7     12823.474        8   2012
8       126.954        9   2012
9       470.167       10   2012
10      889.001       11   2012
11     7788.360       12   2012
12     7750.414       13   2012
13      466.376       14   2012
14     8099.869       15   2012
15       22.084       16   2012
16      353.377       17   2012
17      145.881       18   2012
18      117.728       19   2012
19      227.486       20   2012
20        2.206       21   2012
21     1073.152       22   2012
22     4748.239       23   2012
23     1488.156       24   2012
24     1754.966       25   2012
25     1306.694       26   2012
26      388.389       27   2012
27      499.570       28   2012
28     2455.648       29   2012
29     8463.887       30   2012
30     3801.886       31   2012
31     1508.691       32   2012
32    12440.585       33   2012
33      127.007       34   2012
34       89.734       35   2012
35      406.277       36   2012
36      852.966       37   2012
37     5607.654       38   2012
38                    39   2012
39        8.218       40   2012
40        2.914       41   2012
41     1010.249       42   2012
42                    43   2012
0     71850.431        1   2013
1     76675.722        2   2013
2     57496.442        3   2013
3      1117.508        4   2013
4       657.027        5   2013
5       878.193        6   2013
6      1372.977        7   2013
7     13596.131        8   2013
8       104.864        9   2013
9       513.527       10   2013
10     1237.105       11   2013
11     9939.208       12   2013
12     8979.710       13   2013
13      806.644       14   2013
14     9794.199       15   2013
15       28.118       16   2013
16      303.820       17   2013
17      178.272       18   2013
18      121.162       19   2013
19      239.664       20   2013
20        3.048       21   2013
21     1040.914       22   2013
22     4664.912       23   2013
23     1515.417       24   2013
24     2631.972       25   2013
25     1762.583       26   2013
26      464.614       27   2013
27      573.603       28   2013
28     2203.755       29   2013
29     7121.484       30   2013
30     4825.291       31   2013
31     1557.233       32   2013
32    11261.909       33   2013
33      215.320       34   2013
34      136.975       35   2013
35      598.366       36   2013
36      934.910       37   2013
37     5951.859       38   2013
38                    39   2013
39       12.322       40   2013
40        4.127       41   2013
41     1356.991       42   2013
42      711.196       43   2013
0     74476.702        1   2014
1     80272.653        2   2014
2     58724.171        3   2014
3      1155.623        4   2014
4       683.273        5   2014
5       879.079        6   2014
6      1546.318        7   2014
7     14478.332        8   2014
8       119.408        9   2014
9       573.622       10   2014
10     1058.236       11   2014
11     9808.213       12   2014
12     8577.690       13   2014
13      864.475       14   2014
14    10523.626       15   2014
15       27.250       16   2014
16      240.964       17   2014
17      189.129       18   2014
18      125.383       19   2014
19      270.972       20   2014
20        6.439       21   2014
21     1001.505       22   2014
22     4644.253       23   2014
23     1753.492       24   2014
24     2786.235       25   2014
25     2373.200       26   2014
26      592.044       27   2014
27      557.352       28   2014
28     2258.867       29   2014
29     7381.722       30   2014
30     5795.951       31   2014
31     1558.024       32   2014
32    11922.614       33   2014
33      150.615       34   2014
34      111.063       35   2014
35      406.229       36   2014
36     1001.290       37   2014
37     4525.253       38   2014
38      510.318       39   2014
39       13.015       40   2014
40        6.404       41   2014
41      946.741       42   2014
42      716.710       43   2014
0     75990.530        1   2015
1     83326.362        2   2015
2     58598.098        3   2015
3      1342.339        4   2015
4       795.487        5   2015
5       919.719        6   2015
6      1628.293        7   2015
7     16741.702        8   2015
8       129.114        9   2015
9       700.739       10   2015
10     1281.376       11   2015
11     8625.649       12   2015
12     8322.338       13   2015
13      659.878       14   2015
14     9487.207       15   2015
15       34.372       16   2015
16      238.798       17   2015
17      202.444       18   2015
18      160.117       19   2015
19      277.667       20   2015
20        8.744       21   2015
21     1176.696       22   2015
22     4386.648       23   2015
23     2002.327       24   2015
24     2193.535       25   2015
25     2285.007       26   2015
26      398.806       27   2015
27      542.648       28   2015
28     2624.826       29   2015
29     8824.054       30   2015
30     7335.832       31   2015
31     1616.050       32   2015
32    12142.820       33   2015
33      128.203       34   2015
34      174.444       35   2015
35      506.879       36   2015
36      930.095       37   2015
37     7193.311       38   2015
38      477.300       39   2015
39       12.062       40   2015
40        5.839       41   2015
41      746.036       42   2015
42      726.893       43   2015
0     77295.623        1   2016
1     84567.113        2   2016
2     61083.460        3   2016
3      1330.344        4   2016
4       664.894        5   2016
5       910.213        6   2016
6      1581.258        7   2016
7     16789.338        8   2016
8       131.013        9   2016
9       671.143       10   2016
10     1282.454       11   2016
11     9295.161       12   2016
12     8930.284       13   2016
13      736.785       14   2016
14     9445.147       15   2016
15       36.514       16   2016
16      299.363       17   2016
17      230.898       18   2016
18      160.786       19   2016
19      280.149       20   2016
20       11.715       21   2016
21     1270.585       22   2016
22     4653.458       23   2016
23     2002.545       24   2016
24     2880.145       25   2016
25     2362.575       26   2016
26      458.924       27   2016
27      591.230       28   2016
28     2614.958       29   2016
29     7673.744       30   2016
30     7271.490       31   2016
31     1594.676       32   2016
32    12533.620       33   2016
33      158.486       34   2016
34      177.692       35   2016
35      669.106       36   2016
36      996.733       37   2016
37     7759.618       38   2016
38      487.069       39   2016
39       21.110       40   2016
40        4.971       41   2016
41      935.864       42   2016
42      802.944       43   2016
0     77694.057        1   2017
1     86284.800        2   2017
2     60968.477        3   2017
3      1461.350        4   2017
4       584.347        5   2017
5       927.885        6   2017
6      1875.581        7   2017
7     19116.767        8   2017
8       154.875        9   2017
9       780.980       10   2017
10     1193.319       11   2017
11     7796.389       12   2017
12     8405.001       13   2017
13      629.063       14   2017
14     9090.595       15   2017
15       37.421       16   2017
16      469.622       17   2017
17      268.007       18   2017
18      166.527       19   2017
19      299.398       20   2017
20       14.791       21   2017
21     1499.269       22   2017
22     4723.709       23   2017
23     2114.914       24   2017
24     2090.102       25   2017
25     2118.726       26   2017
26      405.883       27   2017
27      587.360       28   2017
28     2706.510       29   2017
29     8175.666       30   2017
30     8590.743       31   2017
31     1654.037       32   2017
32    12573.087       33   2017
33       96.380       34   2017
34      111.441       35   2017
35      389.181       36   2017
36      850.280       37   2017
37     7500.897       38   2017
38      345.142       39   2017
39       15.495       40   2017
40        6.879       41   2017
41     1070.610       42   2017
42      799.501       43   2017
0     83301.821        1   2018
1     92814.199        2   2018
2     66595.788        3   2018
3      1562.003        4   2018
4       823.384        5   2018
5       900.766        6   2018
6      1785.530        7   2018
7     19857.008        8   2018
8       171.006        9   2018
9       897.003       10   2018
10     1389.930       11   2018
11     9144.798       12   2018
12    10206.624       13   2018
13      848.263       14   2018
14     9985.469       15   2018
15       41.052       16   2018
16      300.825       17   2018
17      235.013       18   2018
18      165.818       19   2018
19      322.700       20   2018
20       17.075       21   2018
21     1623.759       22   2018
22     4609.975       23   2018
23     1894.634       24   2018
24     2634.305       25   2018
25     2289.569       26   2018
26      466.487       27   2018
27      524.076       28   2018
28     2763.562       29   2018
29     7841.187       30   2018
30     9512.378       31   2018
31     1704.891       32   2018
32    12346.615       33   2018
33      193.981       34   2018
34      169.006       35   2018
35      735.467       36   2018
36     1002.437       37   2018
37     8406.527       38   2018
38      571.883       39   2018
39       26.177       40   2018
40        8.598       41   2018
41     1255.503       42   2018
42      862.743       43   2018

In [95]:
production_electricite_renouvelable["quantite_tep"] = pd.to_numeric(production_electricite_renouvelable['quantite_tep'])
production_electricite_renouvelable

    quantite_tep  pays_id  annee
0      51552.228        1   2009
1      54039.770        2   2009
2      39937.608        3   2009
3        590.598        4   2009
4        369.767        5   2009
5        447.811        6   2009
6        865.262        7   2009
7       8735.082        8   2009
8         46.459        9   2009
9        383.855       10   2009
10       727.088       11   2009
11      6606.277       12   2009
12      6417.020       13   2009
13       651.132       14   2009
14      6325.070       15   2009
15         2.640       16   2009
16       305.681       17   2009
17       120.286       18   2009
18        85.527       19   2009
19       248.900       20   2009
20           NaN       21   2009
21       931.644       22   2009
22      4294.920       23   2009
23       797.763       24   2009
24      1635.078       25   2009
25      1360.804       26   2009
26       421.912       27   2009
27       442.525       28   2009
28      1865.946       29   2009
29      6873.181       30   2009
30      2487.542       31   2009
31      1447.374       32   2009
32     10944.196       33   2009
33       178.074       34   2009
34       109.230       35   2009
35       447.206       36   2009
36       958.212       37   2009
37      3279.547       38   2009
38           NaN       39   2009
39        10.318       40   2009
40           NaN       41   2009
41      1041.935       42   2009
42           NaN       43   2009
0      58628.867        1   2010
1      61150.949        2   2010
2      45552.691        3   2010
3        675.015        4   2010
4        552.364        5   2010
5        558.406        6   2010
6       1068.717        7   2010
7       9594.153        8   2010
8         89.758        9   2010
9        335.825       10   2010
10       906.852       11   2010
11      8682.992       12   2010
12      7137.404       13   2010
13       808.647       14   2010
14      6900.625       15   2010
15         6.298       16   2010
16       312.548       17   2010
17       143.248       18   2010
18       140.014       19   2010
19       259.629       20   2010
20         0.058       21   2010
21       962.740       22   2010
22      4143.882       23   2010
23       985.122       24   2010
24      2472.105       25   2010
25      1776.428       26   2010
26       424.135       27   2010
27       544.621       28   2010
28      2080.418       29   2010
29      7066.863       30   2010
30      2522.082       31   2010
31      1466.673       32   2010
32     10179.278       33   2010
33       236.457       34   2010
34       209.071       35   2010
35       650.645       36   2010
36      1080.911       37   2010
37      4790.449       38   2010
38           NaN       39   2010
39        13.500       40   2010
40         6.793       41   2010
41      1151.419       42   2010
42           NaN       43   2010
0      57692.693        1   2011
1      60970.325        2   2011
2      44857.780        3   2011
3        825.790        4   2011
4        404.867        5   2011
5        683.277        6   2011
6       1219.334        7   2011
7      11167.498        8   2011
8        101.438        9   2011
9        466.345       10   2011
10       722.921       11   2011
11      7724.592       12   2011
12      6119.954       13   2011
13       465.793       14   2011
14      7299.712       15   2011
15        15.323       16   2011
16       264.597       17   2011
17       145.188       18   2011
18       112.922       19   2011
19       232.863       20   2011
20         0.851       21   2011
21      1059.345       22   2011
22      3822.112       23   2011
23      1166.572       24   2011
24      2122.934       25   2011
25      1421.408       26   2011
26       345.953       27   2011
27       461.495       28   2011
28      2078.810       29   2011
29      7240.799       30   2011
30      3277.632       31   2011
31      1479.648       32   2011
32     10591.144       33   2011
33       103.513       34   2011
34       123.327       35   2011
35       355.288       36   2011
36       794.755       37   2011
37      4995.672       38   2011
38           NaN       39   2011
39         9.020       40   2011
40         6.535       41   2011
41       962.984       42   2011
42           NaN       43   2011
0      65027.849        1   2012
1      68829.735        2   2012
2      50520.665        3   2012
3       1011.186        4   2012
4        522.468        5   2012
5        756.345        6   2012
6       1275.772        7   2012
7      12823.474        8   2012
8        126.954        9   2012
9        470.167       10   2012
10       889.001       11   2012
11      7788.360       12   2012
12      7750.414       13   2012
13       466.376       14   2012
14      8099.869       15   2012
15        22.084       16   2012
16       353.377       17   2012
17       145.881       18   2012
18       117.728       19   2012
19       227.486       20   2012
20         2.206       21   2012
21      1073.152       22   2012
22      4748.239       23   2012
23      1488.156       24   2012
24      1754.966       25   2012
25      1306.694       26   2012
26       388.389       27   2012
27       499.570       28   2012
28      2455.648       29   2012
29      8463.887       30   2012
30      3801.886       31   2012
31      1508.691       32   2012
32     12440.585       33   2012
33       127.007       34   2012
34        89.734       35   2012
35       406.277       36   2012
36       852.966       37   2012
37      5607.654       38   2012
38           NaN       39   2012
39         8.218       40   2012
40         2.914       41   2012
41      1010.249       42   2012
42           NaN       43   2012
0      71850.431        1   2013
1      76675.722        2   2013
2      57496.442        3   2013
3       1117.508        4   2013
4        657.027        5   2013
5        878.193        6   2013
6       1372.977        7   2013
7      13596.131        8   2013
8        104.864        9   2013
9        513.527       10   2013
10      1237.105       11   2013
11      9939.208       12   2013
12      8979.710       13   2013
13       806.644       14   2013
14      9794.199       15   2013
15        28.118       16   2013
16       303.820       17   2013
17       178.272       18   2013
18       121.162       19   2013
19       239.664       20   2013
20         3.048       21   2013
21      1040.914       22   2013
22      4664.912       23   2013
23      1515.417       24   2013
24      2631.972       25   2013
25      1762.583       26   2013
26       464.614       27   2013
27       573.603       28   2013
28      2203.755       29   2013
29      7121.484       30   2013
30      4825.291       31   2013
31      1557.233       32   2013
32     11261.909       33   2013
33       215.320       34   2013
34       136.975       35   2013
35       598.366       36   2013
36       934.910       37   2013
37      5951.859       38   2013
38           NaN       39   2013
39        12.322       40   2013
40         4.127       41   2013
41      1356.991       42   2013
42       711.196       43   2013
0      74476.702        1   2014
1      80272.653        2   2014
2      58724.171        3   2014
3       1155.623        4   2014
4        683.273        5   2014
5        879.079        6   2014
6       1546.318        7   2014
7      14478.332        8   2014
8        119.408        9   2014
9        573.622       10   2014
10      1058.236       11   2014
11      9808.213       12   2014
12      8577.690       13   2014
13       864.475       14   2014
14     10523.626       15   2014
15        27.250       16   2014
16       240.964       17   2014
17       189.129       18   2014
18       125.383       19   2014
19       270.972       20   2014
20         6.439       21   2014
21      1001.505       22   2014
22      4644.253       23   2014
23      1753.492       24   2014
24      2786.235       25   2014
25      2373.200       26   2014
26       592.044       27   2014
27       557.352       28   2014
28      2258.867       29   2014
29      7381.722       30   2014
30      5795.951       31   2014
31      1558.024       32   2014
32     11922.614       33   2014
33       150.615       34   2014
34       111.063       35   2014
35       406.229       36   2014
36      1001.290       37   2014
37      4525.253       38   2014
38       510.318       39   2014
39        13.015       40   2014
40         6.404       41   2014
41       946.741       42   2014
42       716.710       43   2014
0      75990.530        1   2015
1      83326.362        2   2015
2      58598.098        3   2015
3       1342.339        4   2015
4        795.487        5   2015
5        919.719        6   2015
6       1628.293        7   2015
7      16741.702        8   2015
8        129.114        9   2015
9        700.739       10   2015
10      1281.376       11   2015
11      8625.649       12   2015
12      8322.338       13   2015
13       659.878       14   2015
14      9487.207       15   2015
15        34.372       16   2015
16       238.798       17   2015
17       202.444       18   2015
18       160.117       19   2015
19       277.667       20   2015
20         8.744       21   2015
21      1176.696       22   2015
22      4386.648       23   2015
23      2002.327       24   2015
24      2193.535       25   2015
25      2285.007       26   2015
26       398.806       27   2015
27       542.648       28   2015
28      2624.826       29   2015
29      8824.054       30   2015
30      7335.832       31   2015
31      1616.050       32   2015
32     12142.820       33   2015
33       128.203       34   2015
34       174.444       35   2015
35       506.879       36   2015
36       930.095       37   2015
37      7193.311       38   2015
38       477.300       39   2015
39        12.062       40   2015
40         5.839       41   2015
41       746.036       42   2015
42       726.893       43   2015
0      77295.623        1   2016
1      84567.113        2   2016
2      61083.460        3   2016
3       1330.344        4   2016
4        664.894        5   2016
5        910.213        6   2016
6       1581.258        7   2016
7      16789.338        8   2016
8        131.013        9   2016
9        671.143       10   2016
10      1282.454       11   2016
11      9295.161       12   2016
12      8930.284       13   2016
13       736.785       14   2016
14      9445.147       15   2016
15        36.514       16   2016
16       299.363       17   2016
17       230.898       18   2016
18       160.786       19   2016
19       280.149       20   2016
20        11.715       21   2016
21      1270.585       22   2016
22      4653.458       23   2016
23      2002.545       24   2016
24      2880.145       25   2016
25      2362.575       26   2016
26       458.924       27   2016
27       591.230       28   2016
28      2614.958       29   2016
29      7673.744       30   2016
30      7271.490       31   2016
31      1594.676       32   2016
32     12533.620       33   2016
33       158.486       34   2016
34       177.692       35   2016
35       669.106       36   2016
36       996.733       37   2016
37      7759.618       38   2016
38       487.069       39   2016
39        21.110       40   2016
40         4.971       41   2016
41       935.864       42   2016
42       802.944       43   2016
0      77694.057        1   2017
1      86284.800        2   2017
2      60968.477        3   2017
3       1461.350        4   2017
4        584.347        5   2017
5        927.885        6   2017
6       1875.581        7   2017
7      19116.767        8   2017
8        154.875        9   2017
9        780.980       10   2017
10      1193.319       11   2017
11      7796.389       12   2017
12      8405.001       13   2017
13       629.063       14   2017
14      9090.595       15   2017
15        37.421       16   2017
16       469.622       17   2017
17       268.007       18   2017
18       166.527       19   2017
19       299.398       20   2017
20        14.791       21   2017
21      1499.269       22   2017
22      4723.709       23   2017
23      2114.914       24   2017
24      2090.102       25   2017
25      2118.726       26   2017
26       405.883       27   2017
27       587.360       28   2017
28      2706.510       29   2017
29      8175.666       30   2017
30      8590.743       31   2017
31      1654.037       32   2017
32     12573.087       33   2017
33        96.380       34   2017
34       111.441       35   2017
35       389.181       36   2017
36       850.280       37   2017
37      7500.897       38   2017
38       345.142       39   2017
39        15.495       40   2017
40         6.879       41   2017
41      1070.610       42   2017
42       799.501       43   2017
0      83301.821        1   2018
1      92814.199        2   2018
2      66595.788        3   2018
3       1562.003        4   2018
4        823.384        5   2018
5        900.766        6   2018
6       1785.530        7   2018
7      19857.008        8   2018
8        171.006        9   2018
9        897.003       10   2018
10      1389.930       11   2018
11      9144.798       12   2018
12     10206.624       13   2018
13       848.263       14   2018
14      9985.469       15   2018
15        41.052       16   2018
16       300.825       17   2018
17       235.013       18   2018
18       165.818       19   2018
19       322.700       20   2018
20        17.075       21   2018
21      1623.759       22   2018
22      4609.975       23   2018
23      1894.634       24   2018
24      2634.305       25   2018
25      2289.569       26   2018
26       466.487       27   2018
27       524.076       28   2018
28      2763.562       29   2018
29      7841.187       30   2018
30      9512.378       31   2018
31      1704.891       32   2018
32     12346.615       33   2018
33       193.981       34   2018
34       169.006       35   2018
35       735.467       36   2018
36      1002.437       37   2018
37      8406.527       38   2018
38       571.883       39   2018
39        26.177       40   2018
40         8.598       41   2018
41      1255.503       42   2018
42       862.743       43   2018

In [96]:
production_electricite_renouvelable.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 430 entries, 0 to 42
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   quantite_tep  419 non-null    float64
 1   pays_id       430 non-null    int64
 2   annee         430 non-null    int64
dtypes: float64(1), int64(2)
memory usage: 13.4 KB

In [97]:
production_electricite_renouvelable.insert(0, 'id', range(1, 1 + len(production_electricite_renouvelable)))
production_electricite_renouvelable

     id  quantite_tep  pays_id  annee
0     1     51552.228        1   2009
1     2     54039.770        2   2009
2     3     39937.608        3   2009
3     4       590.598        4   2009
4     5       369.767        5   2009
5     6       447.811        6   2009
6     7       865.262        7   2009
7     8      8735.082        8   2009
8     9        46.459        9   2009
9    10       383.855       10   2009
10   11       727.088       11   2009
11   12      6606.277       12   2009
12   13      6417.020       13   2009
13   14       651.132       14   2009
14   15      6325.070       15   2009
15   16         2.640       16   2009
16   17       305.681       17   2009
17   18       120.286       18   2009
18   19        85.527       19   2009
19   20       248.900       20   2009
20   21           NaN       21   2009
21   22       931.644       22   2009
22   23      4294.920       23   2009
23   24       797.763       24   2009
24   25      1635.078       25   2009
25   26      1360.804       26   2009
26   27       421.912       27   2009
27   28       442.525       28   2009
28   29      1865.946       29   2009
29   30      6873.181       30   2009
30   31      2487.542       31   2009
31   32      1447.374       32   2009
32   33     10944.196       33   2009
33   34       178.074       34   2009
34   35       109.230       35   2009
35   36       447.206       36   2009
36   37       958.212       37   2009
37   38      3279.547       38   2009
38   39           NaN       39   2009
39   40        10.318       40   2009
40   41           NaN       41   2009
41   42      1041.935       42   2009
42   43           NaN       43   2009
0    44     58628.867        1   2010
1    45     61150.949        2   2010
2    46     45552.691        3   2010
3    47       675.015        4   2010
4    48       552.364        5   2010
5    49       558.406        6   2010
6    50      1068.717        7   2010
7    51      9594.153        8   2010
8    52        89.758        9   2010
9    53       335.825       10   2010
10   54       906.852       11   2010
11   55      8682.992       12   2010
12   56      7137.404       13   2010
13   57       808.647       14   2010
14   58      6900.625       15   2010
15   59         6.298       16   2010
16   60       312.548       17   2010
17   61       143.248       18   2010
18   62       140.014       19   2010
19   63       259.629       20   2010
20   64         0.058       21   2010
21   65       962.740       22   2010
22   66      4143.882       23   2010
23   67       985.122       24   2010
24   68      2472.105       25   2010
25   69      1776.428       26   2010
26   70       424.135       27   2010
27   71       544.621       28   2010
28   72      2080.418       29   2010
29   73      7066.863       30   2010
30   74      2522.082       31   2010
31   75      1466.673       32   2010
32   76     10179.278       33   2010
33   77       236.457       34   2010
34   78       209.071       35   2010
35   79       650.645       36   2010
36   80      1080.911       37   2010
37   81      4790.449       38   2010
38   82           NaN       39   2010
39   83        13.500       40   2010
40   84         6.793       41   2010
41   85      1151.419       42   2010
42   86           NaN       43   2010
0    87     57692.693        1   2011
1    88     60970.325        2   2011
2    89     44857.780        3   2011
3    90       825.790        4   2011
4    91       404.867        5   2011
5    92       683.277        6   2011
6    93      1219.334        7   2011
7    94     11167.498        8   2011
8    95       101.438        9   2011
9    96       466.345       10   2011
10   97       722.921       11   2011
11   98      7724.592       12   2011
12   99      6119.954       13   2011
13  100       465.793       14   2011
14  101      7299.712       15   2011
15  102        15.323       16   2011
16  103       264.597       17   2011
17  104       145.188       18   2011
18  105       112.922       19   2011
19  106       232.863       20   2011
20  107         0.851       21   2011
21  108      1059.345       22   2011
22  109      3822.112       23   2011
23  110      1166.572       24   2011
24  111      2122.934       25   2011
25  112      1421.408       26   2011
26  113       345.953       27   2011
27  114       461.495       28   2011
28  115      2078.810       29   2011
29  116      7240.799       30   2011
30  117      3277.632       31   2011
31  118      1479.648       32   2011
32  119     10591.144       33   2011
33  120       103.513       34   2011
34  121       123.327       35   2011
35  122       355.288       36   2011
36  123       794.755       37   2011
37  124      4995.672       38   2011
38  125           NaN       39   2011
39  126         9.020       40   2011
40  127         6.535       41   2011
41  128       962.984       42   2011
42  129           NaN       43   2011
0   130     65027.849        1   2012
1   131     68829.735        2   2012
2   132     50520.665        3   2012
3   133      1011.186        4   2012
4   134       522.468        5   2012
5   135       756.345        6   2012
6   136      1275.772        7   2012
7   137     12823.474        8   2012
8   138       126.954        9   2012
9   139       470.167       10   2012
10  140       889.001       11   2012
11  141      7788.360       12   2012
12  142      7750.414       13   2012
13  143       466.376       14   2012
14  144      8099.869       15   2012
15  145        22.084       16   2012
16  146       353.377       17   2012
17  147       145.881       18   2012
18  148       117.728       19   2012
19  149       227.486       20   2012
20  150         2.206       21   2012
21  151      1073.152       22   2012
22  152      4748.239       23   2012
23  153      1488.156       24   2012
24  154      1754.966       25   2012
25  155      1306.694       26   2012
26  156       388.389       27   2012
27  157       499.570       28   2012
28  158      2455.648       29   2012
29  159      8463.887       30   2012
30  160      3801.886       31   2012
31  161      1508.691       32   2012
32  162     12440.585       33   2012
33  163       127.007       34   2012
34  164        89.734       35   2012
35  165       406.277       36   2012
36  166       852.966       37   2012
37  167      5607.654       38   2012
38  168           NaN       39   2012
39  169         8.218       40   2012
40  170         2.914       41   2012
41  171      1010.249       42   2012
42  172           NaN       43   2012
0   173     71850.431        1   2013
1   174     76675.722        2   2013
2   175     57496.442        3   2013
3   176      1117.508        4   2013
4   177       657.027        5   2013
5   178       878.193        6   2013
6   179      1372.977        7   2013
7   180     13596.131        8   2013
8   181       104.864        9   2013
9   182       513.527       10   2013
10  183      1237.105       11   2013
11  184      9939.208       12   2013
12  185      8979.710       13   2013
13  186       806.644       14   2013
14  187      9794.199       15   2013
15  188        28.118       16   2013
16  189       303.820       17   2013
17  190       178.272       18   2013
18  191       121.162       19   2013
19  192       239.664       20   2013
20  193         3.048       21   2013
21  194      1040.914       22   2013
22  195      4664.912       23   2013
23  196      1515.417       24   2013
24  197      2631.972       25   2013
25  198      1762.583       26   2013
26  199       464.614       27   2013
27  200       573.603       28   2013
28  201      2203.755       29   2013
29  202      7121.484       30   2013
30  203      4825.291       31   2013
31  204      1557.233       32   2013
32  205     11261.909       33   2013
33  206       215.320       34   2013
34  207       136.975       35   2013
35  208       598.366       36   2013
36  209       934.910       37   2013
37  210      5951.859       38   2013
38  211           NaN       39   2013
39  212        12.322       40   2013
40  213         4.127       41   2013
41  214      1356.991       42   2013
42  215       711.196       43   2013
0   216     74476.702        1   2014
1   217     80272.653        2   2014
2   218     58724.171        3   2014
3   219      1155.623        4   2014
4   220       683.273        5   2014
5   221       879.079        6   2014
6   222      1546.318        7   2014
7   223     14478.332        8   2014
8   224       119.408        9   2014
9   225       573.622       10   2014
10  226      1058.236       11   2014
11  227      9808.213       12   2014
12  228      8577.690       13   2014
13  229       864.475       14   2014
14  230     10523.626       15   2014
15  231        27.250       16   2014
16  232       240.964       17   2014
17  233       189.129       18   2014
18  234       125.383       19   2014
19  235       270.972       20   2014
20  236         6.439       21   2014
21  237      1001.505       22   2014
22  238      4644.253       23   2014
23  239      1753.492       24   2014
24  240      2786.235       25   2014
25  241      2373.200       26   2014
26  242       592.044       27   2014
27  243       557.352       28   2014
28  244      2258.867       29   2014
29  245      7381.722       30   2014
30  246      5795.951       31   2014
31  247      1558.024       32   2014
32  248     11922.614       33   2014
33  249       150.615       34   2014
34  250       111.063       35   2014
35  251       406.229       36   2014
36  252      1001.290       37   2014
37  253      4525.253       38   2014
38  254       510.318       39   2014
39  255        13.015       40   2014
40  256         6.404       41   2014
41  257       946.741       42   2014
42  258       716.710       43   2014
0   259     75990.530        1   2015
1   260     83326.362        2   2015
2   261     58598.098        3   2015
3   262      1342.339        4   2015
4   263       795.487        5   2015
5   264       919.719        6   2015
6   265      1628.293        7   2015
7   266     16741.702        8   2015
8   267       129.114        9   2015
9   268       700.739       10   2015
10  269      1281.376       11   2015
11  270      8625.649       12   2015
12  271      8322.338       13   2015
13  272       659.878       14   2015
14  273      9487.207       15   2015
15  274        34.372       16   2015
16  275       238.798       17   2015
17  276       202.444       18   2015
18  277       160.117       19   2015
19  278       277.667       20   2015
20  279         8.744       21   2015
21  280      1176.696       22   2015
22  281      4386.648       23   2015
23  282      2002.327       24   2015
24  283      2193.535       25   2015
25  284      2285.007       26   2015
26  285       398.806       27   2015
27  286       542.648       28   2015
28  287      2624.826       29   2015
29  288      8824.054       30   2015
30  289      7335.832       31   2015
31  290      1616.050       32   2015
32  291     12142.820       33   2015
33  292       128.203       34   2015
34  293       174.444       35   2015
35  294       506.879       36   2015
36  295       930.095       37   2015
37  296      7193.311       38   2015
38  297       477.300       39   2015
39  298        12.062       40   2015
40  299         5.839       41   2015
41  300       746.036       42   2015
42  301       726.893       43   2015
0   302     77295.623        1   2016
1   303     84567.113        2   2016
2   304     61083.460        3   2016
3   305      1330.344        4   2016
4   306       664.894        5   2016
5   307       910.213        6   2016
6   308      1581.258        7   2016
7   309     16789.338        8   2016
8   310       131.013        9   2016
9   311       671.143       10   2016
10  312      1282.454       11   2016
11  313      9295.161       12   2016
12  314      8930.284       13   2016
13  315       736.785       14   2016
14  316      9445.147       15   2016
15  317        36.514       16   2016
16  318       299.363       17   2016
17  319       230.898       18   2016
18  320       160.786       19   2016
19  321       280.149       20   2016
20  322        11.715       21   2016
21  323      1270.585       22   2016
22  324      4653.458       23   2016
23  325      2002.545       24   2016
24  326      2880.145       25   2016
25  327      2362.575       26   2016
26  328       458.924       27   2016
27  329       591.230       28   2016
28  330      2614.958       29   2016
29  331      7673.744       30   2016
30  332      7271.490       31   2016
31  333      1594.676       32   2016
32  334     12533.620       33   2016
33  335       158.486       34   2016
34  336       177.692       35   2016
35  337       669.106       36   2016
36  338       996.733       37   2016
37  339      7759.618       38   2016
38  340       487.069       39   2016
39  341        21.110       40   2016
40  342         4.971       41   2016
41  343       935.864       42   2016
42  344       802.944       43   2016
0   345     77694.057        1   2017
1   346     86284.800        2   2017
2   347     60968.477        3   2017
3   348      1461.350        4   2017
4   349       584.347        5   2017
5   350       927.885        6   2017
6   351      1875.581        7   2017
7   352     19116.767        8   2017
8   353       154.875        9   2017
9   354       780.980       10   2017
10  355      1193.319       11   2017
11  356      7796.389       12   2017
12  357      8405.001       13   2017
13  358       629.063       14   2017
14  359      9090.595       15   2017
15  360        37.421       16   2017
16  361       469.622       17   2017
17  362       268.007       18   2017
18  363       166.527       19   2017
19  364       299.398       20   2017
20  365        14.791       21   2017
21  366      1499.269       22   2017
22  367      4723.709       23   2017
23  368      2114.914       24   2017
24  369      2090.102       25   2017
25  370      2118.726       26   2017
26  371       405.883       27   2017
27  372       587.360       28   2017
28  373      2706.510       29   2017
29  374      8175.666       30   2017
30  375      8590.743       31   2017
31  376      1654.037       32   2017
32  377     12573.087       33   2017
33  378        96.380       34   2017
34  379       111.441       35   2017
35  380       389.181       36   2017
36  381       850.280       37   2017
37  382      7500.897       38   2017
38  383       345.142       39   2017
39  384        15.495       40   2017
40  385         6.879       41   2017
41  386      1070.610       42   2017
42  387       799.501       43   2017
0   388     83301.821        1   2018
1   389     92814.199        2   2018
2   390     66595.788        3   2018
3   391      1562.003        4   2018
4   392       823.384        5   2018
5   393       900.766        6   2018
6   394      1785.530        7   2018
7   395     19857.008        8   2018
8   396       171.006        9   2018
9   397       897.003       10   2018
10  398      1389.930       11   2018
11  399      9144.798       12   2018
12  400     10206.624       13   2018
13  401       848.263       14   2018
14  402      9985.469       15   2018
15  403        41.052       16   2018
16  404       300.825       17   2018
17  405       235.013       18   2018
18  406       165.818       19   2018
19  407       322.700       20   2018
20  408        17.075       21   2018
21  409      1623.759       22   2018
22  410      4609.975       23   2018
23  411      1894.634       24   2018
24  412      2634.305       25   2018
25  413      2289.569       26   2018
26  414       466.487       27   2018
27  415       524.076       28   2018
28  416      2763.562       29   2018
29  417      7841.187       30   2018
30  418      9512.378       31   2018
31  419      1704.891       32   2018
32  420     12346.615       33   2018
33  421       193.981       34   2018
34  422       169.006       35   2018
35  423       735.467       36   2018
36  424      1002.437       37   2018
37  425      8406.527       38   2018
38  426       571.883       39   2018
39  427        26.177       40   2018
40  428         8.598       41   2018
41  429      1255.503       42   2018
42  430       862.743       43   2018

In [98]:
production_electricite_renouvelable = production_electricite_renouvelable[['id','pays_id','annee','quantite_tep']]
production_electricite_renouvelable

     id  pays_id  annee  quantite_tep
0     1        1   2009     51552.228
1     2        2   2009     54039.770
2     3        3   2009     39937.608
3     4        4   2009       590.598
4     5        5   2009       369.767
5     6        6   2009       447.811
6     7        7   2009       865.262
7     8        8   2009      8735.082
8     9        9   2009        46.459
9    10       10   2009       383.855
10   11       11   2009       727.088
11   12       12   2009      6606.277
12   13       13   2009      6417.020
13   14       14   2009       651.132
14   15       15   2009      6325.070
15   16       16   2009         2.640
16   17       17   2009       305.681
17   18       18   2009       120.286
18   19       19   2009        85.527
19   20       20   2009       248.900
20   21       21   2009           NaN
21   22       22   2009       931.644
22   23       23   2009      4294.920
23   24       24   2009       797.763
24   25       25   2009      1635.078
25   26       26   2009      1360.804
26   27       27   2009       421.912
27   28       28   2009       442.525
28   29       29   2009      1865.946
29   30       30   2009      6873.181
30   31       31   2009      2487.542
31   32       32   2009      1447.374
32   33       33   2009     10944.196
33   34       34   2009       178.074
34   35       35   2009       109.230
35   36       36   2009       447.206
36   37       37   2009       958.212
37   38       38   2009      3279.547
38   39       39   2009           NaN
39   40       40   2009        10.318
40   41       41   2009           NaN
41   42       42   2009      1041.935
42   43       43   2009           NaN
0    44        1   2010     58628.867
1    45        2   2010     61150.949
2    46        3   2010     45552.691
3    47        4   2010       675.015
4    48        5   2010       552.364
5    49        6   2010       558.406
6    50        7   2010      1068.717
7    51        8   2010      9594.153
8    52        9   2010        89.758
9    53       10   2010       335.825
10   54       11   2010       906.852
11   55       12   2010      8682.992
12   56       13   2010      7137.404
13   57       14   2010       808.647
14   58       15   2010      6900.625
15   59       16   2010         6.298
16   60       17   2010       312.548
17   61       18   2010       143.248
18   62       19   2010       140.014
19   63       20   2010       259.629
20   64       21   2010         0.058
21   65       22   2010       962.740
22   66       23   2010      4143.882
23   67       24   2010       985.122
24   68       25   2010      2472.105
25   69       26   2010      1776.428
26   70       27   2010       424.135
27   71       28   2010       544.621
28   72       29   2010      2080.418
29   73       30   2010      7066.863
30   74       31   2010      2522.082
31   75       32   2010      1466.673
32   76       33   2010     10179.278
33   77       34   2010       236.457
34   78       35   2010       209.071
35   79       36   2010       650.645
36   80       37   2010      1080.911
37   81       38   2010      4790.449
38   82       39   2010           NaN
39   83       40   2010        13.500
40   84       41   2010         6.793
41   85       42   2010      1151.419
42   86       43   2010           NaN
0    87        1   2011     57692.693
1    88        2   2011     60970.325
2    89        3   2011     44857.780
3    90        4   2011       825.790
4    91        5   2011       404.867
5    92        6   2011       683.277
6    93        7   2011      1219.334
7    94        8   2011     11167.498
8    95        9   2011       101.438
9    96       10   2011       466.345
10   97       11   2011       722.921
11   98       12   2011      7724.592
12   99       13   2011      6119.954
13  100       14   2011       465.793
14  101       15   2011      7299.712
15  102       16   2011        15.323
16  103       17   2011       264.597
17  104       18   2011       145.188
18  105       19   2011       112.922
19  106       20   2011       232.863
20  107       21   2011         0.851
21  108       22   2011      1059.345
22  109       23   2011      3822.112
23  110       24   2011      1166.572
24  111       25   2011      2122.934
25  112       26   2011      1421.408
26  113       27   2011       345.953
27  114       28   2011       461.495
28  115       29   2011      2078.810
29  116       30   2011      7240.799
30  117       31   2011      3277.632
31  118       32   2011      1479.648
32  119       33   2011     10591.144
33  120       34   2011       103.513
34  121       35   2011       123.327
35  122       36   2011       355.288
36  123       37   2011       794.755
37  124       38   2011      4995.672
38  125       39   2011           NaN
39  126       40   2011         9.020
40  127       41   2011         6.535
41  128       42   2011       962.984
42  129       43   2011           NaN
0   130        1   2012     65027.849
1   131        2   2012     68829.735
2   132        3   2012     50520.665
3   133        4   2012      1011.186
4   134        5   2012       522.468
5   135        6   2012       756.345
6   136        7   2012      1275.772
7   137        8   2012     12823.474
8   138        9   2012       126.954
9   139       10   2012       470.167
10  140       11   2012       889.001
11  141       12   2012      7788.360
12  142       13   2012      7750.414
13  143       14   2012       466.376
14  144       15   2012      8099.869
15  145       16   2012        22.084
16  146       17   2012       353.377
17  147       18   2012       145.881
18  148       19   2012       117.728
19  149       20   2012       227.486
20  150       21   2012         2.206
21  151       22   2012      1073.152
22  152       23   2012      4748.239
23  153       24   2012      1488.156
24  154       25   2012      1754.966
25  155       26   2012      1306.694
26  156       27   2012       388.389
27  157       28   2012       499.570
28  158       29   2012      2455.648
29  159       30   2012      8463.887
30  160       31   2012      3801.886
31  161       32   2012      1508.691
32  162       33   2012     12440.585
33  163       34   2012       127.007
34  164       35   2012        89.734
35  165       36   2012       406.277
36  166       37   2012       852.966
37  167       38   2012      5607.654
38  168       39   2012           NaN
39  169       40   2012         8.218
40  170       41   2012         2.914
41  171       42   2012      1010.249
42  172       43   2012           NaN
0   173        1   2013     71850.431
1   174        2   2013     76675.722
2   175        3   2013     57496.442
3   176        4   2013      1117.508
4   177        5   2013       657.027
5   178        6   2013       878.193
6   179        7   2013      1372.977
7   180        8   2013     13596.131
8   181        9   2013       104.864
9   182       10   2013       513.527
10  183       11   2013      1237.105
11  184       12   2013      9939.208
12  185       13   2013      8979.710
13  186       14   2013       806.644
14  187       15   2013      9794.199
15  188       16   2013        28.118
16  189       17   2013       303.820
17  190       18   2013       178.272
18  191       19   2013       121.162
19  192       20   2013       239.664
20  193       21   2013         3.048
21  194       22   2013      1040.914
22  195       23   2013      4664.912
23  196       24   2013      1515.417
24  197       25   2013      2631.972
25  198       26   2013      1762.583
26  199       27   2013       464.614
27  200       28   2013       573.603
28  201       29   2013      2203.755
29  202       30   2013      7121.484
30  203       31   2013      4825.291
31  204       32   2013      1557.233
32  205       33   2013     11261.909
33  206       34   2013       215.320
34  207       35   2013       136.975
35  208       36   2013       598.366
36  209       37   2013       934.910
37  210       38   2013      5951.859
38  211       39   2013           NaN
39  212       40   2013        12.322
40  213       41   2013         4.127
41  214       42   2013      1356.991
42  215       43   2013       711.196
0   216        1   2014     74476.702
1   217        2   2014     80272.653
2   218        3   2014     58724.171
3   219        4   2014      1155.623
4   220        5   2014       683.273
5   221        6   2014       879.079
6   222        7   2014      1546.318
7   223        8   2014     14478.332
8   224        9   2014       119.408
9   225       10   2014       573.622
10  226       11   2014      1058.236
11  227       12   2014      9808.213
12  228       13   2014      8577.690
13  229       14   2014       864.475
14  230       15   2014     10523.626
15  231       16   2014        27.250
16  232       17   2014       240.964
17  233       18   2014       189.129
18  234       19   2014       125.383
19  235       20   2014       270.972
20  236       21   2014         6.439
21  237       22   2014      1001.505
22  238       23   2014      4644.253
23  239       24   2014      1753.492
24  240       25   2014      2786.235
25  241       26   2014      2373.200
26  242       27   2014       592.044
27  243       28   2014       557.352
28  244       29   2014      2258.867
29  245       30   2014      7381.722
30  246       31   2014      5795.951
31  247       32   2014      1558.024
32  248       33   2014     11922.614
33  249       34   2014       150.615
34  250       35   2014       111.063
35  251       36   2014       406.229
36  252       37   2014      1001.290
37  253       38   2014      4525.253
38  254       39   2014       510.318
39  255       40   2014        13.015
40  256       41   2014         6.404
41  257       42   2014       946.741
42  258       43   2014       716.710
0   259        1   2015     75990.530
1   260        2   2015     83326.362
2   261        3   2015     58598.098
3   262        4   2015      1342.339
4   263        5   2015       795.487
5   264        6   2015       919.719
6   265        7   2015      1628.293
7   266        8   2015     16741.702
8   267        9   2015       129.114
9   268       10   2015       700.739
10  269       11   2015      1281.376
11  270       12   2015      8625.649
12  271       13   2015      8322.338
13  272       14   2015       659.878
14  273       15   2015      9487.207
15  274       16   2015        34.372
16  275       17   2015       238.798
17  276       18   2015       202.444
18  277       19   2015       160.117
19  278       20   2015       277.667
20  279       21   2015         8.744
21  280       22   2015      1176.696
22  281       23   2015      4386.648
23  282       24   2015      2002.327
24  283       25   2015      2193.535
25  284       26   2015      2285.007
26  285       27   2015       398.806
27  286       28   2015       542.648
28  287       29   2015      2624.826
29  288       30   2015      8824.054
30  289       31   2015      7335.832
31  290       32   2015      1616.050
32  291       33   2015     12142.820
33  292       34   2015       128.203
34  293       35   2015       174.444
35  294       36   2015       506.879
36  295       37   2015       930.095
37  296       38   2015      7193.311
38  297       39   2015       477.300
39  298       40   2015        12.062
40  299       41   2015         5.839
41  300       42   2015       746.036
42  301       43   2015       726.893
0   302        1   2016     77295.623
1   303        2   2016     84567.113
2   304        3   2016     61083.460
3   305        4   2016      1330.344
4   306        5   2016       664.894
5   307        6   2016       910.213
6   308        7   2016      1581.258
7   309        8   2016     16789.338
8   310        9   2016       131.013
9   311       10   2016       671.143
10  312       11   2016      1282.454
11  313       12   2016      9295.161
12  314       13   2016      8930.284
13  315       14   2016       736.785
14  316       15   2016      9445.147
15  317       16   2016        36.514
16  318       17   2016       299.363
17  319       18   2016       230.898
18  320       19   2016       160.786
19  321       20   2016       280.149
20  322       21   2016        11.715
21  323       22   2016      1270.585
22  324       23   2016      4653.458
23  325       24   2016      2002.545
24  326       25   2016      2880.145
25  327       26   2016      2362.575
26  328       27   2016       458.924
27  329       28   2016       591.230
28  330       29   2016      2614.958
29  331       30   2016      7673.744
30  332       31   2016      7271.490
31  333       32   2016      1594.676
32  334       33   2016     12533.620
33  335       34   2016       158.486
34  336       35   2016       177.692
35  337       36   2016       669.106
36  338       37   2016       996.733
37  339       38   2016      7759.618
38  340       39   2016       487.069
39  341       40   2016        21.110
40  342       41   2016         4.971
41  343       42   2016       935.864
42  344       43   2016       802.944
0   345        1   2017     77694.057
1   346        2   2017     86284.800
2   347        3   2017     60968.477
3   348        4   2017      1461.350
4   349        5   2017       584.347
5   350        6   2017       927.885
6   351        7   2017      1875.581
7   352        8   2017     19116.767
8   353        9   2017       154.875
9   354       10   2017       780.980
10  355       11   2017      1193.319
11  356       12   2017      7796.389
12  357       13   2017      8405.001
13  358       14   2017       629.063
14  359       15   2017      9090.595
15  360       16   2017        37.421
16  361       17   2017       469.622
17  362       18   2017       268.007
18  363       19   2017       166.527
19  364       20   2017       299.398
20  365       21   2017        14.791
21  366       22   2017      1499.269
22  367       23   2017      4723.709
23  368       24   2017      2114.914
24  369       25   2017      2090.102
25  370       26   2017      2118.726
26  371       27   2017       405.883
27  372       28   2017       587.360
28  373       29   2017      2706.510
29  374       30   2017      8175.666
30  375       31   2017      8590.743
31  376       32   2017      1654.037
32  377       33   2017     12573.087
33  378       34   2017        96.380
34  379       35   2017       111.441
35  380       36   2017       389.181
36  381       37   2017       850.280
37  382       38   2017      7500.897
38  383       39   2017       345.142
39  384       40   2017        15.495
40  385       41   2017         6.879
41  386       42   2017      1070.610
42  387       43   2017       799.501
0   388        1   2018     83301.821
1   389        2   2018     92814.199
2   390        3   2018     66595.788
3   391        4   2018      1562.003
4   392        5   2018       823.384
5   393        6   2018       900.766
6   394        7   2018      1785.530
7   395        8   2018     19857.008
8   396        9   2018       171.006
9   397       10   2018       897.003
10  398       11   2018      1389.930
11  399       12   2018      9144.798
12  400       13   2018     10206.624
13  401       14   2018       848.263
14  402       15   2018      9985.469
15  403       16   2018        41.052
16  404       17   2018       300.825
17  405       18   2018       235.013
18  406       19   2018       165.818
19  407       20   2018       322.700
20  408       21   2018        17.075
21  409       22   2018      1623.759
22  410       23   2018      4609.975
23  411       24   2018      1894.634
24  412       25   2018      2634.305
25  413       26   2018      2289.569
26  414       27   2018       466.487
27  415       28   2018       524.076
28  416       29   2018      2763.562
29  417       30   2018      7841.187
30  418       31   2018      9512.378
31  419       32   2018      1704.891
32  420       33   2018     12346.615
33  421       34   2018       193.981
34  422       35   2018       169.006
35  423       36   2018       735.467
36  424       37   2018      1002.437
37  425       38   2018      8406.527
38  426       39   2018       571.883
39  427       40   2018        26.177
40  428       41   2018         8.598
41  429       42   2018      1255.503
42  430       43   2018       862.743

### 2.4. Création du fichier 'production_electricite_renouvelable_table.tsv"

In [99]:
#production_electricite_renouvelable.to_csv('production_electricite_renouvelable_table.tsv',index=False,header=['id','pays_id','annee','quantite_tep'], sep='\t')

## 3. Le total de la production d'électricité

![image](capture_ecran/production_electricite_total.png)

Nous avons sélectionné parmis l'ensemble de ce dataset l'intégralité des combustibles en Europe de 2009 à 2018 en milliers de tonnes équivalent pétrole.

In [100]:
data3 = pd.read_csv('data/nrg_bal_peh_1_total.tsv',sep='[|\t]', engine='python', encoding = "ISO-8859-1")
data3

,"GEO,NRG_BAL,SIEC,UNIT\TIME",2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,"Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","244.415,946","256.256,793","252.559,704","252.297,715","250.738,370","245.607,203","249.554,191","251.385,363","254.161,138","252.920,496"
1,"Union européenne - 28 pays (2013-2020),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","276.811,058","289.108,889","284.200,638","283.585,663","281.545,700","274.678,627","278.624,390","280.429,187","283.060,838","281.359,242"
2,"Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","196.495,458","205.466,311","201.240,068","200.843,565","200.335,625","195.145,509","198.230,875","200.540,855","201.942,440","200.574,261"
3,"Belgique,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","7.837,577","8.162,939","7.747,746","7.110,535","7.142,193","6.209,733","5.963,474","7.333,482","7.413,981","6.415,090"
4,"Bulgarie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","3.692,897","4.010,194","4.365,744","4.068,211","3.763,441","4.081,811","4.230,655","3.890,260","3.919,070","4.025,400"
5,"Tchéquie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","7.066,699","7.379,137","7.514,188","7.510,245","7.466,746","7.399,811","7.206,351","7.155,123","7.476,084","7.558,639"
6,"Danemark,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","3.128,375","3.341,539","3.029,159","2.639,821","2.987,341","2.767,293","2.488,446","2.625,830","2.669,108","2.611,916"
7,"Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","51.125,107","54.259,501","52.538,521","53.868,788","54.766,638","53.807,653","55.587,618","55.766,208","56.063,801","55.167,068"
8,"Estonie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","754,800","1.114,693","1.108,660","1.028,932","1.141,408","1.070,139","895,666","1.047,780","1.110,704","1.062,752"
9,"Irlande,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","2.434,530","2.437,941","2.335,686","2.352,110","2.228,754","2.243,085","2.441,155","2.623,642","2.654,581","2.677,024"
10,"Grèce,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","5.276,443","4.934,797","5.110,625","5.241,538","4.914,233","4.339,922","4.460,396","4.680,820","4.752,028","4.579,775"
11,"Espagne,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","25.303,439","25.913,001","25.251,591","25.570,389","24.559,909","23.968,164","24.135,477","23.616,962","23.700,344","23.590,542"
12,"France,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","46.060,545","48.938,359","49.265,195","49.175,178","49.987,860","49.166,532","49.769,935","48.462,534","48.255,417","49.980,732"
13,"Croatie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","1.156,893","1.281,390","977,831","924,760","1.208,363","1.165,335","980,428","1.102,305","1.030,396","1.172,115"
14,"Italie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","25.110,746","25.905,838","25.947,751","25.668,568","24.853,766","24.003,913","24.281,691","24.852,309","25.379,967","24.858,748"
15,"Chypre,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","448,384","457,630","423,836","405,575","368,874","374,026","389,918","420,263","430,298","435,130"
16,"Lettonie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","478,768","569,814","524,012","530,333","533,829","441,910","475,857","552,501","647,566","578,235"
17,"Lituanie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","1.297,242","472,826","392,565","414,066","388,981","357,192","401,523","343,669","338,527","281,978"
18,"Luxembourg,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","333,481","394,779","319,544","328,201","248,420","254,942","237,840","188,958","192,188","189,245"
19,"Hongrie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","3.087,534","3.213,254","3.097,092","2.977,998","2.601,915","2.523,469","2.605,143","2.736,331","2.820,550","2.739,897"
20,"Malte,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","186,414","181,744","187,352","197,219","193,590","193,026","112,183","73,696","142,025","168,708"
21,"Pays-Bas,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","9.764,359","10.242,071","9.786,172","8.863,973","8.728,051","8.874,666","9.478,075","9.894,607","10.071,975","9.833,606"
22,"Autriche,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","5.939,015","6.114,368","5.657,920","6.241,786","5.876,409","5.625,578","5.613,460","5.872,144","6.131,720","5.897,163"
23,"Pologne,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","13.042,704","13.549,029","14.053,553","13.934,503","14.141,739","13.664,384","14.172,768","14.322,391","14.652,069","14.610,025"
24,"Portugal,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","4.317,029","4.650,537","4.510,598","4.007,871","4.442,670","4.539,682","4.506,580","5.187,287","5.110,208","5.127,780"
25,"Roumanie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","4.988,319","5.243,238","5.349,525","5.076,944","5.063,306","5.647,001","5.700,338","5.597,854","5.528,463","5.578,372"
26,"Slovénie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","1.410,420","1.413,435","1.380,739","1.353,055","1.384,593","1.499,376","1.298,334","1.418,905","1.403,803","1.404,191"
27,"Slovaquie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","2.245,534","2.391,912","2.457,282","2.458,727","2.473,173","2.345,916","2.304,643","2.315,907","2.371,711","2.309,114"
28,"Finlande,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","6.171,625","6.910,126","6.294,273","6.026,721","6.102,274","5.830,054","5.877,050","5.889,181","5.771,596","6.017,380"
29,"Suède,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","11.757,067","12.772,701","12.932,544","14.321,668","13.169,894","13.212,590","13.939,187","13.414,414","14.122,958","14.049,871"
30,"Royaume-Uni,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","32.395,112","32.852,096","31.640,934","31.287,948","30.807,330","29.071,424","29.070,199","29.043,824","28.899,700","28.438,746"
31,"Islande,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","1.447,550","1.466,845","1.479,820","1.508,949","1.557,662","1.558,282","1.616,394","1.594,934","1.654,216","1.705,052"
32,"Norvège,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","11.323,990","10.620,292","10.961,393","12.694,153","11.506,277","12.180,310","12.400,000","12.788,822","12.825,107","12.601,582"
33,"Monténégro,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","237,317","345,830","228,362","244,547","339,223","272,799","258,212","270,094","213,482","327,661"
34,"Macédoine du Nord,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","587,132","624,290","581,195","538,401","523,991","462,052","485,450","484,050","481,530","482,130"
35,"Albanie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","447,291","650,731","360,361","406,277","598,366","406,229","506,879","669,106","389,181","735,467"
36,"Serbie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","3.295,099","3.276,268","3.319,003","3.164,144","3.428,805","2.928,633","3.293,035","3.382,803","3.185,328","3.218,035"
37,"Turquie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","16.744,269","18.151,107","19.715,315","20.583,378","20.625,614","21.635,818","22.466,715","23.533,462","25.488,323","26.126,541"
38,"Bosnie-Herzégovine,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,:,"1.463,715","1.413,414","1.527,653","1.413,414","1.647,463"
39,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","427,859","444,368","498,788","510,970","561,075","467,444","526,164","514,317","508,885","508,617"
40,"Moldavie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","0,000","91,488","87,360","80,128","77,816","82,844","80,646","77,886","77,042","82,029"
41,"Ukraine,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","14.928,521","16.236,285","16.762,468","17.100,447","16.713,396","15.719,570","14.033,826","14.143,818","13.412,752","13.741,531"
42,"Géorgie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,"864,936","891,774","931,450","995,206","991,505","1.044,592"

In [101]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   GEO,NRG_BAL,SIEC,UNIT\TIME  43 non-null     object
 1   2009                        43 non-null     object
 2   2010                        43 non-null     object
 3   2011                        43 non-null     object
 4   2012                        43 non-null     object
 5   2013                        43 non-null     object
 6   2014                        43 non-null     object
 7   2015                        43 non-null     object
 8   2016                        43 non-null     object
 9   2017                        43 non-null     object
 10  2018                        43 non-null     object
dtypes: object(11)
memory usage: 3.8+ KB

### 3.1. Split de la colonne GEO,NRG_BAL,SIEC,UNIT\TIME

In [102]:
data3['GEO,NRG_BAL,SIEC,UNIT\TIME']

0                                     Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
1                                            Union européenne - 28 pays (2013-2020),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
2                                            Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
3                                                                          Belgique,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
4                                                                          Bulgarie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
5                                                                          Tchéquie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
6                                                                          Danemark,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
7                            Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
8                                                                           Estonie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
9                                                                           Irlande,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
10                                                                            Grèce,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
11                                                                          Espagne,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
12                                                                           France,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
13                                                                          Croatie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
14                                                                           Italie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
15                                                                           Chypre,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
16                                                                         Lettonie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
17                                                                         Lituanie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
18                                                                       Luxembourg,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
19                                                                          Hongrie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
20                                                                            Malte,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
21                                                                         Pays-Bas,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
22                                                                         Autriche,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
23                                                                          Pologne,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
24                                                                         Portugal,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
25                                                                         Roumanie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
26                                                                         Slovénie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
27                                                                        Slovaquie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
28                                                                         Finlande,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
29                                                                            Suède,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
30                                                                      Royaume-Uni,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
31                                                                          Islande,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
32                                                                          Norvège,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
33                                                                       Monténégro,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
34                                                                Macédoine du Nord,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
35                                                                          Albanie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
36                                                                           Serbie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
37                                                                          Turquie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
38                                                               Bosnie-Herzégovine,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
39    Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
40                                                                         Moldavie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
41                                                                          Ukraine,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
42                                                                          Géorgie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)
Name: GEO,NRG_BAL,SIEC,UNIT\TIME, dtype: object

In [103]:
text_columns3 = data[['GEO,NRG_BAL,SIEC,UNIT\TIME']]
text_columns3

                                                                                                                                                                GEO,NRG_BAL,SIEC,UNIT\TIME
0                                   Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
1                                          Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
2                                          Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
3                                                                        Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
4                                                                        Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
5                                                                        Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
6                                                                        Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
7                          Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
8                                                                         Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
9                                                                         Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
10                                                                          Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
11                                                                        Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
12                                                                         France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
13                                                                        Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
14                                                                         Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
15                                                                         Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
16                                                                       Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
17                                                                       Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
18                                                                     Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
19                                                                        Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
20                                                                          Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
21                                                                       Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
22                                                                       Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
23                                                                        Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
24                                                                       Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
25                                                                       Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
26                                                                       Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
27                                                                      Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
28                                                                       Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
29                                                                          Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
30                                                                    Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
31                                                                        Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
32                                                                        Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
33                                                                     Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
34                                                              Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
35                                                                        Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
36                                                                         Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
37                                                                        Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
38                                                             Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
39  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
40                                                                       Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
41                                                                        Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
42                                                                        Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)

In [104]:
text_columns3 = text_columns3.replace("Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)","Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale")
text_columns3

                                                                                                                                                                GEO,NRG_BAL,SIEC,UNIT\TIME
0                                   Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
1                                          Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
2                                          Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
3                                                                        Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
4                                                                        Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
5                                                                        Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
6                                                                        Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
7                                                                                                   Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale
8                                                                         Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
9                                                                         Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
10                                                                          Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
11                                                                        Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
12                                                                         France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
13                                                                        Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
14                                                                         Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
15                                                                         Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
16                                                                       Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
17                                                                       Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
18                                                                     Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
19                                                                        Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
20                                                                          Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
21                                                                       Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
22                                                                       Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
23                                                                        Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
24                                                                       Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
25                                                                       Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
26                                                                       Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
27                                                                      Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
28                                                                       Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
29                                                                          Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
30                                                                    Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
31                                                                        Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
32                                                                        Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
33                                                                     Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
34                                                              Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
35                                                                        Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
36                                                                         Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
37                                                                        Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
38                                                             Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
39  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
40                                                                       Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
41                                                                        Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
42                                                                        Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)

In [105]:
text_columns3[['GEO', 'NRG_BAL', 'SIEC', 'UNIT\TIME']] = text_columns3['GEO,NRG_BAL,SIEC,UNIT\TIME'].str.split(pat=',', n=3,expand=True)
text_columns3

,"GEO,NRG_BAL,SIEC,UNIT\TIME",GEO,NRG_BAL,SIEC,UNIT\TIME
0,"Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
1,"Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Union européenne - 28 pays (2013-2020),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
2,"Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
3,"Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Belgique,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
4,"Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Bulgarie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
5,"Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Tchéquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
6,"Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Danemark,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
7,"Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale",Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale,None,None
8,"Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Estonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
9,"Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Irlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
10,"Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Grèce,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
11,"Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Espagne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
12,"France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",France,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
13,"Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Croatie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
14,"Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Italie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
15,"Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Chypre,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
16,"Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Lettonie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
17,"Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Lituanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
18,"Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Luxembourg,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
19,"Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Hongrie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
20,"Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Malte,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
21,"Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Pays-Bas,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
22,"Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Autriche,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
23,"Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Pologne,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
24,"Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Portugal,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
25,"Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Roumanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
26,"Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Slovénie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
27,"Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Slovaquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
28,"Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Finlande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
29,"Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Suède,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
30,"Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Royaume-Uni,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
31,"Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Islande,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
32,"Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Norvège,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
33,"Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Monténégro,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
34,"Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Macédoine du Nord,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
35,"Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Albanie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
36,"Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Serbie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
37,"Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Turquie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
38,"Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Bosnie-Herzégovine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
39,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
40,"Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Moldavie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
41,"Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Ukraine,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)
42,"Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)",Géorgie,Production brute d'électricité,Combustibles fossiles solides,Milliers de tonnes équivalent pétrole (TEP)

In [106]:
new_column3 = text_columns3[['GEO']]
new_column3

                                                                              GEO
0                                   Union européenne - 27 pays (à partir de 2020)
1                                          Union européenne - 28 pays (2013-2020)
2                                          Zone euro - 19 pays (à partir de 2015)
3                                                                        Belgique
4                                                                        Bulgarie
5                                                                        Tchéquie
6                                                                        Danemark
7                             Allemagne jusqu'en 1990 ancien territoire de la RFA
8                                                                         Estonie
9                                                                         Irlande
10                                                                          Grèce
11                                                                        Espagne
12                                                                         France
13                                                                        Croatie
14                                                                         Italie
15                                                                         Chypre
16                                                                       Lettonie
17                                                                       Lituanie
18                                                                     Luxembourg
19                                                                        Hongrie
20                                                                          Malte
21                                                                       Pays-Bas
22                                                                       Autriche
23                                                                        Pologne
24                                                                       Portugal
25                                                                       Roumanie
26                                                                       Slovénie
27                                                                      Slovaquie
28                                                                       Finlande
29                                                                          Suède
30                                                                    Royaume-Uni
31                                                                        Islande
32                                                                        Norvège
33                                                                     Monténégro
34                                                              Macédoine du Nord
35                                                                        Albanie
36                                                                         Serbie
37                                                                        Turquie
38                                                             Bosnie-Herzégovine
39  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40                                                                       Moldavie
41                                                                        Ukraine
42                                                                        Géorgie

In [107]:
df3 = pd.concat([data3, new_column3], axis=1)
df3

,"GEO,NRG_BAL,SIEC,UNIT\TIME",2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO
0,"Union européenne - 27 pays (à partir de 2020),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","244.415,946","256.256,793","252.559,704","252.297,715","250.738,370","245.607,203","249.554,191","251.385,363","254.161,138","252.920,496",Union européenne - 27 pays (à partir de 2020)
1,"Union européenne - 28 pays (2013-2020),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","276.811,058","289.108,889","284.200,638","283.585,663","281.545,700","274.678,627","278.624,390","280.429,187","283.060,838","281.359,242",Union européenne - 28 pays (2013-2020)
2,"Zone euro - 19 pays (à partir de 2015),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","196.495,458","205.466,311","201.240,068","200.843,565","200.335,625","195.145,509","198.230,875","200.540,855","201.942,440","200.574,261",Zone euro - 19 pays (à partir de 2015)
3,"Belgique,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","7.837,577","8.162,939","7.747,746","7.110,535","7.142,193","6.209,733","5.963,474","7.333,482","7.413,981","6.415,090",Belgique
4,"Bulgarie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","3.692,897","4.010,194","4.365,744","4.068,211","3.763,441","4.081,811","4.230,655","3.890,260","3.919,070","4.025,400",Bulgarie
5,"Tchéquie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","7.066,699","7.379,137","7.514,188","7.510,245","7.466,746","7.399,811","7.206,351","7.155,123","7.476,084","7.558,639",Tchéquie
6,"Danemark,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","3.128,375","3.341,539","3.029,159","2.639,821","2.987,341","2.767,293","2.488,446","2.625,830","2.669,108","2.611,916",Danemark
7,"Allemagne (jusqu'en 1990, ancien territoire de la RFA),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","51.125,107","54.259,501","52.538,521","53.868,788","54.766,638","53.807,653","55.587,618","55.766,208","56.063,801","55.167,068",Allemagne jusqu'en 1990 ancien territoire de la RFA
8,"Estonie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","754,800","1.114,693","1.108,660","1.028,932","1.141,408","1.070,139","895,666","1.047,780","1.110,704","1.062,752",Estonie
9,"Irlande,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","2.434,530","2.437,941","2.335,686","2.352,110","2.228,754","2.243,085","2.441,155","2.623,642","2.654,581","2.677,024",Irlande
10,"Grèce,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","5.276,443","4.934,797","5.110,625","5.241,538","4.914,233","4.339,922","4.460,396","4.680,820","4.752,028","4.579,775",Grèce
11,"Espagne,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","25.303,439","25.913,001","25.251,591","25.570,389","24.559,909","23.968,164","24.135,477","23.616,962","23.700,344","23.590,542",Espagne
12,"France,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","46.060,545","48.938,359","49.265,195","49.175,178","49.987,860","49.166,532","49.769,935","48.462,534","48.255,417","49.980,732",France
13,"Croatie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","1.156,893","1.281,390","977,831","924,760","1.208,363","1.165,335","980,428","1.102,305","1.030,396","1.172,115",Croatie
14,"Italie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","25.110,746","25.905,838","25.947,751","25.668,568","24.853,766","24.003,913","24.281,691","24.852,309","25.379,967","24.858,748",Italie
15,"Chypre,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","448,384","457,630","423,836","405,575","368,874","374,026","389,918","420,263","430,298","435,130",Chypre
16,"Lettonie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","478,768","569,814","524,012","530,333","533,829","441,910","475,857","552,501","647,566","578,235",Lettonie
17,"Lituanie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","1.297,242","472,826","392,565","414,066","388,981","357,192","401,523","343,669","338,527","281,978",Lituanie
18,"Luxembourg,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","333,481","394,779","319,544","328,201","248,420","254,942","237,840","188,958","192,188","189,245",Luxembourg
19,"Hongrie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","3.087,534","3.213,254","3.097,092","2.977,998","2.601,915","2.523,469","2.605,143","2.736,331","2.820,550","2.739,897",Hongrie
20,"Malte,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","186,414","181,744","187,352","197,219","193,590","193,026","112,183","73,696","142,025","168,708",Malte
21,"Pays-Bas,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","9.764,359","10.242,071","9.786,172","8.863,973","8.728,051","8.874,666","9.478,075","9.894,607","10.071,975","9.833,606",Pays-Bas
22,"Autriche,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","5.939,015","6.114,368","5.657,920","6.241,786","5.876,409","5.625,578","5.613,460","5.872,144","6.131,720","5.897,163",Autriche
23,"Pologne,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","13.042,704","13.549,029","14.053,553","13.934,503","14.141,739","13.664,384","14.172,768","14.322,391","14.652,069","14.610,025",Pologne
24,"Portugal,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","4.317,029","4.650,537","4.510,598","4.007,871","4.442,670","4.539,682","4.506,580","5.187,287","5.110,208","5.127,780",Portugal
25,"Roumanie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","4.988,319","5.243,238","5.349,525","5.076,944","5.063,306","5.647,001","5.700,338","5.597,854","5.528,463","5.578,372",Roumanie
26,"Slovénie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","1.410,420","1.413,435","1.380,739","1.353,055","1.384,593","1.499,376","1.298,334","1.418,905","1.403,803","1.404,191",Slovénie
27,"Slovaquie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","2.245,534","2.391,912","2.457,282","2.458,727","2.473,173","2.345,916","2.304,643","2.315,907","2.371,711","2.309,114",Slovaquie
28,"Finlande,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","6.171,625","6.910,126","6.294,273","6.026,721","6.102,274","5.830,054","5.877,050","5.889,181","5.771,596","6.017,380",Finlande
29,"Suède,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","11.757,067","12.772,701","12.932,544","14.321,668","13.169,894","13.212,590","13.939,187","13.414,414","14.122,958","14.049,871",Suède
30,"Royaume-Uni,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","32.395,112","32.852,096","31.640,934","31.287,948","30.807,330","29.071,424","29.070,199","29.043,824","28.899,700","28.438,746",Royaume-Uni
31,"Islande,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","1.447,550","1.466,845","1.479,820","1.508,949","1.557,662","1.558,282","1.616,394","1.594,934","1.654,216","1.705,052",Islande
32,"Norvège,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","11.323,990","10.620,292","10.961,393","12.694,153","11.506,277","12.180,310","12.400,000","12.788,822","12.825,107","12.601,582",Norvège
33,"Monténégro,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","237,317","345,830","228,362","244,547","339,223","272,799","258,212","270,094","213,482","327,661",Monténégro
34,"Macédoine du Nord,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","587,132","624,290","581,195","538,401","523,991","462,052","485,450","484,050","481,530","482,130",Macédoine du Nord
35,"Albanie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","447,291","650,731","360,361","406,277","598,366","406,229","506,879","669,106","389,181","735,467",Albanie
36,"Serbie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","3.295,099","3.276,268","3.319,003","3.164,144","3.428,805","2.928,633","3.293,035","3.382,803","3.185,328","3.218,035",Serbie
37,"Turquie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","16.744,269","18.151,107","19.715,315","20.583,378","20.625,614","21.635,818","22.466,715","23.533,462","25.488,323","26.126,541",Turquie
38,"Bosnie-Herzégovine,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,:,"1.463,715","1.413,414","1.527,653","1.413,414","1.647,463",Bosnie-Herzégovine
39,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","427,859","444,368","498,788","510,970","561,075","467,444","526,164","514,317","508,885","508,617",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,"Moldavie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","0,000","91,488","87,360","80,128","77,816","82,844","80,646","77,886","77,042","82,029",Moldavie
41,"Ukraine,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)","14.928,521","16.236,285","16.762,468","17.100,447","16.713,396","15.719,570","14.033,826","14.143,818","13.412,752","13.741,531",Ukraine
42,"Géorgie,Production brute d'électricité,Total,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,"864,936","891,774","931,450","995,206","991,505","1.044,592",Géorgie

In [108]:
df3 = df3.drop(columns=['GEO,NRG_BAL,SIEC,UNIT\TIME'])
df3

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO
0,"244.415,946","256.256,793","252.559,704","252.297,715","250.738,370","245.607,203","249.554,191","251.385,363","254.161,138","252.920,496",Union européenne - 27 pays (à partir de 2020)
1,"276.811,058","289.108,889","284.200,638","283.585,663","281.545,700","274.678,627","278.624,390","280.429,187","283.060,838","281.359,242",Union européenne - 28 pays (2013-2020)
2,"196.495,458","205.466,311","201.240,068","200.843,565","200.335,625","195.145,509","198.230,875","200.540,855","201.942,440","200.574,261",Zone euro - 19 pays (à partir de 2015)
3,"7.837,577","8.162,939","7.747,746","7.110,535","7.142,193","6.209,733","5.963,474","7.333,482","7.413,981","6.415,090",Belgique
4,"3.692,897","4.010,194","4.365,744","4.068,211","3.763,441","4.081,811","4.230,655","3.890,260","3.919,070","4.025,400",Bulgarie
5,"7.066,699","7.379,137","7.514,188","7.510,245","7.466,746","7.399,811","7.206,351","7.155,123","7.476,084","7.558,639",Tchéquie
6,"3.128,375","3.341,539","3.029,159","2.639,821","2.987,341","2.767,293","2.488,446","2.625,830","2.669,108","2.611,916",Danemark
7,"51.125,107","54.259,501","52.538,521","53.868,788","54.766,638","53.807,653","55.587,618","55.766,208","56.063,801","55.167,068",Allemagne jusqu'en 1990 ancien territoire de la RFA
8,"754,800","1.114,693","1.108,660","1.028,932","1.141,408","1.070,139","895,666","1.047,780","1.110,704","1.062,752",Estonie
9,"2.434,530","2.437,941","2.335,686","2.352,110","2.228,754","2.243,085","2.441,155","2.623,642","2.654,581","2.677,024",Irlande
10,"5.276,443","4.934,797","5.110,625","5.241,538","4.914,233","4.339,922","4.460,396","4.680,820","4.752,028","4.579,775",Grèce
11,"25.303,439","25.913,001","25.251,591","25.570,389","24.559,909","23.968,164","24.135,477","23.616,962","23.700,344","23.590,542",Espagne
12,"46.060,545","48.938,359","49.265,195","49.175,178","49.987,860","49.166,532","49.769,935","48.462,534","48.255,417","49.980,732",France
13,"1.156,893","1.281,390","977,831","924,760","1.208,363","1.165,335","980,428","1.102,305","1.030,396","1.172,115",Croatie
14,"25.110,746","25.905,838","25.947,751","25.668,568","24.853,766","24.003,913","24.281,691","24.852,309","25.379,967","24.858,748",Italie
15,"448,384","457,630","423,836","405,575","368,874","374,026","389,918","420,263","430,298","435,130",Chypre
16,"478,768","569,814","524,012","530,333","533,829","441,910","475,857","552,501","647,566","578,235",Lettonie
17,"1.297,242","472,826","392,565","414,066","388,981","357,192","401,523","343,669","338,527","281,978",Lituanie
18,"333,481","394,779","319,544","328,201","248,420","254,942","237,840","188,958","192,188","189,245",Luxembourg
19,"3.087,534","3.213,254","3.097,092","2.977,998","2.601,915","2.523,469","2.605,143","2.736,331","2.820,550","2.739,897",Hongrie
20,"186,414","181,744","187,352","197,219","193,590","193,026","112,183","73,696","142,025","168,708",Malte
21,"9.764,359","10.242,071","9.786,172","8.863,973","8.728,051","8.874,666","9.478,075","9.894,607","10.071,975","9.833,606",Pays-Bas
22,"5.939,015","6.114,368","5.657,920","6.241,786","5.876,409","5.625,578","5.613,460","5.872,144","6.131,720","5.897,163",Autriche
23,"13.042,704","13.549,029","14.053,553","13.934,503","14.141,739","13.664,384","14.172,768","14.322,391","14.652,069","14.610,025",Pologne
24,"4.317,029","4.650,537","4.510,598","4.007,871","4.442,670","4.539,682","4.506,580","5.187,287","5.110,208","5.127,780",Portugal
25,"4.988,319","5.243,238","5.349,525","5.076,944","5.063,306","5.647,001","5.700,338","5.597,854","5.528,463","5.578,372",Roumanie
26,"1.410,420","1.413,435","1.380,739","1.353,055","1.384,593","1.499,376","1.298,334","1.418,905","1.403,803","1.404,191",Slovénie
27,"2.245,534","2.391,912","2.457,282","2.458,727","2.473,173","2.345,916","2.304,643","2.315,907","2.371,711","2.309,114",Slovaquie
28,"6.171,625","6.910,126","6.294,273","6.026,721","6.102,274","5.830,054","5.877,050","5.889,181","5.771,596","6.017,380",Finlande
29,"11.757,067","12.772,701","12.932,544","14.321,668","13.169,894","13.212,590","13.939,187","13.414,414","14.122,958","14.049,871",Suède
30,"32.395,112","32.852,096","31.640,934","31.287,948","30.807,330","29.071,424","29.070,199","29.043,824","28.899,700","28.438,746",Royaume-Uni
31,"1.447,550","1.466,845","1.479,820","1.508,949","1.557,662","1.558,282","1.616,394","1.594,934","1.654,216","1.705,052",Islande
32,"11.323,990","10.620,292","10.961,393","12.694,153","11.506,277","12.180,310","12.400,000","12.788,822","12.825,107","12.601,582",Norvège
33,"237,317","345,830","228,362","244,547","339,223","272,799","258,212","270,094","213,482","327,661",Monténégro
34,"587,132","624,290","581,195","538,401","523,991","462,052","485,450","484,050","481,530","482,130",Macédoine du Nord
35,"447,291","650,731","360,361","406,277","598,366","406,229","506,879","669,106","389,181","735,467",Albanie
36,"3.295,099","3.276,268","3.319,003","3.164,144","3.428,805","2.928,633","3.293,035","3.382,803","3.185,328","3.218,035",Serbie
37,"16.744,269","18.151,107","19.715,315","20.583,378","20.625,614","21.635,818","22.466,715","23.533,462","25.488,323","26.126,541",Turquie
38,:,:,:,:,:,"1.463,715","1.413,414","1.527,653","1.413,414","1.647,463",Bosnie-Herzégovine
39,"427,859","444,368","498,788","510,970","561,075","467,444","526,164","514,317","508,885","508,617",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,"0,000","91,488","87,360","80,128","77,816","82,844","80,646","77,886","77,042","82,029",Moldavie
41,"14.928,521","16.236,285","16.762,468","17.100,447","16.713,396","15.719,570","14.033,826","14.143,818","13.412,752","13.741,531",Ukraine
42,:,:,:,:,"864,936","891,774","931,450","995,206","991,505","1.044,592",Géorgie

In [109]:
df_merge3 = pd.merge(df3, code_pays, how ='inner', left_on='GEO', right_on= 'libelle')
df_merge3

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO,id,code,libelle
0,"244.415,946","256.256,793","252.559,704","252.297,715","250.738,370","245.607,203","249.554,191","251.385,363","254.161,138","252.920,496",Union européenne - 27 pays (à partir de 2020),1,EU27_20,Union européenne - 27 pays (à partir de 2020)
1,"276.811,058","289.108,889","284.200,638","283.585,663","281.545,700","274.678,627","278.624,390","280.429,187","283.060,838","281.359,242",Union européenne - 28 pays (2013-2020),2,EU28,Union européenne - 28 pays (2013-2020)
2,"196.495,458","205.466,311","201.240,068","200.843,565","200.335,625","195.145,509","198.230,875","200.540,855","201.942,440","200.574,261",Zone euro - 19 pays (à partir de 2015),3,EA19,Zone euro - 19 pays (à partir de 2015)
3,"7.837,577","8.162,939","7.747,746","7.110,535","7.142,193","6.209,733","5.963,474","7.333,482","7.413,981","6.415,090",Belgique,4,BE,Belgique
4,"3.692,897","4.010,194","4.365,744","4.068,211","3.763,441","4.081,811","4.230,655","3.890,260","3.919,070","4.025,400",Bulgarie,5,BG,Bulgarie
5,"7.066,699","7.379,137","7.514,188","7.510,245","7.466,746","7.399,811","7.206,351","7.155,123","7.476,084","7.558,639",Tchéquie,6,CZ,Tchéquie
6,"3.128,375","3.341,539","3.029,159","2.639,821","2.987,341","2.767,293","2.488,446","2.625,830","2.669,108","2.611,916",Danemark,7,DK,Danemark
7,"51.125,107","54.259,501","52.538,521","53.868,788","54.766,638","53.807,653","55.587,618","55.766,208","56.063,801","55.167,068",Allemagne jusqu'en 1990 ancien territoire de la RFA,8,DE,Allemagne jusqu'en 1990 ancien territoire de la RFA
8,"754,800","1.114,693","1.108,660","1.028,932","1.141,408","1.070,139","895,666","1.047,780","1.110,704","1.062,752",Estonie,9,EE,Estonie
9,"2.434,530","2.437,941","2.335,686","2.352,110","2.228,754","2.243,085","2.441,155","2.623,642","2.654,581","2.677,024",Irlande,10,IE,Irlande
10,"5.276,443","4.934,797","5.110,625","5.241,538","4.914,233","4.339,922","4.460,396","4.680,820","4.752,028","4.579,775",Grèce,11,EL,Grèce
11,"25.303,439","25.913,001","25.251,591","25.570,389","24.559,909","23.968,164","24.135,477","23.616,962","23.700,344","23.590,542",Espagne,12,ES,Espagne
12,"46.060,545","48.938,359","49.265,195","49.175,178","49.987,860","49.166,532","49.769,935","48.462,534","48.255,417","49.980,732",France,13,FR,France
13,"1.156,893","1.281,390","977,831","924,760","1.208,363","1.165,335","980,428","1.102,305","1.030,396","1.172,115",Croatie,14,HR,Croatie
14,"25.110,746","25.905,838","25.947,751","25.668,568","24.853,766","24.003,913","24.281,691","24.852,309","25.379,967","24.858,748",Italie,15,IT,Italie
15,"448,384","457,630","423,836","405,575","368,874","374,026","389,918","420,263","430,298","435,130",Chypre,16,CY,Chypre
16,"478,768","569,814","524,012","530,333","533,829","441,910","475,857","552,501","647,566","578,235",Lettonie,17,LV,Lettonie
17,"1.297,242","472,826","392,565","414,066","388,981","357,192","401,523","343,669","338,527","281,978",Lituanie,18,LT,Lituanie
18,"333,481","394,779","319,544","328,201","248,420","254,942","237,840","188,958","192,188","189,245",Luxembourg,19,LU,Luxembourg
19,"3.087,534","3.213,254","3.097,092","2.977,998","2.601,915","2.523,469","2.605,143","2.736,331","2.820,550","2.739,897",Hongrie,20,HU,Hongrie
20,"186,414","181,744","187,352","197,219","193,590","193,026","112,183","73,696","142,025","168,708",Malte,21,MT,Malte
21,"9.764,359","10.242,071","9.786,172","8.863,973","8.728,051","8.874,666","9.478,075","9.894,607","10.071,975","9.833,606",Pays-Bas,22,NL,Pays-Bas
22,"5.939,015","6.114,368","5.657,920","6.241,786","5.876,409","5.625,578","5.613,460","5.872,144","6.131,720","5.897,163",Autriche,23,AT,Autriche
23,"13.042,704","13.549,029","14.053,553","13.934,503","14.141,739","13.664,384","14.172,768","14.322,391","14.652,069","14.610,025",Pologne,24,PL,Pologne
24,"4.317,029","4.650,537","4.510,598","4.007,871","4.442,670","4.539,682","4.506,580","5.187,287","5.110,208","5.127,780",Portugal,25,PT,Portugal
25,"4.988,319","5.243,238","5.349,525","5.076,944","5.063,306","5.647,001","5.700,338","5.597,854","5.528,463","5.578,372",Roumanie,26,RO,Roumanie
26,"1.410,420","1.413,435","1.380,739","1.353,055","1.384,593","1.499,376","1.298,334","1.418,905","1.403,803","1.404,191",Slovénie,27,SI,Slovénie
27,"2.245,534","2.391,912","2.457,282","2.458,727","2.473,173","2.345,916","2.304,643","2.315,907","2.371,711","2.309,114",Slovaquie,28,SK,Slovaquie
28,"6.171,625","6.910,126","6.294,273","6.026,721","6.102,274","5.830,054","5.877,050","5.889,181","5.771,596","6.017,380",Finlande,29,FI,Finlande
29,"11.757,067","12.772,701","12.932,544","14.321,668","13.169,894","13.212,590","13.939,187","13.414,414","14.122,958","14.049,871",Suède,30,SE,Suède
30,"32.395,112","32.852,096","31.640,934","31.287,948","30.807,330","29.071,424","29.070,199","29.043,824","28.899,700","28.438,746",Royaume-Uni,31,UK,Royaume-Uni
31,"1.447,550","1.466,845","1.479,820","1.508,949","1.557,662","1.558,282","1.616,394","1.594,934","1.654,216","1.705,052",Islande,32,IS,Islande
32,"11.323,990","10.620,292","10.961,393","12.694,153","11.506,277","12.180,310","12.400,000","12.788,822","12.825,107","12.601,582",Norvège,33,NO,Norvège
33,"237,317","345,830","228,362","244,547","339,223","272,799","258,212","270,094","213,482","327,661",Monténégro,34,ME,Monténégro
34,"587,132","624,290","581,195","538,401","523,991","462,052","485,450","484,050","481,530","482,130",Macédoine du Nord,35,MK,Macédoine du Nord
35,"447,291","650,731","360,361","406,277","598,366","406,229","506,879","669,106","389,181","735,467",Albanie,36,AL,Albanie
36,"3.295,099","3.276,268","3.319,003","3.164,144","3.428,805","2.928,633","3.293,035","3.382,803","3.185,328","3.218,035",Serbie,37,RS,Serbie
37,"16.744,269","18.151,107","19.715,315","20.583,378","20.625,614","21.635,818","22.466,715","23.533,462","25.488,323","26.126,541",Turquie,38,TR,Turquie
38,:,:,:,:,:,"1.463,715","1.413,414","1.527,653","1.413,414","1.647,463",Bosnie-Herzégovine,39,BA,Bosnie-Herzégovine
39,"427,859","444,368","498,788","510,970","561,075","467,444","526,164","514,317","508,885","508,617",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),40,XK,Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,"0,000","91,488","87,360","80,128","77,816","82,844","80,646","77,886","77,042","82,029",Moldavie,41,MD,Moldavie
41,"14.928,521","16.236,285","16.762,468","17.100,447","16.713,396","15.719,570","14.033,826","14.143,818","13.412,752","13.741,531",Ukraine,42,UA,Ukraine
42,:,:,:,:,"864,936","891,774","931,450","995,206","991,505","1.044,592",Géorgie,43,GE,Géorgie

In [110]:
df_merge3 = df_merge3.drop(columns=['libelle', 'GEO', 'code'])
df_merge3

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,id
0,"244.415,946","256.256,793","252.559,704","252.297,715","250.738,370","245.607,203","249.554,191","251.385,363","254.161,138","252.920,496",1
1,"276.811,058","289.108,889","284.200,638","283.585,663","281.545,700","274.678,627","278.624,390","280.429,187","283.060,838","281.359,242",2
2,"196.495,458","205.466,311","201.240,068","200.843,565","200.335,625","195.145,509","198.230,875","200.540,855","201.942,440","200.574,261",3
3,"7.837,577","8.162,939","7.747,746","7.110,535","7.142,193","6.209,733","5.963,474","7.333,482","7.413,981","6.415,090",4
4,"3.692,897","4.010,194","4.365,744","4.068,211","3.763,441","4.081,811","4.230,655","3.890,260","3.919,070","4.025,400",5
5,"7.066,699","7.379,137","7.514,188","7.510,245","7.466,746","7.399,811","7.206,351","7.155,123","7.476,084","7.558,639",6
6,"3.128,375","3.341,539","3.029,159","2.639,821","2.987,341","2.767,293","2.488,446","2.625,830","2.669,108","2.611,916",7
7,"51.125,107","54.259,501","52.538,521","53.868,788","54.766,638","53.807,653","55.587,618","55.766,208","56.063,801","55.167,068",8
8,"754,800","1.114,693","1.108,660","1.028,932","1.141,408","1.070,139","895,666","1.047,780","1.110,704","1.062,752",9
9,"2.434,530","2.437,941","2.335,686","2.352,110","2.228,754","2.243,085","2.441,155","2.623,642","2.654,581","2.677,024",10
10,"5.276,443","4.934,797","5.110,625","5.241,538","4.914,233","4.339,922","4.460,396","4.680,820","4.752,028","4.579,775",11
11,"25.303,439","25.913,001","25.251,591","25.570,389","24.559,909","23.968,164","24.135,477","23.616,962","23.700,344","23.590,542",12
12,"46.060,545","48.938,359","49.265,195","49.175,178","49.987,860","49.166,532","49.769,935","48.462,534","48.255,417","49.980,732",13
13,"1.156,893","1.281,390","977,831","924,760","1.208,363","1.165,335","980,428","1.102,305","1.030,396","1.172,115",14
14,"25.110,746","25.905,838","25.947,751","25.668,568","24.853,766","24.003,913","24.281,691","24.852,309","25.379,967","24.858,748",15
15,"448,384","457,630","423,836","405,575","368,874","374,026","389,918","420,263","430,298","435,130",16
16,"478,768","569,814","524,012","530,333","533,829","441,910","475,857","552,501","647,566","578,235",17
17,"1.297,242","472,826","392,565","414,066","388,981","357,192","401,523","343,669","338,527","281,978",18
18,"333,481","394,779","319,544","328,201","248,420","254,942","237,840","188,958","192,188","189,245",19
19,"3.087,534","3.213,254","3.097,092","2.977,998","2.601,915","2.523,469","2.605,143","2.736,331","2.820,550","2.739,897",20
20,"186,414","181,744","187,352","197,219","193,590","193,026","112,183","73,696","142,025","168,708",21
21,"9.764,359","10.242,071","9.786,172","8.863,973","8.728,051","8.874,666","9.478,075","9.894,607","10.071,975","9.833,606",22
22,"5.939,015","6.114,368","5.657,920","6.241,786","5.876,409","5.625,578","5.613,460","5.872,144","6.131,720","5.897,163",23
23,"13.042,704","13.549,029","14.053,553","13.934,503","14.141,739","13.664,384","14.172,768","14.322,391","14.652,069","14.610,025",24
24,"4.317,029","4.650,537","4.510,598","4.007,871","4.442,670","4.539,682","4.506,580","5.187,287","5.110,208","5.127,780",25
25,"4.988,319","5.243,238","5.349,525","5.076,944","5.063,306","5.647,001","5.700,338","5.597,854","5.528,463","5.578,372",26
26,"1.410,420","1.413,435","1.380,739","1.353,055","1.384,593","1.499,376","1.298,334","1.418,905","1.403,803","1.404,191",27
27,"2.245,534","2.391,912","2.457,282","2.458,727","2.473,173","2.345,916","2.304,643","2.315,907","2.371,711","2.309,114",28
28,"6.171,625","6.910,126","6.294,273","6.026,721","6.102,274","5.830,054","5.877,050","5.889,181","5.771,596","6.017,380",29
29,"11.757,067","12.772,701","12.932,544","14.321,668","13.169,894","13.212,590","13.939,187","13.414,414","14.122,958","14.049,871",30
30,"32.395,112","32.852,096","31.640,934","31.287,948","30.807,330","29.071,424","29.070,199","29.043,824","28.899,700","28.438,746",31
31,"1.447,550","1.466,845","1.479,820","1.508,949","1.557,662","1.558,282","1.616,394","1.594,934","1.654,216","1.705,052",32
32,"11.323,990","10.620,292","10.961,393","12.694,153","11.506,277","12.180,310","12.400,000","12.788,822","12.825,107","12.601,582",33
33,"237,317","345,830","228,362","244,547","339,223","272,799","258,212","270,094","213,482","327,661",34
34,"587,132","624,290","581,195","538,401","523,991","462,052","485,450","484,050","481,530","482,130",35
35,"447,291","650,731","360,361","406,277","598,366","406,229","506,879","669,106","389,181","735,467",36
36,"3.295,099","3.276,268","3.319,003","3.164,144","3.428,805","2.928,633","3.293,035","3.382,803","3.185,328","3.218,035",37
37,"16.744,269","18.151,107","19.715,315","20.583,378","20.625,614","21.635,818","22.466,715","23.533,462","25.488,323","26.126,541",38
38,:,:,:,:,:,"1.463,715","1.413,414","1.527,653","1.413,414","1.647,463",39
39,"427,859","444,368","498,788","510,970","561,075","467,444","526,164","514,317","508,885","508,617",40
40,"0,000","91,488","87,360","80,128","77,816","82,844","80,646","77,886","77,042","82,029",41
41,"14.928,521","16.236,285","16.762,468","17.100,447","16.713,396","15.719,570","14.033,826","14.143,818","13.412,752","13.741,531",42
42,:,:,:,:,"864,936","891,774","931,450","995,206","991,505","1.044,592",43

### 3.2. Transformation des colonnes "années" en lignes

In [111]:
df_merge3.columns

Index(['2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', 'id'],
      dtype='object')

In [112]:
df_global3 = []
for i in range(2009,2019):
    df_i3 = df_merge3[[f'{i}', 'id']]
    df_i3.rename(columns={f'{i}':'quantite_tep', 'id':'pays_id'}, inplace=True)
    df_i3['annee'] = i
    df_global3.append(df_i3)
df_global3[0]

/home/camille/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
<ipython-input-112-17a5cc911492>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_i3['annee'] = i

   quantite_tep  pays_id  annee
0   244.415,946        1   2009
1   276.811,058        2   2009
2   196.495,458        3   2009
3     7.837,577        4   2009
4     3.692,897        5   2009
5     7.066,699        6   2009
6     3.128,375        7   2009
7    51.125,107        8   2009
8       754,800        9   2009
9     2.434,530       10   2009
10    5.276,443       11   2009
11   25.303,439       12   2009
12   46.060,545       13   2009
13    1.156,893       14   2009
14   25.110,746       15   2009
15      448,384       16   2009
16      478,768       17   2009
17    1.297,242       18   2009
18      333,481       19   2009
19    3.087,534       20   2009
20      186,414       21   2009
21    9.764,359       22   2009
22    5.939,015       23   2009
23   13.042,704       24   2009
24    4.317,029       25   2009
25    4.988,319       26   2009
26    1.410,420       27   2009
27    2.245,534       28   2009
28    6.171,625       29   2009
29   11.757,067       30   2009
30   32.395,112       31   2009
31    1.447,550       32   2009
32   11.323,990       33   2009
33      237,317       34   2009
34      587,132       35   2009
35      447,291       36   2009
36    3.295,099       37   2009
37   16.744,269       38   2009
38            :       39   2009
39      427,859       40   2009
40        0,000       41   2009
41   14.928,521       42   2009
42            :       43   2009

In [113]:
frames = [ df_global3[i] for i in range(0,10) ]
production_electricite_total = pd.concat(frames)
production_electricite_total

   quantite_tep  pays_id  annee
0   244.415,946        1   2009
1   276.811,058        2   2009
2   196.495,458        3   2009
3     7.837,577        4   2009
4     3.692,897        5   2009
5     7.066,699        6   2009
6     3.128,375        7   2009
7    51.125,107        8   2009
8       754,800        9   2009
9     2.434,530       10   2009
10    5.276,443       11   2009
11   25.303,439       12   2009
12   46.060,545       13   2009
13    1.156,893       14   2009
14   25.110,746       15   2009
15      448,384       16   2009
16      478,768       17   2009
17    1.297,242       18   2009
18      333,481       19   2009
19    3.087,534       20   2009
20      186,414       21   2009
21    9.764,359       22   2009
22    5.939,015       23   2009
23   13.042,704       24   2009
24    4.317,029       25   2009
25    4.988,319       26   2009
26    1.410,420       27   2009
27    2.245,534       28   2009
28    6.171,625       29   2009
29   11.757,067       30   2009
30   32.395,112       31   2009
31    1.447,550       32   2009
32   11.323,990       33   2009
33      237,317       34   2009
34      587,132       35   2009
35      447,291       36   2009
36    3.295,099       37   2009
37   16.744,269       38   2009
38            :       39   2009
39      427,859       40   2009
40        0,000       41   2009
41   14.928,521       42   2009
42            :       43   2009
0   256.256,793        1   2010
1   289.108,889        2   2010
2   205.466,311        3   2010
3     8.162,939        4   2010
4     4.010,194        5   2010
5     7.379,137        6   2010
6     3.341,539        7   2010
7    54.259,501        8   2010
8     1.114,693        9   2010
9     2.437,941       10   2010
10    4.934,797       11   2010
11   25.913,001       12   2010
12   48.938,359       13   2010
13    1.281,390       14   2010
14   25.905,838       15   2010
15      457,630       16   2010
16      569,814       17   2010
17      472,826       18   2010
18      394,779       19   2010
19    3.213,254       20   2010
20      181,744       21   2010
21   10.242,071       22   2010
22    6.114,368       23   2010
23   13.549,029       24   2010
24    4.650,537       25   2010
25    5.243,238       26   2010
26    1.413,435       27   2010
27    2.391,912       28   2010
28    6.910,126       29   2010
29   12.772,701       30   2010
30   32.852,096       31   2010
31    1.466,845       32   2010
32   10.620,292       33   2010
33      345,830       34   2010
34      624,290       35   2010
35      650,731       36   2010
36    3.276,268       37   2010
37   18.151,107       38   2010
38            :       39   2010
39      444,368       40   2010
40       91,488       41   2010
41   16.236,285       42   2010
42            :       43   2010
0   252.559,704        1   2011
1   284.200,638        2   2011
2   201.240,068        3   2011
3     7.747,746        4   2011
4     4.365,744        5   2011
5     7.514,188        6   2011
6     3.029,159        7   2011
7    52.538,521        8   2011
8     1.108,660        9   2011
9     2.335,686       10   2011
10    5.110,625       11   2011
11   25.251,591       12   2011
12   49.265,195       13   2011
13      977,831       14   2011
14   25.947,751       15   2011
15      423,836       16   2011
16      524,012       17   2011
17      392,565       18   2011
18      319,544       19   2011
19    3.097,092       20   2011
20      187,352       21   2011
21    9.786,172       22   2011
22    5.657,920       23   2011
23   14.053,553       24   2011
24    4.510,598       25   2011
25    5.349,525       26   2011
26    1.380,739       27   2011
27    2.457,282       28   2011
28    6.294,273       29   2011
29   12.932,544       30   2011
30   31.640,934       31   2011
31    1.479,820       32   2011
32   10.961,393       33   2011
33      228,362       34   2011
34      581,195       35   2011
35      360,361       36   2011
36    3.319,003       37   2011
37   19.715,315       38   2011
38            :       39   2011
39      498,788       40   2011
40       87,360       41   2011
41   16.762,468       42   2011
42            :       43   2011
0   252.297,715        1   2012
1   283.585,663        2   2012
2   200.843,565        3   2012
3     7.110,535        4   2012
4     4.068,211        5   2012
5     7.510,245        6   2012
6     2.639,821        7   2012
7    53.868,788        8   2012
8     1.028,932        9   2012
9     2.352,110       10   2012
10    5.241,538       11   2012
11   25.570,389       12   2012
12   49.175,178       13   2012
13      924,760       14   2012
14   25.668,568       15   2012
15      405,575       16   2012
16      530,333       17   2012
17      414,066       18   2012
18      328,201       19   2012
19    2.977,998       20   2012
20      197,219       21   2012
21    8.863,973       22   2012
22    6.241,786       23   2012
23   13.934,503       24   2012
24    4.007,871       25   2012
25    5.076,944       26   2012
26    1.353,055       27   2012
27    2.458,727       28   2012
28    6.026,721       29   2012
29   14.321,668       30   2012
30   31.287,948       31   2012
31    1.508,949       32   2012
32   12.694,153       33   2012
33      244,547       34   2012
34      538,401       35   2012
35      406,277       36   2012
36    3.164,144       37   2012
37   20.583,378       38   2012
38            :       39   2012
39      510,970       40   2012
40       80,128       41   2012
41   17.100,447       42   2012
42            :       43   2012
0   250.738,370        1   2013
1   281.545,700        2   2013
2   200.335,625        3   2013
3     7.142,193        4   2013
4     3.763,441        5   2013
5     7.466,746        6   2013
6     2.987,341        7   2013
7    54.766,638        8   2013
8     1.141,408        9   2013
9     2.228,754       10   2013
10    4.914,233       11   2013
11   24.559,909       12   2013
12   49.987,860       13   2013
13    1.208,363       14   2013
14   24.853,766       15   2013
15      368,874       16   2013
16      533,829       17   2013
17      388,981       18   2013
18      248,420       19   2013
19    2.601,915       20   2013
20      193,590       21   2013
21    8.728,051       22   2013
22    5.876,409       23   2013
23   14.141,739       24   2013
24    4.442,670       25   2013
25    5.063,306       26   2013
26    1.384,593       27   2013
27    2.473,173       28   2013
28    6.102,274       29   2013
29   13.169,894       30   2013
30   30.807,330       31   2013
31    1.557,662       32   2013
32   11.506,277       33   2013
33      339,223       34   2013
34      523,991       35   2013
35      598,366       36   2013
36    3.428,805       37   2013
37   20.625,614       38   2013
38            :       39   2013
39      561,075       40   2013
40       77,816       41   2013
41   16.713,396       42   2013
42      864,936       43   2013
0   245.607,203        1   2014
1   274.678,627        2   2014
2   195.145,509        3   2014
3     6.209,733        4   2014
4     4.081,811        5   2014
5     7.399,811        6   2014
6     2.767,293        7   2014
7    53.807,653        8   2014
8     1.070,139        9   2014
9     2.243,085       10   2014
10    4.339,922       11   2014
11   23.968,164       12   2014
12   49.166,532       13   2014
13    1.165,335       14   2014
14   24.003,913       15   2014
15      374,026       16   2014
16      441,910       17   2014
17      357,192       18   2014
18      254,942       19   2014
19    2.523,469       20   2014
20      193,026       21   2014
21    8.874,666       22   2014
22    5.625,578       23   2014
23   13.664,384       24   2014
24    4.539,682       25   2014
25    5.647,001       26   2014
26    1.499,376       27   2014
27    2.345,916       28   2014
28    5.830,054       29   2014
29   13.212,590       30   2014
30   29.071,424       31   2014
31    1.558,282       32   2014
32   12.180,310       33   2014
33      272,799       34   2014
34      462,052       35   2014
35      406,229       36   2014
36    2.928,633       37   2014
37   21.635,818       38   2014
38    1.463,715       39   2014
39      467,444       40   2014
40       82,844       41   2014
41   15.719,570       42   2014
42      891,774       43   2014
0   249.554,191        1   2015
1   278.624,390        2   2015
2   198.230,875        3   2015
3     5.963,474        4   2015
4     4.230,655        5   2015
5     7.206,351        6   2015
6     2.488,446        7   2015
7    55.587,618        8   2015
8       895,666        9   2015
9     2.441,155       10   2015
10    4.460,396       11   2015
11   24.135,477       12   2015
12   49.769,935       13   2015
13      980,428       14   2015
14   24.281,691       15   2015
15      389,918       16   2015
16      475,857       17   2015
17      401,523       18   2015
18      237,840       19   2015
19    2.605,143       20   2015
20      112,183       21   2015
21    9.478,075       22   2015
22    5.613,460       23   2015
23   14.172,768       24   2015
24    4.506,580       25   2015
25    5.700,338       26   2015
26    1.298,334       27   2015
27    2.304,643       28   2015
28    5.877,050       29   2015
29   13.939,187       30   2015
30   29.070,199       31   2015
31    1.616,394       32   2015
32   12.400,000       33   2015
33      258,212       34   2015
34      485,450       35   2015
35      506,879       36   2015
36    3.293,035       37   2015
37   22.466,715       38   2015
38    1.413,414       39   2015
39      526,164       40   2015
40       80,646       41   2015
41   14.033,826       42   2015
42      931,450       43   2015
0   251.385,363        1   2016
1   280.429,187        2   2016
2   200.540,855        3   2016
3     7.333,482        4   2016
4     3.890,260        5   2016
5     7.155,123        6   2016
6     2.625,830        7   2016
7    55.766,208        8   2016
8     1.047,780        9   2016
9     2.623,642       10   2016
10    4.680,820       11   2016
11   23.616,962       12   2016
12   48.462,534       13   2016
13    1.102,305       14   2016
14   24.852,309       15   2016
15      420,263       16   2016
16      552,501       17   2016
17      343,669       18   2016
18      188,958       19   2016
19    2.736,331       20   2016
20       73,696       21   2016
21    9.894,607       22   2016
22    5.872,144       23   2016
23   14.322,391       24   2016
24    5.187,287       25   2016
25    5.597,854       26   2016
26    1.418,905       27   2016
27    2.315,907       28   2016
28    5.889,181       29   2016
29   13.414,414       30   2016
30   29.043,824       31   2016
31    1.594,934       32   2016
32   12.788,822       33   2016
33      270,094       34   2016
34      484,050       35   2016
35      669,106       36   2016
36    3.382,803       37   2016
37   23.533,462       38   2016
38    1.527,653       39   2016
39      514,317       40   2016
40       77,886       41   2016
41   14.143,818       42   2016
42      995,206       43   2016
0   254.161,138        1   2017
1   283.060,838        2   2017
2   201.942,440        3   2017
3     7.413,981        4   2017
4     3.919,070        5   2017
5     7.476,084        6   2017
6     2.669,108        7   2017
7    56.063,801        8   2017
8     1.110,704        9   2017
9     2.654,581       10   2017
10    4.752,028       11   2017
11   23.700,344       12   2017
12   48.255,417       13   2017
13    1.030,396       14   2017
14   25.379,967       15   2017
15      430,298       16   2017
16      647,566       17   2017
17      338,527       18   2017
18      192,188       19   2017
19    2.820,550       20   2017
20      142,025       21   2017
21   10.071,975       22   2017
22    6.131,720       23   2017
23   14.652,069       24   2017
24    5.110,208       25   2017
25    5.528,463       26   2017
26    1.403,803       27   2017
27    2.371,711       28   2017
28    5.771,596       29   2017
29   14.122,958       30   2017
30   28.899,700       31   2017
31    1.654,216       32   2017
32   12.825,107       33   2017
33      213,482       34   2017
34      481,530       35   2017
35      389,181       36   2017
36    3.185,328       37   2017
37   25.488,323       38   2017
38    1.413,414       39   2017
39      508,885       40   2017
40       77,042       41   2017
41   13.412,752       42   2017
42      991,505       43   2017
0   252.920,496        1   2018
1   281.359,242        2   2018
2   200.574,261        3   2018
3     6.415,090        4   2018
4     4.025,400        5   2018
5     7.558,639        6   2018
6     2.611,916        7   2018
7    55.167,068        8   2018
8     1.062,752        9   2018
9     2.677,024       10   2018
10    4.579,775       11   2018
11   23.590,542       12   2018
12   49.980,732       13   2018
13    1.172,115       14   2018
14   24.858,748       15   2018
15      435,130       16   2018
16      578,235       17   2018
17      281,978       18   2018
18      189,245       19   2018
19    2.739,897       20   2018
20      168,708       21   2018
21    9.833,606       22   2018
22    5.897,163       23   2018
23   14.610,025       24   2018
24    5.127,780       25   2018
25    5.578,372       26   2018
26    1.404,191       27   2018
27    2.309,114       28   2018
28    6.017,380       29   2018
29   14.049,871       30   2018
30   28.438,746       31   2018
31    1.705,052       32   2018
32   12.601,582       33   2018
33      327,661       34   2018
34      482,130       35   2018
35      735,467       36   2018
36    3.218,035       37   2018
37   26.126,541       38   2018
38    1.647,463       39   2018
39      508,617       40   2018
40       82,029       41   2018
41   13.741,531       42   2018
42    1.044,592       43   2018

### 3.3. Nettoyage de la donnée

In [114]:
production_electricite_total = production_electricite_total.replace([':', '0,000'], '')
production_electricite_total

   quantite_tep  pays_id  annee
0   244.415,946        1   2009
1   276.811,058        2   2009
2   196.495,458        3   2009
3     7.837,577        4   2009
4     3.692,897        5   2009
5     7.066,699        6   2009
6     3.128,375        7   2009
7    51.125,107        8   2009
8       754,800        9   2009
9     2.434,530       10   2009
10    5.276,443       11   2009
11   25.303,439       12   2009
12   46.060,545       13   2009
13    1.156,893       14   2009
14   25.110,746       15   2009
15      448,384       16   2009
16      478,768       17   2009
17    1.297,242       18   2009
18      333,481       19   2009
19    3.087,534       20   2009
20      186,414       21   2009
21    9.764,359       22   2009
22    5.939,015       23   2009
23   13.042,704       24   2009
24    4.317,029       25   2009
25    4.988,319       26   2009
26    1.410,420       27   2009
27    2.245,534       28   2009
28    6.171,625       29   2009
29   11.757,067       30   2009
30   32.395,112       31   2009
31    1.447,550       32   2009
32   11.323,990       33   2009
33      237,317       34   2009
34      587,132       35   2009
35      447,291       36   2009
36    3.295,099       37   2009
37   16.744,269       38   2009
38                    39   2009
39      427,859       40   2009
40                    41   2009
41   14.928,521       42   2009
42                    43   2009
0   256.256,793        1   2010
1   289.108,889        2   2010
2   205.466,311        3   2010
3     8.162,939        4   2010
4     4.010,194        5   2010
5     7.379,137        6   2010
6     3.341,539        7   2010
7    54.259,501        8   2010
8     1.114,693        9   2010
9     2.437,941       10   2010
10    4.934,797       11   2010
11   25.913,001       12   2010
12   48.938,359       13   2010
13    1.281,390       14   2010
14   25.905,838       15   2010
15      457,630       16   2010
16      569,814       17   2010
17      472,826       18   2010
18      394,779       19   2010
19    3.213,254       20   2010
20      181,744       21   2010
21   10.242,071       22   2010
22    6.114,368       23   2010
23   13.549,029       24   2010
24    4.650,537       25   2010
25    5.243,238       26   2010
26    1.413,435       27   2010
27    2.391,912       28   2010
28    6.910,126       29   2010
29   12.772,701       30   2010
30   32.852,096       31   2010
31    1.466,845       32   2010
32   10.620,292       33   2010
33      345,830       34   2010
34      624,290       35   2010
35      650,731       36   2010
36    3.276,268       37   2010
37   18.151,107       38   2010
38                    39   2010
39      444,368       40   2010
40       91,488       41   2010
41   16.236,285       42   2010
42                    43   2010
0   252.559,704        1   2011
1   284.200,638        2   2011
2   201.240,068        3   2011
3     7.747,746        4   2011
4     4.365,744        5   2011
5     7.514,188        6   2011
6     3.029,159        7   2011
7    52.538,521        8   2011
8     1.108,660        9   2011
9     2.335,686       10   2011
10    5.110,625       11   2011
11   25.251,591       12   2011
12   49.265,195       13   2011
13      977,831       14   2011
14   25.947,751       15   2011
15      423,836       16   2011
16      524,012       17   2011
17      392,565       18   2011
18      319,544       19   2011
19    3.097,092       20   2011
20      187,352       21   2011
21    9.786,172       22   2011
22    5.657,920       23   2011
23   14.053,553       24   2011
24    4.510,598       25   2011
25    5.349,525       26   2011
26    1.380,739       27   2011
27    2.457,282       28   2011
28    6.294,273       29   2011
29   12.932,544       30   2011
30   31.640,934       31   2011
31    1.479,820       32   2011
32   10.961,393       33   2011
33      228,362       34   2011
34      581,195       35   2011
35      360,361       36   2011
36    3.319,003       37   2011
37   19.715,315       38   2011
38                    39   2011
39      498,788       40   2011
40       87,360       41   2011
41   16.762,468       42   2011
42                    43   2011
0   252.297,715        1   2012
1   283.585,663        2   2012
2   200.843,565        3   2012
3     7.110,535        4   2012
4     4.068,211        5   2012
5     7.510,245        6   2012
6     2.639,821        7   2012
7    53.868,788        8   2012
8     1.028,932        9   2012
9     2.352,110       10   2012
10    5.241,538       11   2012
11   25.570,389       12   2012
12   49.175,178       13   2012
13      924,760       14   2012
14   25.668,568       15   2012
15      405,575       16   2012
16      530,333       17   2012
17      414,066       18   2012
18      328,201       19   2012
19    2.977,998       20   2012
20      197,219       21   2012
21    8.863,973       22   2012
22    6.241,786       23   2012
23   13.934,503       24   2012
24    4.007,871       25   2012
25    5.076,944       26   2012
26    1.353,055       27   2012
27    2.458,727       28   2012
28    6.026,721       29   2012
29   14.321,668       30   2012
30   31.287,948       31   2012
31    1.508,949       32   2012
32   12.694,153       33   2012
33      244,547       34   2012
34      538,401       35   2012
35      406,277       36   2012
36    3.164,144       37   2012
37   20.583,378       38   2012
38                    39   2012
39      510,970       40   2012
40       80,128       41   2012
41   17.100,447       42   2012
42                    43   2012
0   250.738,370        1   2013
1   281.545,700        2   2013
2   200.335,625        3   2013
3     7.142,193        4   2013
4     3.763,441        5   2013
5     7.466,746        6   2013
6     2.987,341        7   2013
7    54.766,638        8   2013
8     1.141,408        9   2013
9     2.228,754       10   2013
10    4.914,233       11   2013
11   24.559,909       12   2013
12   49.987,860       13   2013
13    1.208,363       14   2013
14   24.853,766       15   2013
15      368,874       16   2013
16      533,829       17   2013
17      388,981       18   2013
18      248,420       19   2013
19    2.601,915       20   2013
20      193,590       21   2013
21    8.728,051       22   2013
22    5.876,409       23   2013
23   14.141,739       24   2013
24    4.442,670       25   2013
25    5.063,306       26   2013
26    1.384,593       27   2013
27    2.473,173       28   2013
28    6.102,274       29   2013
29   13.169,894       30   2013
30   30.807,330       31   2013
31    1.557,662       32   2013
32   11.506,277       33   2013
33      339,223       34   2013
34      523,991       35   2013
35      598,366       36   2013
36    3.428,805       37   2013
37   20.625,614       38   2013
38                    39   2013
39      561,075       40   2013
40       77,816       41   2013
41   16.713,396       42   2013
42      864,936       43   2013
0   245.607,203        1   2014
1   274.678,627        2   2014
2   195.145,509        3   2014
3     6.209,733        4   2014
4     4.081,811        5   2014
5     7.399,811        6   2014
6     2.767,293        7   2014
7    53.807,653        8   2014
8     1.070,139        9   2014
9     2.243,085       10   2014
10    4.339,922       11   2014
11   23.968,164       12   2014
12   49.166,532       13   2014
13    1.165,335       14   2014
14   24.003,913       15   2014
15      374,026       16   2014
16      441,910       17   2014
17      357,192       18   2014
18      254,942       19   2014
19    2.523,469       20   2014
20      193,026       21   2014
21    8.874,666       22   2014
22    5.625,578       23   2014
23   13.664,384       24   2014
24    4.539,682       25   2014
25    5.647,001       26   2014
26    1.499,376       27   2014
27    2.345,916       28   2014
28    5.830,054       29   2014
29   13.212,590       30   2014
30   29.071,424       31   2014
31    1.558,282       32   2014
32   12.180,310       33   2014
33      272,799       34   2014
34      462,052       35   2014
35      406,229       36   2014
36    2.928,633       37   2014
37   21.635,818       38   2014
38    1.463,715       39   2014
39      467,444       40   2014
40       82,844       41   2014
41   15.719,570       42   2014
42      891,774       43   2014
0   249.554,191        1   2015
1   278.624,390        2   2015
2   198.230,875        3   2015
3     5.963,474        4   2015
4     4.230,655        5   2015
5     7.206,351        6   2015
6     2.488,446        7   2015
7    55.587,618        8   2015
8       895,666        9   2015
9     2.441,155       10   2015
10    4.460,396       11   2015
11   24.135,477       12   2015
12   49.769,935       13   2015
13      980,428       14   2015
14   24.281,691       15   2015
15      389,918       16   2015
16      475,857       17   2015
17      401,523       18   2015
18      237,840       19   2015
19    2.605,143       20   2015
20      112,183       21   2015
21    9.478,075       22   2015
22    5.613,460       23   2015
23   14.172,768       24   2015
24    4.506,580       25   2015
25    5.700,338       26   2015
26    1.298,334       27   2015
27    2.304,643       28   2015
28    5.877,050       29   2015
29   13.939,187       30   2015
30   29.070,199       31   2015
31    1.616,394       32   2015
32   12.400,000       33   2015
33      258,212       34   2015
34      485,450       35   2015
35      506,879       36   2015
36    3.293,035       37   2015
37   22.466,715       38   2015
38    1.413,414       39   2015
39      526,164       40   2015
40       80,646       41   2015
41   14.033,826       42   2015
42      931,450       43   2015
0   251.385,363        1   2016
1   280.429,187        2   2016
2   200.540,855        3   2016
3     7.333,482        4   2016
4     3.890,260        5   2016
5     7.155,123        6   2016
6     2.625,830        7   2016
7    55.766,208        8   2016
8     1.047,780        9   2016
9     2.623,642       10   2016
10    4.680,820       11   2016
11   23.616,962       12   2016
12   48.462,534       13   2016
13    1.102,305       14   2016
14   24.852,309       15   2016
15      420,263       16   2016
16      552,501       17   2016
17      343,669       18   2016
18      188,958       19   2016
19    2.736,331       20   2016
20       73,696       21   2016
21    9.894,607       22   2016
22    5.872,144       23   2016
23   14.322,391       24   2016
24    5.187,287       25   2016
25    5.597,854       26   2016
26    1.418,905       27   2016
27    2.315,907       28   2016
28    5.889,181       29   2016
29   13.414,414       30   2016
30   29.043,824       31   2016
31    1.594,934       32   2016
32   12.788,822       33   2016
33      270,094       34   2016
34      484,050       35   2016
35      669,106       36   2016
36    3.382,803       37   2016
37   23.533,462       38   2016
38    1.527,653       39   2016
39      514,317       40   2016
40       77,886       41   2016
41   14.143,818       42   2016
42      995,206       43   2016
0   254.161,138        1   2017
1   283.060,838        2   2017
2   201.942,440        3   2017
3     7.413,981        4   2017
4     3.919,070        5   2017
5     7.476,084        6   2017
6     2.669,108        7   2017
7    56.063,801        8   2017
8     1.110,704        9   2017
9     2.654,581       10   2017
10    4.752,028       11   2017
11   23.700,344       12   2017
12   48.255,417       13   2017
13    1.030,396       14   2017
14   25.379,967       15   2017
15      430,298       16   2017
16      647,566       17   2017
17      338,527       18   2017
18      192,188       19   2017
19    2.820,550       20   2017
20      142,025       21   2017
21   10.071,975       22   2017
22    6.131,720       23   2017
23   14.652,069       24   2017
24    5.110,208       25   2017
25    5.528,463       26   2017
26    1.403,803       27   2017
27    2.371,711       28   2017
28    5.771,596       29   2017
29   14.122,958       30   2017
30   28.899,700       31   2017
31    1.654,216       32   2017
32   12.825,107       33   2017
33      213,482       34   2017
34      481,530       35   2017
35      389,181       36   2017
36    3.185,328       37   2017
37   25.488,323       38   2017
38    1.413,414       39   2017
39      508,885       40   2017
40       77,042       41   2017
41   13.412,752       42   2017
42      991,505       43   2017
0   252.920,496        1   2018
1   281.359,242        2   2018
2   200.574,261        3   2018
3     6.415,090        4   2018
4     4.025,400        5   2018
5     7.558,639        6   2018
6     2.611,916        7   2018
7    55.167,068        8   2018
8     1.062,752        9   2018
9     2.677,024       10   2018
10    4.579,775       11   2018
11   23.590,542       12   2018
12   49.980,732       13   2018
13    1.172,115       14   2018
14   24.858,748       15   2018
15      435,130       16   2018
16      578,235       17   2018
17      281,978       18   2018
18      189,245       19   2018
19    2.739,897       20   2018
20      168,708       21   2018
21    9.833,606       22   2018
22    5.897,163       23   2018
23   14.610,025       24   2018
24    5.127,780       25   2018
25    5.578,372       26   2018
26    1.404,191       27   2018
27    2.309,114       28   2018
28    6.017,380       29   2018
29   14.049,871       30   2018
30   28.438,746       31   2018
31    1.705,052       32   2018
32   12.601,582       33   2018
33      327,661       34   2018
34      482,130       35   2018
35      735,467       36   2018
36    3.218,035       37   2018
37   26.126,541       38   2018
38    1.647,463       39   2018
39      508,617       40   2018
40       82,029       41   2018
41   13.741,531       42   2018
42    1.044,592       43   2018

In [115]:
production_electricite_total['quantite_tep'] = production_electricite_total['quantite_tep'].apply(lambda x: x.replace('.', ''))
production_electricite_total

   quantite_tep  pays_id  annee
0    244415,946        1   2009
1    276811,058        2   2009
2    196495,458        3   2009
3      7837,577        4   2009
4      3692,897        5   2009
5      7066,699        6   2009
6      3128,375        7   2009
7     51125,107        8   2009
8       754,800        9   2009
9      2434,530       10   2009
10     5276,443       11   2009
11    25303,439       12   2009
12    46060,545       13   2009
13     1156,893       14   2009
14    25110,746       15   2009
15      448,384       16   2009
16      478,768       17   2009
17     1297,242       18   2009
18      333,481       19   2009
19     3087,534       20   2009
20      186,414       21   2009
21     9764,359       22   2009
22     5939,015       23   2009
23    13042,704       24   2009
24     4317,029       25   2009
25     4988,319       26   2009
26     1410,420       27   2009
27     2245,534       28   2009
28     6171,625       29   2009
29    11757,067       30   2009
30    32395,112       31   2009
31     1447,550       32   2009
32    11323,990       33   2009
33      237,317       34   2009
34      587,132       35   2009
35      447,291       36   2009
36     3295,099       37   2009
37    16744,269       38   2009
38                    39   2009
39      427,859       40   2009
40                    41   2009
41    14928,521       42   2009
42                    43   2009
0    256256,793        1   2010
1    289108,889        2   2010
2    205466,311        3   2010
3      8162,939        4   2010
4      4010,194        5   2010
5      7379,137        6   2010
6      3341,539        7   2010
7     54259,501        8   2010
8      1114,693        9   2010
9      2437,941       10   2010
10     4934,797       11   2010
11    25913,001       12   2010
12    48938,359       13   2010
13     1281,390       14   2010
14    25905,838       15   2010
15      457,630       16   2010
16      569,814       17   2010
17      472,826       18   2010
18      394,779       19   2010
19     3213,254       20   2010
20      181,744       21   2010
21    10242,071       22   2010
22     6114,368       23   2010
23    13549,029       24   2010
24     4650,537       25   2010
25     5243,238       26   2010
26     1413,435       27   2010
27     2391,912       28   2010
28     6910,126       29   2010
29    12772,701       30   2010
30    32852,096       31   2010
31     1466,845       32   2010
32    10620,292       33   2010
33      345,830       34   2010
34      624,290       35   2010
35      650,731       36   2010
36     3276,268       37   2010
37    18151,107       38   2010
38                    39   2010
39      444,368       40   2010
40       91,488       41   2010
41    16236,285       42   2010
42                    43   2010
0    252559,704        1   2011
1    284200,638        2   2011
2    201240,068        3   2011
3      7747,746        4   2011
4      4365,744        5   2011
5      7514,188        6   2011
6      3029,159        7   2011
7     52538,521        8   2011
8      1108,660        9   2011
9      2335,686       10   2011
10     5110,625       11   2011
11    25251,591       12   2011
12    49265,195       13   2011
13      977,831       14   2011
14    25947,751       15   2011
15      423,836       16   2011
16      524,012       17   2011
17      392,565       18   2011
18      319,544       19   2011
19     3097,092       20   2011
20      187,352       21   2011
21     9786,172       22   2011
22     5657,920       23   2011
23    14053,553       24   2011
24     4510,598       25   2011
25     5349,525       26   2011
26     1380,739       27   2011
27     2457,282       28   2011
28     6294,273       29   2011
29    12932,544       30   2011
30    31640,934       31   2011
31     1479,820       32   2011
32    10961,393       33   2011
33      228,362       34   2011
34      581,195       35   2011
35      360,361       36   2011
36     3319,003       37   2011
37    19715,315       38   2011
38                    39   2011
39      498,788       40   2011
40       87,360       41   2011
41    16762,468       42   2011
42                    43   2011
0    252297,715        1   2012
1    283585,663        2   2012
2    200843,565        3   2012
3      7110,535        4   2012
4      4068,211        5   2012
5      7510,245        6   2012
6      2639,821        7   2012
7     53868,788        8   2012
8      1028,932        9   2012
9      2352,110       10   2012
10     5241,538       11   2012
11    25570,389       12   2012
12    49175,178       13   2012
13      924,760       14   2012
14    25668,568       15   2012
15      405,575       16   2012
16      530,333       17   2012
17      414,066       18   2012
18      328,201       19   2012
19     2977,998       20   2012
20      197,219       21   2012
21     8863,973       22   2012
22     6241,786       23   2012
23    13934,503       24   2012
24     4007,871       25   2012
25     5076,944       26   2012
26     1353,055       27   2012
27     2458,727       28   2012
28     6026,721       29   2012
29    14321,668       30   2012
30    31287,948       31   2012
31     1508,949       32   2012
32    12694,153       33   2012
33      244,547       34   2012
34      538,401       35   2012
35      406,277       36   2012
36     3164,144       37   2012
37    20583,378       38   2012
38                    39   2012
39      510,970       40   2012
40       80,128       41   2012
41    17100,447       42   2012
42                    43   2012
0    250738,370        1   2013
1    281545,700        2   2013
2    200335,625        3   2013
3      7142,193        4   2013
4      3763,441        5   2013
5      7466,746        6   2013
6      2987,341        7   2013
7     54766,638        8   2013
8      1141,408        9   2013
9      2228,754       10   2013
10     4914,233       11   2013
11    24559,909       12   2013
12    49987,860       13   2013
13     1208,363       14   2013
14    24853,766       15   2013
15      368,874       16   2013
16      533,829       17   2013
17      388,981       18   2013
18      248,420       19   2013
19     2601,915       20   2013
20      193,590       21   2013
21     8728,051       22   2013
22     5876,409       23   2013
23    14141,739       24   2013
24     4442,670       25   2013
25     5063,306       26   2013
26     1384,593       27   2013
27     2473,173       28   2013
28     6102,274       29   2013
29    13169,894       30   2013
30    30807,330       31   2013
31     1557,662       32   2013
32    11506,277       33   2013
33      339,223       34   2013
34      523,991       35   2013
35      598,366       36   2013
36     3428,805       37   2013
37    20625,614       38   2013
38                    39   2013
39      561,075       40   2013
40       77,816       41   2013
41    16713,396       42   2013
42      864,936       43   2013
0    245607,203        1   2014
1    274678,627        2   2014
2    195145,509        3   2014
3      6209,733        4   2014
4      4081,811        5   2014
5      7399,811        6   2014
6      2767,293        7   2014
7     53807,653        8   2014
8      1070,139        9   2014
9      2243,085       10   2014
10     4339,922       11   2014
11    23968,164       12   2014
12    49166,532       13   2014
13     1165,335       14   2014
14    24003,913       15   2014
15      374,026       16   2014
16      441,910       17   2014
17      357,192       18   2014
18      254,942       19   2014
19     2523,469       20   2014
20      193,026       21   2014
21     8874,666       22   2014
22     5625,578       23   2014
23    13664,384       24   2014
24     4539,682       25   2014
25     5647,001       26   2014
26     1499,376       27   2014
27     2345,916       28   2014
28     5830,054       29   2014
29    13212,590       30   2014
30    29071,424       31   2014
31     1558,282       32   2014
32    12180,310       33   2014
33      272,799       34   2014
34      462,052       35   2014
35      406,229       36   2014
36     2928,633       37   2014
37    21635,818       38   2014
38     1463,715       39   2014
39      467,444       40   2014
40       82,844       41   2014
41    15719,570       42   2014
42      891,774       43   2014
0    249554,191        1   2015
1    278624,390        2   2015
2    198230,875        3   2015
3      5963,474        4   2015
4      4230,655        5   2015
5      7206,351        6   2015
6      2488,446        7   2015
7     55587,618        8   2015
8       895,666        9   2015
9      2441,155       10   2015
10     4460,396       11   2015
11    24135,477       12   2015
12    49769,935       13   2015
13      980,428       14   2015
14    24281,691       15   2015
15      389,918       16   2015
16      475,857       17   2015
17      401,523       18   2015
18      237,840       19   2015
19     2605,143       20   2015
20      112,183       21   2015
21     9478,075       22   2015
22     5613,460       23   2015
23    14172,768       24   2015
24     4506,580       25   2015
25     5700,338       26   2015
26     1298,334       27   2015
27     2304,643       28   2015
28     5877,050       29   2015
29    13939,187       30   2015
30    29070,199       31   2015
31     1616,394       32   2015
32    12400,000       33   2015
33      258,212       34   2015
34      485,450       35   2015
35      506,879       36   2015
36     3293,035       37   2015
37    22466,715       38   2015
38     1413,414       39   2015
39      526,164       40   2015
40       80,646       41   2015
41    14033,826       42   2015
42      931,450       43   2015
0    251385,363        1   2016
1    280429,187        2   2016
2    200540,855        3   2016
3      7333,482        4   2016
4      3890,260        5   2016
5      7155,123        6   2016
6      2625,830        7   2016
7     55766,208        8   2016
8      1047,780        9   2016
9      2623,642       10   2016
10     4680,820       11   2016
11    23616,962       12   2016
12    48462,534       13   2016
13     1102,305       14   2016
14    24852,309       15   2016
15      420,263       16   2016
16      552,501       17   2016
17      343,669       18   2016
18      188,958       19   2016
19     2736,331       20   2016
20       73,696       21   2016
21     9894,607       22   2016
22     5872,144       23   2016
23    14322,391       24   2016
24     5187,287       25   2016
25     5597,854       26   2016
26     1418,905       27   2016
27     2315,907       28   2016
28     5889,181       29   2016
29    13414,414       30   2016
30    29043,824       31   2016
31     1594,934       32   2016
32    12788,822       33   2016
33      270,094       34   2016
34      484,050       35   2016
35      669,106       36   2016
36     3382,803       37   2016
37    23533,462       38   2016
38     1527,653       39   2016
39      514,317       40   2016
40       77,886       41   2016
41    14143,818       42   2016
42      995,206       43   2016
0    254161,138        1   2017
1    283060,838        2   2017
2    201942,440        3   2017
3      7413,981        4   2017
4      3919,070        5   2017
5      7476,084        6   2017
6      2669,108        7   2017
7     56063,801        8   2017
8      1110,704        9   2017
9      2654,581       10   2017
10     4752,028       11   2017
11    23700,344       12   2017
12    48255,417       13   2017
13     1030,396       14   2017
14    25379,967       15   2017
15      430,298       16   2017
16      647,566       17   2017
17      338,527       18   2017
18      192,188       19   2017
19     2820,550       20   2017
20      142,025       21   2017
21    10071,975       22   2017
22     6131,720       23   2017
23    14652,069       24   2017
24     5110,208       25   2017
25     5528,463       26   2017
26     1403,803       27   2017
27     2371,711       28   2017
28     5771,596       29   2017
29    14122,958       30   2017
30    28899,700       31   2017
31     1654,216       32   2017
32    12825,107       33   2017
33      213,482       34   2017
34      481,530       35   2017
35      389,181       36   2017
36     3185,328       37   2017
37    25488,323       38   2017
38     1413,414       39   2017
39      508,885       40   2017
40       77,042       41   2017
41    13412,752       42   2017
42      991,505       43   2017
0    252920,496        1   2018
1    281359,242        2   2018
2    200574,261        3   2018
3      6415,090        4   2018
4      4025,400        5   2018
5      7558,639        6   2018
6      2611,916        7   2018
7     55167,068        8   2018
8      1062,752        9   2018
9      2677,024       10   2018
10     4579,775       11   2018
11    23590,542       12   2018
12    49980,732       13   2018
13     1172,115       14   2018
14    24858,748       15   2018
15      435,130       16   2018
16      578,235       17   2018
17      281,978       18   2018
18      189,245       19   2018
19     2739,897       20   2018
20      168,708       21   2018
21     9833,606       22   2018
22     5897,163       23   2018
23    14610,025       24   2018
24     5127,780       25   2018
25     5578,372       26   2018
26     1404,191       27   2018
27     2309,114       28   2018
28     6017,380       29   2018
29    14049,871       30   2018
30    28438,746       31   2018
31     1705,052       32   2018
32    12601,582       33   2018
33      327,661       34   2018
34      482,130       35   2018
35      735,467       36   2018
36     3218,035       37   2018
37    26126,541       38   2018
38     1647,463       39   2018
39      508,617       40   2018
40       82,029       41   2018
41    13741,531       42   2018
42     1044,592       43   2018

In [116]:
production_electricite_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 430 entries, 0 to 42
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   quantite_tep  430 non-null    object
 1   pays_id       430 non-null    int64
 2   annee         430 non-null    int64
dtypes: int64(2), object(1)
memory usage: 13.4+ KB

In [117]:
production_electricite_total['quantite_tep'] = production_electricite_total['quantite_tep'].apply(lambda x: x.replace(',', '.'))
production_electricite_total

   quantite_tep  pays_id  annee
0    244415.946        1   2009
1    276811.058        2   2009
2    196495.458        3   2009
3      7837.577        4   2009
4      3692.897        5   2009
5      7066.699        6   2009
6      3128.375        7   2009
7     51125.107        8   2009
8       754.800        9   2009
9      2434.530       10   2009
10     5276.443       11   2009
11    25303.439       12   2009
12    46060.545       13   2009
13     1156.893       14   2009
14    25110.746       15   2009
15      448.384       16   2009
16      478.768       17   2009
17     1297.242       18   2009
18      333.481       19   2009
19     3087.534       20   2009
20      186.414       21   2009
21     9764.359       22   2009
22     5939.015       23   2009
23    13042.704       24   2009
24     4317.029       25   2009
25     4988.319       26   2009
26     1410.420       27   2009
27     2245.534       28   2009
28     6171.625       29   2009
29    11757.067       30   2009
30    32395.112       31   2009
31     1447.550       32   2009
32    11323.990       33   2009
33      237.317       34   2009
34      587.132       35   2009
35      447.291       36   2009
36     3295.099       37   2009
37    16744.269       38   2009
38                    39   2009
39      427.859       40   2009
40                    41   2009
41    14928.521       42   2009
42                    43   2009
0    256256.793        1   2010
1    289108.889        2   2010
2    205466.311        3   2010
3      8162.939        4   2010
4      4010.194        5   2010
5      7379.137        6   2010
6      3341.539        7   2010
7     54259.501        8   2010
8      1114.693        9   2010
9      2437.941       10   2010
10     4934.797       11   2010
11    25913.001       12   2010
12    48938.359       13   2010
13     1281.390       14   2010
14    25905.838       15   2010
15      457.630       16   2010
16      569.814       17   2010
17      472.826       18   2010
18      394.779       19   2010
19     3213.254       20   2010
20      181.744       21   2010
21    10242.071       22   2010
22     6114.368       23   2010
23    13549.029       24   2010
24     4650.537       25   2010
25     5243.238       26   2010
26     1413.435       27   2010
27     2391.912       28   2010
28     6910.126       29   2010
29    12772.701       30   2010
30    32852.096       31   2010
31     1466.845       32   2010
32    10620.292       33   2010
33      345.830       34   2010
34      624.290       35   2010
35      650.731       36   2010
36     3276.268       37   2010
37    18151.107       38   2010
38                    39   2010
39      444.368       40   2010
40       91.488       41   2010
41    16236.285       42   2010
42                    43   2010
0    252559.704        1   2011
1    284200.638        2   2011
2    201240.068        3   2011
3      7747.746        4   2011
4      4365.744        5   2011
5      7514.188        6   2011
6      3029.159        7   2011
7     52538.521        8   2011
8      1108.660        9   2011
9      2335.686       10   2011
10     5110.625       11   2011
11    25251.591       12   2011
12    49265.195       13   2011
13      977.831       14   2011
14    25947.751       15   2011
15      423.836       16   2011
16      524.012       17   2011
17      392.565       18   2011
18      319.544       19   2011
19     3097.092       20   2011
20      187.352       21   2011
21     9786.172       22   2011
22     5657.920       23   2011
23    14053.553       24   2011
24     4510.598       25   2011
25     5349.525       26   2011
26     1380.739       27   2011
27     2457.282       28   2011
28     6294.273       29   2011
29    12932.544       30   2011
30    31640.934       31   2011
31     1479.820       32   2011
32    10961.393       33   2011
33      228.362       34   2011
34      581.195       35   2011
35      360.361       36   2011
36     3319.003       37   2011
37    19715.315       38   2011
38                    39   2011
39      498.788       40   2011
40       87.360       41   2011
41    16762.468       42   2011
42                    43   2011
0    252297.715        1   2012
1    283585.663        2   2012
2    200843.565        3   2012
3      7110.535        4   2012
4      4068.211        5   2012
5      7510.245        6   2012
6      2639.821        7   2012
7     53868.788        8   2012
8      1028.932        9   2012
9      2352.110       10   2012
10     5241.538       11   2012
11    25570.389       12   2012
12    49175.178       13   2012
13      924.760       14   2012
14    25668.568       15   2012
15      405.575       16   2012
16      530.333       17   2012
17      414.066       18   2012
18      328.201       19   2012
19     2977.998       20   2012
20      197.219       21   2012
21     8863.973       22   2012
22     6241.786       23   2012
23    13934.503       24   2012
24     4007.871       25   2012
25     5076.944       26   2012
26     1353.055       27   2012
27     2458.727       28   2012
28     6026.721       29   2012
29    14321.668       30   2012
30    31287.948       31   2012
31     1508.949       32   2012
32    12694.153       33   2012
33      244.547       34   2012
34      538.401       35   2012
35      406.277       36   2012
36     3164.144       37   2012
37    20583.378       38   2012
38                    39   2012
39      510.970       40   2012
40       80.128       41   2012
41    17100.447       42   2012
42                    43   2012
0    250738.370        1   2013
1    281545.700        2   2013
2    200335.625        3   2013
3      7142.193        4   2013
4      3763.441        5   2013
5      7466.746        6   2013
6      2987.341        7   2013
7     54766.638        8   2013
8      1141.408        9   2013
9      2228.754       10   2013
10     4914.233       11   2013
11    24559.909       12   2013
12    49987.860       13   2013
13     1208.363       14   2013
14    24853.766       15   2013
15      368.874       16   2013
16      533.829       17   2013
17      388.981       18   2013
18      248.420       19   2013
19     2601.915       20   2013
20      193.590       21   2013
21     8728.051       22   2013
22     5876.409       23   2013
23    14141.739       24   2013
24     4442.670       25   2013
25     5063.306       26   2013
26     1384.593       27   2013
27     2473.173       28   2013
28     6102.274       29   2013
29    13169.894       30   2013
30    30807.330       31   2013
31     1557.662       32   2013
32    11506.277       33   2013
33      339.223       34   2013
34      523.991       35   2013
35      598.366       36   2013
36     3428.805       37   2013
37    20625.614       38   2013
38                    39   2013
39      561.075       40   2013
40       77.816       41   2013
41    16713.396       42   2013
42      864.936       43   2013
0    245607.203        1   2014
1    274678.627        2   2014
2    195145.509        3   2014
3      6209.733        4   2014
4      4081.811        5   2014
5      7399.811        6   2014
6      2767.293        7   2014
7     53807.653        8   2014
8      1070.139        9   2014
9      2243.085       10   2014
10     4339.922       11   2014
11    23968.164       12   2014
12    49166.532       13   2014
13     1165.335       14   2014
14    24003.913       15   2014
15      374.026       16   2014
16      441.910       17   2014
17      357.192       18   2014
18      254.942       19   2014
19     2523.469       20   2014
20      193.026       21   2014
21     8874.666       22   2014
22     5625.578       23   2014
23    13664.384       24   2014
24     4539.682       25   2014
25     5647.001       26   2014
26     1499.376       27   2014
27     2345.916       28   2014
28     5830.054       29   2014
29    13212.590       30   2014
30    29071.424       31   2014
31     1558.282       32   2014
32    12180.310       33   2014
33      272.799       34   2014
34      462.052       35   2014
35      406.229       36   2014
36     2928.633       37   2014
37    21635.818       38   2014
38     1463.715       39   2014
39      467.444       40   2014
40       82.844       41   2014
41    15719.570       42   2014
42      891.774       43   2014
0    249554.191        1   2015
1    278624.390        2   2015
2    198230.875        3   2015
3      5963.474        4   2015
4      4230.655        5   2015
5      7206.351        6   2015
6      2488.446        7   2015
7     55587.618        8   2015
8       895.666        9   2015
9      2441.155       10   2015
10     4460.396       11   2015
11    24135.477       12   2015
12    49769.935       13   2015
13      980.428       14   2015
14    24281.691       15   2015
15      389.918       16   2015
16      475.857       17   2015
17      401.523       18   2015
18      237.840       19   2015
19     2605.143       20   2015
20      112.183       21   2015
21     9478.075       22   2015
22     5613.460       23   2015
23    14172.768       24   2015
24     4506.580       25   2015
25     5700.338       26   2015
26     1298.334       27   2015
27     2304.643       28   2015
28     5877.050       29   2015
29    13939.187       30   2015
30    29070.199       31   2015
31     1616.394       32   2015
32    12400.000       33   2015
33      258.212       34   2015
34      485.450       35   2015
35      506.879       36   2015
36     3293.035       37   2015
37    22466.715       38   2015
38     1413.414       39   2015
39      526.164       40   2015
40       80.646       41   2015
41    14033.826       42   2015
42      931.450       43   2015
0    251385.363        1   2016
1    280429.187        2   2016
2    200540.855        3   2016
3      7333.482        4   2016
4      3890.260        5   2016
5      7155.123        6   2016
6      2625.830        7   2016
7     55766.208        8   2016
8      1047.780        9   2016
9      2623.642       10   2016
10     4680.820       11   2016
11    23616.962       12   2016
12    48462.534       13   2016
13     1102.305       14   2016
14    24852.309       15   2016
15      420.263       16   2016
16      552.501       17   2016
17      343.669       18   2016
18      188.958       19   2016
19     2736.331       20   2016
20       73.696       21   2016
21     9894.607       22   2016
22     5872.144       23   2016
23    14322.391       24   2016
24     5187.287       25   2016
25     5597.854       26   2016
26     1418.905       27   2016
27     2315.907       28   2016
28     5889.181       29   2016
29    13414.414       30   2016
30    29043.824       31   2016
31     1594.934       32   2016
32    12788.822       33   2016
33      270.094       34   2016
34      484.050       35   2016
35      669.106       36   2016
36     3382.803       37   2016
37    23533.462       38   2016
38     1527.653       39   2016
39      514.317       40   2016
40       77.886       41   2016
41    14143.818       42   2016
42      995.206       43   2016
0    254161.138        1   2017
1    283060.838        2   2017
2    201942.440        3   2017
3      7413.981        4   2017
4      3919.070        5   2017
5      7476.084        6   2017
6      2669.108        7   2017
7     56063.801        8   2017
8      1110.704        9   2017
9      2654.581       10   2017
10     4752.028       11   2017
11    23700.344       12   2017
12    48255.417       13   2017
13     1030.396       14   2017
14    25379.967       15   2017
15      430.298       16   2017
16      647.566       17   2017
17      338.527       18   2017
18      192.188       19   2017
19     2820.550       20   2017
20      142.025       21   2017
21    10071.975       22   2017
22     6131.720       23   2017
23    14652.069       24   2017
24     5110.208       25   2017
25     5528.463       26   2017
26     1403.803       27   2017
27     2371.711       28   2017
28     5771.596       29   2017
29    14122.958       30   2017
30    28899.700       31   2017
31     1654.216       32   2017
32    12825.107       33   2017
33      213.482       34   2017
34      481.530       35   2017
35      389.181       36   2017
36     3185.328       37   2017
37    25488.323       38   2017
38     1413.414       39   2017
39      508.885       40   2017
40       77.042       41   2017
41    13412.752       42   2017
42      991.505       43   2017
0    252920.496        1   2018
1    281359.242        2   2018
2    200574.261        3   2018
3      6415.090        4   2018
4      4025.400        5   2018
5      7558.639        6   2018
6      2611.916        7   2018
7     55167.068        8   2018
8      1062.752        9   2018
9      2677.024       10   2018
10     4579.775       11   2018
11    23590.542       12   2018
12    49980.732       13   2018
13     1172.115       14   2018
14    24858.748       15   2018
15      435.130       16   2018
16      578.235       17   2018
17      281.978       18   2018
18      189.245       19   2018
19     2739.897       20   2018
20      168.708       21   2018
21     9833.606       22   2018
22     5897.163       23   2018
23    14610.025       24   2018
24     5127.780       25   2018
25     5578.372       26   2018
26     1404.191       27   2018
27     2309.114       28   2018
28     6017.380       29   2018
29    14049.871       30   2018
30    28438.746       31   2018
31     1705.052       32   2018
32    12601.582       33   2018
33      327.661       34   2018
34      482.130       35   2018
35      735.467       36   2018
36     3218.035       37   2018
37    26126.541       38   2018
38     1647.463       39   2018
39      508.617       40   2018
40       82.029       41   2018
41    13741.531       42   2018
42     1044.592       43   2018

In [118]:
production_electricite_total["quantite_tep"] = pd.to_numeric(production_electricite_total['quantite_tep'])
production_electricite_total

    quantite_tep  pays_id  annee
0     244415.946        1   2009
1     276811.058        2   2009
2     196495.458        3   2009
3       7837.577        4   2009
4       3692.897        5   2009
5       7066.699        6   2009
6       3128.375        7   2009
7      51125.107        8   2009
8        754.800        9   2009
9       2434.530       10   2009
10      5276.443       11   2009
11     25303.439       12   2009
12     46060.545       13   2009
13      1156.893       14   2009
14     25110.746       15   2009
15       448.384       16   2009
16       478.768       17   2009
17      1297.242       18   2009
18       333.481       19   2009
19      3087.534       20   2009
20       186.414       21   2009
21      9764.359       22   2009
22      5939.015       23   2009
23     13042.704       24   2009
24      4317.029       25   2009
25      4988.319       26   2009
26      1410.420       27   2009
27      2245.534       28   2009
28      6171.625       29   2009
29     11757.067       30   2009
30     32395.112       31   2009
31      1447.550       32   2009
32     11323.990       33   2009
33       237.317       34   2009
34       587.132       35   2009
35       447.291       36   2009
36      3295.099       37   2009
37     16744.269       38   2009
38           NaN       39   2009
39       427.859       40   2009
40           NaN       41   2009
41     14928.521       42   2009
42           NaN       43   2009
0     256256.793        1   2010
1     289108.889        2   2010
2     205466.311        3   2010
3       8162.939        4   2010
4       4010.194        5   2010
5       7379.137        6   2010
6       3341.539        7   2010
7      54259.501        8   2010
8       1114.693        9   2010
9       2437.941       10   2010
10      4934.797       11   2010
11     25913.001       12   2010
12     48938.359       13   2010
13      1281.390       14   2010
14     25905.838       15   2010
15       457.630       16   2010
16       569.814       17   2010
17       472.826       18   2010
18       394.779       19   2010
19      3213.254       20   2010
20       181.744       21   2010
21     10242.071       22   2010
22      6114.368       23   2010
23     13549.029       24   2010
24      4650.537       25   2010
25      5243.238       26   2010
26      1413.435       27   2010
27      2391.912       28   2010
28      6910.126       29   2010
29     12772.701       30   2010
30     32852.096       31   2010
31      1466.845       32   2010
32     10620.292       33   2010
33       345.830       34   2010
34       624.290       35   2010
35       650.731       36   2010
36      3276.268       37   2010
37     18151.107       38   2010
38           NaN       39   2010
39       444.368       40   2010
40        91.488       41   2010
41     16236.285       42   2010
42           NaN       43   2010
0     252559.704        1   2011
1     284200.638        2   2011
2     201240.068        3   2011
3       7747.746        4   2011
4       4365.744        5   2011
5       7514.188        6   2011
6       3029.159        7   2011
7      52538.521        8   2011
8       1108.660        9   2011
9       2335.686       10   2011
10      5110.625       11   2011
11     25251.591       12   2011
12     49265.195       13   2011
13       977.831       14   2011
14     25947.751       15   2011
15       423.836       16   2011
16       524.012       17   2011
17       392.565       18   2011
18       319.544       19   2011
19      3097.092       20   2011
20       187.352       21   2011
21      9786.172       22   2011
22      5657.920       23   2011
23     14053.553       24   2011
24      4510.598       25   2011
25      5349.525       26   2011
26      1380.739       27   2011
27      2457.282       28   2011
28      6294.273       29   2011
29     12932.544       30   2011
30     31640.934       31   2011
31      1479.820       32   2011
32     10961.393       33   2011
33       228.362       34   2011
34       581.195       35   2011
35       360.361       36   2011
36      3319.003       37   2011
37     19715.315       38   2011
38           NaN       39   2011
39       498.788       40   2011
40        87.360       41   2011
41     16762.468       42   2011
42           NaN       43   2011
0     252297.715        1   2012
1     283585.663        2   2012
2     200843.565        3   2012
3       7110.535        4   2012
4       4068.211        5   2012
5       7510.245        6   2012
6       2639.821        7   2012
7      53868.788        8   2012
8       1028.932        9   2012
9       2352.110       10   2012
10      5241.538       11   2012
11     25570.389       12   2012
12     49175.178       13   2012
13       924.760       14   2012
14     25668.568       15   2012
15       405.575       16   2012
16       530.333       17   2012
17       414.066       18   2012
18       328.201       19   2012
19      2977.998       20   2012
20       197.219       21   2012
21      8863.973       22   2012
22      6241.786       23   2012
23     13934.503       24   2012
24      4007.871       25   2012
25      5076.944       26   2012
26      1353.055       27   2012
27      2458.727       28   2012
28      6026.721       29   2012
29     14321.668       30   2012
30     31287.948       31   2012
31      1508.949       32   2012
32     12694.153       33   2012
33       244.547       34   2012
34       538.401       35   2012
35       406.277       36   2012
36      3164.144       37   2012
37     20583.378       38   2012
38           NaN       39   2012
39       510.970       40   2012
40        80.128       41   2012
41     17100.447       42   2012
42           NaN       43   2012
0     250738.370        1   2013
1     281545.700        2   2013
2     200335.625        3   2013
3       7142.193        4   2013
4       3763.441        5   2013
5       7466.746        6   2013
6       2987.341        7   2013
7      54766.638        8   2013
8       1141.408        9   2013
9       2228.754       10   2013
10      4914.233       11   2013
11     24559.909       12   2013
12     49987.860       13   2013
13      1208.363       14   2013
14     24853.766       15   2013
15       368.874       16   2013
16       533.829       17   2013
17       388.981       18   2013
18       248.420       19   2013
19      2601.915       20   2013
20       193.590       21   2013
21      8728.051       22   2013
22      5876.409       23   2013
23     14141.739       24   2013
24      4442.670       25   2013
25      5063.306       26   2013
26      1384.593       27   2013
27      2473.173       28   2013
28      6102.274       29   2013
29     13169.894       30   2013
30     30807.330       31   2013
31      1557.662       32   2013
32     11506.277       33   2013
33       339.223       34   2013
34       523.991       35   2013
35       598.366       36   2013
36      3428.805       37   2013
37     20625.614       38   2013
38           NaN       39   2013
39       561.075       40   2013
40        77.816       41   2013
41     16713.396       42   2013
42       864.936       43   2013
0     245607.203        1   2014
1     274678.627        2   2014
2     195145.509        3   2014
3       6209.733        4   2014
4       4081.811        5   2014
5       7399.811        6   2014
6       2767.293        7   2014
7      53807.653        8   2014
8       1070.139        9   2014
9       2243.085       10   2014
10      4339.922       11   2014
11     23968.164       12   2014
12     49166.532       13   2014
13      1165.335       14   2014
14     24003.913       15   2014
15       374.026       16   2014
16       441.910       17   2014
17       357.192       18   2014
18       254.942       19   2014
19      2523.469       20   2014
20       193.026       21   2014
21      8874.666       22   2014
22      5625.578       23   2014
23     13664.384       24   2014
24      4539.682       25   2014
25      5647.001       26   2014
26      1499.376       27   2014
27      2345.916       28   2014
28      5830.054       29   2014
29     13212.590       30   2014
30     29071.424       31   2014
31      1558.282       32   2014
32     12180.310       33   2014
33       272.799       34   2014
34       462.052       35   2014
35       406.229       36   2014
36      2928.633       37   2014
37     21635.818       38   2014
38      1463.715       39   2014
39       467.444       40   2014
40        82.844       41   2014
41     15719.570       42   2014
42       891.774       43   2014
0     249554.191        1   2015
1     278624.390        2   2015
2     198230.875        3   2015
3       5963.474        4   2015
4       4230.655        5   2015
5       7206.351        6   2015
6       2488.446        7   2015
7      55587.618        8   2015
8        895.666        9   2015
9       2441.155       10   2015
10      4460.396       11   2015
11     24135.477       12   2015
12     49769.935       13   2015
13       980.428       14   2015
14     24281.691       15   2015
15       389.918       16   2015
16       475.857       17   2015
17       401.523       18   2015
18       237.840       19   2015
19      2605.143       20   2015
20       112.183       21   2015
21      9478.075       22   2015
22      5613.460       23   2015
23     14172.768       24   2015
24      4506.580       25   2015
25      5700.338       26   2015
26      1298.334       27   2015
27      2304.643       28   2015
28      5877.050       29   2015
29     13939.187       30   2015
30     29070.199       31   2015
31      1616.394       32   2015
32     12400.000       33   2015
33       258.212       34   2015
34       485.450       35   2015
35       506.879       36   2015
36      3293.035       37   2015
37     22466.715       38   2015
38      1413.414       39   2015
39       526.164       40   2015
40        80.646       41   2015
41     14033.826       42   2015
42       931.450       43   2015
0     251385.363        1   2016
1     280429.187        2   2016
2     200540.855        3   2016
3       7333.482        4   2016
4       3890.260        5   2016
5       7155.123        6   2016
6       2625.830        7   2016
7      55766.208        8   2016
8       1047.780        9   2016
9       2623.642       10   2016
10      4680.820       11   2016
11     23616.962       12   2016
12     48462.534       13   2016
13      1102.305       14   2016
14     24852.309       15   2016
15       420.263       16   2016
16       552.501       17   2016
17       343.669       18   2016
18       188.958       19   2016
19      2736.331       20   2016
20        73.696       21   2016
21      9894.607       22   2016
22      5872.144       23   2016
23     14322.391       24   2016
24      5187.287       25   2016
25      5597.854       26   2016
26      1418.905       27   2016
27      2315.907       28   2016
28      5889.181       29   2016
29     13414.414       30   2016
30     29043.824       31   2016
31      1594.934       32   2016
32     12788.822       33   2016
33       270.094       34   2016
34       484.050       35   2016
35       669.106       36   2016
36      3382.803       37   2016
37     23533.462       38   2016
38      1527.653       39   2016
39       514.317       40   2016
40        77.886       41   2016
41     14143.818       42   2016
42       995.206       43   2016
0     254161.138        1   2017
1     283060.838        2   2017
2     201942.440        3   2017
3       7413.981        4   2017
4       3919.070        5   2017
5       7476.084        6   2017
6       2669.108        7   2017
7      56063.801        8   2017
8       1110.704        9   2017
9       2654.581       10   2017
10      4752.028       11   2017
11     23700.344       12   2017
12     48255.417       13   2017
13      1030.396       14   2017
14     25379.967       15   2017
15       430.298       16   2017
16       647.566       17   2017
17       338.527       18   2017
18       192.188       19   2017
19      2820.550       20   2017
20       142.025       21   2017
21     10071.975       22   2017
22      6131.720       23   2017
23     14652.069       24   2017
24      5110.208       25   2017
25      5528.463       26   2017
26      1403.803       27   2017
27      2371.711       28   2017
28      5771.596       29   2017
29     14122.958       30   2017
30     28899.700       31   2017
31      1654.216       32   2017
32     12825.107       33   2017
33       213.482       34   2017
34       481.530       35   2017
35       389.181       36   2017
36      3185.328       37   2017
37     25488.323       38   2017
38      1413.414       39   2017
39       508.885       40   2017
40        77.042       41   2017
41     13412.752       42   2017
42       991.505       43   2017
0     252920.496        1   2018
1     281359.242        2   2018
2     200574.261        3   2018
3       6415.090        4   2018
4       4025.400        5   2018
5       7558.639        6   2018
6       2611.916        7   2018
7      55167.068        8   2018
8       1062.752        9   2018
9       2677.024       10   2018
10      4579.775       11   2018
11     23590.542       12   2018
12     49980.732       13   2018
13      1172.115       14   2018
14     24858.748       15   2018
15       435.130       16   2018
16       578.235       17   2018
17       281.978       18   2018
18       189.245       19   2018
19      2739.897       20   2018
20       168.708       21   2018
21      9833.606       22   2018
22      5897.163       23   2018
23     14610.025       24   2018
24      5127.780       25   2018
25      5578.372       26   2018
26      1404.191       27   2018
27      2309.114       28   2018
28      6017.380       29   2018
29     14049.871       30   2018
30     28438.746       31   2018
31      1705.052       32   2018
32     12601.582       33   2018
33       327.661       34   2018
34       482.130       35   2018
35       735.467       36   2018
36      3218.035       37   2018
37     26126.541       38   2018
38      1647.463       39   2018
39       508.617       40   2018
40        82.029       41   2018
41     13741.531       42   2018
42      1044.592       43   2018

In [119]:
production_electricite_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 430 entries, 0 to 42
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   quantite_tep  420 non-null    float64
 1   pays_id       430 non-null    int64
 2   annee         430 non-null    int64
dtypes: float64(1), int64(2)
memory usage: 13.4 KB

In [120]:
production_electricite_total.insert(0, 'id', range(1, 1 + len(production_electricite_total)))
production_electricite_total

     id  quantite_tep  pays_id  annee
0     1    244415.946        1   2009
1     2    276811.058        2   2009
2     3    196495.458        3   2009
3     4      7837.577        4   2009
4     5      3692.897        5   2009
5     6      7066.699        6   2009
6     7      3128.375        7   2009
7     8     51125.107        8   2009
8     9       754.800        9   2009
9    10      2434.530       10   2009
10   11      5276.443       11   2009
11   12     25303.439       12   2009
12   13     46060.545       13   2009
13   14      1156.893       14   2009
14   15     25110.746       15   2009
15   16       448.384       16   2009
16   17       478.768       17   2009
17   18      1297.242       18   2009
18   19       333.481       19   2009
19   20      3087.534       20   2009
20   21       186.414       21   2009
21   22      9764.359       22   2009
22   23      5939.015       23   2009
23   24     13042.704       24   2009
24   25      4317.029       25   2009
25   26      4988.319       26   2009
26   27      1410.420       27   2009
27   28      2245.534       28   2009
28   29      6171.625       29   2009
29   30     11757.067       30   2009
30   31     32395.112       31   2009
31   32      1447.550       32   2009
32   33     11323.990       33   2009
33   34       237.317       34   2009
34   35       587.132       35   2009
35   36       447.291       36   2009
36   37      3295.099       37   2009
37   38     16744.269       38   2009
38   39           NaN       39   2009
39   40       427.859       40   2009
40   41           NaN       41   2009
41   42     14928.521       42   2009
42   43           NaN       43   2009
0    44    256256.793        1   2010
1    45    289108.889        2   2010
2    46    205466.311        3   2010
3    47      8162.939        4   2010
4    48      4010.194        5   2010
5    49      7379.137        6   2010
6    50      3341.539        7   2010
7    51     54259.501        8   2010
8    52      1114.693        9   2010
9    53      2437.941       10   2010
10   54      4934.797       11   2010
11   55     25913.001       12   2010
12   56     48938.359       13   2010
13   57      1281.390       14   2010
14   58     25905.838       15   2010
15   59       457.630       16   2010
16   60       569.814       17   2010
17   61       472.826       18   2010
18   62       394.779       19   2010
19   63      3213.254       20   2010
20   64       181.744       21   2010
21   65     10242.071       22   2010
22   66      6114.368       23   2010
23   67     13549.029       24   2010
24   68      4650.537       25   2010
25   69      5243.238       26   2010
26   70      1413.435       27   2010
27   71      2391.912       28   2010
28   72      6910.126       29   2010
29   73     12772.701       30   2010
30   74     32852.096       31   2010
31   75      1466.845       32   2010
32   76     10620.292       33   2010
33   77       345.830       34   2010
34   78       624.290       35   2010
35   79       650.731       36   2010
36   80      3276.268       37   2010
37   81     18151.107       38   2010
38   82           NaN       39   2010
39   83       444.368       40   2010
40   84        91.488       41   2010
41   85     16236.285       42   2010
42   86           NaN       43   2010
0    87    252559.704        1   2011
1    88    284200.638        2   2011
2    89    201240.068        3   2011
3    90      7747.746        4   2011
4    91      4365.744        5   2011
5    92      7514.188        6   2011
6    93      3029.159        7   2011
7    94     52538.521        8   2011
8    95      1108.660        9   2011
9    96      2335.686       10   2011
10   97      5110.625       11   2011
11   98     25251.591       12   2011
12   99     49265.195       13   2011
13  100       977.831       14   2011
14  101     25947.751       15   2011
15  102       423.836       16   2011
16  103       524.012       17   2011
17  104       392.565       18   2011
18  105       319.544       19   2011
19  106      3097.092       20   2011
20  107       187.352       21   2011
21  108      9786.172       22   2011
22  109      5657.920       23   2011
23  110     14053.553       24   2011
24  111      4510.598       25   2011
25  112      5349.525       26   2011
26  113      1380.739       27   2011
27  114      2457.282       28   2011
28  115      6294.273       29   2011
29  116     12932.544       30   2011
30  117     31640.934       31   2011
31  118      1479.820       32   2011
32  119     10961.393       33   2011
33  120       228.362       34   2011
34  121       581.195       35   2011
35  122       360.361       36   2011
36  123      3319.003       37   2011
37  124     19715.315       38   2011
38  125           NaN       39   2011
39  126       498.788       40   2011
40  127        87.360       41   2011
41  128     16762.468       42   2011
42  129           NaN       43   2011
0   130    252297.715        1   2012
1   131    283585.663        2   2012
2   132    200843.565        3   2012
3   133      7110.535        4   2012
4   134      4068.211        5   2012
5   135      7510.245        6   2012
6   136      2639.821        7   2012
7   137     53868.788        8   2012
8   138      1028.932        9   2012
9   139      2352.110       10   2012
10  140      5241.538       11   2012
11  141     25570.389       12   2012
12  142     49175.178       13   2012
13  143       924.760       14   2012
14  144     25668.568       15   2012
15  145       405.575       16   2012
16  146       530.333       17   2012
17  147       414.066       18   2012
18  148       328.201       19   2012
19  149      2977.998       20   2012
20  150       197.219       21   2012
21  151      8863.973       22   2012
22  152      6241.786       23   2012
23  153     13934.503       24   2012
24  154      4007.871       25   2012
25  155      5076.944       26   2012
26  156      1353.055       27   2012
27  157      2458.727       28   2012
28  158      6026.721       29   2012
29  159     14321.668       30   2012
30  160     31287.948       31   2012
31  161      1508.949       32   2012
32  162     12694.153       33   2012
33  163       244.547       34   2012
34  164       538.401       35   2012
35  165       406.277       36   2012
36  166      3164.144       37   2012
37  167     20583.378       38   2012
38  168           NaN       39   2012
39  169       510.970       40   2012
40  170        80.128       41   2012
41  171     17100.447       42   2012
42  172           NaN       43   2012
0   173    250738.370        1   2013
1   174    281545.700        2   2013
2   175    200335.625        3   2013
3   176      7142.193        4   2013
4   177      3763.441        5   2013
5   178      7466.746        6   2013
6   179      2987.341        7   2013
7   180     54766.638        8   2013
8   181      1141.408        9   2013
9   182      2228.754       10   2013
10  183      4914.233       11   2013
11  184     24559.909       12   2013
12  185     49987.860       13   2013
13  186      1208.363       14   2013
14  187     24853.766       15   2013
15  188       368.874       16   2013
16  189       533.829       17   2013
17  190       388.981       18   2013
18  191       248.420       19   2013
19  192      2601.915       20   2013
20  193       193.590       21   2013
21  194      8728.051       22   2013
22  195      5876.409       23   2013
23  196     14141.739       24   2013
24  197      4442.670       25   2013
25  198      5063.306       26   2013
26  199      1384.593       27   2013
27  200      2473.173       28   2013
28  201      6102.274       29   2013
29  202     13169.894       30   2013
30  203     30807.330       31   2013
31  204      1557.662       32   2013
32  205     11506.277       33   2013
33  206       339.223       34   2013
34  207       523.991       35   2013
35  208       598.366       36   2013
36  209      3428.805       37   2013
37  210     20625.614       38   2013
38  211           NaN       39   2013
39  212       561.075       40   2013
40  213        77.816       41   2013
41  214     16713.396       42   2013
42  215       864.936       43   2013
0   216    245607.203        1   2014
1   217    274678.627        2   2014
2   218    195145.509        3   2014
3   219      6209.733        4   2014
4   220      4081.811        5   2014
5   221      7399.811        6   2014
6   222      2767.293        7   2014
7   223     53807.653        8   2014
8   224      1070.139        9   2014
9   225      2243.085       10   2014
10  226      4339.922       11   2014
11  227     23968.164       12   2014
12  228     49166.532       13   2014
13  229      1165.335       14   2014
14  230     24003.913       15   2014
15  231       374.026       16   2014
16  232       441.910       17   2014
17  233       357.192       18   2014
18  234       254.942       19   2014
19  235      2523.469       20   2014
20  236       193.026       21   2014
21  237      8874.666       22   2014
22  238      5625.578       23   2014
23  239     13664.384       24   2014
24  240      4539.682       25   2014
25  241      5647.001       26   2014
26  242      1499.376       27   2014
27  243      2345.916       28   2014
28  244      5830.054       29   2014
29  245     13212.590       30   2014
30  246     29071.424       31   2014
31  247      1558.282       32   2014
32  248     12180.310       33   2014
33  249       272.799       34   2014
34  250       462.052       35   2014
35  251       406.229       36   2014
36  252      2928.633       37   2014
37  253     21635.818       38   2014
38  254      1463.715       39   2014
39  255       467.444       40   2014
40  256        82.844       41   2014
41  257     15719.570       42   2014
42  258       891.774       43   2014
0   259    249554.191        1   2015
1   260    278624.390        2   2015
2   261    198230.875        3   2015
3   262      5963.474        4   2015
4   263      4230.655        5   2015
5   264      7206.351        6   2015
6   265      2488.446        7   2015
7   266     55587.618        8   2015
8   267       895.666        9   2015
9   268      2441.155       10   2015
10  269      4460.396       11   2015
11  270     24135.477       12   2015
12  271     49769.935       13   2015
13  272       980.428       14   2015
14  273     24281.691       15   2015
15  274       389.918       16   2015
16  275       475.857       17   2015
17  276       401.523       18   2015
18  277       237.840       19   2015
19  278      2605.143       20   2015
20  279       112.183       21   2015
21  280      9478.075       22   2015
22  281      5613.460       23   2015
23  282     14172.768       24   2015
24  283      4506.580       25   2015
25  284      5700.338       26   2015
26  285      1298.334       27   2015
27  286      2304.643       28   2015
28  287      5877.050       29   2015
29  288     13939.187       30   2015
30  289     29070.199       31   2015
31  290      1616.394       32   2015
32  291     12400.000       33   2015
33  292       258.212       34   2015
34  293       485.450       35   2015
35  294       506.879       36   2015
36  295      3293.035       37   2015
37  296     22466.715       38   2015
38  297      1413.414       39   2015
39  298       526.164       40   2015
40  299        80.646       41   2015
41  300     14033.826       42   2015
42  301       931.450       43   2015
0   302    251385.363        1   2016
1   303    280429.187        2   2016
2   304    200540.855        3   2016
3   305      7333.482        4   2016
4   306      3890.260        5   2016
5   307      7155.123        6   2016
6   308      2625.830        7   2016
7   309     55766.208        8   2016
8   310      1047.780        9   2016
9   311      2623.642       10   2016
10  312      4680.820       11   2016
11  313     23616.962       12   2016
12  314     48462.534       13   2016
13  315      1102.305       14   2016
14  316     24852.309       15   2016
15  317       420.263       16   2016
16  318       552.501       17   2016
17  319       343.669       18   2016
18  320       188.958       19   2016
19  321      2736.331       20   2016
20  322        73.696       21   2016
21  323      9894.607       22   2016
22  324      5872.144       23   2016
23  325     14322.391       24   2016
24  326      5187.287       25   2016
25  327      5597.854       26   2016
26  328      1418.905       27   2016
27  329      2315.907       28   2016
28  330      5889.181       29   2016
29  331     13414.414       30   2016
30  332     29043.824       31   2016
31  333      1594.934       32   2016
32  334     12788.822       33   2016
33  335       270.094       34   2016
34  336       484.050       35   2016
35  337       669.106       36   2016
36  338      3382.803       37   2016
37  339     23533.462       38   2016
38  340      1527.653       39   2016
39  341       514.317       40   2016
40  342        77.886       41   2016
41  343     14143.818       42   2016
42  344       995.206       43   2016
0   345    254161.138        1   2017
1   346    283060.838        2   2017
2   347    201942.440        3   2017
3   348      7413.981        4   2017
4   349      3919.070        5   2017
5   350      7476.084        6   2017
6   351      2669.108        7   2017
7   352     56063.801        8   2017
8   353      1110.704        9   2017
9   354      2654.581       10   2017
10  355      4752.028       11   2017
11  356     23700.344       12   2017
12  357     48255.417       13   2017
13  358      1030.396       14   2017
14  359     25379.967       15   2017
15  360       430.298       16   2017
16  361       647.566       17   2017
17  362       338.527       18   2017
18  363       192.188       19   2017
19  364      2820.550       20   2017
20  365       142.025       21   2017
21  366     10071.975       22   2017
22  367      6131.720       23   2017
23  368     14652.069       24   2017
24  369      5110.208       25   2017
25  370      5528.463       26   2017
26  371      1403.803       27   2017
27  372      2371.711       28   2017
28  373      5771.596       29   2017
29  374     14122.958       30   2017
30  375     28899.700       31   2017
31  376      1654.216       32   2017
32  377     12825.107       33   2017
33  378       213.482       34   2017
34  379       481.530       35   2017
35  380       389.181       36   2017
36  381      3185.328       37   2017
37  382     25488.323       38   2017
38  383      1413.414       39   2017
39  384       508.885       40   2017
40  385        77.042       41   2017
41  386     13412.752       42   2017
42  387       991.505       43   2017
0   388    252920.496        1   2018
1   389    281359.242        2   2018
2   390    200574.261        3   2018
3   391      6415.090        4   2018
4   392      4025.400        5   2018
5   393      7558.639        6   2018
6   394      2611.916        7   2018
7   395     55167.068        8   2018
8   396      1062.752        9   2018
9   397      2677.024       10   2018
10  398      4579.775       11   2018
11  399     23590.542       12   2018
12  400     49980.732       13   2018
13  401      1172.115       14   2018
14  402     24858.748       15   2018
15  403       435.130       16   2018
16  404       578.235       17   2018
17  405       281.978       18   2018
18  406       189.245       19   2018
19  407      2739.897       20   2018
20  408       168.708       21   2018
21  409      9833.606       22   2018
22  410      5897.163       23   2018
23  411     14610.025       24   2018
24  412      5127.780       25   2018
25  413      5578.372       26   2018
26  414      1404.191       27   2018
27  415      2309.114       28   2018
28  416      6017.380       29   2018
29  417     14049.871       30   2018
30  418     28438.746       31   2018
31  419      1705.052       32   2018
32  420     12601.582       33   2018
33  421       327.661       34   2018
34  422       482.130       35   2018
35  423       735.467       36   2018
36  424      3218.035       37   2018
37  425     26126.541       38   2018
38  426      1647.463       39   2018
39  427       508.617       40   2018
40  428        82.029       41   2018
41  429     13741.531       42   2018
42  430      1044.592       43   2018

In [121]:
production_electricite_total = production_electricite_total[['id','pays_id','annee','quantite_tep']]
production_electricite_total

     id  pays_id  annee  quantite_tep
0     1        1   2009    244415.946
1     2        2   2009    276811.058
2     3        3   2009    196495.458
3     4        4   2009      7837.577
4     5        5   2009      3692.897
5     6        6   2009      7066.699
6     7        7   2009      3128.375
7     8        8   2009     51125.107
8     9        9   2009       754.800
9    10       10   2009      2434.530
10   11       11   2009      5276.443
11   12       12   2009     25303.439
12   13       13   2009     46060.545
13   14       14   2009      1156.893
14   15       15   2009     25110.746
15   16       16   2009       448.384
16   17       17   2009       478.768
17   18       18   2009      1297.242
18   19       19   2009       333.481
19   20       20   2009      3087.534
20   21       21   2009       186.414
21   22       22   2009      9764.359
22   23       23   2009      5939.015
23   24       24   2009     13042.704
24   25       25   2009      4317.029
25   26       26   2009      4988.319
26   27       27   2009      1410.420
27   28       28   2009      2245.534
28   29       29   2009      6171.625
29   30       30   2009     11757.067
30   31       31   2009     32395.112
31   32       32   2009      1447.550
32   33       33   2009     11323.990
33   34       34   2009       237.317
34   35       35   2009       587.132
35   36       36   2009       447.291
36   37       37   2009      3295.099
37   38       38   2009     16744.269
38   39       39   2009           NaN
39   40       40   2009       427.859
40   41       41   2009           NaN
41   42       42   2009     14928.521
42   43       43   2009           NaN
0    44        1   2010    256256.793
1    45        2   2010    289108.889
2    46        3   2010    205466.311
3    47        4   2010      8162.939
4    48        5   2010      4010.194
5    49        6   2010      7379.137
6    50        7   2010      3341.539
7    51        8   2010     54259.501
8    52        9   2010      1114.693
9    53       10   2010      2437.941
10   54       11   2010      4934.797
11   55       12   2010     25913.001
12   56       13   2010     48938.359
13   57       14   2010      1281.390
14   58       15   2010     25905.838
15   59       16   2010       457.630
16   60       17   2010       569.814
17   61       18   2010       472.826
18   62       19   2010       394.779
19   63       20   2010      3213.254
20   64       21   2010       181.744
21   65       22   2010     10242.071
22   66       23   2010      6114.368
23   67       24   2010     13549.029
24   68       25   2010      4650.537
25   69       26   2010      5243.238
26   70       27   2010      1413.435
27   71       28   2010      2391.912
28   72       29   2010      6910.126
29   73       30   2010     12772.701
30   74       31   2010     32852.096
31   75       32   2010      1466.845
32   76       33   2010     10620.292
33   77       34   2010       345.830
34   78       35   2010       624.290
35   79       36   2010       650.731
36   80       37   2010      3276.268
37   81       38   2010     18151.107
38   82       39   2010           NaN
39   83       40   2010       444.368
40   84       41   2010        91.488
41   85       42   2010     16236.285
42   86       43   2010           NaN
0    87        1   2011    252559.704
1    88        2   2011    284200.638
2    89        3   2011    201240.068
3    90        4   2011      7747.746
4    91        5   2011      4365.744
5    92        6   2011      7514.188
6    93        7   2011      3029.159
7    94        8   2011     52538.521
8    95        9   2011      1108.660
9    96       10   2011      2335.686
10   97       11   2011      5110.625
11   98       12   2011     25251.591
12   99       13   2011     49265.195
13  100       14   2011       977.831
14  101       15   2011     25947.751
15  102       16   2011       423.836
16  103       17   2011       524.012
17  104       18   2011       392.565
18  105       19   2011       319.544
19  106       20   2011      3097.092
20  107       21   2011       187.352
21  108       22   2011      9786.172
22  109       23   2011      5657.920
23  110       24   2011     14053.553
24  111       25   2011      4510.598
25  112       26   2011      5349.525
26  113       27   2011      1380.739
27  114       28   2011      2457.282
28  115       29   2011      6294.273
29  116       30   2011     12932.544
30  117       31   2011     31640.934
31  118       32   2011      1479.820
32  119       33   2011     10961.393
33  120       34   2011       228.362
34  121       35   2011       581.195
35  122       36   2011       360.361
36  123       37   2011      3319.003
37  124       38   2011     19715.315
38  125       39   2011           NaN
39  126       40   2011       498.788
40  127       41   2011        87.360
41  128       42   2011     16762.468
42  129       43   2011           NaN
0   130        1   2012    252297.715
1   131        2   2012    283585.663
2   132        3   2012    200843.565
3   133        4   2012      7110.535
4   134        5   2012      4068.211
5   135        6   2012      7510.245
6   136        7   2012      2639.821
7   137        8   2012     53868.788
8   138        9   2012      1028.932
9   139       10   2012      2352.110
10  140       11   2012      5241.538
11  141       12   2012     25570.389
12  142       13   2012     49175.178
13  143       14   2012       924.760
14  144       15   2012     25668.568
15  145       16   2012       405.575
16  146       17   2012       530.333
17  147       18   2012       414.066
18  148       19   2012       328.201
19  149       20   2012      2977.998
20  150       21   2012       197.219
21  151       22   2012      8863.973
22  152       23   2012      6241.786
23  153       24   2012     13934.503
24  154       25   2012      4007.871
25  155       26   2012      5076.944
26  156       27   2012      1353.055
27  157       28   2012      2458.727
28  158       29   2012      6026.721
29  159       30   2012     14321.668
30  160       31   2012     31287.948
31  161       32   2012      1508.949
32  162       33   2012     12694.153
33  163       34   2012       244.547
34  164       35   2012       538.401
35  165       36   2012       406.277
36  166       37   2012      3164.144
37  167       38   2012     20583.378
38  168       39   2012           NaN
39  169       40   2012       510.970
40  170       41   2012        80.128
41  171       42   2012     17100.447
42  172       43   2012           NaN
0   173        1   2013    250738.370
1   174        2   2013    281545.700
2   175        3   2013    200335.625
3   176        4   2013      7142.193
4   177        5   2013      3763.441
5   178        6   2013      7466.746
6   179        7   2013      2987.341
7   180        8   2013     54766.638
8   181        9   2013      1141.408
9   182       10   2013      2228.754
10  183       11   2013      4914.233
11  184       12   2013     24559.909
12  185       13   2013     49987.860
13  186       14   2013      1208.363
14  187       15   2013     24853.766
15  188       16   2013       368.874
16  189       17   2013       533.829
17  190       18   2013       388.981
18  191       19   2013       248.420
19  192       20   2013      2601.915
20  193       21   2013       193.590
21  194       22   2013      8728.051
22  195       23   2013      5876.409
23  196       24   2013     14141.739
24  197       25   2013      4442.670
25  198       26   2013      5063.306
26  199       27   2013      1384.593
27  200       28   2013      2473.173
28  201       29   2013      6102.274
29  202       30   2013     13169.894
30  203       31   2013     30807.330
31  204       32   2013      1557.662
32  205       33   2013     11506.277
33  206       34   2013       339.223
34  207       35   2013       523.991
35  208       36   2013       598.366
36  209       37   2013      3428.805
37  210       38   2013     20625.614
38  211       39   2013           NaN
39  212       40   2013       561.075
40  213       41   2013        77.816
41  214       42   2013     16713.396
42  215       43   2013       864.936
0   216        1   2014    245607.203
1   217        2   2014    274678.627
2   218        3   2014    195145.509
3   219        4   2014      6209.733
4   220        5   2014      4081.811
5   221        6   2014      7399.811
6   222        7   2014      2767.293
7   223        8   2014     53807.653
8   224        9   2014      1070.139
9   225       10   2014      2243.085
10  226       11   2014      4339.922
11  227       12   2014     23968.164
12  228       13   2014     49166.532
13  229       14   2014      1165.335
14  230       15   2014     24003.913
15  231       16   2014       374.026
16  232       17   2014       441.910
17  233       18   2014       357.192
18  234       19   2014       254.942
19  235       20   2014      2523.469
20  236       21   2014       193.026
21  237       22   2014      8874.666
22  238       23   2014      5625.578
23  239       24   2014     13664.384
24  240       25   2014      4539.682
25  241       26   2014      5647.001
26  242       27   2014      1499.376
27  243       28   2014      2345.916
28  244       29   2014      5830.054
29  245       30   2014     13212.590
30  246       31   2014     29071.424
31  247       32   2014      1558.282
32  248       33   2014     12180.310
33  249       34   2014       272.799
34  250       35   2014       462.052
35  251       36   2014       406.229
36  252       37   2014      2928.633
37  253       38   2014     21635.818
38  254       39   2014      1463.715
39  255       40   2014       467.444
40  256       41   2014        82.844
41  257       42   2014     15719.570
42  258       43   2014       891.774
0   259        1   2015    249554.191
1   260        2   2015    278624.390
2   261        3   2015    198230.875
3   262        4   2015      5963.474
4   263        5   2015      4230.655
5   264        6   2015      7206.351
6   265        7   2015      2488.446
7   266        8   2015     55587.618
8   267        9   2015       895.666
9   268       10   2015      2441.155
10  269       11   2015      4460.396
11  270       12   2015     24135.477
12  271       13   2015     49769.935
13  272       14   2015       980.428
14  273       15   2015     24281.691
15  274       16   2015       389.918
16  275       17   2015       475.857
17  276       18   2015       401.523
18  277       19   2015       237.840
19  278       20   2015      2605.143
20  279       21   2015       112.183
21  280       22   2015      9478.075
22  281       23   2015      5613.460
23  282       24   2015     14172.768
24  283       25   2015      4506.580
25  284       26   2015      5700.338
26  285       27   2015      1298.334
27  286       28   2015      2304.643
28  287       29   2015      5877.050
29  288       30   2015     13939.187
30  289       31   2015     29070.199
31  290       32   2015      1616.394
32  291       33   2015     12400.000
33  292       34   2015       258.212
34  293       35   2015       485.450
35  294       36   2015       506.879
36  295       37   2015      3293.035
37  296       38   2015     22466.715
38  297       39   2015      1413.414
39  298       40   2015       526.164
40  299       41   2015        80.646
41  300       42   2015     14033.826
42  301       43   2015       931.450
0   302        1   2016    251385.363
1   303        2   2016    280429.187
2   304        3   2016    200540.855
3   305        4   2016      7333.482
4   306        5   2016      3890.260
5   307        6   2016      7155.123
6   308        7   2016      2625.830
7   309        8   2016     55766.208
8   310        9   2016      1047.780
9   311       10   2016      2623.642
10  312       11   2016      4680.820
11  313       12   2016     23616.962
12  314       13   2016     48462.534
13  315       14   2016      1102.305
14  316       15   2016     24852.309
15  317       16   2016       420.263
16  318       17   2016       552.501
17  319       18   2016       343.669
18  320       19   2016       188.958
19  321       20   2016      2736.331
20  322       21   2016        73.696
21  323       22   2016      9894.607
22  324       23   2016      5872.144
23  325       24   2016     14322.391
24  326       25   2016      5187.287
25  327       26   2016      5597.854
26  328       27   2016      1418.905
27  329       28   2016      2315.907
28  330       29   2016      5889.181
29  331       30   2016     13414.414
30  332       31   2016     29043.824
31  333       32   2016      1594.934
32  334       33   2016     12788.822
33  335       34   2016       270.094
34  336       35   2016       484.050
35  337       36   2016       669.106
36  338       37   2016      3382.803
37  339       38   2016     23533.462
38  340       39   2016      1527.653
39  341       40   2016       514.317
40  342       41   2016        77.886
41  343       42   2016     14143.818
42  344       43   2016       995.206
0   345        1   2017    254161.138
1   346        2   2017    283060.838
2   347        3   2017    201942.440
3   348        4   2017      7413.981
4   349        5   2017      3919.070
5   350        6   2017      7476.084
6   351        7   2017      2669.108
7   352        8   2017     56063.801
8   353        9   2017      1110.704
9   354       10   2017      2654.581
10  355       11   2017      4752.028
11  356       12   2017     23700.344
12  357       13   2017     48255.417
13  358       14   2017      1030.396
14  359       15   2017     25379.967
15  360       16   2017       430.298
16  361       17   2017       647.566
17  362       18   2017       338.527
18  363       19   2017       192.188
19  364       20   2017      2820.550
20  365       21   2017       142.025
21  366       22   2017     10071.975
22  367       23   2017      6131.720
23  368       24   2017     14652.069
24  369       25   2017      5110.208
25  370       26   2017      5528.463
26  371       27   2017      1403.803
27  372       28   2017      2371.711
28  373       29   2017      5771.596
29  374       30   2017     14122.958
30  375       31   2017     28899.700
31  376       32   2017      1654.216
32  377       33   2017     12825.107
33  378       34   2017       213.482
34  379       35   2017       481.530
35  380       36   2017       389.181
36  381       37   2017      3185.328
37  382       38   2017     25488.323
38  383       39   2017      1413.414
39  384       40   2017       508.885
40  385       41   2017        77.042
41  386       42   2017     13412.752
42  387       43   2017       991.505
0   388        1   2018    252920.496
1   389        2   2018    281359.242
2   390        3   2018    200574.261
3   391        4   2018      6415.090
4   392        5   2018      4025.400
5   393        6   2018      7558.639
6   394        7   2018      2611.916
7   395        8   2018     55167.068
8   396        9   2018      1062.752
9   397       10   2018      2677.024
10  398       11   2018      4579.775
11  399       12   2018     23590.542
12  400       13   2018     49980.732
13  401       14   2018      1172.115
14  402       15   2018     24858.748
15  403       16   2018       435.130
16  404       17   2018       578.235
17  405       18   2018       281.978
18  406       19   2018       189.245
19  407       20   2018      2739.897
20  408       21   2018       168.708
21  409       22   2018      9833.606
22  410       23   2018      5897.163
23  411       24   2018     14610.025
24  412       25   2018      5127.780
25  413       26   2018      5578.372
26  414       27   2018      1404.191
27  415       28   2018      2309.114
28  416       29   2018      6017.380
29  417       30   2018     14049.871
30  418       31   2018     28438.746
31  419       32   2018      1705.052
32  420       33   2018     12601.582
33  421       34   2018       327.661
34  422       35   2018       482.130
35  423       36   2018       735.467
36  424       37   2018      3218.035
37  425       38   2018     26126.541
38  426       39   2018      1647.463
39  427       40   2018       508.617
40  428       41   2018        82.029
41  429       42   2018     13741.531
42  430       43   2018      1044.592

### 3.4. Création du fichier 'production_electricite_total_table.tsv"

In [122]:
#production_electricite_total.to_csv('production_electricite_total_table.tsv',index=False,header=['id','pays_id','annee','quantite_tep'], sep='\t')

# Bilans énergétiques complets

Description du dataset :

Le bilan énergétique permet aux utilisateurs de voir la quantité totale d'énergie extraite de l'environnement, échangée, transformée et utilisée par différents types d'utilisateurs finaux. Il permet d'avoir une vue complète de la situation énergétique d'un pays en Europe.

Source : https://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=nrg_bal_c&lang=fr

![image](capture_ecran/bilan_energetique.png)

In [123]:
data4 = pd.read_csv('data/nrg_bal_c_1.tsv',sep='[|\t]', engine='python', encoding = "ISO-8859-1")
data4

,"GEO,NRG_BAL,SIEC,UNIT\TIME",2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,"Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)","1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358"
1,"Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)","1.753.056,279","1.822.120,349","1.761.409,324","1.742.951,287","1.722.313,367","1.659.086,406","1.681.983,678","1.693.249,846","1.721.741,714","1.710.170,493"
2,"Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)","1.253.421,592","1.296.048,886","1.252.241,799","1.238.694,638","1.226.679,207","1.180.842,298","1.198.759,376","1.205.968,471","1.225.122,441","1.212.380,518"
3,"Belgique,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)","63.916,596","68.878,716","64.267,405","60.990,365","63.316,171","59.435,943","59.865,503","63.826,559","64.476,211","64.311,555"
4,"Bulgarie,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)","17.777,017","18.012,371","19.275,494","18.461,695","17.172,828","17.955,249","18.767,900","18.371,189","19.015,844","19.065,531"
...,...,...,...,...,...,...,...,...,...,...,...
15475,"Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,:,"2.517,239","2.633,845","2.808,311","2.909,440","2.819,491"
15476,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)","936,034","949,272","1.071,759","1.004,865","940,568","988,544","1.099,920","1.082,140","1.170,518","1.099,836"
15477,"Moldavie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)","104,754","1.783,504","1.820,975","1.737,504","1.750,940","1.705,874","1.739,195","1.789,511","1.847,253","1.961,166"
15478,"Ukraine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)","61.332,164","75.990,523","67.430,735","64.008,379","58.920,157","54.151,267","42.877,279","43.885,974","42.229,820","43.319,635"
15479,"Géorgie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796"

In [124]:
data4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15480 entries, 0 to 15479
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   GEO,NRG_BAL,SIEC,UNIT\TIME  15480 non-null  object
 1   2009                        15480 non-null  object
 2   2010                        15480 non-null  object
 3   2011                        15480 non-null  object
 4   2012                        15480 non-null  object
 5   2013                        15480 non-null  object
 6   2014                        15480 non-null  object
 7   2015                        15480 non-null  object
 8   2016                        15480 non-null  object
 9   2017                        15480 non-null  object
 10  2018                        15480 non-null  object
dtypes: object(11)
memory usage: 1.3+ MB

### Split de la colonne GEO,NRG_BAL,SIEC,UNIT\TIME

In [125]:
data4['GEO,NRG_BAL,SIEC,UNIT\\TIME']

0                                                                Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
1                                                                       Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
2                                                                       Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
3                                                                                                     Belgique,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
4                                                                                                     Bulgarie,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
                                                                                               ...
15475                                                               Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15476    Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15477                                                                         Moldavie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15478                                                                          Ukraine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15479                                                                          Géorgie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
Name: GEO,NRG_BAL,SIEC,UNIT\TIME, Length: 15480, dtype: object

In [126]:
text_columns4 = data4[['GEO,NRG_BAL,SIEC,UNIT\TIME']]
text_columns4

                                                                                                                                                             GEO,NRG_BAL,SIEC,UNIT\TIME
0                                                              Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
1                                                                     Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
2                                                                     Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
3                                                                                                   Belgique,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
4                                                                                                   Bulgarie,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
...                                                                                                                                                                                 ...
15475                                                             Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15476  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15477                                                                       Moldavie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15478                                                                        Ukraine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15479                                                                        Géorgie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)

[15480 rows x 1 columns]

==> Le nom du pays Allemagne est répété plusieurs fois dans ce dataframe car il y a tous les types de combustible répertoriés. Il faut donc utiliser les regex pour modifier la donnée.

In [127]:
text_columns4 = text_columns4.replace({'GEO,NRG_BAL,SIEC,UNIT\TIME': r'^Allemagne \((.*?)\)'},{'GEO,NRG_BAL,SIEC,UNIT\TIME': "Allemagne jusqu'en 1990 ancien territoire de la RFA"}, regex=True)
text_columns4

                                                                                                                                                             GEO,NRG_BAL,SIEC,UNIT\TIME
0                                                              Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
1                                                                     Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
2                                                                     Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
3                                                                                                   Belgique,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
4                                                                                                   Bulgarie,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
...                                                                                                                                                                                 ...
15475                                                             Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15476  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15477                                                                       Moldavie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15478                                                                        Ukraine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15479                                                                        Géorgie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)

[15480 rows x 1 columns]

In [128]:
text_columns4 = text_columns4.replace({'GEO,NRG_BAL,SIEC,UNIT\TIME': r'Énergie hydrocinétique, houlomotrice, marémotrice'},{'GEO,NRG_BAL,SIEC,UNIT\TIME': "Énergie hydrocinétique houlomotrice marémotrice"}, regex=True)
text_columns4

                                                                                                                                                             GEO,NRG_BAL,SIEC,UNIT\TIME
0                                                              Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
1                                                                     Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
2                                                                     Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
3                                                                                                   Belgique,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
4                                                                                                   Bulgarie,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
...                                                                                                                                                                                 ...
15475                                                             Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15476  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15477                                                                       Moldavie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15478                                                                        Ukraine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15479                                                                        Géorgie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)

[15480 rows x 1 columns]

In [129]:
text_columns4[['GEO', 'NRG_BAL','SIEC','UNIT\TIME']] = text_columns4['GEO,NRG_BAL,SIEC,UNIT\TIME'].str.split(pat=',',n=3,expand=True)
text_columns4

,"GEO,NRG_BAL,SIEC,UNIT\TIME",GEO,NRG_BAL,SIEC,UNIT\TIME
0,"Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
1,"Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)",Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
2,"Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)",Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
3,"Belgique,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)",Belgique,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
4,"Bulgarie,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)",Bulgarie,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)
...,...,...,...,...,...
15475,"Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)",Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15476,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15477,"Moldavie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)",Moldavie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15478,"Ukraine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)",Ukraine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)
15479,"Géorgie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)",Géorgie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)

==> Ici on ajoute les colonnes qui nous intérèssent dans un dataframe : le nom des pays (GEO), le type d'utilisateurs finaux (NRG_BAL) et le type de combustible (SIEC).

In [130]:
new_columns4 = text_columns4[['GEO', 'NRG_BAL', 'SIEC']]
new_columns4

,GEO,NRG_BAL,SIEC
0,Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total
1,Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total
2,Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total
3,Belgique,Énergie disponible brute,Total
4,Bulgarie,Énergie disponible brute,Total
...,...,...,...
15475,Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile
15476,Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile
15477,Moldavie,Disponible pour la consommation finale,Énergie fossile
15478,Ukraine,Disponible pour la consommation finale,Énergie fossile
15479,Géorgie,Disponible pour la consommation finale,Énergie fossile

In [131]:
df4 = pd.concat([data4, new_columns4], axis=1)
df4

,"GEO,NRG_BAL,SIEC,UNIT\TIME",2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO,NRG_BAL,SIEC
0,"Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)","1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total
1,"Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)","1.753.056,279","1.822.120,349","1.761.409,324","1.742.951,287","1.722.313,367","1.659.086,406","1.681.983,678","1.693.249,846","1.721.741,714","1.710.170,493",Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total
2,"Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)","1.253.421,592","1.296.048,886","1.252.241,799","1.238.694,638","1.226.679,207","1.180.842,298","1.198.759,376","1.205.968,471","1.225.122,441","1.212.380,518",Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total
3,"Belgique,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)","63.916,596","68.878,716","64.267,405","60.990,365","63.316,171","59.435,943","59.865,503","63.826,559","64.476,211","64.311,555",Belgique,Énergie disponible brute,Total
4,"Bulgarie,Énergie disponible brute,Total,Milliers de tonnes équivalent pétrole (TEP)","17.777,017","18.012,371","19.275,494","18.461,695","17.172,828","17.955,249","18.767,900","18.371,189","19.015,844","19.065,531",Bulgarie,Énergie disponible brute,Total
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,"Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,:,"2.517,239","2.633,845","2.808,311","2.909,440","2.819,491",Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile
15476,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)","936,034","949,272","1.071,759","1.004,865","940,568","988,544","1.099,920","1.082,140","1.170,518","1.099,836",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile
15477,"Moldavie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)","104,754","1.783,504","1.820,975","1.737,504","1.750,940","1.705,874","1.739,195","1.789,511","1.847,253","1.961,166",Moldavie,Disponible pour la consommation finale,Énergie fossile
15478,"Ukraine,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)","61.332,164","75.990,523","67.430,735","64.008,379","58.920,157","54.151,267","42.877,279","43.885,974","42.229,820","43.319,635",Ukraine,Disponible pour la consommation finale,Énergie fossile
15479,"Géorgie,Disponible pour la consommation finale,Énergie fossile,Milliers de tonnes équivalent pétrole (TEP)",:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",Géorgie,Disponible pour la consommation finale,Énergie fossile

In [132]:
df4 = df4.drop(columns=['GEO,NRG_BAL,SIEC,UNIT\TIME'])
df4

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO,NRG_BAL,SIEC
0,"1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total
1,"1.753.056,279","1.822.120,349","1.761.409,324","1.742.951,287","1.722.313,367","1.659.086,406","1.681.983,678","1.693.249,846","1.721.741,714","1.710.170,493",Union européenne - 28 pays (2013-2020),Énergie disponible brute,Total
2,"1.253.421,592","1.296.048,886","1.252.241,799","1.238.694,638","1.226.679,207","1.180.842,298","1.198.759,376","1.205.968,471","1.225.122,441","1.212.380,518",Zone euro - 19 pays (à partir de 2015),Énergie disponible brute,Total
3,"63.916,596","68.878,716","64.267,405","60.990,365","63.316,171","59.435,943","59.865,503","63.826,559","64.476,211","64.311,555",Belgique,Énergie disponible brute,Total
4,"17.777,017","18.012,371","19.275,494","18.461,695","17.172,828","17.955,249","18.767,900","18.371,189","19.015,844","19.065,531",Bulgarie,Énergie disponible brute,Total
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,:,:,:,:,:,"2.517,239","2.633,845","2.808,311","2.909,440","2.819,491",Bosnie-Herzégovine,Disponible pour la consommation finale,Énergie fossile
15476,"936,034","949,272","1.071,759","1.004,865","940,568","988,544","1.099,920","1.082,140","1.170,518","1.099,836",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Disponible pour la consommation finale,Énergie fossile
15477,"104,754","1.783,504","1.820,975","1.737,504","1.750,940","1.705,874","1.739,195","1.789,511","1.847,253","1.961,166",Moldavie,Disponible pour la consommation finale,Énergie fossile
15478,"61.332,164","75.990,523","67.430,735","64.008,379","58.920,157","54.151,267","42.877,279","43.885,974","42.229,820","43.319,635",Ukraine,Disponible pour la consommation finale,Énergie fossile
15479,:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",Géorgie,Disponible pour la consommation finale,Énergie fossile

==> Maintenant que nous avons récupéré le noms des pays, le type d'utilisateurs finaux, le type de combustible on vient faire une jointure avec le dataframe sur les codes geo (chaque nom de pays à un code qui lui est attribué). L'objectif est de venir ajouter une nouvelle colonne "pays_id" qui sera notre clé étrangère.

In [133]:
df_merge4_GEO = pd.merge(df4, code_pays, how ='inner', left_on='GEO', right_on= 'libelle')
df_merge4_GEO

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO,NRG_BAL,SIEC,id,code,libelle
0,"1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
1,"231.679,642","245.080,876","250.530,239","248.790,224","244.950,895","232.663,828","233.806,139","224.739,165","218.879,488","210.257,730",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Combustibles fossiles solides,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
2,"3.717,009","3.250,274","7.305,204","7.268,341","6.140,390","5.445,559","5.108,953","3.457,960","3.288,946","3.344,618",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Anthracite,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
3,"35.744,314","41.816,643","42.360,208","42.758,134","37.992,639","38.651,898","36.592,612","38.216,969","38.879,344","37.721,391",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Charbon à coke,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
4,"105.865,084","114.306,012","111.121,186","109.424,907","115.401,092","105.509,930","110.443,256","107.144,946","99.138,554","94.766,213",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Autre charbon bitumineux,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,:,:,:,:,"0,000","0,000","0,000","0,000","0,000","0,000",Géorgie,Disponible pour la consommation finale,Chaleur nucléaire,43,GE,Géorgie
15476,:,:,:,:,"780,241","841,474","851,742","901,740","963,758","1.026,423",Géorgie,Disponible pour la consommation finale,Électricité,43,GE,Géorgie
15477,:,:,:,:,"0,000","0,000","0,000","0,000","0,000","0,000",Géorgie,Disponible pour la consommation finale,Chaleur,43,GE,Géorgie
15478,:,:,:,:,"481,107","465,033","398,204","386,381","363,306","270,629",Géorgie,Disponible pour la consommation finale,Bioénergie,43,GE,Géorgie
15479,:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",Géorgie,Disponible pour la consommation finale,Énergie fossile,43,GE,Géorgie

In [134]:
df_merge4_GEO.loc[df_merge4_GEO['SIEC']== 'Énergie hydrocinétique houlomotrice marémotrice'].count()['SIEC']

215

==> On renomme la colonne "id" en "pays_id".

In [135]:
df_merge4_GEO = df_merge4_GEO.rename(columns={'id':'pays_id'})
df_merge4_GEO

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,GEO,NRG_BAL,SIEC,pays_id,code,libelle
0,"1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Total,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
1,"231.679,642","245.080,876","250.530,239","248.790,224","244.950,895","232.663,828","233.806,139","224.739,165","218.879,488","210.257,730",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Combustibles fossiles solides,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
2,"3.717,009","3.250,274","7.305,204","7.268,341","6.140,390","5.445,559","5.108,953","3.457,960","3.288,946","3.344,618",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Anthracite,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
3,"35.744,314","41.816,643","42.360,208","42.758,134","37.992,639","38.651,898","36.592,612","38.216,969","38.879,344","37.721,391",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Charbon à coke,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
4,"105.865,084","114.306,012","111.121,186","109.424,907","115.401,092","105.509,930","110.443,256","107.144,946","99.138,554","94.766,213",Union européenne - 27 pays (à partir de 2020),Énergie disponible brute,Autre charbon bitumineux,1,EU27_20,Union européenne - 27 pays (à partir de 2020)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,:,:,:,:,"0,000","0,000","0,000","0,000","0,000","0,000",Géorgie,Disponible pour la consommation finale,Chaleur nucléaire,43,GE,Géorgie
15476,:,:,:,:,"780,241","841,474","851,742","901,740","963,758","1.026,423",Géorgie,Disponible pour la consommation finale,Électricité,43,GE,Géorgie
15477,:,:,:,:,"0,000","0,000","0,000","0,000","0,000","0,000",Géorgie,Disponible pour la consommation finale,Chaleur,43,GE,Géorgie
15478,:,:,:,:,"481,107","465,033","398,204","386,381","363,306","270,629",Géorgie,Disponible pour la consommation finale,Bioénergie,43,GE,Géorgie
15479,:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",Géorgie,Disponible pour la consommation finale,Énergie fossile,43,GE,Géorgie

==> On supprime les colonnes qui ne nous sont plus utiles.

In [136]:
df_merge4_GEO = df_merge4_GEO.drop(columns=['libelle', 'GEO', 'code'])
df_merge4_GEO

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,NRG_BAL,SIEC,pays_id
0,"1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",Énergie disponible brute,Total,1
1,"231.679,642","245.080,876","250.530,239","248.790,224","244.950,895","232.663,828","233.806,139","224.739,165","218.879,488","210.257,730",Énergie disponible brute,Combustibles fossiles solides,1
2,"3.717,009","3.250,274","7.305,204","7.268,341","6.140,390","5.445,559","5.108,953","3.457,960","3.288,946","3.344,618",Énergie disponible brute,Anthracite,1
3,"35.744,314","41.816,643","42.360,208","42.758,134","37.992,639","38.651,898","36.592,612","38.216,969","38.879,344","37.721,391",Énergie disponible brute,Charbon à coke,1
4,"105.865,084","114.306,012","111.121,186","109.424,907","115.401,092","105.509,930","110.443,256","107.144,946","99.138,554","94.766,213",Énergie disponible brute,Autre charbon bitumineux,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,:,:,:,:,"0,000","0,000","0,000","0,000","0,000","0,000",Disponible pour la consommation finale,Chaleur nucléaire,43
15476,:,:,:,:,"780,241","841,474","851,742","901,740","963,758","1.026,423",Disponible pour la consommation finale,Électricité,43
15477,:,:,:,:,"0,000","0,000","0,000","0,000","0,000","0,000",Disponible pour la consommation finale,Chaleur,43
15478,:,:,:,:,"481,107","465,033","398,204","386,381","363,306","270,629",Disponible pour la consommation finale,Bioénergie,43
15479,:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",Disponible pour la consommation finale,Énergie fossile,43

==> On vient faire de nouveau une jointure mais cette fois-ci pour le code siec.

In [137]:
df_merge4_GEO_SIEC = pd.merge(df_merge4_GEO, code_siec, how ='inner', left_on='SIEC', right_on= 'libelle')
df_merge4_GEO_SIEC

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,NRG_BAL,SIEC,pays_id,code,libelle
0,"1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",Énergie disponible brute,Total,1,TOTAL,Total
1,"1.467.560,011","1.527.504,208","1.481.151,414","1.462.448,243","1.447.349,972","1.395.864,951","1.414.513,827","1.425.165,154","1.452.807,683","1.438.360,241",Approvisionnement énergétique total,Total,1,TOTAL,Total
2,"1.404.006,235","1.458.425,475","1.413.315,695","1.397.537,408","1.385.280,197","1.331.254,800","1.353.734,285","1.365.495,232","1.384.998,787","1.375.662,702",Consommation d'énergie primaire (Europe 2020-2030),Total,1,TOTAL,Total
3,"980.840,909","1.023.958,647","982.540,178","980.544,065","978.804,405","937.762,043","957.744,242","976.733,334","989.101,390","989.416,677",Consommation finale d'énergie (Europe 2020-2030),Total,1,TOTAL,Total
4,"1.031.170,431","1.073.251,018","1.032.947,087","1.019.282,970","1.020.883,310","977.699,997","993.931,112","1.013.083,910","1.039.297,143","1.035.451,395",Disponible pour la consommation finale,Total,1,TOTAL,Total
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,:,:,:,:,"3.037,951","3.307,001","3.615,383","3.716,343","3.751,800","3.738,677",Énergie disponible brute,Énergie fossile,43,FE,Énergie fossile
15476,:,:,:,:,"2.949,473","3.224,436","3.544,518","3.643,424","3.654,231","3.631,778",Approvisionnement énergétique total,Énergie fossile,43,FE,Énergie fossile
15477,:,:,:,:,: z,: z,: z,: z,: z,: z,Consommation d'énergie primaire (Europe 2020-2030),Énergie fossile,43,FE,Énergie fossile
15478,:,:,:,:,: z,: z,: z,: z,: z,: z,Consommation finale d'énergie (Europe 2020-2030),Énergie fossile,43,FE,Énergie fossile
15479,:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",Disponible pour la consommation finale,Énergie fossile,43,FE,Énergie fossile

In [138]:
import seaborn as sns

In [139]:
test = df_merge4_GEO_SIEC['code'].value_counts()
tto = pd.DataFrame(test)
tto.sort_index()

                    code
BIOE                 215
C0000X0350-0370      215
C0110                215
C0121                215
C0129                215
C0210                215
C0220                215
C0311                215
C0312                215
C0320                215
C0330                215
C0340                215
C0350                215
C0350-0370           215
C0360                215
C0371                215
C0379                215
E7000                215
FE                   215
G3000                215
H8000                215
N900H                215
O4000XBIO            215
O4100_TOT            215
O4200                215
O4300                215
O4400X4410           215
O4500                215
O4610                215
O4620                215
O4630                215
O4640                215
O4651                215
O4652XR5210B         215
O4653                215
O4661XR5230B         215
O4669                215
O4671XR5220B         215
O4680                215
O4691                215
O4692                215
O4693                215
O4694                215
O4695                215
O4699                215
P1000                215
P1100                215
P1200                215
R5110-5150_W6000RI   215
R5160                215
R5210B               215
R5210P               215
R5220B               215
R5220P               215
R5230B               215
R5230P               215
R5290                215
R5300                215
RA000                215
RA100                215
RA200                215
RA300                215
RA410                215
RA420                215
RA500                215
RA600                215
S2000                215
TOTAL                215
W6100                215
W6100_6220           215
W6210                215
W6220                215

==> On renomme la colonne "id" en "siec".

In [140]:
df_merge4_GEO_SIEC.rename(columns={'code':'siec'}, inplace=True)
df_merge4_GEO_SIEC

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,NRG_BAL,SIEC,pays_id,siec,libelle
0,"1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",Énergie disponible brute,Total,1,TOTAL,Total
1,"1.467.560,011","1.527.504,208","1.481.151,414","1.462.448,243","1.447.349,972","1.395.864,951","1.414.513,827","1.425.165,154","1.452.807,683","1.438.360,241",Approvisionnement énergétique total,Total,1,TOTAL,Total
2,"1.404.006,235","1.458.425,475","1.413.315,695","1.397.537,408","1.385.280,197","1.331.254,800","1.353.734,285","1.365.495,232","1.384.998,787","1.375.662,702",Consommation d'énergie primaire (Europe 2020-2030),Total,1,TOTAL,Total
3,"980.840,909","1.023.958,647","982.540,178","980.544,065","978.804,405","937.762,043","957.744,242","976.733,334","989.101,390","989.416,677",Consommation finale d'énergie (Europe 2020-2030),Total,1,TOTAL,Total
4,"1.031.170,431","1.073.251,018","1.032.947,087","1.019.282,970","1.020.883,310","977.699,997","993.931,112","1.013.083,910","1.039.297,143","1.035.451,395",Disponible pour la consommation finale,Total,1,TOTAL,Total
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,:,:,:,:,"3.037,951","3.307,001","3.615,383","3.716,343","3.751,800","3.738,677",Énergie disponible brute,Énergie fossile,43,FE,Énergie fossile
15476,:,:,:,:,"2.949,473","3.224,436","3.544,518","3.643,424","3.654,231","3.631,778",Approvisionnement énergétique total,Énergie fossile,43,FE,Énergie fossile
15477,:,:,:,:,: z,: z,: z,: z,: z,: z,Consommation d'énergie primaire (Europe 2020-2030),Énergie fossile,43,FE,Énergie fossile
15478,:,:,:,:,: z,: z,: z,: z,: z,: z,Consommation finale d'énergie (Europe 2020-2030),Énergie fossile,43,FE,Énergie fossile
15479,:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",Disponible pour la consommation finale,Énergie fossile,43,FE,Énergie fossile

==> On supprime les colonnes qui ne nous sont plus utiles.

In [141]:
df_merge4_GEO_SIEC = df_merge4_GEO_SIEC.drop(columns=['SIEC','libelle'])
df_merge4_GEO_SIEC

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,NRG_BAL,pays_id,siec
0,"1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",Énergie disponible brute,1,TOTAL
1,"1.467.560,011","1.527.504,208","1.481.151,414","1.462.448,243","1.447.349,972","1.395.864,951","1.414.513,827","1.425.165,154","1.452.807,683","1.438.360,241",Approvisionnement énergétique total,1,TOTAL
2,"1.404.006,235","1.458.425,475","1.413.315,695","1.397.537,408","1.385.280,197","1.331.254,800","1.353.734,285","1.365.495,232","1.384.998,787","1.375.662,702",Consommation d'énergie primaire (Europe 2020-2030),1,TOTAL
3,"980.840,909","1.023.958,647","982.540,178","980.544,065","978.804,405","937.762,043","957.744,242","976.733,334","989.101,390","989.416,677",Consommation finale d'énergie (Europe 2020-2030),1,TOTAL
4,"1.031.170,431","1.073.251,018","1.032.947,087","1.019.282,970","1.020.883,310","977.699,997","993.931,112","1.013.083,910","1.039.297,143","1.035.451,395",Disponible pour la consommation finale,1,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,:,:,:,:,"3.037,951","3.307,001","3.615,383","3.716,343","3.751,800","3.738,677",Énergie disponible brute,43,FE
15476,:,:,:,:,"2.949,473","3.224,436","3.544,518","3.643,424","3.654,231","3.631,778",Approvisionnement énergétique total,43,FE
15477,:,:,:,:,: z,: z,: z,: z,: z,: z,Consommation d'énergie primaire (Europe 2020-2030),43,FE
15478,:,:,:,:,: z,: z,: z,: z,: z,: z,Consommation finale d'énergie (Europe 2020-2030),43,FE
15479,:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",Disponible pour la consommation finale,43,FE

==> De nouveau on vient faire une jointure mais cette fois-ci pour le code nrg_bal.

In [142]:
df_merge4_final = pd.merge(df_merge4_GEO_SIEC, code_nrg, how ='inner', left_on='NRG_BAL', right_on= 'libelle')
df_merge4_final

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,NRG_BAL,pays_id,siec,code,libelle
0,"1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",Énergie disponible brute,1,TOTAL,GAE,Énergie disponible brute
1,"1.753.056,279","1.822.120,349","1.761.409,324","1.742.951,287","1.722.313,367","1.659.086,406","1.681.983,678","1.693.249,846","1.721.741,714","1.710.170,493",Énergie disponible brute,2,TOTAL,GAE,Énergie disponible brute
2,"1.253.421,592","1.296.048,886","1.252.241,799","1.238.694,638","1.226.679,207","1.180.842,298","1.198.759,376","1.205.968,471","1.225.122,441","1.212.380,518",Énergie disponible brute,3,TOTAL,GAE,Énergie disponible brute
3,"63.916,596","68.878,716","64.267,405","60.990,365","63.316,171","59.435,943","59.865,503","63.826,559","64.476,211","64.311,555",Énergie disponible brute,4,TOTAL,GAE,Énergie disponible brute
4,"17.777,017","18.012,371","19.275,494","18.461,695","17.172,828","17.955,249","18.767,900","18.371,189","19.015,844","19.065,531",Énergie disponible brute,5,TOTAL,GAE,Énergie disponible brute
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,:,:,:,:,:,"2.517,239","2.633,845","2.808,311","2.909,440","2.819,491",Disponible pour la consommation finale,39,FE,AFC,Disponible pour la consommation finale
15476,"936,034","949,272","1.071,759","1.004,865","940,568","988,544","1.099,920","1.082,140","1.170,518","1.099,836",Disponible pour la consommation finale,40,FE,AFC,Disponible pour la consommation finale
15477,"104,754","1.783,504","1.820,975","1.737,504","1.750,940","1.705,874","1.739,195","1.789,511","1.847,253","1.961,166",Disponible pour la consommation finale,41,FE,AFC,Disponible pour la consommation finale
15478,"61.332,164","75.990,523","67.430,735","64.008,379","58.920,157","54.151,267","42.877,279","43.885,974","42.229,820","43.319,635",Disponible pour la consommation finale,42,FE,AFC,Disponible pour la consommation finale
15479,:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",Disponible pour la consommation finale,43,FE,AFC,Disponible pour la consommation finale

==> On renomme la colonne "id" en "nrg_bal".

In [143]:
df_merge4_final.rename(columns={'code':'nrg_bal'}, inplace=True)
df_merge4_final

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,NRG_BAL,pays_id,siec,nrg_bal,libelle
0,"1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",Énergie disponible brute,1,TOTAL,GAE,Énergie disponible brute
1,"1.753.056,279","1.822.120,349","1.761.409,324","1.742.951,287","1.722.313,367","1.659.086,406","1.681.983,678","1.693.249,846","1.721.741,714","1.710.170,493",Énergie disponible brute,2,TOTAL,GAE,Énergie disponible brute
2,"1.253.421,592","1.296.048,886","1.252.241,799","1.238.694,638","1.226.679,207","1.180.842,298","1.198.759,376","1.205.968,471","1.225.122,441","1.212.380,518",Énergie disponible brute,3,TOTAL,GAE,Énergie disponible brute
3,"63.916,596","68.878,716","64.267,405","60.990,365","63.316,171","59.435,943","59.865,503","63.826,559","64.476,211","64.311,555",Énergie disponible brute,4,TOTAL,GAE,Énergie disponible brute
4,"17.777,017","18.012,371","19.275,494","18.461,695","17.172,828","17.955,249","18.767,900","18.371,189","19.015,844","19.065,531",Énergie disponible brute,5,TOTAL,GAE,Énergie disponible brute
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,:,:,:,:,:,"2.517,239","2.633,845","2.808,311","2.909,440","2.819,491",Disponible pour la consommation finale,39,FE,AFC,Disponible pour la consommation finale
15476,"936,034","949,272","1.071,759","1.004,865","940,568","988,544","1.099,920","1.082,140","1.170,518","1.099,836",Disponible pour la consommation finale,40,FE,AFC,Disponible pour la consommation finale
15477,"104,754","1.783,504","1.820,975","1.737,504","1.750,940","1.705,874","1.739,195","1.789,511","1.847,253","1.961,166",Disponible pour la consommation finale,41,FE,AFC,Disponible pour la consommation finale
15478,"61.332,164","75.990,523","67.430,735","64.008,379","58.920,157","54.151,267","42.877,279","43.885,974","42.229,820","43.319,635",Disponible pour la consommation finale,42,FE,AFC,Disponible pour la consommation finale
15479,:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",Disponible pour la consommation finale,43,FE,AFC,Disponible pour la consommation finale

==> On supprime les colonnes qui ne nous sont plus utiles.

In [144]:
df_merge4_final = df_merge4_final.drop(columns=['NRG_BAL','libelle'])
df_merge4_final

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,pays_id,siec,nrg_bal
0,"1.545.747,381","1.606.325,202","1.560.522,900","1.538.347,100","1.520.992,527","1.468.734,048","1.488.521,744","1.502.731,529","1.533.590,240","1.522.579,358",1,TOTAL,GAE
1,"1.753.056,279","1.822.120,349","1.761.409,324","1.742.951,287","1.722.313,367","1.659.086,406","1.681.983,678","1.693.249,846","1.721.741,714","1.710.170,493",2,TOTAL,GAE
2,"1.253.421,592","1.296.048,886","1.252.241,799","1.238.694,638","1.226.679,207","1.180.842,298","1.198.759,376","1.205.968,471","1.225.122,441","1.212.380,518",3,TOTAL,GAE
3,"63.916,596","68.878,716","64.267,405","60.990,365","63.316,171","59.435,943","59.865,503","63.826,559","64.476,211","64.311,555",4,TOTAL,GAE
4,"17.777,017","18.012,371","19.275,494","18.461,695","17.172,828","17.955,249","18.767,900","18.371,189","19.015,844","19.065,531",5,TOTAL,GAE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15475,:,:,:,:,:,"2.517,239","2.633,845","2.808,311","2.909,440","2.819,491",39,FE,AFC
15476,"936,034","949,272","1.071,759","1.004,865","940,568","988,544","1.099,920","1.082,140","1.170,518","1.099,836",40,FE,AFC
15477,"104,754","1.783,504","1.820,975","1.737,504","1.750,940","1.705,874","1.739,195","1.789,511","1.847,253","1.961,166",41,FE,AFC
15478,"61.332,164","75.990,523","67.430,735","64.008,379","58.920,157","54.151,267","42.877,279","43.885,974","42.229,820","43.319,635",42,FE,AFC
15479,:,:,:,:,"2.593,422","2.825,091","3.083,168","3.267,685","3.302,829","3.276,796",43,FE,AFC

### Transformation des colonnes "années" en lignes

In [145]:
df_merge4_final.columns

Index(['2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', 'pays_id', 'siec', 'nrg_bal'],
      dtype='object')

In [146]:
df_global4 = []
for i in range(2009,2019):
    df_i4 = df_merge4_final[[f'{i}', 'pays_id','siec','nrg_bal']]
    df_i4 .rename(columns={f'{i}':'quantite_tep'}, inplace=True)
    df_i4 ['annee'] = i
    df_global4.append(df_i4)
df_global4[0]

/home/camille/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
<ipython-input-146-0ab830c5ab21>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_i4 ['annee'] = i

        quantite_tep  pays_id   siec nrg_bal  annee
0      1.545.747,381        1  TOTAL    GAE    2009
1      1.753.056,279        2  TOTAL    GAE    2009
2      1.253.421,592        3  TOTAL    GAE    2009
3         63.916,596        4  TOTAL    GAE    2009
4         17.777,017        5  TOTAL    GAE    2009
...              ...      ...    ...     ...    ...
15475              :       39     FE    AFC    2009
15476        936,034       40     FE    AFC    2009
15477        104,754       41     FE    AFC    2009
15478     61.332,164       42     FE    AFC    2009
15479              :       43     FE    AFC    2009

[15480 rows x 5 columns]

In [147]:
len(df_global4)

10

In [148]:
frames = [ df_global4[i] for i in range(0,10) ]
bilan_energetique = pd.concat(frames)
bilan_energetique

        quantite_tep  pays_id   siec nrg_bal  annee
0      1.545.747,381        1  TOTAL    GAE    2009
1      1.753.056,279        2  TOTAL    GAE    2009
2      1.253.421,592        3  TOTAL    GAE    2009
3         63.916,596        4  TOTAL    GAE    2009
4         17.777,017        5  TOTAL    GAE    2009
...              ...      ...    ...     ...    ...
15475      2.819,491       39     FE    AFC    2018
15476      1.099,836       40     FE    AFC    2018
15477      1.961,166       41     FE    AFC    2018
15478     43.319,635       42     FE    AFC    2018
15479      3.276,796       43     FE    AFC    2018

[154800 rows x 5 columns]

### Nettoyage de la donnée

In [149]:
bilan_energetique = bilan_energetique.replace([': z', ':', '0,000'], '')
bilan_energetique

        quantite_tep  pays_id   siec nrg_bal  annee
0      1.545.747,381        1  TOTAL    GAE    2009
1      1.753.056,279        2  TOTAL    GAE    2009
2      1.253.421,592        3  TOTAL    GAE    2009
3         63.916,596        4  TOTAL    GAE    2009
4         17.777,017        5  TOTAL    GAE    2009
...              ...      ...    ...     ...    ...
15475      2.819,491       39     FE    AFC    2018
15476      1.099,836       40     FE    AFC    2018
15477      1.961,166       41     FE    AFC    2018
15478     43.319,635       42     FE    AFC    2018
15479      3.276,796       43     FE    AFC    2018

[154800 rows x 5 columns]

In [150]:
bilan_energetique ['quantite_tep'] = bilan_energetique ['quantite_tep'].apply(lambda x: x.replace('.', ''))
bilan_energetique

      quantite_tep  pays_id   siec nrg_bal  annee
0      1545747,381        1  TOTAL    GAE    2009
1      1753056,279        2  TOTAL    GAE    2009
2      1253421,592        3  TOTAL    GAE    2009
3        63916,596        4  TOTAL    GAE    2009
4        17777,017        5  TOTAL    GAE    2009
...            ...      ...    ...     ...    ...
15475     2819,491       39     FE    AFC    2018
15476     1099,836       40     FE    AFC    2018
15477     1961,166       41     FE    AFC    2018
15478    43319,635       42     FE    AFC    2018
15479     3276,796       43     FE    AFC    2018

[154800 rows x 5 columns]

In [151]:
bilan_energetique.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 154800 entries, 0 to 15479
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   quantite_tep  154800 non-null  object
 1   pays_id       154800 non-null  int64
 2   siec          154800 non-null  object
 3   nrg_bal       154800 non-null  object
 4   annee         154800 non-null  int64
dtypes: int64(2), object(3)
memory usage: 7.1+ MB

In [152]:
bilan_energetique['quantite_tep'] = bilan_energetique['quantite_tep'].apply(lambda x: x.replace(',', '.'))
bilan_energetique

      quantite_tep  pays_id   siec nrg_bal  annee
0      1545747.381        1  TOTAL    GAE    2009
1      1753056.279        2  TOTAL    GAE    2009
2      1253421.592        3  TOTAL    GAE    2009
3        63916.596        4  TOTAL    GAE    2009
4        17777.017        5  TOTAL    GAE    2009
...            ...      ...    ...     ...    ...
15475     2819.491       39     FE    AFC    2018
15476     1099.836       40     FE    AFC    2018
15477     1961.166       41     FE    AFC    2018
15478    43319.635       42     FE    AFC    2018
15479     3276.796       43     FE    AFC    2018

[154800 rows x 5 columns]

In [153]:
bilan_energetique["quantite_tep"] = pd.to_numeric(bilan_energetique['quantite_tep'])
bilan_energetique

       quantite_tep  pays_id   siec nrg_bal  annee
0       1545747.381        1  TOTAL    GAE    2009
1       1753056.279        2  TOTAL    GAE    2009
2       1253421.592        3  TOTAL    GAE    2009
3         63916.596        4  TOTAL    GAE    2009
4         17777.017        5  TOTAL    GAE    2009
...             ...      ...    ...     ...    ...
15475      2819.491       39     FE    AFC    2018
15476      1099.836       40     FE    AFC    2018
15477      1961.166       41     FE    AFC    2018
15478     43319.635       42     FE    AFC    2018
15479      3276.796       43     FE    AFC    2018

[154800 rows x 5 columns]

In [154]:
bilan_energetique.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 154800 entries, 0 to 15479
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   quantite_tep  50813 non-null   float64
 1   pays_id       154800 non-null  int64
 2   siec          154800 non-null  object
 3   nrg_bal       154800 non-null  object
 4   annee         154800 non-null  int64
dtypes: float64(1), int64(2), object(2)
memory usage: 7.1+ MB

In [155]:
bilan_energetique.insert(0, 'id', range(1, 1 + len(bilan_energetique)))
bilan_energetique

           id  quantite_tep  pays_id   siec nrg_bal  annee
0           1   1545747.381        1  TOTAL    GAE    2009
1           2   1753056.279        2  TOTAL    GAE    2009
2           3   1253421.592        3  TOTAL    GAE    2009
3           4     63916.596        4  TOTAL    GAE    2009
4           5     17777.017        5  TOTAL    GAE    2009
...       ...           ...      ...    ...     ...    ...
15475  154796      2819.491       39     FE    AFC    2018
15476  154797      1099.836       40     FE    AFC    2018
15477  154798      1961.166       41     FE    AFC    2018
15478  154799     43319.635       42     FE    AFC    2018
15479  154800      3276.796       43     FE    AFC    2018

[154800 rows x 6 columns]

In [156]:
bilan_energetique = bilan_energetique[['id','pays_id','siec','nrg_bal','annee','quantite_tep']]
bilan_energetique

           id  pays_id   siec nrg_bal  annee  quantite_tep
0           1        1  TOTAL    GAE    2009   1545747.381
1           2        2  TOTAL    GAE    2009   1753056.279
2           3        3  TOTAL    GAE    2009   1253421.592
3           4        4  TOTAL    GAE    2009     63916.596
4           5        5  TOTAL    GAE    2009     17777.017
...       ...      ...    ...     ...    ...           ...
15475  154796       39     FE    AFC    2018      2819.491
15476  154797       40     FE    AFC    2018      1099.836
15477  154798       41     FE    AFC    2018      1961.166
15478  154799       42     FE    AFC    2018     43319.635
15479  154800       43     FE    AFC    2018      3276.796

[154800 rows x 6 columns]

### Création du fichier 'bilan_energetique_table.tsv"

In [157]:
#bilan_energetique.to_csv('bilan_energetique_table.tsv',index=False,header=['id','pays_id','siec','nrg_bal','annee','quantite_tep'], sep='\t')

# Evolution de la population européenne

Fichier extrait du site Eurostat sur l'évolution de la population européenne de 1960 à 2020, au 1er janvier.

![image](capture_ecran/population.png)

In [158]:
data5 = pd.read_csv('data/demo_gind_1.tsv', sep='\t', encoding = "ISO-8859-1")
data5

,"GEO,INDIC_DE\TIME",1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,"Union européenne - 27 pays (à partir de 2020),Population au 1er janvier - totale",354.531.754,357.404.302,360.431.043,364.153.147,367.355.615,370.521.157,373.443.503,376.321.214,379.076.041,...,439.942.305 b,440.552.661 b,441.257.711,442.883.888 b,443.666.812 b,444.802.830,445.534.430 b,446.098.424 p,446.824.564 ep,447.706.209 ep
1,"Union européenne - 28 pays (2013-2020),Population au 1er janvier - totale",406.731.754,410.004.302,413.431.043,417.653.147,421.155.615,424.721.157,427.939.603,431.122.114,434.162.341,...,502.964.837 b,504.047.749 b,505.163.053,507.235.091 b,508.520.205 b,510.181.874,511.378.572 b,512.372.000 p,513.471.676 ep,:
2,"Union européenne - 27 pays (2007-2013),Population au 1er janvier - totale",402.604.332,405.851.363,409.249.398,413.441.369,416.916.043,420.454.977,423.643.938,426.796.378,429.810.712,...,498.674.980 b,499.771.765 b,500.900.913,502.988.282 b,504.294.889 b,505.991.205,507.224.359 b,508.266.507 p,509.395.430 ep,510.673.586 ep
3,"Zone euro - 19 pays (à partir de 2015),Population au 1er janvier - totale",263.140.292,265.392.392,267.691.048,270.714.128,273.072.410,275.430.651,277.770.462,279.854.101,281.656.968,...,334.572.589 b,335.288.924 b,336.044.966,337.764.352 b,338.562.121 b,339.787.987,340.541.142 b,341.145.721 p,341.902.187 ep,342.806.623 ep
4,"Zone euro - 18 pays (2014),Population au 1er janvier - totale",260.384.692,262.590.892,264.845.448,267.833.028,270.155.610,272.477.051,274.781.162,276.827.301,278.594.968,...,331.520.001 b,332.285.283 b,333.073.061,334.820.880 b,335.640.859 b,336.899.429,337.693.238 b,338.336.820 p,339.108.003 ep,340.012.533 ep
5,"Belgique,Population au 1er janvier - totale",9.128.824,9.178.154,9.189.741,9.251.414,9.328.126,9.428.100,9.499.234,9.556.380,9.605.601,...,11.000.638 b,11.075.889 b,11.137.974,11.180.840,11.237.274,11.311.117,11.351.727,11.398.589,11.455.519,11.549.888
6,"Bulgarie,Population au 1er janvier - totale",7.829.246,7.905.502,7.980.734,8.045.158,8.111.132,8.177.547,8.230.788,8.285.325,8.335.126,...,7.369.431,7.327.224,7.284.552,7.245.677,7.202.198,7.153.784,7.101.859,7.050.034,7.000.039,6.951.482
7,"Tchéquie,Population au 1er janvier - totale",9.637.840,9.566.172,9.607.129,9.642.191,9.699.179,9.756.429,9.802.287,9.839.792,9.866.006,...,10.486.731,10.505.445,10.516.125,10.512.419,10.538.275,10.553.843,10.578.820,10.610.055,10.649.800,10.693.939
8,"Danemark,Population au 1er janvier - totale",4.565.455,4.593.750,4.629.624,4.665.829,4.703.136,4.741.008,4.777.015,4.817.746,4.852.962,...,5.560.628,5.580.516,5.602.628,5.627.235,5.659.715,5.707.251,5.748.769,5.781.190,5.806.081,5.822.763
9,"Allemagne (jusqu'en 1990, ancien territoire de la RFA),Population au 1er janvier - totale",55.257.088,55.958.321,56.589.148,57.247.246,57.864.509,58.587.451,59.296.591,59.792.934,59.948.474,...,80.222.065 b,80.327.900,80.523.746,80.767.463,81.197.537,82.175.684,82.521.653,82.792.351,83.019.213,83.166.711
10,"Allemagne incluant l'ancienne RDA,Population au 1er janvier - totale",72.542.990,73.086.809,73.668.454,74.383.113,75.045.592,75.591.082,76.336.308,76.864.314,77.038.358,...,80.222.065 b,80.327.900,80.523.746,80.767.463,81.197.537,82.175.684,82.521.653,82.792.351,83.019.213,83.166.711
11,"Estonie,Population au 1er janvier - totale",1.206.362,1.216.712,1.233.441,1.249.804,1.267.910,1.286.262,1.302.870,1.314.323,1.323.569,...,1.329.660,1.325.217,1.320.174,1.315.819,1.314.870 b,1.315.944,1.315.635,1.319.133,1.324.820,1.328.976
12,"Irlande,Population au 1er janvier - totale",2.835.500,2.821.700,2.827.100,2.845.000,2.860.300,2.872.800,2.881.800,2.895.800,2.909.100,...,4.570.881,4.589.287,4.609.779,4.637.852,4.677.627,4.726.286,4.784.383,4.830.392,4.904.240 e,4.963.839 e
13,"Grèce,Population au 1er janvier - totale",8.300.399,8.363.050,8.433.050,8.463.416,8.495.834,8.525.024,8.575.642,8.651.660,8.716.516,...,11.123.392,11.086.406,11.003.615,10.926.807,10.858.018,10.783.748,10.768.193,10.741.165,10.724.599,10.709.739 ep
14,"Espagne,Population au 1er janvier - totale",30.327.000,30.583.000,30.895.500,31.151.231,31.442.070,31.776.320,32.132.264,32.434.123,32.931.771,...,46.667.174,46.818.219,46.727.890,46.512.199,46.449.565,46.440.099,46.528.024,46.658.447,46.937.060,47.329.981 p
15,"France,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,64.978.721,65.276.983,65.600.350,66.165.980 b,66.458.153,66.638.391,66.809.816,66.918.941 p,67.012.883 p,67.098.824 p
16,"France (métropolitaine),Population au 1er janvier - totale",45.464.797,45.903.656,46.422.000,47.573.406,48.059.029,48.561.800,48.953.792,49.373.537,49.723.072,...,63.070.344,63.375.971,63.697.865,:,:,:,:,:,:,:
17,"Croatie,Population au 1er janvier - totale",4.127.422,4.152.939,4.181.645,4.211.778,4.239.572,4.266.180,4.295.665,4.325.736,4.351.629,...,4.289.857,4.275.984,4.262.140,4.246.809,4.225.316,4.190.669,4.154.213,4.105.493,4.076.246,4.058.165
18,"Italie,Population au 1er janvier - totale",50.025.500,50.373.900,50.698.800,51.060.100,51.443.900,51.906.800,52.317.900,52.720.100,53.080.900,...,59.364.690,59.394.207,59.685.227,60.782.668,60.795.612,60.665.551,60.589.445,60.483.973,60.359.546 p,60.244.639 p
19,"Chypre,Population au 1er janvier - totale",572.000,573.566,575.900,578.900,585.500,588.400,593.200,597.100,601.800,...,839.751,862.011,865.878,858.000,847.008,848.319,854.802,864.236,875.899,888.005 p
20,"Lettonie,Population au 1er janvier - totale",2.104.128,2.137.830,2.167.531,2.195.640,2.226.198,2.255.048,2.276.789,2.289.645,2.312.795,...,2.074.605,2.044.813,2.023.825,2.001.468,1.986.096,1.968.957,1.950.116,1.934.379,1.919.968,1.907.675
21,"Lituanie,Population au 1er janvier - totale",2.755.600,2.801.500,2.845.600,2.881.100,2.916.800,2.953.600,2.989.300,3.026.800,3.062.000,...,3.052.588,3.003.641,2.971.905,2.943.472,2.921.262,2.888.558,2.847.904,2.808.901,2.794.184,2.794.090
22,"Luxembourg,Population au 1er janvier - totale",313.050,314.889,318.800,322.700,325.500,330.000,333.000,334.790,335.200,...,511.840,524.853 b,537.039,549.680,562.958,576.249,590.667 b,602.005,613.894,626.108
23,"Hongrie,Population au 1er janvier - totale",9.961.044,10.005.980,10.049.935,10.071.715,10.104.179,10.135.490,10.160.380,10.196.926,10.236.282,...,9.985.722,9.931.925 b,9.908.798,9.877.365,9.855.571,9.830.485,9.797.561,9.778.371,9.772.756,9.769.526
24,"Malte,Population au 1er janvier - totale",327.200,325.900,324.600,323.200,321.900,320.600,317.000,313.400,309.700,...,414.989,417.546,422.509,429.424,439.691,450.415,460.297,475.701,493.559,514.564
25,"Pays-Bas,Population au 1er janvier - totale",11.417.254,11.556.008,11.721.416,11.889.962,12.041.970,12.212.269,12.377.194,12.535.307,12.661.095,...,16.655.799,16.730.348,16.779.575,16.829.289,16.900.726,16.979.120,17.081.507,17.181.084,17.282.163,17.407.585
26,"Autriche,Population au 1er janvier - totale",7.030.385,7.064.693,7.107.904,7.151.824,7.199.798,7.247.804,7.293.973,7.350.159,7.403.837,...,8.375.164,8.408.121,8.451.860,8.507.786,8.584.926,8.700.471,8.772.865,8.822.267,8.858.775,8.901.064
27,"Pologne,Population au 1er janvier - totale",29.479.900,29.795.000,30.133.000,30.484.000,30.940.000,31.338.900,31.551.000,31.811.000,32.163.310,...,38.062.718,38.063.792,38.062.535,38.017.856,38.005.614,37.967.209,37.972.964,37.976.687,37.972.812,37.958.138
28,"Portugal,Population au 1er janvier - totale",8.826.040,8.889.392,8.969.240,9.018.730,9.041.980,9.028.750,8.968.440,8.893.540,8.855.500,...,10.572.721,10.542.398,10.487.289,10.427.301,10.374.822,10.341.330,10.309.573,10.291.027,10.276.617,10.295.909
29,"Roumanie,Population au 1er janvier - totale",18.319.210,18.494.600,18.615.900,18.737.200,18.858.500,18.979.752,19.083.400,19.347.500,19.720.984,...,20.199.059,20.095.996,20.020.074,19.947.311,19.870.647,19.760.585,19.643.949,19.530.631,19.414.458,19.317.984 p
30,"Slovénie,Population au 1er janvier - totale",1.580.535,1.588.904,1.599.357,1.607.941,1.626.000,1.638.227,1.660.092,1.679.717,1.699.339,...,2.050.189,2.055.496,2.058.821,2.061.085,2.062.874,2.064.188,2.065.895,2.066.880,2.080.908,2.095.861
31,"Slovaquie,Population au 1er janvier - totale",3.969.682,4.166.507,4.216.827,4.259.549,4.304.484,4.350.198,4.391.768,4.431.564,4.467.170,...,5.392.446,5.404.322,5.410.836,5.415.949,5.421.349,5.426.252,5.435.343,5.443.120,5.450.421,5.457.873
32,"Finlande,Population au 1er janvier - totale",4.413.046,4.446.222,4.475.787,4.507.098,4.539.519,4.557.567,4.569.896,4.591.842,4.619.645,...,5.375.276,5.401.267,5.426.674,5.451.270,5.471.753,5.487.308,5.503.297,5.513.130,5.517.919,5.525.292
33,"Suède,Population au 1er janvier - totale",7.471.345,7.497.967,7.542.028,7.581.148,7.627.507,7.695.200,7.772.506,7.843.088,7.892.774,...,9.415.570,9.482.855,9.555.893,9.644.864,9.747.355,9.851.017,9.995.153,10.120.242,10.230.185,10.327.589
34,"Royaume-Uni,Population au 1er janvier - totale",52.200.000,52.600.000,53.000.000,53.500.000,53.800.000,54.200.000,54.496.100,54.800.900,55.086.300,...,63.022.532,63.495.088,63.905.342,64.351.203,64.853.393,65.379.044,65.844.142,66.273.576,66.647.112,67.025.542 p
35,"Espace économique européen (EEE) (UE28 - 2013-2020 et IS, LI, NO),Population au 1er janvier - totale",410.489.590,413.792.993,417.253.762,421.507.905,425.041.422,428.639.503,431.890.552,435.107.549,438.183.835,...,508.239.743 b,509.389.669 b,510.573.023,512.705.861 b,514.053.164 b,515.762.746,517.013.048 b,518.054.183 p,519.195.257 ep,520.502.213 ep
36,"Espace économique européen (EEE) (UE27 - 2007-2013 et IS, LI, NO),Population au 1er janvier - totale",406.362.168,409.640.054,413.072.117,417.296.127,420.801.850,424.373.323,427.594.887,430.781.813,433.832.206,...,503.949.886 b,505.113.685 b,506.310.883,508.459.052 b,509.827.848 b,511.572.077,512.858.835 b,513.948.690 p,515.119.011 ep,516.444.048 ep
37,"Association Européenne de Libre Echange (AELE),Population au 1er janvier - totale",9.053.336,9.148.844,9.331.154,9.493.953,9.635.106,9.747.502,9.834.737,9.937.651,10.052.847,...,13.145.040 b,13.296.582,13.449.030,13.610.401,13.770.625,13.907.998,14.054.026,14.166.313,14.268.108,14.376.495 p
38,"Islande,Population au 1er janvier - totale",173.855,177.292,180.765,183.991,187.314,190.652,193.919,197.221,200.281,...,318.452,319.575,321.857,325.671,329.100,332.529,338.349,348.450,356.991,364.134
39,"Liechtenstein,Population au 1er janvier - totale",16.274,16.628,17.125,17.761,18.425,19.085,19.304,19.916,20.433,...,36.149,36.475,36.838,37.129,37.366,37.622,37.810,38.114,38.378,38.748 p
40,"Norvège,Population au 1er janvier - totale",3.567.707,3.594.771,3.624.829,3.653.006,3.680.068,3.708.609,3.737.726,3.768.298,3.800.780,...,4.920.305,4.985.870,5.051.275,5.107.970,5.166.493,5.210.721,5.258.317,5.295.619,5.328.212,5.367.580
41,"Suisse,Population au 1er janvier - totale",5.295.500,5.360.153,5.508.435,5.639.195,5.749.299,5.829.156,5.883.788,5.952.216,6.031.353,...,7.870.134 b,7.954.662,8.039.060,8.139.631,8.237.666,8.327.126,8.419.550,8.484.130,8.544.527,8.606.033
42,"Monténégro,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,619.850,620.308,620.893,621.521,622.099,622.218,622.387,622.359,622.182,621.873
43,"Macédoine du Nord,Population au 1er janvier - totale",1.384.451,1.399.403,1.417.200,1.438.342,1.461.522,1.486.469,1.512.988,1.538.694,1.562.211,...,2.057.284,2.059.794,2.062.294,2.065.769,2.069.172,2.071.278,2.073.702,2.075.301,2.077.132 e,2.076.255 e
44,"Albanie,Population au 1er janvier - totale",1.583.800,1.633.800,1.685.800,1.736.838,1.788.404,1.839.866,1.889.715,1.939.430,1.991.765,...,2.907.361,2.903.008,2.897.770,2.892.394,2.885.796,2.875.592,2.876.591,2.870.324,2.862.427,2.845.955
45,"Serbie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,7.251.549 b,7.216.649,7.181.505,7.146.759,7.114.393,7.076.372,7.040.272,7.001.444,6.963.764,6.926.705
46,"Turquie,Population au 1er janvier - totale",27.119.962,27.755.078,28.435.197,29.162.545,29.939.582,30.769.013,31.499.416,32.273.630,33.093.700,...,73.722.988,74.724.269,75.627.384,76.667.864,77.695.904,78.741.053,79.814.871,80.810.525,82.003.882,83.154.997
47,"Andorre,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,78.115 b,78.115,76.246,:,:,71.732,:,74.794 e,76.177 e,77.543 e
48,"Biélorussie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,9.481.193,9.465.150,9.463.840,9.468.154,9.480.868 e,9.498.364,9.504.704,9.491.823,9.427.348,9.408.350
49,"Bosnie-Herzégovine,Population au 1er janvier - totale",3.212.349,3.265.629,3.329.909,3.406.130,3.480.448,3.553.053,3.627.922,3.700.916,3.767.185,...,3.843.183,3.839.265,3.835.645,3.830.911,3.825.334,3.515.982,3.509.728,3.500.295,3.492.018 p,:
50,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Population au 1er janvier - totale",932.500,958.000,984.500,1.009.000,1.033.500,1.060.500,1.088.000,1.116.000,1.145.000,...,1.794.180 b,1.780.021 e,1.815.606 e,1.820.631 e,1.804.944 e,1.771.604 e,1.783.531 e,1.798.506 e,1.795.666,1.782.115 e
51,"Moldavie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,3.560.430,3.559.541,3.559.497,3.557.634,3.555.159,3.553.056,3.550.852,3.547.539,:,:
52,"Monaco,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,:,:,:,:,37.700 e,38.200,:,38.300,38.300 e,:
53,"Russie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,142.856.536,143.056.383,:,143.666.931,:,:,:,:,:,:
54,"Saint-Marin,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,31.863,33.376,33.562,32.520,32.789,33.005,33.196,34.453,34.590,34.735
55,"Ukraine,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,45.598.179,45.453.282,45.372.692,45.245.894,42.759.661 b,42.590.879,42.414.905,42.216.766,41.983.564 e,41.732.779 e
56,"Arménie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,3.262.650,3.274.285,3.026.878,:,3.010.598,2.998.577,2.986.151,2.972.732,2.965.269,2.959.694
57,"Azerbaïdjan,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,9.111.078,9.235.085,9.356.483,9.477.119,9.593.038,9.705.643,9.809.981,9.898.085,9.981.457,10.067.108
58,"Géorgie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,4.469.250,4.497.617,:,4.490.498,3.729.500 e,3.720.400,3.726.374,3.729.633,3.723.464,3.716.858

In [159]:
data5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 62 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   GEO,INDIC_DE\TIME  59 non-null     object
 1   1960               59 non-null     object
 2   1961               59 non-null     object
 3   1962               59 non-null     object
 4   1963               59 non-null     object
 5   1964               59 non-null     object
 6   1965               59 non-null     object
 7   1966               59 non-null     object
 8   1967               59 non-null     object
 9   1968               59 non-null     object
 10  1969               59 non-null     object
 11  1970               59 non-null     object
 12  1971               59 non-null     object
 13  1972               59 non-null     object
 14  1973               59 non-null     object
 15  1974               59 non-null     object
 16  1975               59 non-null     object
 17  1976               59 non-null     object
 18  1977               59 non-null     object
 19  1978               59 non-null     object
 20  1979               59 non-null     object
 21  1980               59 non-null     object
 22  1981               59 non-null     object
 23  1982               59 non-null     object
 24  1983               59 non-null     object
 25  1984               59 non-null     object
 26  1985               59 non-null     object
 27  1986               59 non-null     object
 28  1987               59 non-null     object
 29  1988               59 non-null     object
 30  1989               59 non-null     object
 31  1990               59 non-null     object
 32  1991               59 non-null     object
 33  1992               59 non-null     object
 34  1993               59 non-null     object
 35  1994               59 non-null     object
 36  1995               59 non-null     object
 37  1996               59 non-null     object
 38  1997               59 non-null     object
 39  1998               59 non-null     object
 40  1999               59 non-null     object
 41  2000               59 non-null     object
 42  2001               59 non-null     object
 43  2002               59 non-null     object
 44  2003               59 non-null     object
 45  2004               59 non-null     object
 46  2005               59 non-null     object
 47  2006               59 non-null     object
 48  2007               59 non-null     object
 49  2008               59 non-null     object
 50  2009               59 non-null     object
 51  2010               59 non-null     object
 52  2011               59 non-null     object
 53  2012               59 non-null     object
 54  2013               59 non-null     object
 55  2014               59 non-null     object
 56  2015               59 non-null     object
 57  2016               59 non-null     object
 58  2017               59 non-null     object
 59  2018               59 non-null     object
 60  2019               59 non-null     object
 61  2020               59 non-null     object
dtypes: object(62)
memory usage: 28.7+ KB

### Split de la colonne "GEO,INDIC_DE\TIME"

In [160]:
data5.columns.tolist()

['GEO,INDIC_DE\\TIME',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020']

In [161]:
data5['GEO,INDIC_DE\\TIME']

0                                     Union européenne - 27 pays (à partir de 2020),Population au 1er janvier - totale
1                                            Union européenne - 28 pays (2013-2020),Population au 1er janvier - totale
2                                            Union européenne - 27 pays (2007-2013),Population au 1er janvier - totale
3                                            Zone euro - 19 pays (à partir de 2015),Population au 1er janvier - totale
4                                                        Zone euro - 18 pays (2014),Population au 1er janvier - totale
5                                                                          Belgique,Population au 1er janvier - totale
6                                                                          Bulgarie,Population au 1er janvier - totale
7                                                                          Tchéquie,Population au 1er janvier - totale
8                                                                          Danemark,Population au 1er janvier - totale
9                            Allemagne (jusqu'en 1990, ancien territoire de la RFA),Population au 1er janvier - totale
10                                                Allemagne incluant l'ancienne RDA,Population au 1er janvier - totale
11                                                                          Estonie,Population au 1er janvier - totale
12                                                                          Irlande,Population au 1er janvier - totale
13                                                                            Grèce,Population au 1er janvier - totale
14                                                                          Espagne,Population au 1er janvier - totale
15                                                                           France,Population au 1er janvier - totale
16                                                          France (métropolitaine),Population au 1er janvier - totale
17                                                                          Croatie,Population au 1er janvier - totale
18                                                                           Italie,Population au 1er janvier - totale
19                                                                           Chypre,Population au 1er janvier - totale
20                                                                         Lettonie,Population au 1er janvier - totale
21                                                                         Lituanie,Population au 1er janvier - totale
22                                                                       Luxembourg,Population au 1er janvier - totale
23                                                                          Hongrie,Population au 1er janvier - totale
24                                                                            Malte,Population au 1er janvier - totale
25                                                                         Pays-Bas,Population au 1er janvier - totale
26                                                                         Autriche,Population au 1er janvier - totale
27                                                                          Pologne,Population au 1er janvier - totale
28                                                                         Portugal,Population au 1er janvier - totale
29                                                                         Roumanie,Population au 1er janvier - totale
30                                                                         Slovénie,Population au 1er janvier - totale
31                                                                        Slovaquie,Population au 1er janvier - totale
32                                                                         Finlande,Population au 1er janvier - totale
33                                                                            Suède,Population au 1er janvier - totale
34                                                                      Royaume-Uni,Population au 1er janvier - totale
35                Espace économique européen (EEE) (UE28 - 2013-2020 et IS, LI, NO),Population au 1er janvier - totale
36                Espace économique européen (EEE) (UE27 - 2007-2013 et IS, LI, NO),Population au 1er janvier - totale
37                                   Association Européenne de Libre Echange (AELE),Population au 1er janvier - totale
38                                                                          Islande,Population au 1er janvier - totale
39                                                                    Liechtenstein,Population au 1er janvier - totale
40                                                                          Norvège,Population au 1er janvier - totale
41                                                                           Suisse,Population au 1er janvier - totale
42                                                                       Monténégro,Population au 1er janvier - totale
43                                                                Macédoine du Nord,Population au 1er janvier - totale
44                                                                          Albanie,Population au 1er janvier - totale
45                                                                           Serbie,Population au 1er janvier - totale
46                                                                          Turquie,Population au 1er janvier - totale
47                                                                          Andorre,Population au 1er janvier - totale
48                                                                      Biélorussie,Population au 1er janvier - totale
49                                                               Bosnie-Herzégovine,Population au 1er janvier - totale
50    Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Population au 1er janvier - totale
51                                                                         Moldavie,Population au 1er janvier - totale
52                                                                           Monaco,Population au 1er janvier - totale
53                                                                           Russie,Population au 1er janvier - totale
54                                                                      Saint-Marin,Population au 1er janvier - totale
55                                                                          Ukraine,Population au 1er janvier - totale
56                                                                          Arménie,Population au 1er janvier - totale
57                                                                      Azerbaïdjan,Population au 1er janvier - totale
58                                                                          Géorgie,Population au 1er janvier - totale
Name: GEO,INDIC_DE\TIME, dtype: object

In [162]:
text_columns5 = data5[['GEO,INDIC_DE\\TIME']]
text_columns5

                                                                                                   GEO,INDIC_DE\TIME
0                                   Union européenne - 27 pays (à partir de 2020),Population au 1er janvier - totale
1                                          Union européenne - 28 pays (2013-2020),Population au 1er janvier - totale
2                                          Union européenne - 27 pays (2007-2013),Population au 1er janvier - totale
3                                          Zone euro - 19 pays (à partir de 2015),Population au 1er janvier - totale
4                                                      Zone euro - 18 pays (2014),Population au 1er janvier - totale
5                                                                        Belgique,Population au 1er janvier - totale
6                                                                        Bulgarie,Population au 1er janvier - totale
7                                                                        Tchéquie,Population au 1er janvier - totale
8                                                                        Danemark,Population au 1er janvier - totale
9                          Allemagne (jusqu'en 1990, ancien territoire de la RFA),Population au 1er janvier - totale
10                                              Allemagne incluant l'ancienne RDA,Population au 1er janvier - totale
11                                                                        Estonie,Population au 1er janvier - totale
12                                                                        Irlande,Population au 1er janvier - totale
13                                                                          Grèce,Population au 1er janvier - totale
14                                                                        Espagne,Population au 1er janvier - totale
15                                                                         France,Population au 1er janvier - totale
16                                                        France (métropolitaine),Population au 1er janvier - totale
17                                                                        Croatie,Population au 1er janvier - totale
18                                                                         Italie,Population au 1er janvier - totale
19                                                                         Chypre,Population au 1er janvier - totale
20                                                                       Lettonie,Population au 1er janvier - totale
21                                                                       Lituanie,Population au 1er janvier - totale
22                                                                     Luxembourg,Population au 1er janvier - totale
23                                                                        Hongrie,Population au 1er janvier - totale
24                                                                          Malte,Population au 1er janvier - totale
25                                                                       Pays-Bas,Population au 1er janvier - totale
26                                                                       Autriche,Population au 1er janvier - totale
27                                                                        Pologne,Population au 1er janvier - totale
28                                                                       Portugal,Population au 1er janvier - totale
29                                                                       Roumanie,Population au 1er janvier - totale
30                                                                       Slovénie,Population au 1er janvier - totale
31                                                                      Slovaquie,Population au 1er janvier - totale
32                                                                       Finlande,Population au 1er janvier - totale
33                                                                          Suède,Population au 1er janvier - totale
34                                                                    Royaume-Uni,Population au 1er janvier - totale
35              Espace économique européen (EEE) (UE28 - 2013-2020 et IS, LI, NO),Population au 1er janvier - totale
36              Espace économique européen (EEE) (UE27 - 2007-2013 et IS, LI, NO),Population au 1er janvier - totale
37                                 Association Européenne de Libre Echange (AELE),Population au 1er janvier - totale
38                                                                        Islande,Population au 1er janvier - totale
39                                                                  Liechtenstein,Population au 1er janvier - totale
40                                                                        Norvège,Population au 1er janvier - totale
41                                                                         Suisse,Population au 1er janvier - totale
42                                                                     Monténégro,Population au 1er janvier - totale
43                                                              Macédoine du Nord,Population au 1er janvier - totale
44                                                                        Albanie,Population au 1er janvier - totale
45                                                                         Serbie,Population au 1er janvier - totale
46                                                                        Turquie,Population au 1er janvier - totale
47                                                                        Andorre,Population au 1er janvier - totale
48                                                                    Biélorussie,Population au 1er janvier - totale
49                                                             Bosnie-Herzégovine,Population au 1er janvier - totale
50  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Population au 1er janvier - totale
51                                                                       Moldavie,Population au 1er janvier - totale
52                                                                         Monaco,Population au 1er janvier - totale
53                                                                         Russie,Population au 1er janvier - totale
54                                                                    Saint-Marin,Population au 1er janvier - totale
55                                                                        Ukraine,Population au 1er janvier - totale
56                                                                        Arménie,Population au 1er janvier - totale
57                                                                    Azerbaïdjan,Population au 1er janvier - totale
58                                                                        Géorgie,Population au 1er janvier - totale

In [163]:
text_columns5.columns

Index(['GEO,INDIC_DE\TIME'], dtype='object')

In [164]:
text_columns5 = text_columns5.replace("Allemagne (jusqu'en 1990, ancien territoire de la RFA),Population au 1er janvier - totale","Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale")
text_columns5

                                                                                                   GEO,INDIC_DE\TIME
0                                   Union européenne - 27 pays (à partir de 2020),Population au 1er janvier - totale
1                                          Union européenne - 28 pays (2013-2020),Population au 1er janvier - totale
2                                          Union européenne - 27 pays (2007-2013),Population au 1er janvier - totale
3                                          Zone euro - 19 pays (à partir de 2015),Population au 1er janvier - totale
4                                                      Zone euro - 18 pays (2014),Population au 1er janvier - totale
5                                                                        Belgique,Population au 1er janvier - totale
6                                                                        Bulgarie,Population au 1er janvier - totale
7                                                                        Tchéquie,Population au 1er janvier - totale
8                                                                        Danemark,Population au 1er janvier - totale
9                             Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale
10                                              Allemagne incluant l'ancienne RDA,Population au 1er janvier - totale
11                                                                        Estonie,Population au 1er janvier - totale
12                                                                        Irlande,Population au 1er janvier - totale
13                                                                          Grèce,Population au 1er janvier - totale
14                                                                        Espagne,Population au 1er janvier - totale
15                                                                         France,Population au 1er janvier - totale
16                                                        France (métropolitaine),Population au 1er janvier - totale
17                                                                        Croatie,Population au 1er janvier - totale
18                                                                         Italie,Population au 1er janvier - totale
19                                                                         Chypre,Population au 1er janvier - totale
20                                                                       Lettonie,Population au 1er janvier - totale
21                                                                       Lituanie,Population au 1er janvier - totale
22                                                                     Luxembourg,Population au 1er janvier - totale
23                                                                        Hongrie,Population au 1er janvier - totale
24                                                                          Malte,Population au 1er janvier - totale
25                                                                       Pays-Bas,Population au 1er janvier - totale
26                                                                       Autriche,Population au 1er janvier - totale
27                                                                        Pologne,Population au 1er janvier - totale
28                                                                       Portugal,Population au 1er janvier - totale
29                                                                       Roumanie,Population au 1er janvier - totale
30                                                                       Slovénie,Population au 1er janvier - totale
31                                                                      Slovaquie,Population au 1er janvier - totale
32                                                                       Finlande,Population au 1er janvier - totale
33                                                                          Suède,Population au 1er janvier - totale
34                                                                    Royaume-Uni,Population au 1er janvier - totale
35              Espace économique européen (EEE) (UE28 - 2013-2020 et IS, LI, NO),Population au 1er janvier - totale
36              Espace économique européen (EEE) (UE27 - 2007-2013 et IS, LI, NO),Population au 1er janvier - totale
37                                 Association Européenne de Libre Echange (AELE),Population au 1er janvier - totale
38                                                                        Islande,Population au 1er janvier - totale
39                                                                  Liechtenstein,Population au 1er janvier - totale
40                                                                        Norvège,Population au 1er janvier - totale
41                                                                         Suisse,Population au 1er janvier - totale
42                                                                     Monténégro,Population au 1er janvier - totale
43                                                              Macédoine du Nord,Population au 1er janvier - totale
44                                                                        Albanie,Population au 1er janvier - totale
45                                                                         Serbie,Population au 1er janvier - totale
46                                                                        Turquie,Population au 1er janvier - totale
47                                                                        Andorre,Population au 1er janvier - totale
48                                                                    Biélorussie,Population au 1er janvier - totale
49                                                             Bosnie-Herzégovine,Population au 1er janvier - totale
50  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Population au 1er janvier - totale
51                                                                       Moldavie,Population au 1er janvier - totale
52                                                                         Monaco,Population au 1er janvier - totale
53                                                                         Russie,Population au 1er janvier - totale
54                                                                    Saint-Marin,Population au 1er janvier - totale
55                                                                        Ukraine,Population au 1er janvier - totale
56                                                                        Arménie,Population au 1er janvier - totale
57                                                                    Azerbaïdjan,Population au 1er janvier - totale
58                                                                        Géorgie,Population au 1er janvier - totale

In [165]:
text_columns5[['GEO','INDIC_DE\TIME']] = text_columns5['GEO,INDIC_DE\TIME'].str.split(pat=',',n=1,expand=True)
text_columns5

,"GEO,INDIC_DE\TIME",GEO,INDIC_DE\TIME
0,"Union européenne - 27 pays (à partir de 2020),Population au 1er janvier - totale",Union européenne - 27 pays (à partir de 2020),Population au 1er janvier - totale
1,"Union européenne - 28 pays (2013-2020),Population au 1er janvier - totale",Union européenne - 28 pays (2013-2020),Population au 1er janvier - totale
2,"Union européenne - 27 pays (2007-2013),Population au 1er janvier - totale",Union européenne - 27 pays (2007-2013),Population au 1er janvier - totale
3,"Zone euro - 19 pays (à partir de 2015),Population au 1er janvier - totale",Zone euro - 19 pays (à partir de 2015),Population au 1er janvier - totale
4,"Zone euro - 18 pays (2014),Population au 1er janvier - totale",Zone euro - 18 pays (2014),Population au 1er janvier - totale
5,"Belgique,Population au 1er janvier - totale",Belgique,Population au 1er janvier - totale
6,"Bulgarie,Population au 1er janvier - totale",Bulgarie,Population au 1er janvier - totale
7,"Tchéquie,Population au 1er janvier - totale",Tchéquie,Population au 1er janvier - totale
8,"Danemark,Population au 1er janvier - totale",Danemark,Population au 1er janvier - totale
9,"Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale",Allemagne jusqu'en 1990 ancien territoire de la RFA,Population au 1er janvier - totale
10,"Allemagne incluant l'ancienne RDA,Population au 1er janvier - totale",Allemagne incluant l'ancienne RDA,Population au 1er janvier - totale
11,"Estonie,Population au 1er janvier - totale",Estonie,Population au 1er janvier - totale
12,"Irlande,Population au 1er janvier - totale",Irlande,Population au 1er janvier - totale
13,"Grèce,Population au 1er janvier - totale",Grèce,Population au 1er janvier - totale
14,"Espagne,Population au 1er janvier - totale",Espagne,Population au 1er janvier - totale
15,"France,Population au 1er janvier - totale",France,Population au 1er janvier - totale
16,"France (métropolitaine),Population au 1er janvier - totale",France (métropolitaine),Population au 1er janvier - totale
17,"Croatie,Population au 1er janvier - totale",Croatie,Population au 1er janvier - totale
18,"Italie,Population au 1er janvier - totale",Italie,Population au 1er janvier - totale
19,"Chypre,Population au 1er janvier - totale",Chypre,Population au 1er janvier - totale
20,"Lettonie,Population au 1er janvier - totale",Lettonie,Population au 1er janvier - totale
21,"Lituanie,Population au 1er janvier - totale",Lituanie,Population au 1er janvier - totale
22,"Luxembourg,Population au 1er janvier - totale",Luxembourg,Population au 1er janvier - totale
23,"Hongrie,Population au 1er janvier - totale",Hongrie,Population au 1er janvier - totale
24,"Malte,Population au 1er janvier - totale",Malte,Population au 1er janvier - totale
25,"Pays-Bas,Population au 1er janvier - totale",Pays-Bas,Population au 1er janvier - totale
26,"Autriche,Population au 1er janvier - totale",Autriche,Population au 1er janvier - totale
27,"Pologne,Population au 1er janvier - totale",Pologne,Population au 1er janvier - totale
28,"Portugal,Population au 1er janvier - totale",Portugal,Population au 1er janvier - totale
29,"Roumanie,Population au 1er janvier - totale",Roumanie,Population au 1er janvier - totale
30,"Slovénie,Population au 1er janvier - totale",Slovénie,Population au 1er janvier - totale
31,"Slovaquie,Population au 1er janvier - totale",Slovaquie,Population au 1er janvier - totale
32,"Finlande,Population au 1er janvier - totale",Finlande,Population au 1er janvier - totale
33,"Suède,Population au 1er janvier - totale",Suède,Population au 1er janvier - totale
34,"Royaume-Uni,Population au 1er janvier - totale",Royaume-Uni,Population au 1er janvier - totale
35,"Espace économique européen (EEE) (UE28 - 2013-2020 et IS, LI, NO),Population au 1er janvier - totale",Espace économique européen (EEE) (UE28 - 2013-2020 et IS,"LI, NO),Population au 1er janvier - totale"
36,"Espace économique européen (EEE) (UE27 - 2007-2013 et IS, LI, NO),Population au 1er janvier - totale",Espace économique européen (EEE) (UE27 - 2007-2013 et IS,"LI, NO),Population au 1er janvier - totale"
37,"Association Européenne de Libre Echange (AELE),Population au 1er janvier - totale",Association Européenne de Libre Echange (AELE),Population au 1er janvier - totale
38,"Islande,Population au 1er janvier - totale",Islande,Population au 1er janvier - totale
39,"Liechtenstein,Population au 1er janvier - totale",Liechtenstein,Population au 1er janvier - totale
40,"Norvège,Population au 1er janvier - totale",Norvège,Population au 1er janvier - totale
41,"Suisse,Population au 1er janvier - totale",Suisse,Population au 1er janvier - totale
42,"Monténégro,Population au 1er janvier - totale",Monténégro,Population au 1er janvier - totale
43,"Macédoine du Nord,Population au 1er janvier - totale",Macédoine du Nord,Population au 1er janvier - totale
44,"Albanie,Population au 1er janvier - totale",Albanie,Population au 1er janvier - totale
45,"Serbie,Population au 1er janvier - totale",Serbie,Population au 1er janvier - totale
46,"Turquie,Population au 1er janvier - totale",Turquie,Population au 1er janvier - totale
47,"Andorre,Population au 1er janvier - totale",Andorre,Population au 1er janvier - totale
48,"Biélorussie,Population au 1er janvier - totale",Biélorussie,Population au 1er janvier - totale
49,"Bosnie-Herzégovine,Population au 1er janvier - totale",Bosnie-Herzégovine,Population au 1er janvier - totale
50,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Population au 1er janvier - totale",Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Population au 1er janvier - totale
51,"Moldavie,Population au 1er janvier - totale",Moldavie,Population au 1er janvier - totale
52,"Monaco,Population au 1er janvier - totale",Monaco,Population au 1er janvier - totale
53,"Russie,Population au 1er janvier - totale",Russie,Population au 1er janvier - totale
54,"Saint-Marin,Population au 1er janvier - totale",Saint-Marin,Population au 1er janvier - totale
55,"Ukraine,Population au 1er janvier - totale",Ukraine,Population au 1er janvier - totale
56,"Arménie,Population au 1er janvier - totale",Arménie,Population au 1er janvier - totale
57,"Azerbaïdjan,Population au 1er janvier - totale",Azerbaïdjan,Population au 1er janvier - totale
58,"Géorgie,Population au 1er janvier - totale",Géorgie,Population au 1er janvier - totale

In [166]:
new_column5 = text_columns5[['GEO']]
new_column5

                                                                              GEO
0                                   Union européenne - 27 pays (à partir de 2020)
1                                          Union européenne - 28 pays (2013-2020)
2                                          Union européenne - 27 pays (2007-2013)
3                                          Zone euro - 19 pays (à partir de 2015)
4                                                      Zone euro - 18 pays (2014)
5                                                                        Belgique
6                                                                        Bulgarie
7                                                                        Tchéquie
8                                                                        Danemark
9                             Allemagne jusqu'en 1990 ancien territoire de la RFA
10                                              Allemagne incluant l'ancienne RDA
11                                                                        Estonie
12                                                                        Irlande
13                                                                          Grèce
14                                                                        Espagne
15                                                                         France
16                                                        France (métropolitaine)
17                                                                        Croatie
18                                                                         Italie
19                                                                         Chypre
20                                                                       Lettonie
21                                                                       Lituanie
22                                                                     Luxembourg
23                                                                        Hongrie
24                                                                          Malte
25                                                                       Pays-Bas
26                                                                       Autriche
27                                                                        Pologne
28                                                                       Portugal
29                                                                       Roumanie
30                                                                       Slovénie
31                                                                      Slovaquie
32                                                                       Finlande
33                                                                          Suède
34                                                                    Royaume-Uni
35                       Espace économique européen (EEE) (UE28 - 2013-2020 et IS
36                       Espace économique européen (EEE) (UE27 - 2007-2013 et IS
37                                 Association Européenne de Libre Echange (AELE)
38                                                                        Islande
39                                                                  Liechtenstein
40                                                                        Norvège
41                                                                         Suisse
42                                                                     Monténégro
43                                                              Macédoine du Nord
44                                                                        Albanie
45                                                                         Serbie
46                                                                        Turquie
47                                                                        Andorre
48                                                                    Biélorussie
49                                                             Bosnie-Herzégovine
50  Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
51                                                                       Moldavie
52                                                                         Monaco
53                                                                         Russie
54                                                                    Saint-Marin
55                                                                        Ukraine
56                                                                        Arménie
57                                                                    Azerbaïdjan
58                                                                        Géorgie

In [167]:
df5 = pd.concat([data5, new_column5], axis=1)
df5

,"GEO,INDIC_DE\TIME",1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,GEO
0,"Union européenne - 27 pays (à partir de 2020),Population au 1er janvier - totale",354.531.754,357.404.302,360.431.043,364.153.147,367.355.615,370.521.157,373.443.503,376.321.214,379.076.041,...,440.552.661 b,441.257.711,442.883.888 b,443.666.812 b,444.802.830,445.534.430 b,446.098.424 p,446.824.564 ep,447.706.209 ep,Union européenne - 27 pays (à partir de 2020)
1,"Union européenne - 28 pays (2013-2020),Population au 1er janvier - totale",406.731.754,410.004.302,413.431.043,417.653.147,421.155.615,424.721.157,427.939.603,431.122.114,434.162.341,...,504.047.749 b,505.163.053,507.235.091 b,508.520.205 b,510.181.874,511.378.572 b,512.372.000 p,513.471.676 ep,:,Union européenne - 28 pays (2013-2020)
2,"Union européenne - 27 pays (2007-2013),Population au 1er janvier - totale",402.604.332,405.851.363,409.249.398,413.441.369,416.916.043,420.454.977,423.643.938,426.796.378,429.810.712,...,499.771.765 b,500.900.913,502.988.282 b,504.294.889 b,505.991.205,507.224.359 b,508.266.507 p,509.395.430 ep,510.673.586 ep,Union européenne - 27 pays (2007-2013)
3,"Zone euro - 19 pays (à partir de 2015),Population au 1er janvier - totale",263.140.292,265.392.392,267.691.048,270.714.128,273.072.410,275.430.651,277.770.462,279.854.101,281.656.968,...,335.288.924 b,336.044.966,337.764.352 b,338.562.121 b,339.787.987,340.541.142 b,341.145.721 p,341.902.187 ep,342.806.623 ep,Zone euro - 19 pays (à partir de 2015)
4,"Zone euro - 18 pays (2014),Population au 1er janvier - totale",260.384.692,262.590.892,264.845.448,267.833.028,270.155.610,272.477.051,274.781.162,276.827.301,278.594.968,...,332.285.283 b,333.073.061,334.820.880 b,335.640.859 b,336.899.429,337.693.238 b,338.336.820 p,339.108.003 ep,340.012.533 ep,Zone euro - 18 pays (2014)
5,"Belgique,Population au 1er janvier - totale",9.128.824,9.178.154,9.189.741,9.251.414,9.328.126,9.428.100,9.499.234,9.556.380,9.605.601,...,11.075.889 b,11.137.974,11.180.840,11.237.274,11.311.117,11.351.727,11.398.589,11.455.519,11.549.888,Belgique
6,"Bulgarie,Population au 1er janvier - totale",7.829.246,7.905.502,7.980.734,8.045.158,8.111.132,8.177.547,8.230.788,8.285.325,8.335.126,...,7.327.224,7.284.552,7.245.677,7.202.198,7.153.784,7.101.859,7.050.034,7.000.039,6.951.482,Bulgarie
7,"Tchéquie,Population au 1er janvier - totale",9.637.840,9.566.172,9.607.129,9.642.191,9.699.179,9.756.429,9.802.287,9.839.792,9.866.006,...,10.505.445,10.516.125,10.512.419,10.538.275,10.553.843,10.578.820,10.610.055,10.649.800,10.693.939,Tchéquie
8,"Danemark,Population au 1er janvier - totale",4.565.455,4.593.750,4.629.624,4.665.829,4.703.136,4.741.008,4.777.015,4.817.746,4.852.962,...,5.580.516,5.602.628,5.627.235,5.659.715,5.707.251,5.748.769,5.781.190,5.806.081,5.822.763,Danemark
9,"Allemagne (jusqu'en 1990, ancien territoire de la RFA),Population au 1er janvier - totale",55.257.088,55.958.321,56.589.148,57.247.246,57.864.509,58.587.451,59.296.591,59.792.934,59.948.474,...,80.327.900,80.523.746,80.767.463,81.197.537,82.175.684,82.521.653,82.792.351,83.019.213,83.166.711,Allemagne jusqu'en 1990 ancien territoire de la RFA
10,"Allemagne incluant l'ancienne RDA,Population au 1er janvier - totale",72.542.990,73.086.809,73.668.454,74.383.113,75.045.592,75.591.082,76.336.308,76.864.314,77.038.358,...,80.327.900,80.523.746,80.767.463,81.197.537,82.175.684,82.521.653,82.792.351,83.019.213,83.166.711,Allemagne incluant l'ancienne RDA
11,"Estonie,Population au 1er janvier - totale",1.206.362,1.216.712,1.233.441,1.249.804,1.267.910,1.286.262,1.302.870,1.314.323,1.323.569,...,1.325.217,1.320.174,1.315.819,1.314.870 b,1.315.944,1.315.635,1.319.133,1.324.820,1.328.976,Estonie
12,"Irlande,Population au 1er janvier - totale",2.835.500,2.821.700,2.827.100,2.845.000,2.860.300,2.872.800,2.881.800,2.895.800,2.909.100,...,4.589.287,4.609.779,4.637.852,4.677.627,4.726.286,4.784.383,4.830.392,4.904.240 e,4.963.839 e,Irlande
13,"Grèce,Population au 1er janvier - totale",8.300.399,8.363.050,8.433.050,8.463.416,8.495.834,8.525.024,8.575.642,8.651.660,8.716.516,...,11.086.406,11.003.615,10.926.807,10.858.018,10.783.748,10.768.193,10.741.165,10.724.599,10.709.739 ep,Grèce
14,"Espagne,Population au 1er janvier - totale",30.327.000,30.583.000,30.895.500,31.151.231,31.442.070,31.776.320,32.132.264,32.434.123,32.931.771,...,46.818.219,46.727.890,46.512.199,46.449.565,46.440.099,46.528.024,46.658.447,46.937.060,47.329.981 p,Espagne
15,"France,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,65.276.983,65.600.350,66.165.980 b,66.458.153,66.638.391,66.809.816,66.918.941 p,67.012.883 p,67.098.824 p,France
16,"France (métropolitaine),Population au 1er janvier - totale",45.464.797,45.903.656,46.422.000,47.573.406,48.059.029,48.561.800,48.953.792,49.373.537,49.723.072,...,63.375.971,63.697.865,:,:,:,:,:,:,:,France (métropolitaine)
17,"Croatie,Population au 1er janvier - totale",4.127.422,4.152.939,4.181.645,4.211.778,4.239.572,4.266.180,4.295.665,4.325.736,4.351.629,...,4.275.984,4.262.140,4.246.809,4.225.316,4.190.669,4.154.213,4.105.493,4.076.246,4.058.165,Croatie
18,"Italie,Population au 1er janvier - totale",50.025.500,50.373.900,50.698.800,51.060.100,51.443.900,51.906.800,52.317.900,52.720.100,53.080.900,...,59.394.207,59.685.227,60.782.668,60.795.612,60.665.551,60.589.445,60.483.973,60.359.546 p,60.244.639 p,Italie
19,"Chypre,Population au 1er janvier - totale",572.000,573.566,575.900,578.900,585.500,588.400,593.200,597.100,601.800,...,862.011,865.878,858.000,847.008,848.319,854.802,864.236,875.899,888.005 p,Chypre
20,"Lettonie,Population au 1er janvier - totale",2.104.128,2.137.830,2.167.531,2.195.640,2.226.198,2.255.048,2.276.789,2.289.645,2.312.795,...,2.044.813,2.023.825,2.001.468,1.986.096,1.968.957,1.950.116,1.934.379,1.919.968,1.907.675,Lettonie
21,"Lituanie,Population au 1er janvier - totale",2.755.600,2.801.500,2.845.600,2.881.100,2.916.800,2.953.600,2.989.300,3.026.800,3.062.000,...,3.003.641,2.971.905,2.943.472,2.921.262,2.888.558,2.847.904,2.808.901,2.794.184,2.794.090,Lituanie
22,"Luxembourg,Population au 1er janvier - totale",313.050,314.889,318.800,322.700,325.500,330.000,333.000,334.790,335.200,...,524.853 b,537.039,549.680,562.958,576.249,590.667 b,602.005,613.894,626.108,Luxembourg
23,"Hongrie,Population au 1er janvier - totale",9.961.044,10.005.980,10.049.935,10.071.715,10.104.179,10.135.490,10.160.380,10.196.926,10.236.282,...,9.931.925 b,9.908.798,9.877.365,9.855.571,9.830.485,9.797.561,9.778.371,9.772.756,9.769.526,Hongrie
24,"Malte,Population au 1er janvier - totale",327.200,325.900,324.600,323.200,321.900,320.600,317.000,313.400,309.700,...,417.546,422.509,429.424,439.691,450.415,460.297,475.701,493.559,514.564,Malte
25,"Pays-Bas,Population au 1er janvier - totale",11.417.254,11.556.008,11.721.416,11.889.962,12.041.970,12.212.269,12.377.194,12.535.307,12.661.095,...,16.730.348,16.779.575,16.829.289,16.900.726,16.979.120,17.081.507,17.181.084,17.282.163,17.407.585,Pays-Bas
26,"Autriche,Population au 1er janvier - totale",7.030.385,7.064.693,7.107.904,7.151.824,7.199.798,7.247.804,7.293.973,7.350.159,7.403.837,...,8.408.121,8.451.860,8.507.786,8.584.926,8.700.471,8.772.865,8.822.267,8.858.775,8.901.064,Autriche
27,"Pologne,Population au 1er janvier - totale",29.479.900,29.795.000,30.133.000,30.484.000,30.940.000,31.338.900,31.551.000,31.811.000,32.163.310,...,38.063.792,38.062.535,38.017.856,38.005.614,37.967.209,37.972.964,37.976.687,37.972.812,37.958.138,Pologne
28,"Portugal,Population au 1er janvier - totale",8.826.040,8.889.392,8.969.240,9.018.730,9.041.980,9.028.750,8.968.440,8.893.540,8.855.500,...,10.542.398,10.487.289,10.427.301,10.374.822,10.341.330,10.309.573,10.291.027,10.276.617,10.295.909,Portugal
29,"Roumanie,Population au 1er janvier - totale",18.319.210,18.494.600,18.615.900,18.737.200,18.858.500,18.979.752,19.083.400,19.347.500,19.720.984,...,20.095.996,20.020.074,19.947.311,19.870.647,19.760.585,19.643.949,19.530.631,19.414.458,19.317.984 p,Roumanie
30,"Slovénie,Population au 1er janvier - totale",1.580.535,1.588.904,1.599.357,1.607.941,1.626.000,1.638.227,1.660.092,1.679.717,1.699.339,...,2.055.496,2.058.821,2.061.085,2.062.874,2.064.188,2.065.895,2.066.880,2.080.908,2.095.861,Slovénie
31,"Slovaquie,Population au 1er janvier - totale",3.969.682,4.166.507,4.216.827,4.259.549,4.304.484,4.350.198,4.391.768,4.431.564,4.467.170,...,5.404.322,5.410.836,5.415.949,5.421.349,5.426.252,5.435.343,5.443.120,5.450.421,5.457.873,Slovaquie
32,"Finlande,Population au 1er janvier - totale",4.413.046,4.446.222,4.475.787,4.507.098,4.539.519,4.557.567,4.569.896,4.591.842,4.619.645,...,5.401.267,5.426.674,5.451.270,5.471.753,5.487.308,5.503.297,5.513.130,5.517.919,5.525.292,Finlande
33,"Suède,Population au 1er janvier - totale",7.471.345,7.497.967,7.542.028,7.581.148,7.627.507,7.695.200,7.772.506,7.843.088,7.892.774,...,9.482.855,9.555.893,9.644.864,9.747.355,9.851.017,9.995.153,10.120.242,10.230.185,10.327.589,Suède
34,"Royaume-Uni,Population au 1er janvier - totale",52.200.000,52.600.000,53.000.000,53.500.000,53.800.000,54.200.000,54.496.100,54.800.900,55.086.300,...,63.495.088,63.905.342,64.351.203,64.853.393,65.379.044,65.844.142,66.273.576,66.647.112,67.025.542 p,Royaume-Uni
35,"Espace économique européen (EEE) (UE28 - 2013-2020 et IS, LI, NO),Population au 1er janvier - totale",410.489.590,413.792.993,417.253.762,421.507.905,425.041.422,428.639.503,431.890.552,435.107.549,438.183.835,...,509.389.669 b,510.573.023,512.705.861 b,514.053.164 b,515.762.746,517.013.048 b,518.054.183 p,519.195.257 ep,520.502.213 ep,Espace économique européen (EEE) (UE28 - 2013-2020 et IS
36,"Espace économique européen (EEE) (UE27 - 2007-2013 et IS, LI, NO),Population au 1er janvier - totale",406.362.168,409.640.054,413.072.117,417.296.127,420.801.850,424.373.323,427.594.887,430.781.813,433.832.206,...,505.113.685 b,506.310.883,508.459.052 b,509.827.848 b,511.572.077,512.858.835 b,513.948.690 p,515.119.011 ep,516.444.048 ep,Espace économique européen (EEE) (UE27 - 2007-2013 et IS
37,"Association Européenne de Libre Echange (AELE),Population au 1er janvier - totale",9.053.336,9.148.844,9.331.154,9.493.953,9.635.106,9.747.502,9.834.737,9.937.651,10.052.847,...,13.296.582,13.449.030,13.610.401,13.770.625,13.907.998,14.054.026,14.166.313,14.268.108,14.376.495 p,Association Européenne de Libre Echange (AELE)
38,"Islande,Population au 1er janvier - totale",173.855,177.292,180.765,183.991,187.314,190.652,193.919,197.221,200.281,...,319.575,321.857,325.671,329.100,332.529,338.349,348.450,356.991,364.134,Islande
39,"Liechtenstein,Population au 1er janvier - totale",16.274,16.628,17.125,17.761,18.425,19.085,19.304,19.916,20.433,...,36.475,36.838,37.129,37.366,37.622,37.810,38.114,38.378,38.748 p,Liechtenstein
40,"Norvège,Population au 1er janvier - totale",3.567.707,3.594.771,3.624.829,3.653.006,3.680.068,3.708.609,3.737.726,3.768.298,3.800.780,...,4.985.870,5.051.275,5.107.970,5.166.493,5.210.721,5.258.317,5.295.619,5.328.212,5.367.580,Norvège
41,"Suisse,Population au 1er janvier - totale",5.295.500,5.360.153,5.508.435,5.639.195,5.749.299,5.829.156,5.883.788,5.952.216,6.031.353,...,7.954.662,8.039.060,8.139.631,8.237.666,8.327.126,8.419.550,8.484.130,8.544.527,8.606.033,Suisse
42,"Monténégro,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,620.308,620.893,621.521,622.099,622.218,622.387,622.359,622.182,621.873,Monténégro
43,"Macédoine du Nord,Population au 1er janvier - totale",1.384.451,1.399.403,1.417.200,1.438.342,1.461.522,1.486.469,1.512.988,1.538.694,1.562.211,...,2.059.794,2.062.294,2.065.769,2.069.172,2.071.278,2.073.702,2.075.301,2.077.132 e,2.076.255 e,Macédoine du Nord
44,"Albanie,Population au 1er janvier - totale",1.583.800,1.633.800,1.685.800,1.736.838,1.788.404,1.839.866,1.889.715,1.939.430,1.991.765,...,2.903.008,2.897.770,2.892.394,2.885.796,2.875.592,2.876.591,2.870.324,2.862.427,2.845.955,Albanie
45,"Serbie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,7.216.649,7.181.505,7.146.759,7.114.393,7.076.372,7.040.272,7.001.444,6.963.764,6.926.705,Serbie
46,"Turquie,Population au 1er janvier - totale",27.119.962,27.755.078,28.435.197,29.162.545,29.939.582,30.769.013,31.499.416,32.273.630,33.093.700,...,74.724.269,75.627.384,76.667.864,77.695.904,78.741.053,79.814.871,80.810.525,82.003.882,83.154.997,Turquie
47,"Andorre,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,78.115,76.246,:,:,71.732,:,74.794 e,76.177 e,77.543 e,Andorre
48,"Biélorussie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,9.465.150,9.463.840,9.468.154,9.480.868 e,9.498.364,9.504.704,9.491.823,9.427.348,9.408.350,Biélorussie
49,"Bosnie-Herzégovine,Population au 1er janvier - totale",3.212.349,3.265.629,3.329.909,3.406.130,3.480.448,3.553.053,3.627.922,3.700.916,3.767.185,...,3.839.265,3.835.645,3.830.911,3.825.334,3.515.982,3.509.728,3.500.295,3.492.018 p,:,Bosnie-Herzégovine
50,"Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),Population au 1er janvier - totale",932.500,958.000,984.500,1.009.000,1.033.500,1.060.500,1.088.000,1.116.000,1.145.000,...,1.780.021 e,1.815.606 e,1.820.631 e,1.804.944 e,1.771.604 e,1.783.531 e,1.798.506 e,1.795.666,1.782.115 e,Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
51,"Moldavie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,3.559.541,3.559.497,3.557.634,3.555.159,3.553.056,3.550.852,3.547.539,:,:,Moldavie
52,"Monaco,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,:,:,:,37.700 e,38.200,:,38.300,38.300 e,:,Monaco
53,"Russie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,143.056.383,:,143.666.931,:,:,:,:,:,:,Russie
54,"Saint-Marin,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,33.376,33.562,32.520,32.789,33.005,33.196,34.453,34.590,34.735,Saint-Marin
55,"Ukraine,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,45.453.282,45.372.692,45.245.894,42.759.661 b,42.590.879,42.414.905,42.216.766,41.983.564 e,41.732.779 e,Ukraine
56,"Arménie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,3.274.285,3.026.878,:,3.010.598,2.998.577,2.986.151,2.972.732,2.965.269,2.959.694,Arménie
57,"Azerbaïdjan,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,9.235.085,9.356.483,9.477.119,9.593.038,9.705.643,9.809.981,9.898.085,9.981.457,10.067.108,Azerbaïdjan
58,"Géorgie,Population au 1er janvier - totale",:,:,:,:,:,:,:,:,:,...,4.497.617,:,4.490.498,3.729.500 e,3.720.400,3.726.374,3.729.633,3.723.464,3.716.858,Géorgie

In [168]:
df5 = df5.drop(columns=['GEO,INDIC_DE\TIME'])
df5

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,GEO
0,354.531.754,357.404.302,360.431.043,364.153.147,367.355.615,370.521.157,373.443.503,376.321.214,379.076.041,381.626.236,...,440.552.661 b,441.257.711,442.883.888 b,443.666.812 b,444.802.830,445.534.430 b,446.098.424 p,446.824.564 ep,447.706.209 ep,Union européenne - 27 pays (à partir de 2020)
1,406.731.754,410.004.302,413.431.043,417.653.147,421.155.615,424.721.157,427.939.603,431.122.114,434.162.341,436.963.336,...,504.047.749 b,505.163.053,507.235.091 b,508.520.205 b,510.181.874,511.378.572 b,512.372.000 p,513.471.676 ep,:,Union européenne - 28 pays (2013-2020)
2,402.604.332,405.851.363,409.249.398,413.441.369,416.916.043,420.454.977,423.643.938,426.796.378,429.810.712,432.583.709,...,499.771.765 b,500.900.913,502.988.282 b,504.294.889 b,505.991.205,507.224.359 b,508.266.507 p,509.395.430 ep,510.673.586 ep,Union européenne - 27 pays (2007-2013)
3,263.140.292,265.392.392,267.691.048,270.714.128,273.072.410,275.430.651,277.770.462,279.854.101,281.656.968,283.567.243,...,335.288.924 b,336.044.966,337.764.352 b,338.562.121 b,339.787.987,340.541.142 b,341.145.721 p,341.902.187 ep,342.806.623 ep,Zone euro - 19 pays (à partir de 2015)
4,260.384.692,262.590.892,264.845.448,267.833.028,270.155.610,272.477.051,274.781.162,276.827.301,278.594.968,280.471.543,...,332.285.283 b,333.073.061,334.820.880 b,335.640.859 b,336.899.429,337.693.238 b,338.336.820 p,339.108.003 ep,340.012.533 ep,Zone euro - 18 pays (2014)
5,9.128.824,9.178.154,9.189.741,9.251.414,9.328.126,9.428.100,9.499.234,9.556.380,9.605.601,9.631.910,...,11.075.889 b,11.137.974,11.180.840,11.237.274,11.311.117,11.351.727,11.398.589,11.455.519,11.549.888,Belgique
6,7.829.246,7.905.502,7.980.734,8.045.158,8.111.132,8.177.547,8.230.788,8.285.325,8.335.126,8.404.080,...,7.327.224,7.284.552,7.245.677,7.202.198,7.153.784,7.101.859,7.050.034,7.000.039,6.951.482,Bulgarie
7,9.637.840,9.566.172,9.607.129,9.642.191,9.699.179,9.756.429,9.802.287,9.839.792,9.866.006,9.886.686,...,10.505.445,10.516.125,10.512.419,10.538.275,10.553.843,10.578.820,10.610.055,10.649.800,10.693.939,Tchéquie
8,4.565.455,4.593.750,4.629.624,4.665.829,4.703.136,4.741.008,4.777.015,4.817.746,4.852.962,4.876.803,...,5.580.516,5.602.628,5.627.235,5.659.715,5.707.251,5.748.769,5.781.190,5.806.081,5.822.763,Danemark
9,55.257.088,55.958.321,56.589.148,57.247.246,57.864.509,58.587.451,59.296.591,59.792.934,59.948.474,60.463.033,...,80.327.900,80.523.746,80.767.463,81.197.537,82.175.684,82.521.653,82.792.351,83.019.213,83.166.711,Allemagne jusqu'en 1990 ancien territoire de la RFA
10,72.542.990,73.086.809,73.668.454,74.383.113,75.045.592,75.591.082,76.336.308,76.864.314,77.038.358,77.550.269,...,80.327.900,80.523.746,80.767.463,81.197.537,82.175.684,82.521.653,82.792.351,83.019.213,83.166.711,Allemagne incluant l'ancienne RDA
11,1.206.362,1.216.712,1.233.441,1.249.804,1.267.910,1.286.262,1.302.870,1.314.323,1.323.569,1.338.858,...,1.325.217,1.320.174,1.315.819,1.314.870 b,1.315.944,1.315.635,1.319.133,1.324.820,1.328.976,Estonie
12,2.835.500,2.821.700,2.827.100,2.845.000,2.860.300,2.872.800,2.881.800,2.895.800,2.909.100,2.922.000,...,4.589.287,4.609.779,4.637.852,4.677.627,4.726.286,4.784.383,4.830.392,4.904.240 e,4.963.839 e,Irlande
13,8.300.399,8.363.050,8.433.050,8.463.416,8.495.834,8.525.024,8.575.642,8.651.660,8.716.516,8.765.014,...,11.086.406,11.003.615,10.926.807,10.858.018,10.783.748,10.768.193,10.741.165,10.724.599,10.709.739 ep,Grèce
14,30.327.000,30.583.000,30.895.500,31.151.231,31.442.070,31.776.320,32.132.264,32.434.123,32.931.771,33.294.497,...,46.818.219,46.727.890,46.512.199,46.449.565,46.440.099,46.528.024,46.658.447,46.937.060,47.329.981 p,Espagne
15,:,:,:,:,:,:,:,:,:,:,...,65.276.983,65.600.350,66.165.980 b,66.458.153,66.638.391,66.809.816,66.918.941 p,67.012.883 p,67.098.824 p,France
16,45.464.797,45.903.656,46.422.000,47.573.406,48.059.029,48.561.800,48.953.792,49.373.537,49.723.072,50.107.735,...,63.375.971,63.697.865,:,:,:,:,:,:,:,France (métropolitaine)
17,4.127.422,4.152.939,4.181.645,4.211.778,4.239.572,4.266.180,4.295.665,4.325.736,4.351.629,4.379.627,...,4.275.984,4.262.140,4.246.809,4.225.316,4.190.669,4.154.213,4.105.493,4.076.246,4.058.165,Croatie
18,50.025.500,50.373.900,50.698.800,51.060.100,51.443.900,51.906.800,52.317.900,52.720.100,53.080.900,53.390.600,...,59.394.207,59.685.227,60.782.668,60.795.612,60.665.551,60.589.445,60.483.973,60.359.546 p,60.244.639 p,Italie
19,572.000,573.566,575.900,578.900,585.500,588.400,593.200,597.100,601.800,606.800,...,862.011,865.878,858.000,847.008,848.319,854.802,864.236,875.899,888.005 p,Chypre
20,2.104.128,2.137.830,2.167.531,2.195.640,2.226.198,2.255.048,2.276.789,2.289.645,2.312.795,2.334.443,...,2.044.813,2.023.825,2.001.468,1.986.096,1.968.957,1.950.116,1.934.379,1.919.968,1.907.675,Lettonie
21,2.755.600,2.801.500,2.845.600,2.881.100,2.916.800,2.953.600,2.989.300,3.026.800,3.062.000,3.095.700,...,3.003.641,2.971.905,2.943.472,2.921.262,2.888.558,2.847.904,2.808.901,2.794.184,2.794.090,Lituanie
22,313.050,314.889,318.800,322.700,325.500,330.000,333.000,334.790,335.200,336.500,...,524.853 b,537.039,549.680,562.958,576.249,590.667 b,602.005,613.894,626.108,Luxembourg
23,9.961.044,10.005.980,10.049.935,10.071.715,10.104.179,10.135.490,10.160.380,10.196.926,10.236.282,10.275.347,...,9.931.925 b,9.908.798,9.877.365,9.855.571,9.830.485,9.797.561,9.778.371,9.772.756,9.769.526,Hongrie
24,327.200,325.900,324.600,323.200,321.900,320.600,317.000,313.400,309.700,306.100,...,417.546,422.509,429.424,439.691,450.415,460.297,475.701,493.559,514.564,Malte
25,11.417.254,11.556.008,11.721.416,11.889.962,12.041.970,12.212.269,12.377.194,12.535.307,12.661.095,12.798.346,...,16.730.348,16.779.575,16.829.289,16.900.726,16.979.120,17.081.507,17.181.084,17.282.163,17.407.585,Pays-Bas
26,7.030.385,7.064.693,7.107.904,7.151.824,7.199.798,7.247.804,7.293.973,7.350.159,7.403.837,7.426.968,...,8.408.121,8.451.860,8.507.786,8.584.926,8.700.471,8.772.865,8.822.267,8.858.775,8.901.064,Autriche
27,29.479.900,29.795.000,30.133.000,30.484.000,30.940.000,31.338.900,31.551.000,31.811.000,32.163.310,32.426.000,...,38.063.792,38.062.535,38.017.856,38.005.614,37.967.209,37.972.964,37.976.687,37.972.812,37.958.138,Pologne
28,8.826.040,8.889.392,8.969.240,9.018.730,9.041.980,9.028.750,8.968.440,8.893.540,8.855.500,8.817.800,...,10.542.398,10.487.289,10.427.301,10.374.822,10.341.330,10.309.573,10.291.027,10.276.617,10.295.909,Portugal
29,18.319.210,18.494.600,18.615.900,18.737.200,18.858.500,18.979.752,19.083.400,19.347.500,19.720.984,19.878.678,...,20.095.996,20.020.074,19.947.311,19.870.647,19.760.585,19.643.949,19.530.631,19.414.458,19.317.984 p,Roumanie
30,1.580.535,1.588.904,1.599.357,1.607.941,1.626.000,1.638.227,1.660.092,1.679.717,1.699.339,1.709.752,...,2.055.496,2.058.821,2.061.085,2.062.874,2.064.188,2.065.895,2.066.880,2.080.908,2.095.861,Slovénie
31,3.969.682,4.166.507,4.216.827,4.259.549,4.304.484,4.350.198,4.391.768,4.431.564,4.467.170,4.500.659,...,5.404.322,5.410.836,5.415.949,5.421.349,5.426.252,5.435.343,5.443.120,5.450.421,5.457.873,Slovaquie
32,4.413.046,4.446.222,4.475.787,4.507.098,4.539.519,4.557.567,4.569.896,4.591.842,4.619.645,4.633.292,...,5.401.267,5.426.674,5.451.270,5.471.753,5.487.308,5.503.297,5.513.130,5.517.919,5.525.292,Finlande
33,7.471.345,7.497.967,7.542.028,7.581.148,7.627.507,7.695.200,7.772.506,7.843.088,7.892.774,7.931.772,...,9.482.855,9.555.893,9.644.864,9.747.355,9.851.017,9.995.153,10.120.242,10.230.185,10.327.589,Suède
34,52.200.000,52.600.000,53.000.000,53.500.000,53.800.000,54.200.000,54.496.100,54.800.900,55.086.300,55.337.100,...,63.495.088,63.905.342,64.351.203,64.853.393,65.379.044,65.844.142,66.273.576,66.647.112,67.025.542 p,Royaume-Uni
35,410.489.590,413.792.993,417.253.762,421.507.905,425.041.422,428.639.503,431.890.552,435.107.549,438.183.835,441.019.460,...,509.389.669 b,510.573.023,512.705.861 b,514.053.164 b,515.762.746,517.013.048 b,518.054.183 p,519.195.257 ep,520.502.213 ep,Espace économique européen (EEE) (UE28 - 2013-2020 et IS
36,406.362.168,409.640.054,413.072.117,417.296.127,420.801.850,424.373.323,427.594.887,430.781.813,433.832.206,436.639.833,...,505.113.685 b,506.310.883,508.459.052 b,509.827.848 b,511.572.077,512.858.835 b,513.948.690 p,515.119.011 ep,516.444.048 ep,Espace économique européen (EEE) (UE27 - 2007-2013 et IS
37,9.053.336,9.148.844,9.331.154,9.493.953,9.635.106,9.747.502,9.834.737,9.937.651,10.052.847,10.160.198,...,13.296.582,13.449.030,13.610.401,13.770.625,13.907.998,14.054.026,14.166.313,14.268.108,14.376.495 p,Association Européenne de Libre Echange (AELE)
38,173.855,177.292,180.765,183.991,187.314,190.652,193.919,197.221,200.281,202.695,...,319.575,321.857,325.671,329.100,332.529,338.349,348.450,356.991,364.134,Islande
39,16.274,16.628,17.125,17.761,18.425,19.085,19.304,19.916,20.433,21.237,...,36.475,36.838,37.129,37.366,37.622,37.810,38.114,38.378,38.748 p,Liechtenstein
40,3.567.707,3.594.771,3.624.829,3.653.006,3.680.068,3.708.609,3.737.726,3.768.298,3.800.780,3.832.192,...,4.985.870,5.051.275,5.107.970,5.166.493,5.210.721,5.258.317,5.295.619,5.328.212,5.367.580,Norvège
41,5.295.500,5.360.153,5.508.435,5.639.195,5.749.299,5.829.156,5.883.788,5.952.216,6.031.353,6.104.074,...,7.954.662,8.039.060,8.139.631,8.237.666,8.327.126,8.419.550,8.484.130,8.544.527,8.606.033,Suisse
42,:,:,:,:,:,:,:,:,:,:,...,620.308,620.893,621.521,622.099,622.218,622.387,622.359,622.182,621.873,Monténégro
43,1.384.451,1.399.403,1.417.200,1.438.342,1.461.522,1.486.469,1.512.988,1.538.694,1.562.211,1.589.217,...,2.059.794,2.062.294,2.065.769,2.069.172,2.071.278,2.073.702,2.075.301,2.077.132 e,2.076.255 e,Macédoine du Nord
44,1.583.800,1.633.800,1.685.800,1.736.838,1.788.404,1.839.866,1.889.715,1.939.430,1.991.765,2.052.778,...,2.903.008,2.897.770,2.892.394,2.885.796,2.875.592,2.876.591,2.870.324,2.862.427,2.845.955,Albanie
45,:,:,:,:,:,:,:,:,:,:,...,7.216.649,7.181.505,7.146.759,7.114.393,7.076.372,7.040.272,7.001.444,6.963.764,6.926.705,Serbie
46,27.119.962,27.755.078,28.435.197,29.162.545,29.939.582,30.769.013,31.499.416,32.273.630,33.093.700,33.961.875,...,74.724.269,75.627.384,76.667.864,77.695.904,78.741.053,79.814.871,80.810.525,82.003.882,83.154.997,Turquie
47,:,:,:,:,:,:,:,:,:,:,...,78.115,76.246,:,:,71.732,:,74.794 e,76.177 e,77.543 e,Andorre
48,:,:,:,:,:,:,:,:,:,:,...,9.465.150,9.463.840,9.468.154,9.480.868 e,9.498.364,9.504.704,9.491.823,9.427.348,9.408.350,Biélorussie
49,3.212.349,3.265.629,3.329.909,3.406.130,3.480.448,3.553.053,3.627.922,3.700.916,3.767.185,3.734.546,...,3.839.265,3.835.645,3.830.911,3.825.334,3.515.982,3.509.728,3.500.295,3.492.018 p,:,Bosnie-Herzégovine
50,932.500,958.000,984.500,1.009.000,1.033.500,1.060.500,1.088.000,1.116.000,1.145.000,1.174.000,...,1.780.021 e,1.815.606 e,1.820.631 e,1.804.944 e,1.771.604 e,1.783.531 e,1.798.506 e,1.795.666,1.782.115 e,Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
51,:,:,:,:,:,:,:,:,:,:,...,3.559.541,3.559.497,3.557.634,3.555.159,3.553.056,3.550.852,3.547.539,:,:,Moldavie
52,:,:,:,:,:,:,:,:,:,:,...,:,:,:,37.700 e,38.200,:,38.300,38.300 e,:,Monaco
53,:,:,:,:,:,:,:,:,:,:,...,143.056.383,:,143.666.931,:,:,:,:,:,:,Russie
54,:,:,:,:,:,:,:,:,:,:,...,33.376,33.562,32.520,32.789,33.005,33.196,34.453,34.590,34.735,Saint-Marin
55,:,:,:,:,:,:,:,:,:,:,...,45.453.282,45.372.692,45.245.894,42.759.661 b,42.590.879,42.414.905,42.216.766,41.983.564 e,41.732.779 e,Ukraine
56,:,:,:,:,:,:,:,:,:,:,...,3.274.285,3.026.878,:,3.010.598,2.998.577,2.986.151,2.972.732,2.965.269,2.959.694,Arménie
57,:,:,:,:,:,:,:,:,:,:,...,9.235.085,9.356.483,9.477.119,9.593.038,9.705.643,9.809.981,9.898.085,9.981.457,10.067.108,Azerbaïdjan
58,:,:,:,:,:,:,:,:,:,:,...,4.497.617,:,4.490.498,3.729.500 e,3.720.400,3.726.374,3.729.633,3.723.464,3.716.858,Géorgie

In [169]:
df_merge5 = pd.merge(df5, code_pays, how ='inner', left_on='GEO', right_on= 'libelle')
df_merge5

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2015,2016,2017,2018,2019,2020,GEO,id,code,libelle
0,354.531.754,357.404.302,360.431.043,364.153.147,367.355.615,370.521.157,373.443.503,376.321.214,379.076.041,381.626.236,...,443.666.812 b,444.802.830,445.534.430 b,446.098.424 p,446.824.564 ep,447.706.209 ep,Union européenne - 27 pays (à partir de 2020),1,EU27_20,Union européenne - 27 pays (à partir de 2020)
1,406.731.754,410.004.302,413.431.043,417.653.147,421.155.615,424.721.157,427.939.603,431.122.114,434.162.341,436.963.336,...,508.520.205 b,510.181.874,511.378.572 b,512.372.000 p,513.471.676 ep,:,Union européenne - 28 pays (2013-2020),2,EU28,Union européenne - 28 pays (2013-2020)
2,263.140.292,265.392.392,267.691.048,270.714.128,273.072.410,275.430.651,277.770.462,279.854.101,281.656.968,283.567.243,...,338.562.121 b,339.787.987,340.541.142 b,341.145.721 p,341.902.187 ep,342.806.623 ep,Zone euro - 19 pays (à partir de 2015),3,EA19,Zone euro - 19 pays (à partir de 2015)
3,9.128.824,9.178.154,9.189.741,9.251.414,9.328.126,9.428.100,9.499.234,9.556.380,9.605.601,9.631.910,...,11.237.274,11.311.117,11.351.727,11.398.589,11.455.519,11.549.888,Belgique,4,BE,Belgique
4,7.829.246,7.905.502,7.980.734,8.045.158,8.111.132,8.177.547,8.230.788,8.285.325,8.335.126,8.404.080,...,7.202.198,7.153.784,7.101.859,7.050.034,7.000.039,6.951.482,Bulgarie,5,BG,Bulgarie
5,9.637.840,9.566.172,9.607.129,9.642.191,9.699.179,9.756.429,9.802.287,9.839.792,9.866.006,9.886.686,...,10.538.275,10.553.843,10.578.820,10.610.055,10.649.800,10.693.939,Tchéquie,6,CZ,Tchéquie
6,4.565.455,4.593.750,4.629.624,4.665.829,4.703.136,4.741.008,4.777.015,4.817.746,4.852.962,4.876.803,...,5.659.715,5.707.251,5.748.769,5.781.190,5.806.081,5.822.763,Danemark,7,DK,Danemark
7,55.257.088,55.958.321,56.589.148,57.247.246,57.864.509,58.587.451,59.296.591,59.792.934,59.948.474,60.463.033,...,81.197.537,82.175.684,82.521.653,82.792.351,83.019.213,83.166.711,Allemagne jusqu'en 1990 ancien territoire de la RFA,8,DE,Allemagne jusqu'en 1990 ancien territoire de la RFA
8,1.206.362,1.216.712,1.233.441,1.249.804,1.267.910,1.286.262,1.302.870,1.314.323,1.323.569,1.338.858,...,1.314.870 b,1.315.944,1.315.635,1.319.133,1.324.820,1.328.976,Estonie,9,EE,Estonie
9,2.835.500,2.821.700,2.827.100,2.845.000,2.860.300,2.872.800,2.881.800,2.895.800,2.909.100,2.922.000,...,4.677.627,4.726.286,4.784.383,4.830.392,4.904.240 e,4.963.839 e,Irlande,10,IE,Irlande
10,8.300.399,8.363.050,8.433.050,8.463.416,8.495.834,8.525.024,8.575.642,8.651.660,8.716.516,8.765.014,...,10.858.018,10.783.748,10.768.193,10.741.165,10.724.599,10.709.739 ep,Grèce,11,EL,Grèce
11,30.327.000,30.583.000,30.895.500,31.151.231,31.442.070,31.776.320,32.132.264,32.434.123,32.931.771,33.294.497,...,46.449.565,46.440.099,46.528.024,46.658.447,46.937.060,47.329.981 p,Espagne,12,ES,Espagne
12,:,:,:,:,:,:,:,:,:,:,...,66.458.153,66.638.391,66.809.816,66.918.941 p,67.012.883 p,67.098.824 p,France,13,FR,France
13,4.127.422,4.152.939,4.181.645,4.211.778,4.239.572,4.266.180,4.295.665,4.325.736,4.351.629,4.379.627,...,4.225.316,4.190.669,4.154.213,4.105.493,4.076.246,4.058.165,Croatie,14,HR,Croatie
14,50.025.500,50.373.900,50.698.800,51.060.100,51.443.900,51.906.800,52.317.900,52.720.100,53.080.900,53.390.600,...,60.795.612,60.665.551,60.589.445,60.483.973,60.359.546 p,60.244.639 p,Italie,15,IT,Italie
15,572.000,573.566,575.900,578.900,585.500,588.400,593.200,597.100,601.800,606.800,...,847.008,848.319,854.802,864.236,875.899,888.005 p,Chypre,16,CY,Chypre
16,2.104.128,2.137.830,2.167.531,2.195.640,2.226.198,2.255.048,2.276.789,2.289.645,2.312.795,2.334.443,...,1.986.096,1.968.957,1.950.116,1.934.379,1.919.968,1.907.675,Lettonie,17,LV,Lettonie
17,2.755.600,2.801.500,2.845.600,2.881.100,2.916.800,2.953.600,2.989.300,3.026.800,3.062.000,3.095.700,...,2.921.262,2.888.558,2.847.904,2.808.901,2.794.184,2.794.090,Lituanie,18,LT,Lituanie
18,313.050,314.889,318.800,322.700,325.500,330.000,333.000,334.790,335.200,336.500,...,562.958,576.249,590.667 b,602.005,613.894,626.108,Luxembourg,19,LU,Luxembourg
19,9.961.044,10.005.980,10.049.935,10.071.715,10.104.179,10.135.490,10.160.380,10.196.926,10.236.282,10.275.347,...,9.855.571,9.830.485,9.797.561,9.778.371,9.772.756,9.769.526,Hongrie,20,HU,Hongrie
20,327.200,325.900,324.600,323.200,321.900,320.600,317.000,313.400,309.700,306.100,...,439.691,450.415,460.297,475.701,493.559,514.564,Malte,21,MT,Malte
21,11.417.254,11.556.008,11.721.416,11.889.962,12.041.970,12.212.269,12.377.194,12.535.307,12.661.095,12.798.346,...,16.900.726,16.979.120,17.081.507,17.181.084,17.282.163,17.407.585,Pays-Bas,22,NL,Pays-Bas
22,7.030.385,7.064.693,7.107.904,7.151.824,7.199.798,7.247.804,7.293.973,7.350.159,7.403.837,7.426.968,...,8.584.926,8.700.471,8.772.865,8.822.267,8.858.775,8.901.064,Autriche,23,AT,Autriche
23,29.479.900,29.795.000,30.133.000,30.484.000,30.940.000,31.338.900,31.551.000,31.811.000,32.163.310,32.426.000,...,38.005.614,37.967.209,37.972.964,37.976.687,37.972.812,37.958.138,Pologne,24,PL,Pologne
24,8.826.040,8.889.392,8.969.240,9.018.730,9.041.980,9.028.750,8.968.440,8.893.540,8.855.500,8.817.800,...,10.374.822,10.341.330,10.309.573,10.291.027,10.276.617,10.295.909,Portugal,25,PT,Portugal
25,18.319.210,18.494.600,18.615.900,18.737.200,18.858.500,18.979.752,19.083.400,19.347.500,19.720.984,19.878.678,...,19.870.647,19.760.585,19.643.949,19.530.631,19.414.458,19.317.984 p,Roumanie,26,RO,Roumanie
26,1.580.535,1.588.904,1.599.357,1.607.941,1.626.000,1.638.227,1.660.092,1.679.717,1.699.339,1.709.752,...,2.062.874,2.064.188,2.065.895,2.066.880,2.080.908,2.095.861,Slovénie,27,SI,Slovénie
27,3.969.682,4.166.507,4.216.827,4.259.549,4.304.484,4.350.198,4.391.768,4.431.564,4.467.170,4.500.659,...,5.421.349,5.426.252,5.435.343,5.443.120,5.450.421,5.457.873,Slovaquie,28,SK,Slovaquie
28,4.413.046,4.446.222,4.475.787,4.507.098,4.539.519,4.557.567,4.569.896,4.591.842,4.619.645,4.633.292,...,5.471.753,5.487.308,5.503.297,5.513.130,5.517.919,5.525.292,Finlande,29,FI,Finlande
29,7.471.345,7.497.967,7.542.028,7.581.148,7.627.507,7.695.200,7.772.506,7.843.088,7.892.774,7.931.772,...,9.747.355,9.851.017,9.995.153,10.120.242,10.230.185,10.327.589,Suède,30,SE,Suède
30,52.200.000,52.600.000,53.000.000,53.500.000,53.800.000,54.200.000,54.496.100,54.800.900,55.086.300,55.337.100,...,64.853.393,65.379.044,65.844.142,66.273.576,66.647.112,67.025.542 p,Royaume-Uni,31,UK,Royaume-Uni
31,173.855,177.292,180.765,183.991,187.314,190.652,193.919,197.221,200.281,202.695,...,329.100,332.529,338.349,348.450,356.991,364.134,Islande,32,IS,Islande
32,3.567.707,3.594.771,3.624.829,3.653.006,3.680.068,3.708.609,3.737.726,3.768.298,3.800.780,3.832.192,...,5.166.493,5.210.721,5.258.317,5.295.619,5.328.212,5.367.580,Norvège,33,NO,Norvège
33,:,:,:,:,:,:,:,:,:,:,...,622.099,622.218,622.387,622.359,622.182,621.873,Monténégro,34,ME,Monténégro
34,1.384.451,1.399.403,1.417.200,1.438.342,1.461.522,1.486.469,1.512.988,1.538.694,1.562.211,1.589.217,...,2.069.172,2.071.278,2.073.702,2.075.301,2.077.132 e,2.076.255 e,Macédoine du Nord,35,MK,Macédoine du Nord
35,1.583.800,1.633.800,1.685.800,1.736.838,1.788.404,1.839.866,1.889.715,1.939.430,1.991.765,2.052.778,...,2.885.796,2.875.592,2.876.591,2.870.324,2.862.427,2.845.955,Albanie,36,AL,Albanie
36,:,:,:,:,:,:,:,:,:,:,...,7.114.393,7.076.372,7.040.272,7.001.444,6.963.764,6.926.705,Serbie,37,RS,Serbie
37,27.119.962,27.755.078,28.435.197,29.162.545,29.939.582,30.769.013,31.499.416,32.273.630,33.093.700,33.961.875,...,77.695.904,78.741.053,79.814.871,80.810.525,82.003.882,83.154.997,Turquie,38,TR,Turquie
38,3.212.349,3.265.629,3.329.909,3.406.130,3.480.448,3.553.053,3.627.922,3.700.916,3.767.185,3.734.546,...,3.825.334,3.515.982,3.509.728,3.500.295,3.492.018 p,:,Bosnie-Herzégovine,39,BA,Bosnie-Herzégovine
39,932.500,958.000,984.500,1.009.000,1.033.500,1.060.500,1.088.000,1.116.000,1.145.000,1.174.000,...,1.804.944 e,1.771.604 e,1.783.531 e,1.798.506 e,1.795.666,1.782.115 e,Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies),40,XK,Kosovo (selon la résolution 1244/99 du Conseil de sécurité des Nations Unies)
40,:,:,:,:,:,:,:,:,:,:,...,3.555.159,3.553.056,3.550.852,3.547.539,:,:,Moldavie,41,MD,Moldavie
41,:,:,:,:,:,:,:,:,:,:,...,42.759.661 b,42.590.879,42.414.905,42.216.766,41.983.564 e,41.732.779 e,Ukraine,42,UA,Ukraine
42,:,:,:,:,:,:,:,:,:,:,...,3.729.500 e,3.720.400,3.726.374,3.729.633,3.723.464,3.716.858,Géorgie,43,GE,Géorgie

In [170]:
df_merge5 = df_merge5.drop(columns=['GEO', 'code', 'libelle'])
df_merge5

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,id
0,354.531.754,357.404.302,360.431.043,364.153.147,367.355.615,370.521.157,373.443.503,376.321.214,379.076.041,381.626.236,...,440.552.661 b,441.257.711,442.883.888 b,443.666.812 b,444.802.830,445.534.430 b,446.098.424 p,446.824.564 ep,447.706.209 ep,1
1,406.731.754,410.004.302,413.431.043,417.653.147,421.155.615,424.721.157,427.939.603,431.122.114,434.162.341,436.963.336,...,504.047.749 b,505.163.053,507.235.091 b,508.520.205 b,510.181.874,511.378.572 b,512.372.000 p,513.471.676 ep,:,2
2,263.140.292,265.392.392,267.691.048,270.714.128,273.072.410,275.430.651,277.770.462,279.854.101,281.656.968,283.567.243,...,335.288.924 b,336.044.966,337.764.352 b,338.562.121 b,339.787.987,340.541.142 b,341.145.721 p,341.902.187 ep,342.806.623 ep,3
3,9.128.824,9.178.154,9.189.741,9.251.414,9.328.126,9.428.100,9.499.234,9.556.380,9.605.601,9.631.910,...,11.075.889 b,11.137.974,11.180.840,11.237.274,11.311.117,11.351.727,11.398.589,11.455.519,11.549.888,4
4,7.829.246,7.905.502,7.980.734,8.045.158,8.111.132,8.177.547,8.230.788,8.285.325,8.335.126,8.404.080,...,7.327.224,7.284.552,7.245.677,7.202.198,7.153.784,7.101.859,7.050.034,7.000.039,6.951.482,5
5,9.637.840,9.566.172,9.607.129,9.642.191,9.699.179,9.756.429,9.802.287,9.839.792,9.866.006,9.886.686,...,10.505.445,10.516.125,10.512.419,10.538.275,10.553.843,10.578.820,10.610.055,10.649.800,10.693.939,6
6,4.565.455,4.593.750,4.629.624,4.665.829,4.703.136,4.741.008,4.777.015,4.817.746,4.852.962,4.876.803,...,5.580.516,5.602.628,5.627.235,5.659.715,5.707.251,5.748.769,5.781.190,5.806.081,5.822.763,7
7,55.257.088,55.958.321,56.589.148,57.247.246,57.864.509,58.587.451,59.296.591,59.792.934,59.948.474,60.463.033,...,80.327.900,80.523.746,80.767.463,81.197.537,82.175.684,82.521.653,82.792.351,83.019.213,83.166.711,8
8,1.206.362,1.216.712,1.233.441,1.249.804,1.267.910,1.286.262,1.302.870,1.314.323,1.323.569,1.338.858,...,1.325.217,1.320.174,1.315.819,1.314.870 b,1.315.944,1.315.635,1.319.133,1.324.820,1.328.976,9
9,2.835.500,2.821.700,2.827.100,2.845.000,2.860.300,2.872.800,2.881.800,2.895.800,2.909.100,2.922.000,...,4.589.287,4.609.779,4.637.852,4.677.627,4.726.286,4.784.383,4.830.392,4.904.240 e,4.963.839 e,10
10,8.300.399,8.363.050,8.433.050,8.463.416,8.495.834,8.525.024,8.575.642,8.651.660,8.716.516,8.765.014,...,11.086.406,11.003.615,10.926.807,10.858.018,10.783.748,10.768.193,10.741.165,10.724.599,10.709.739 ep,11
11,30.327.000,30.583.000,30.895.500,31.151.231,31.442.070,31.776.320,32.132.264,32.434.123,32.931.771,33.294.497,...,46.818.219,46.727.890,46.512.199,46.449.565,46.440.099,46.528.024,46.658.447,46.937.060,47.329.981 p,12
12,:,:,:,:,:,:,:,:,:,:,...,65.276.983,65.600.350,66.165.980 b,66.458.153,66.638.391,66.809.816,66.918.941 p,67.012.883 p,67.098.824 p,13
13,4.127.422,4.152.939,4.181.645,4.211.778,4.239.572,4.266.180,4.295.665,4.325.736,4.351.629,4.379.627,...,4.275.984,4.262.140,4.246.809,4.225.316,4.190.669,4.154.213,4.105.493,4.076.246,4.058.165,14
14,50.025.500,50.373.900,50.698.800,51.060.100,51.443.900,51.906.800,52.317.900,52.720.100,53.080.900,53.390.600,...,59.394.207,59.685.227,60.782.668,60.795.612,60.665.551,60.589.445,60.483.973,60.359.546 p,60.244.639 p,15
15,572.000,573.566,575.900,578.900,585.500,588.400,593.200,597.100,601.800,606.800,...,862.011,865.878,858.000,847.008,848.319,854.802,864.236,875.899,888.005 p,16
16,2.104.128,2.137.830,2.167.531,2.195.640,2.226.198,2.255.048,2.276.789,2.289.645,2.312.795,2.334.443,...,2.044.813,2.023.825,2.001.468,1.986.096,1.968.957,1.950.116,1.934.379,1.919.968,1.907.675,17
17,2.755.600,2.801.500,2.845.600,2.881.100,2.916.800,2.953.600,2.989.300,3.026.800,3.062.000,3.095.700,...,3.003.641,2.971.905,2.943.472,2.921.262,2.888.558,2.847.904,2.808.901,2.794.184,2.794.090,18
18,313.050,314.889,318.800,322.700,325.500,330.000,333.000,334.790,335.200,336.500,...,524.853 b,537.039,549.680,562.958,576.249,590.667 b,602.005,613.894,626.108,19
19,9.961.044,10.005.980,10.049.935,10.071.715,10.104.179,10.135.490,10.160.380,10.196.926,10.236.282,10.275.347,...,9.931.925 b,9.908.798,9.877.365,9.855.571,9.830.485,9.797.561,9.778.371,9.772.756,9.769.526,20
20,327.200,325.900,324.600,323.200,321.900,320.600,317.000,313.400,309.700,306.100,...,417.546,422.509,429.424,439.691,450.415,460.297,475.701,493.559,514.564,21
21,11.417.254,11.556.008,11.721.416,11.889.962,12.041.970,12.212.269,12.377.194,12.535.307,12.661.095,12.798.346,...,16.730.348,16.779.575,16.829.289,16.900.726,16.979.120,17.081.507,17.181.084,17.282.163,17.407.585,22
22,7.030.385,7.064.693,7.107.904,7.151.824,7.199.798,7.247.804,7.293.973,7.350.159,7.403.837,7.426.968,...,8.408.121,8.451.860,8.507.786,8.584.926,8.700.471,8.772.865,8.822.267,8.858.775,8.901.064,23
23,29.479.900,29.795.000,30.133.000,30.484.000,30.940.000,31.338.900,31.551.000,31.811.000,32.163.310,32.426.000,...,38.063.792,38.062.535,38.017.856,38.005.614,37.967.209,37.972.964,37.976.687,37.972.812,37.958.138,24
24,8.826.040,8.889.392,8.969.240,9.018.730,9.041.980,9.028.750,8.968.440,8.893.540,8.855.500,8.817.800,...,10.542.398,10.487.289,10.427.301,10.374.822,10.341.330,10.309.573,10.291.027,10.276.617,10.295.909,25
25,18.319.210,18.494.600,18.615.900,18.737.200,18.858.500,18.979.752,19.083.400,19.347.500,19.720.984,19.878.678,...,20.095.996,20.020.074,19.947.311,19.870.647,19.760.585,19.643.949,19.530.631,19.414.458,19.317.984 p,26
26,1.580.535,1.588.904,1.599.357,1.607.941,1.626.000,1.638.227,1.660.092,1.679.717,1.699.339,1.709.752,...,2.055.496,2.058.821,2.061.085,2.062.874,2.064.188,2.065.895,2.066.880,2.080.908,2.095.861,27
27,3.969.682,4.166.507,4.216.827,4.259.549,4.304.484,4.350.198,4.391.768,4.431.564,4.467.170,4.500.659,...,5.404.322,5.410.836,5.415.949,5.421.349,5.426.252,5.435.343,5.443.120,5.450.421,5.457.873,28
28,4.413.046,4.446.222,4.475.787,4.507.098,4.539.519,4.557.567,4.569.896,4.591.842,4.619.645,4.633.292,...,5.401.267,5.426.674,5.451.270,5.471.753,5.487.308,5.503.297,5.513.130,5.517.919,5.525.292,29
29,7.471.345,7.497.967,7.542.028,7.581.148,7.627.507,7.695.200,7.772.506,7.843.088,7.892.774,7.931.772,...,9.482.855,9.555.893,9.644.864,9.747.355,9.851.017,9.995.153,10.120.242,10.230.185,10.327.589,30
30,52.200.000,52.600.000,53.000.000,53.500.000,53.800.000,54.200.000,54.496.100,54.800.900,55.086.300,55.337.100,...,63.495.088,63.905.342,64.351.203,64.853.393,65.379.044,65.844.142,66.273.576,66.647.112,67.025.542 p,31
31,173.855,177.292,180.765,183.991,187.314,190.652,193.919,197.221,200.281,202.695,...,319.575,321.857,325.671,329.100,332.529,338.349,348.450,356.991,364.134,32
32,3.567.707,3.594.771,3.624.829,3.653.006,3.680.068,3.708.609,3.737.726,3.768.298,3.800.780,3.832.192,...,4.985.870,5.051.275,5.107.970,5.166.493,5.210.721,5.258.317,5.295.619,5.328.212,5.367.580,33
33,:,:,:,:,:,:,:,:,:,:,...,620.308,620.893,621.521,622.099,622.218,622.387,622.359,622.182,621.873,34
34,1.384.451,1.399.403,1.417.200,1.438.342,1.461.522,1.486.469,1.512.988,1.538.694,1.562.211,1.589.217,...,2.059.794,2.062.294,2.065.769,2.069.172,2.071.278,2.073.702,2.075.301,2.077.132 e,2.076.255 e,35
35,1.583.800,1.633.800,1.685.800,1.736.838,1.788.404,1.839.866,1.889.715,1.939.430,1.991.765,2.052.778,...,2.903.008,2.897.770,2.892.394,2.885.796,2.875.592,2.876.591,2.870.324,2.862.427,2.845.955,36
36,:,:,:,:,:,:,:,:,:,:,...,7.216.649,7.181.505,7.146.759,7.114.393,7.076.372,7.040.272,7.001.444,6.963.764,6.926.705,37
37,27.119.962,27.755.078,28.435.197,29.162.545,29.939.582,30.769.013,31.499.416,32.273.630,33.093.700,33.961.875,...,74.724.269,75.627.384,76.667.864,77.695.904,78.741.053,79.814.871,80.810.525,82.003.882,83.154.997,38
38,3.212.349,3.265.629,3.329.909,3.406.130,3.480.448,3.553.053,3.627.922,3.700.916,3.767.185,3.734.546,...,3.839.265,3.835.645,3.830.911,3.825.334,3.515.982,3.509.728,3.500.295,3.492.018 p,:,39
39,932.500,958.000,984.500,1.009.000,1.033.500,1.060.500,1.088.000,1.116.000,1.145.000,1.174.000,...,1.780.021 e,1.815.606 e,1.820.631 e,1.804.944 e,1.771.604 e,1.783.531 e,1.798.506 e,1.795.666,1.782.115 e,40
40,:,:,:,:,:,:,:,:,:,:,...,3.559.541,3.559.497,3.557.634,3.555.159,3.553.056,3.550.852,3.547.539,:,:,41
41,:,:,:,:,:,:,:,:,:,:,...,45.453.282,45.372.692,45.245.894,42.759.661 b,42.590.879,42.414.905,42.216.766,41.983.564 e,41.732.779 e,42
42,:,:,:,:,:,:,:,:,:,:,...,4.497.617,:,4.490.498,3.729.500 e,3.720.400,3.726.374,3.729.633,3.723.464,3.716.858,43

### Transformation des colonnes "années" en lignes

In [171]:
df_merge5.columns

Index(['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', 'id'],
      dtype='object')

In [172]:
df_global5 = []
for i in range(1960,2021):
    df_i5 = df_merge5[[f'{i}', 'id']]
    df_i5.rename(columns={f'{i}':'population', 'id':'pays_id'}, inplace=True)
    df_i5['annee'] = i
    df_global5.append(df_i5)
df_global5[0]

/home/camille/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
<ipython-input-172-e5d9a4134515>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_i5['annee'] = i

     population  pays_id  annee
0   354.531.754        1   1960
1   406.731.754        2   1960
2   263.140.292        3   1960
3     9.128.824        4   1960
4     7.829.246        5   1960
5     9.637.840        6   1960
6     4.565.455        7   1960
7    55.257.088        8   1960
8     1.206.362        9   1960
9     2.835.500       10   1960
10    8.300.399       11   1960
11   30.327.000       12   1960
12            :       13   1960
13    4.127.422       14   1960
14   50.025.500       15   1960
15      572.000       16   1960
16    2.104.128       17   1960
17    2.755.600       18   1960
18      313.050       19   1960
19    9.961.044       20   1960
20      327.200       21   1960
21   11.417.254       22   1960
22    7.030.385       23   1960
23   29.479.900       24   1960
24    8.826.040       25   1960
25   18.319.210       26   1960
26    1.580.535       27   1960
27    3.969.682       28   1960
28    4.413.046       29   1960
29    7.471.345       30   1960
30   52.200.000       31   1960
31      173.855       32   1960
32    3.567.707       33   1960
33            :       34   1960
34    1.384.451       35   1960
35    1.583.800       36   1960
36            :       37   1960
37   27.119.962       38   1960
38    3.212.349       39   1960
39      932.500       40   1960
40            :       41   1960
41            :       42   1960
42            :       43   1960

In [173]:
len(df_global5)

61

In [174]:
frames = [ df_global5[i] for i in range(0,61) ]
population = pd.concat(frames)
population

      population  pays_id  annee
0    354.531.754        1   1960
1    406.731.754        2   1960
2    263.140.292        3   1960
3      9.128.824        4   1960
4      7.829.246        5   1960
..           ...      ...    ...
38             :       39   2020
39   1.782.115 e       40   2020
40             :       41   2020
41  41.732.779 e       42   2020
42     3.716.858       43   2020

[2623 rows x 3 columns]

### Nettoyage de la donnée

In [175]:
population['population'] = population['population'].apply(lambda x: x.replace('.', ''))
population

    population  pays_id  annee
0    354531754        1   1960
1    406731754        2   1960
2    263140292        3   1960
3      9128824        4   1960
4      7829246        5   1960
..         ...      ...    ...
38           :       39   2020
39   1782115 e       40   2020
40           :       41   2020
41  41732779 e       42   2020
42     3716858       43   2020

[2623 rows x 3 columns]

==> Dans le fichier sur l'évolution de la population des lettres b,e,p,u,c,f,r,z,d,n,s sont parfois situés à la fin des nombres. Ces lettres permettent d'identifier des données comme étant entre autres provisoires, peu fiables, révisé.

In [176]:
population = population.replace({'population': r'[a-z]'}, {'population':''}, regex=True)
population

   population  pays_id  annee
0   354531754        1   1960
1   406731754        2   1960
2   263140292        3   1960
3     9128824        4   1960
4     7829246        5   1960
..        ...      ...    ...
38          :       39   2020
39   1782115        40   2020
40          :       41   2020
41  41732779        42   2020
42    3716858       43   2020

[2623 rows x 3 columns]

In [177]:
population['population'] = population.population.replace({':':0,'0,000':0})  
population

   population  pays_id  annee
0   354531754        1   1960
1   406731754        2   1960
2   263140292        3   1960
3     9128824        4   1960
4     7829246        5   1960
..        ...      ...    ...
38          0       39   2020
39   1782115        40   2020
40          0       41   2020
41  41732779        42   2020
42    3716858       43   2020

[2623 rows x 3 columns]

In [178]:
population.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2623 entries, 0 to 42
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  2623 non-null   object
 1   pays_id     2623 non-null   int64
 2   annee       2623 non-null   int64
dtypes: int64(2), object(1)
memory usage: 82.0+ KB

In [179]:
population['population'] = population.population.astype(int)
population

    population  pays_id  annee
0    354531754        1   1960
1    406731754        2   1960
2    263140292        3   1960
3      9128824        4   1960
4      7829246        5   1960
..         ...      ...    ...
38           0       39   2020
39     1782115       40   2020
40           0       41   2020
41    41732779       42   2020
42     3716858       43   2020

[2623 rows x 3 columns]

In [180]:
population.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2623 entries, 0 to 42
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  2623 non-null   int64
 1   pays_id     2623 non-null   int64
 2   annee       2623 non-null   int64
dtypes: int64(3)
memory usage: 82.0 KB

In [181]:
population.insert(0, 'id', range(1, 1 + len(population)))
population

      id  population  pays_id  annee
0      1   354531754        1   1960
1      2   406731754        2   1960
2      3   263140292        3   1960
3      4     9128824        4   1960
4      5     7829246        5   1960
..   ...         ...      ...    ...
38  2619           0       39   2020
39  2620     1782115       40   2020
40  2621           0       41   2020
41  2622    41732779       42   2020
42  2623     3716858       43   2020

[2623 rows x 4 columns]

In [182]:
population = population[['id','pays_id','annee','population']]
population

      id  pays_id  annee  population
0      1        1   1960   354531754
1      2        2   1960   406731754
2      3        3   1960   263140292
3      4        4   1960     9128824
4      5        5   1960     7829246
..   ...      ...    ...         ...
38  2619       39   2020           0
39  2620       40   2020     1782115
40  2621       41   2020           0
41  2622       42   2020    41732779
42  2623       43   2020     3716858

[2623 rows x 4 columns]

### Création du fichier 'population_table.tsv"

In [183]:
#population.to_csv('population_table.tsv',index=False,header=['id','pays_id','annee','population'], sep='\t')