In [17]:
import pandas as pd

## Approvisionnement, transformation et consommation d'énergies renouvelables et de déchets

In [27]:
data = pd.read_csv('dataset/t2020_31.tsv', sep='\t')
data

,"unit,indic_eu,geo\time",2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,TARGET
0,"PC,T2020_31,AL",29.621,31.367,32.070,32.657,32.448,31.437,31.867,31.187,35.152,33.167,31.476,34.387,35.487,34.465,34.865,:
1,"PC,T2020_31,AT",22.554,24.378,26.340,28.179,28.856,31.020,31.199,31.563,32.678,32.770,33.653,33.542,33.365,33.144,33.426,34
2,"PC,T2020_31,BA",20.274,19.752,19.213,18.701,16.708,18.471,18.710,17.995,18.014,19.307,24.873,26.607,25.358,23.241,35.972,:
3,"PC,T2020_31,BE",1.890,2.332,2.633,3.101,3.590,4.715,5.643,6.290,7.181,7.515,8.032,8.003,8.712,9.064,9.424,13
4,"PC,T2020_31,BG",9.231,9.173,9.415,9.098,10.345,12.005,13.928,14.152,15.837,18.898,18.050,18.261,18.760,18.701,20.528,16
5,"PC,T2020_31,CY",3.071,3.131,3.263,4.004,5.134,5.925,6.173,6.261,7.137,8.456,9.173,9.929,9.859,10.491,13.882,13
6,"PC,T2020_31,CZ",6.774,7.115,7.363,7.895,8.675,9.978,10.514,10.945,12.816,13.931,15.078,15.073,14.931,14.803,15.150,13
7,"PC,T2020_31,DE",6.211,7.175,8.477,10.054,10.088,10.870,11.686,12.470,13.555,13.766,14.386,14.901,14.885,15.472,16.481,18
8,"PC,T2020_31,DK",14.840,15.955,16.335,17.748,18.545,19.950,21.889,23.388,25.466,27.174,29.310,30.835,31.837,34.720,35.708,30
9,"PC,T2020_31,EA19",8.384,8.972,9.661,10.741,11.432,12.631,13.143,13.167,14.659,15.286,16.107,16.462,16.731,17.282,17.746,:
10,"PC,T2020_31,EE",18.384,17.421,15.965,17.046,18.643,22.931,24.574,25.345,25.524,25.324,26.145,28.228,28.684,29.127,29.996,25
11,"PC,T2020_31,EL",7.161,7.277,7.458,8.249,8.183,8.731,10.077,11.153,13.741,15.326,15.683,15.690,15.390,16.951,18.002,18
12,"PC,T2020_31,ES",8.326,8.430,9.142,9.655,10.737,12.963,13.810,13.223,14.287,15.319,16.125,16.228,17.427,17.563,17.453,20
13,"PC,T2020_31,EU27_2007",:,:,:,:,:,:,:,:,:,:,:,:,:,:,:,20
14,"PC,T2020_31,EU27_2020",9.620,10.239,10.843,11.866,12.564,13.880,14.428,14.587,16.063,16.711,17.482,17.849,18.048,18.471,18.884,:
15,"PC,T2020_31,EU28",8.524,9.107,9.685,10.616,11.368,12.622,13.158,13.411,14.690,15.378,16.219,16.732,16.995,17.474,17.980,20
16,"PC,T2020_31,FI",29.251,28.832,30.061,29.576,31.362,31.344,32.441,32.788,34.434,36.730,38.780,39.320,39.011,40.917,41.162,38
17,"PC,T2020_31,FR",9.507,9.598,9.336,10.241,11.187,12.216,12.672,11.016,13.437,14.043,14.581,15.012,15.680,16.012,16.593,23
18,"PC,T2020_31,HR",23.404,23.691,22.668,22.161,21.986,23.597,25.103,25.389,26.757,28.040,27.817,28.970,28.267,27.280,28.024,20
19,"PC,T2020_31,HU",4.364,6.931,7.433,8.575,8.564,11.674,12.742,13.972,15.530,16.205,14.618,14.495,14.315,13.517,12.489,13
20,"PC,T2020_31,IE",2.366,2.812,3.030,3.455,3.929,5.177,5.707,6.646,7.054,7.618,8.598,9.108,9.258,10.588,11.061,16
21,"PC,T2020_31,IS",58.899,60.270,60.921,71.417,67.348,69.593,70.267,71.476,72.394,71.660,70.484,70.261,70.175,70.691,72.182,:
22,"PC,T2020_31,IT",6.316,7.549,8.328,9.807,11.492,12.775,13.023,12.881,15.441,16.741,17.082,17.526,17.415,18.267,17.775,17
23,"PC,T2020_31,LT",17.223,16.769,16.890,16.483,17.824,19.798,19.640,19.945,21.437,22.689,23.593,25.751,25.615,26.039,24.448,23
24,"PC,T2020_31,LU",0.900,1.404,1.471,2.729,2.815,2.940,2.865,2.874,3.140,3.531,4.512,5.050,5.440,6.286,9.059,11
25,"PC,T2020_31,LV",32.794,32.264,31.141,29.615,29.811,34.318,30.375,33.478,35.709,37.037,38.629,37.538,37.138,39.019,40.292,40
26,"PC,T2020_31,ME",:,35.906,35.003,33.146,32.486,39.465,40.663,40.670,41.531,43.735,44.111,43.089,41.558,39.708,38.807,:
27,"PC,T2020_31,MK",15.702,16.466,16.527,14.976,15.555,17.238,16.451,16.407,18.128,18.509,19.559,19.527,18.044,19.636,18.118,:
28,"PC,T2020_31,MT",0.102,0.124,0.149,0.177,0.195,0.221,0.979,1.850,2.862,3.760,4.744,5.119,6.208,7.270,7.978,10
29,"PC,T2020_31,NL",2.030,2.478,2.778,3.298,3.596,4.266,3.917,4.524,4.659,4.691,5.415,5.657,5.827,6.461,7.385,14
30,"PC,T2020_31,NO",58.444,60.105,60.568,60.439,62.053,65.131,61.515,64.702,65.550,66.746,69.190,69.193,70.163,71.647,72.752,:
31,"PC,T2020_31,PL",6.914,6.900,6.889,6.930,7.713,8.661,9.253,10.295,10.897,11.368,11.495,11.743,11.267,10.964,11.284,15
32,"PC,T2020_31,PT",19.209,19.526,20.786,21.924,22.943,24.421,24.165,24.616,24.579,25.700,29.508,30.514,30.865,30.611,30.322,31
33,"PC,T2020_31,RO",16.811,17.571,17.096,18.195,20.204,22.157,22.834,21.186,22.825,23.886,24.845,24.785,25.032,24.454,23.875,24
34,"PC,T2020_31,RS",12.724,14.257,14.542,14.327,15.888,21.024,19.764,19.118,20.790,21.095,22.864,21.989,21.147,20.287,20.320,:
35,"PC,T2020_31,SE",38.677,40.720,42.447,43.930,44.666,47.880,46.958,48.245,50.230,50.800,51.874,53.009,53.371,54.201,54.645,49
36,"PC,T2020_31,SI",16.134,16.002,15.586,15.609,14.995,20.147,20.420,20.257,20.818,22.407,21.539,21.894,21.293,21.056,21.149,25
37,"PC,T2020_31,SK",6.391,6.360,6.584,7.766,7.723,9.368,9.099,10.348,10.453,10.133,11.713,12.883,12.029,11.465,11.896,14
38,"PC,T2020_31,TR",16.151,15.521,14.051,13.206,13.529,14.086,14.013,12.823,13.208,13.910,13.596,13.603,13.741,12.767,13.659,:
39,"PC,T2020_31,UK",0.907,1.116,1.337,1.603,2.693,3.342,3.782,4.320,4.410,5.498,6.737,8.337,8.981,9.731,11.017,15
40,"PC,T2020_31,XK",20.541,19.773,19.512,18.812,18.429,18.230,18.230,17.598,18.625,18.624,19.544,18.484,24.472,23.082,24.896,:

## Productivité de l'énergie

In [24]:
data2 = pd.read_csv('dataset/t2020_rd310.tsv', sep='\t')
data2

,"unit,geo\time",2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,"EUR_KGOE,AT",8.688,8.340,8.429,8.083,8.151,8.061,8.265,8.721,8.776,8.901,8.489,9.000,9.095,8.973,9.374,9.254,9.345,9.369,9.827
1,"EUR_KGOE,BA",:,:,:,:,:,:,:,:,:,:,:,:,:,:,2.240,2.241,2.112,2.183,2.045
2,"EUR_KGOE,BE",4.730,4.829,4.953,4.767,4.906,5.051,5.182,5.376,5.234,5.523,5.272,5.746,6.100,5.903,6.387,6.470,6.158,6.212,6.321
3,"EUR_KGOE,BG",1.315,1.306,1.417,1.451,1.587,1.607,1.666,1.810,1.943,2.128,2.112,2.020,2.117,2.283,2.225,2.213,2.347,2.347,2.413
4,"EUR_KGOE,CY",5.344,5.503,5.786,5.513,6.323,6.004,6.062,6.166,6.126,6.210,6.591,6.696,6.878,7.205,6.966,7.018,6.923,7.030,7.124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,"PPS_KGOE,SE",4.449,4.236,4.275,4.481,4.559,4.723,5.193,5.664,5.813,5.992,5.691,5.969,6.079,6.225,6.415,7.073,6.795,6.879,7.069
74,"PPS_KGOE,SI",4.613,4.617,4.819,4.979,5.186,5.320,5.569,5.937,5.918,6.006,5.964,6.117,6.324,6.538,6.944,7.210,7.150,7.373,7.751
75,"PPS_KGOE,SK",2.872,2.982,3.147,3.374,3.660,3.915,4.357,5.072,5.422,5.624,5.796,6.096,6.500,6.518,7.143,7.172,6.842,6.661,7.080
76,"PPS_KGOE,TR",6.479,6.870,6.579,6.503,7.182,7.656,7.857,7.985,8.759,8.340,9.022,9.522,9.629,10.612,10.754,10.858,10.387,10.233,10.572
77,"PPS_KGOE,UK",5.489,5.749,6.078,6.257,6.665,6.822,7.204,7.631,7.859,7.938,8.002,8.723,8.811,9.184,10.034,10.286,10.563,11.031,11.316

In [25]:
data3 = pd.read_csv('dataset/ETS_Database_v38.csv', sep='\t')
data3

,country,country_code,ETS information,main activity sector name,unit,value,year
0,Belgium,BE,2. Verified emissions,35 Production of pulp,tonne of CO2 equ.,102581.0,2009
1,Belgium,BE,2. Verified emissions,35 Production of pulp,tonne of CO2 equ.,106671.0,2011
2,Belgium,BE,2. Verified emissions,35 Production of pulp,tonne of CO2 equ.,126702.0,2012
3,Belgium,BE,4. Total surrendered units,35 Production of pulp,tonne of CO2 equ.,98349.0,2007
4,Belgium,BE,4. Total surrendered units,35 Production of pulp,tonne of CO2 equ.,96708.0,2008
...,...,...,...,...,...,...,...
57389,Hungary,HU,2. Verified emissions,10 Aviation,tonne of CO2 equ.,12599748.0,Total 3rd trading period (13-20)
57390,Hungary,HU,1.1.3 Free allocation for modernisation of ele...,23 Metal ore roasting or sintering,tonne of CO2 equ.,0.0,Total 3rd trading period (13-20)
57391,Hungary,HU,1.1.3 Free allocation for modernisation of ele...,"30 Production of lime, or calcination of dolom...",tonne of CO2 equ.,0.0,Total 3rd trading period (13-20)
57392,Hungary,HU,4. Total surrendered units,43 Production of hydrogen and synthesis gas,tonne of CO2 equ.,883972.0,Total 3rd trading period (13-20)
57393,Ireland,IE,1.1.3 Free allocation for modernisation of ele...,10 Aviation,tonne of CO2 equ.,0.0,Total 3rd trading period (13-20)

## Production d'électricité et de chaleur par type de combustible

In [1]:
data4 = pd.read_csv('dataset/nrg_bal_peh.tsv', sep='\t')
data4.head(59)

NameError: name 'pd' is not defined

## Bilan énergétique simplifié

In [22]:
data4 = pd.read_csv('dataset/nrg_bal_s.tsv', sep='\t')
data4

,"nrg_bal,siec,unit,geo\time",2018,2017,2016,2015,2014,2013,2012,2011,2010,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
0,"AFC,C0000X0350-0370,GWH,AL",2598.407,1348.788,589.976,1105.789,1005.406,779.266,898.126,1616.273,1289.769,...,226.936,133.974,106.633,308.961,213.788,459.514,525.540,1067.475,3816.945,6644.088
1,"AFC,C0000X0350-0370,GWH,AT",4111.010,4205.522,4376.613,4341.919,4389.139,4443.805,4329.377,4271.227,4423.737,...,7790.983,8135.222,8906.389,9091.056,9198.056,9353.833,10434.278,11523.667,13590.083,12661.389
2,"AFC,C0000X0350-0370,GWH,BA",3243.089,3080.546,3209.039,3271.128,3142.427,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
3,"AFC,C0000X0350-0370,GWH,BE",9096.112,8535.415,8937.946,9555.746,8722.493,8947.189,6170.370,6776.569,8249.050,...,10747.170,11623.334,12032.319,10003.778,11324.866,11158.154,13592.191,19485.728,21742.136,22835.555
4,"AFC,C0000X0350-0370,GWH,BG",6778.088,5087.590,4601.471,5074.475,4437.746,4881.445,5372.016,5804.197,6071.957,...,5170.405,1527.671,5817.714,12640.555,10061.937,10938.630,11466.180,9843.297,14738.222,21461.183
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138919,"TO_RPI,W6100_6220,TJ,SK",: z,: z,: z,: z,: z,: z,: z,: z,: z,...,: z,: z,: z,: z,: z,: z,: z,: z,: z,: z
138920,"TO_RPI,W6100_6220,TJ,TR",: z,: z,: z,: z,: z,: z,: z,: z,: z,...,: z,: z,: z,: z,: z,: z,: z,: z,: z,: z
138921,"TO_RPI,W6100_6220,TJ,UA",: z,: z,: z,: z,: z,: z,: z,: z,: z,...,: z,: z,: z,: z,: z,: z,: z,: z,: z,: z
138922,"TO_RPI,W6100_6220,TJ,UK",: z,: z,: z,: z,: z,: z,: z,: z,: z,...,: z,: z,: z,: z,: z,: z,: z,: z,: z,: z
138923,"TO_RPI,W6100_6220,TJ,XK",: z,: z,: z,: z,: z,: z,: z,: z,: z,...,:,:,:,:,:,:,:,:,:,: